### PR TITLE
refactor: Use `structs` for extended public/secret keys.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2672)

### CODE REVIEW

**Comment by nurupo** [comment]
*[`toxcore/group_chats.c` line 403 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqHmNn79qkBo_KwHDf-:-NqHmNn79qkBo_KwHDf0:b-dtrkgk) ([raw file](https://github.com/TokTok/c-toxcore/blob/828b76d1e6871bddc7e7fc80f67e14636106b613/toxcore/group_chats.c#L403)):*
> ```C
>         GC_Connection *gconn = get_gc_connection(chat, 0);
>         assert(gconn != nullptr);
>         gconn->addr.public_key = *ext_public_key;
> ```

This is a bit unusual. Had to double-check if this does a shallow copy or a full copy. Turns out it's a full copy.

**Comment by nurupo** [comment]
*[`toxcore/group_chats.c` line 7453 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqHutS5ChAvkvLglGWN:-NqHutS5ChAvkvLglGWO:b-gflrop) ([raw file](https://github.com/TokTok/c-toxcore/blob/828b76d1e6871bddc7e7fc80f67e14636106b613/toxcore/group_chats.c#L7453)):*
> ```C
>            get_sig_pk(&chat->shared_state.founder_public_key), SIG_PUBLIC_KEY_SIZE);
>     memcpy(chat->moderation.self_public_sig_key, get_sig_pk(&chat->self_public_key), SIG_PUBLIC_KEY_SIZE);
>     memcpy(chat->moderation.self_secret_sig_key, get_sig_sk(&chat->self_secret_key), SIG_SECRET_KEY_SIZE);
> ```

Nice typo fix

**Comment by nurupo** [comment]
*[`toxcore/group_pack.c` line 123 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqHzTvu5gZLkVl09nXg:-NqHzTvu5gZLkVl09nXh:b-jqacuq) ([raw file](https://github.com/TokTok/c-toxcore/blob/828b76d1e6871bddc7e7fc80f67e14636106b613/toxcore/group_pack.c#L123)):*
> ```C
> 
>     uint8_t founder_public_key[EXT_PUBLIC_KEY_SIZE];
>     if (!bin_unpack_bin_fixed(bu, founder_public_key, EXT_PUBLIC_KEY_SIZE)) {
> ```

Why not do something like this instead of using a temporary and `memcpy()`?

```C
 if (!bin_unpack_bin_fixed(bu, chat->shared_state.founder_public_key.enc, CRYPTO_PUBLIC_KEY_SIZE)
        || !bin_unpack_bin_fixed(bu, chat->shared_state.founder_public_key.sig, CRYPTO_SIGN_PUBLIC_KEY_SIZE)) {
```

Is it because a partial unpack is undesired?

(Cursed: add a `bool bin_unpack_bin_fixed(Bin_Unpack *bu, uint8_t *data, uint32_t data_length, ...)` variadic function variant that will accept multiple data+data_length tuples, internally allocating a temporary array of the appropriate `data_length1+data_length2...+data_lengthN` size, essentially doing an all or nothing bin unpack into `data1, data2, ... dataN`)

If you must use a temporary, maybe it would make sense to write a dedicated function for this? Something like:

```C
non_null()
static bool bin_unpack_ext_public_key(Bin_Unpack *bu, Extended_Public_Key ext_public_key)
{
    uint8_t tmp_key[EXT_PUBLIC_KEY_SIZE];
    if (!bin_unpack_bin_fixed(bu, tmp_key, EXT_PUBLIC_KEY_SIZE)) {
        return false;
    }
    memcpy(ext_public_key.enc, tmp_key, CRYPTO_PUBLIC_KEY_SIZE);
    memcpy(ext_public_key.sig, tmp_key + CRYPTO_PUBLIC_KEY_SIZE, CRYPTO_SIGN_PUBLIC_KEY_SIZE);
    return true;
}

non_null()
static bool bin_unpack_ext_secret_key(Bin_Unpack *bu, Extended_Secret_Key ext_secret_key)
{
    uint8_t tmp_key[EXT_SECRET_KEY_SIZE];
    if (!bin_unpack_bin_fixed(bu, tmp_key, EXT_SECRET_KEY_SIZE)) {
        return false;
    }
    memcpy(ext_secret_key.enc, tmp_key, CRYPTO_SECRET_KEY_SIZE);
    memcpy(ext_secret_key.sig, tmp_key + CRYPTO_SECRET_KEY_SIZE, CRYPTO_SIGN_SECRET_KEY_SIZE);
    return true;
}
```

**Review by nurupo — CHANGES_REQUESTED** [review]
Don't necessary want to block / don't necessary request code changes, the PR is fine, but just want to make sure my comments are read, as otherwise someone else might approve the PR and it would all go *poof* -- automerged and probably unread.

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-:-NqI8V92AaOfsbnLmjbi:bw2h8nr)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2672)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nurupo)

___
*[`toxcore/group_chats.c` line 403 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqHmNn79qkBo_KwHDf-:-NqJRnyO0xg4oK-osAXe:b-olpoyv) ([raw file](https://github.com/TokTok/c-toxcore/blob/828b76d1e6871bddc7e7fc80f67e14636106b613/toxcore/group_chats.c#L403)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

This is a bit unusual. Had to double-check if this does a shallow copy or a full copy. Turns out it's a full copy.
</blockquote></details>

What should I change to make a struct assignment through `=` more usual?
___
*[`toxcore/group_chats.c` line 7453 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqHutS5ChAvkvLglGWN:-NqJS3Z_-swizlTyiSty:b-67j9nf) ([raw file](https://github.com/TokTok/c-toxcore/blob/828b76d1e6871bddc7e7fc80f67e14636106b613/toxcore/group_chats.c#L7453)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Nice typo fix
</blockquote></details>

Everything is better with structs :).
___
*[`toxcore/group_pack.c` line 123 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqHzTvu5gZLkVl09nXg:-NqJS-76Dr7Y4CH16D9p:btkdls) ([raw file](https://github.com/TokTok/c-toxcore/blob/828b76d1e6871bddc7e7fc80f67e14636106b613/toxcore/group_pack.c#L123)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Why not do something like this instead of using a temporary and `memcpy()`?

```C
 if (!bin_unpack_bin_fixed(bu, chat->shared_state.founder_public_key.enc, CRYPTO_PUBLIC_KEY_SIZE)
        || !bin_unpack_bin_fixed(bu, chat->shared_state.founder_public_key.sig, CRYPTO_SIGN_PUBLIC_KEY_SIZE)) {
```

Is it because a partial unpack is undesired?

(Cursed: add a `bool bin_unpack_bin_fixed(Bin_Unpack *bu, uint8_t *data, uint32_t data_length, ...)` variadic function variant that will accept multiple data+data_length tuples, internally allocating a temporary array of the appropriate `data_length1+data_length2...+data_lengthN` size, essentially doing an all or nothing bin unpack into `data1, data2, ... dataN`)

If you must use a temporary, maybe it would make sense to write a dedicated function for this? Something like:

```C
non_null()
static bool bin_unpack_ext_public_key(Bin_Unpack *bu, Extended_Public_Key ext_public_key)
{
    uint8_t tmp_key[EXT_PUBLIC_KEY_SIZE];
    if (!bin_unpack_bin_fixed(bu, tmp_key, EXT_PUBLIC_KEY_SIZE)) {
        return false;
    }
    memcpy(ext_public_key.enc, tmp_key, CRYPTO_PUBLIC_KEY_SIZE);
    memcpy(ext_public_key.sig, tmp_key + CRYPTO_PUBLIC_KEY_SIZE, CRYPTO_SIGN_PUBLIC_KEY_SIZE);
    return true;
}

non_null()
static bool bin_unpack_ext_secret_key(Bin_Unpack *bu, Extended_Secret_Key ext_secret_key)
{
    uint8_t tmp_key[EXT_SECRET_KEY_SIZE];
    if (!bin_unpack_bin_fixed(bu, tmp_key, EXT_SECRET_KEY_SIZE)) {
        return false;
    }
    memcpy(ext_secret_key.enc, tmp_key, CRYPTO_SECRET_KEY_SIZE);
    memcpy(ext_secret_key.sig, tmp_key + CRYPTO_SECRET_KEY_SIZE, CRYPTO_SIGN_SECRET_KEY_SIZE);
    return true;
}
```
</blockquote></details>

Done, moved to crypto_core_pack module. This had a rather large fallout, so there is a lot more to review now.

**Review by nurupo — CHANGES_REQUESTED** [review]
> Reviewed 11 of 26 files at r3, 20 of 20 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2672)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[`toxcore/crypto_core.c` line 219 at r3](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqNc5MQ0g3f_p1y24th:-NqNc5MQ0g3f_p1y24ti:b351a9c) ([raw file](https://github.com/TokTok/c-toxcore/blob/8a6f81be49d320f171cf763661cd07043ce74049/toxcore/crypto_core.c#L219)):*
> ```C
>                              const Sign_Public_Key *public_key)
> {
>     return crypto_sign_verify_detached(signature, message, message_length, public_key->data) == 0;
> ```

Would making `crypto_sign_*()` take `Sign_Public_Key` and `Sign_Secret_Key` argument types be the next step? Probably in a separate PR though.

EDIT: was looking at r3 when writing that, since r4 there are no more `Sign_Public_Key` and `Sign_Secret_Key`. Still leaving the comment as it might be something to consider.
___
*[`toxcore/crypto_core_pack.c` line 18 at r3](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqNeXl-1287GZCHnryg:-NqNeXl-1287GZCHnryh:br9cktd) ([raw file](https://github.com/TokTok/c-toxcore/blob/8a6f81be49d320f171cf763661cd07043ce74049/toxcore/crypto_core_pack.c#L18)):*
> ```C
>     uint8_t ext_key[EXT_PUBLIC_KEY_SIZE];
>     memcpy(ext_key, key->enc.data, CRYPTO_PUBLIC_KEY_SIZE);
>     memcpy(&ext_key[CRYPTO_PUBLIC_KEY_SIZE], key->sig.data, CRYPTO_SIGN_PUBLIC_KEY_SIZE);
> ```

What do you think about adding static asserts making sure `CRYPTO_[PUBLIC|SECRET]_KEY_SIZE + CRYPTO_SIGN_[PUBLIC|SECRET]_KEY_SIZE == EXT_[PUBLIC|SECRET]_KEY_SIZE`?
Good idea? Unnecessary?
___
*[`toxcore/crypto_core_pack.c` line 25 at r3](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqNdHt7ADlCvF8uZJyg:-NqNdHt7ADlCvF8uZJyh:b-mff4z) ([raw file](https://github.com/TokTok/c-toxcore/blob/8a6f81be49d320f171cf763661cd07043ce74049/toxcore/crypto_core_pack.c#L25)):*
> ```C
> bool pack_extended_secret_key(const Extended_Secret_Key *key, Bin_Pack *bp)
> {
>     uint8_t ext_key[EXT_SECRET_KEY_SIZE];
> ```

Are we okay with leaving secret keys on the stack? Was #2661 somehow special because it was the gc session key?
___
*[`toxcore/crypto_core_pack.c` line 48 at r3](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqNdkql0yUeSGLHNc2L:-NqNdkql0yUeSGLHNc2M:b-mff4z) ([raw file](https://github.com/TokTok/c-toxcore/blob/8a6f81be49d320f171cf763661cd07043ce74049/toxcore/crypto_core_pack.c#L48)):*
> ```C
> bool unpack_extended_secret_key(Extended_Secret_Key *key, Bin_Unpack *bu)
> {
>     uint8_t ext_key[EXT_SECRET_KEY_SIZE];
> ```

Are we okay with leaving secret keys on the stack? Was #2661 somehow special because it was the gc session key?
___
*[`toxcore/group_chats.c` line 403 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqHmNn79qkBo_KwHDf-:-NqN_RCR3mZ5E3yjr1_i:b-kdtqud) ([raw file](https://github.com/TokTok/c-toxcore/blob/828b76d1e6871bddc7e7fc80f67e14636106b613/toxcore/group_chats.c#L403)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

What should I change to make a struct assignment through `=` more usual?
</blockquote></details>

Nothing, was just a blunter on my part. Not used to dealing with fixed-sized arrays in structs, so automatically thought of them as dynamic arrays, in which case the assignment would just assign the array pointers since that's all the struct would contain. But with the fixed-size arrays the struct actually contains all the array data, not just pointers, so the assignment would overwrite the entire array data, which is what we want.

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2672)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nurupo)

___
*[`toxcore/crypto_core.c` line 219 at r3](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqNc5MQ0g3f_p1y24th:-NqPlHbo2bsiutc_PKq6:b-lg0f8q) ([raw file](https://github.com/TokTok/c-toxcore/blob/8a6f81be49d320f171cf763661cd07043ce74049/toxcore/crypto_core.c#L219)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Would making `crypto_sign_*()` take `Sign_Public_Key` and `Sign_Secret_Key` argument types be the next step? Probably in a separate PR though.

EDIT: was looking at r3 when writing that, since r4 there are no more `Sign_Public_Key` and `Sign_Secret_Key`. Still leaving the comment as it might be something to consider.
</blockquote></details>

Those are libsodium functions, so no. But: https://github.com/TokTok/c-toxcore/issues/2680
___
*[`toxcore/crypto_core_pack.c` line 18 at r3](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqNeXl-1287GZCHnryg:-NqPn3ue7aIgEMHhqK4R:b-896fix) ([raw file](https://github.com/TokTok/c-toxcore/blob/8a6f81be49d320f171cf763661cd07043ce74049/toxcore/crypto_core_pack.c#L18)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

What do you think about adding static asserts making sure `CRYPTO_[PUBLIC|SECRET]_KEY_SIZE + CRYPTO_SIGN_[PUBLIC|SECRET]_KEY_SIZE == EXT_[PUBLIC|SECRET]_KEY_SIZE`?
Good idea? Unnecessary?
</blockquote></details>

Done.
___
*[`toxcore/crypto_core_pack.c` line 25 at r3](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqNdHt7ADlCvF8uZJyg:-NqPn4QbDErSF20M8wMW:b-xc63e7) ([raw file](https://github.com/TokTok/c-toxcore/blob/8a6f81be49d320f171cf763661cd07043ce74049/toxcore/crypto_core_pack.c#L25)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Are we okay with leaving secret keys on the stack? Was #2661 somehow special because it was the gc session key?
</blockquote></details>

We're not, good call. I've added memzero to both secret and public key (not strictly necessary, but the symmetry is nice and doesn't harm much (just a little bit of performance that doesn't matter here).
___
*[`toxcore/crypto_core_pack.c` line 48 at r3](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqNdkql0yUeSGLHNc2L:-NqPnHYt-Vqz9DqpDOoc:b-896fix) ([raw file](https://github.com/TokTok/c-toxcore/blob/8a6f81be49d320f171cf763661cd07043ce74049/toxcore/crypto_core_pack.c#L48)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Are we okay with leaving secret keys on the stack? Was #2661 somehow special because it was the gc session key?
</blockquote></details>

Done.
___
*[`toxcore/group_chats.c` line 403 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqHmNn79qkBo_KwHDf-:-NqPnLnk2jyy9WNr-1o8:b48uw9i) ([raw file](https://github.com/TokTok/c-toxcore/blob/828b76d1e6871bddc7e7fc80f67e14636106b613/toxcore/group_chats.c#L403)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Nothing, was just a blunter on my part. Not used to dealing with fixed-sized arrays in structs, so automatically thought of them as dynamic arrays, in which case the assignment would just assign the array pointers since that's all the struct would contain. But with the fixed-size arrays the struct actually contains all the array data, not just pointers, so the assignment would overwrite the entire array data, which is what we want.
</blockquote></details>

Yup :) it's really great, because this way we also don't get automatic pointer conversions (decays), making all the code much more explicit.

**Comment by nurupo** [comment]
*[`toxcore/crypto_core_pack.c` line 25 at r3](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqNdHt7ADlCvF8uZJyg:-NqVi6m40UAAXhe0JiPS:bsw0vh2) ([raw file](https://github.com/TokTok/c-toxcore/blob/8a6f81be49d320f171cf763661cd07043ce74049/toxcore/crypto_core_pack.c#L25)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

We're not, good call. I've added memzero to both secret and public key (not strictly necessary, but the symmetry is nice and doesn't harm much (just a little bit of performance that doesn't matter here).
</blockquote></details>

Eh, that's really unnecessary for the public key and the functions don't have to be symmetric.

**Review by nurupo — APPROVED** [review]
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2672)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Review by nurupo — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2672)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[`toxcore/crypto_core_pack.c` line 17 at r6](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqZXLQACXwKJ_LoAYSB:-NqZXLQB1PTDJN0ORLSp:bxlvb2z) ([raw file](https://github.com/TokTok/c-toxcore/blob/d671110d6c676b55ba64770ab3812c8a375e2d49/toxcore/crypto_core_pack.c#L17)):*
> ```C
> bool pack_extended_public_key(const Extended_Public_Key *key, Bin_Pack *bp)
> {
>     uint8_t ext_key[EXT_PUBLIC_KEY_SIZE];
> ```

Maybe make it `uint8_t ext_key[sizeof(ext_key)];` then too? Since that's how much data we are `memcpy()`'ing into it.
___
*[`toxcore/crypto_core_pack.c` line 28 at r6](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqZXiWB1t3HNhgmyWBy:-NqZXiWB1t3HNhgmyWBz:bbxgkzp) ([raw file](https://github.com/TokTok/c-toxcore/blob/d671110d6c676b55ba64770ab3812c8a375e2d49/toxcore/crypto_core_pack.c#L28)):*
> ```C
> bool pack_extended_secret_key(const Extended_Secret_Key *key, Bin_Pack *bp)
> {
>     uint8_t ext_key[EXT_SECRET_KEY_SIZE];
> ```

Same comment as above
___
*[`toxcore/crypto_core_pack.c` line 41 at r6](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqZXk-v20K4C17kEiX0:-NqZXk-w6RasK9_LjLUr:bbxgkzp) ([raw file](https://github.com/TokTok/c-toxcore/blob/d671110d6c676b55ba64770ab3812c8a375e2d49/toxcore/crypto_core_pack.c#L41)):*
> ```C
> bool unpack_extended_public_key(Extended_Public_Key *key, Bin_Unpack *bu)
> {
>     uint8_t ext_key[EXT_PUBLIC_KEY_SIZE];
> ```

Same comment as above
___
*[`toxcore/crypto_core_pack.c` line 55 at r6](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqZXkq_4np-cVktC6pa:-NqZXkq_4np-cVktC6pb:bbxgkzp) ([raw file](https://github.com/TokTok/c-toxcore/blob/d671110d6c676b55ba64770ab3812c8a375e2d49/toxcore/crypto_core_pack.c#L55)):*
> ```C
> bool unpack_extended_secret_key(Extended_Secret_Key *key, Bin_Unpack *bu)
> {
>     uint8_t ext_key[EXT_SECRET_KEY_SIZE];
> ```

Same comment as above

**Review by nurupo — APPROVED** [review]
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2672)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Comment by nurupo** [comment]
*[`toxcore/crypto_core_pack.c` line 17 at r6](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqZXLQACXwKJ_LoAYSB:-NqZYgWe3fpalR-3YZGG:bb6ywmx) ([raw file](https://github.com/TokTok/c-toxcore/blob/d671110d6c676b55ba64770ab3812c8a375e2d49/toxcore/crypto_core_pack.c#L17)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Typo, I meant `uint8_t ext_key[sizeof(key)];` not `uint8_t ext_key[sizeof(ext_key)];`, but I guess that wouldn't make much sense either.
</blockquote></details>

LGTM

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2672)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

___
*[`toxcore/crypto_core_pack.c` line 17 at r6](https://reviewable.io/reviews/TokTok/c-toxcore/2672#-NqZXLQACXwKJ_LoAYSB:-NqZ_0JF7DZnbXiA5NVv:b-abs4bi) ([raw file](https://github.com/TokTok/c-toxcore/blob/d671110d6c676b55ba64770ab3812c8a375e2d49/toxcore/crypto_core_pack.c#L17)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

I intentionally left this one to be the macro constant. `sizeof(some_struct)` is not what we want here.

**Pull request merged**
