### PR TITLE
perf: fix issue with friend finding taking too long after disconnects.

### LINKED ISSUE #2080: speedup getting online after tox process has been suspended
on mobile devices the tox process gets suspendend (frozen), and the tox goes offline.
if the process gets resumed (unfrozen) tox_iterate is called again and it takes a very long time to see friends online.
on iPhone and Android this is usually near 2 minutes.

that gives a bad user experience and also makes it harder make tox work on the iPhone.

can we speedup the friend lookup after going offline (through timeouts) to get this down to 30 seconds?

i can attach debug info for both platforms if needed.,

### PR DESCRIPTION
**Pull request by JFreegman**
This forces the onion to consider all friends as new after a 10 second
period of the onion being disconnected. new friends are aggressively
searched for in the DHT, whereas old friends are only searched for in
intervals spanning minutes.

maybe fixes #2080 

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2092)

### CODE REVIEW

**Review by Tha14 — APPROVED** [review]
Measured a 03.26s with this optimization compared to a 16.89s after 2 minutes of being offline. Looks promising.

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2092)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[toxcore/onion_client.c, line 1824 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2092#-MwcBwAY9CPHPE7fCXhD:-MwcBwAY9CPHPE7fCXhE:b-4jf7um) ([raw file](https://github.com/toktok/c-toxcore/blob/d139d6f645b260798163a238ab5f918e4b1f5c2c/toxcore/onion_client.c#L1824)):*
> ```C
>         Onion_Friend *o_friend = &onion_c->friends_list[i];
> 
>         if (o_friend->status != 0) {
> ```

can you make defined values instead of magic `0`?

**Comment by JFreegman** [comment]
___
*[toxcore/onion_client.c, line 1824 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2092#-MwcBwAY9CPHPE7fCXhD:-MwcOxEf8LAnz0u-jQZL:b-zeo1a2) ([raw file](https://github.com/toktok/c-toxcore/blob/d139d6f645b260798163a238ab5f918e4b1f5c2c/toxcore/onion_client.c#L1824)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

can you make defined values instead of magic `0`?
</blockquote></details>

It would have to be done across the entire file since that variable is actually defined as 0 == invalid and 1 == valid. So I think it should go in a separate PR. We could just convert it to a bool and give it a better name.

**Comment by sudden6** [comment]
maybe wait for #2103 then

**Review by iphydf — APPROVED** [review]

**Comment by JFreegman** [comment]
> maybe wait for #2103 then

It's been fixed in [another PR](https://github.com/TokTok/c-toxcore/commit/7ca14d4f52d0d5002f6732e537bc032f24f49412)

**Pull request merged**
