### PR TITLE
Release v0.1.11

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/638)

### CODE REVIEW

**Comment by sudden6** [comment]
Is it normal/intended that the FreeBSD script runs cmake for about 10 times and only then runs make?

**Comment by SkyzohKey** [comment]
LGTM :)

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/638#-:-L14HggeMrlhOWLfcQhE:b-jbsf8z)*

**Comment by robinlinden** [comment]
@nurupo Can you have a look at @sudden6's comment?

**Comment by im-grey** [comment]
Thank you for all your hard work.

**Comment by nurupo** [comment]
@sudden6 yeah, that's normal. We also do this on Linux, Windows, etc., it's not just FreeBSD that runs cmake multiple times. Here is the code that is responsible for that https://github.com/TokTok/c-toxcore/blob/b39cc55d374457f66606096904af9fe7ea6562f6/other/travis/toxcore-script#L6-L23, you can see that it's in a platform-independent `toxcore-script` script, and here is the commit that added it https://github.com/TokTok/c-toxcore/commit/0a61d1108547513211560e66809479cab5082ede. It's purpose is to check if certain cmake argument combinations result in a failure when generating the Makefile out of CMakeLists.txt, e.g. incompatible cmake arguments, etc. Can't find the PR that added it though, for some reason the GitHub web page for the commit links to a PR in zoff99's repo instead of the PR in this repo that have added the commit, must be GitHub bug.

**Comment by sudden6** [comment]
@nurupo thanks for clarifying :)

**Comment by iphydf** [comment]
Green :) let's make the release.

**Pull request merged**
