### PR TITLE
Use ninja build system for the cmake-linux build.

### PR DESCRIPTION
**Pull request by iphydf**
This way we can check that building with Ninja works, in addition to "make". We test "make" on Circle CI, so we test Ninja on Travis CI.

---

This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1378)

### CODE REVIEW

**Comment by nurupo** [comment]
So... why?

Neither your PR message, commit message or the change contain a reason as to why. I really hate it when people make PRs without explaining why, even though in most cases just one line would explain it. Even something like https://github.com/TokTok/c-toxcore/pull/1370 could have a single line explaining "~0 is not portable on one's compliment architectures while -1 is".

**Comment by iphydf** [comment]
@nurupo added some notes to the description.

**Comment by Diadlo** [comment]
@iphydf AFAIK `ninja` and `make` are interchangeable. So there is no reason to make separate tests for the `ninja` build system. CMake takes responsibility.

**Comment by iphydf** [comment]
cmake takes responsibility, but at some point something is going to change that breaks this, and cmake will have taken the responsibility of posting on their blog/website/etc, and we'll have missed it, and the first time we hear of the problem is when some user tries and fails.

**Comment by nurupo** [comment]
Huh.

**Comment by nurupo** [comment]
I'm not against the proposed change, LGTM, but the reason behind it is a bit ridiculous. 

>cmake takes responsibility, but at some point something is going to change that breaks this, and cmake will have taken the responsibility of posting on their blog/website/etc, and we'll have missed it, and the first time we hear of the problem is when some user tries and fails.

If something changes in a new version of cmake that breaks a generator - there is not much we can do about it, that's something that should be fixed in cmake, and if they refuse to fix it then I guess whoever used to build toxcore using the now broken generator will have to use some other generator, as we are not going to support a cmake fork that fixes it.

Also, cmake supports more than just make and ninja, cmake [supports maybe 15-40 various generators](https://cmake.org/cmake/help/v3.17/manual/cmake-generators.7.html) for build systems, IDEs and IDE x build system combinations across all OSes:

```
$ cmake -G
CMake Error: No generator specified for -G

Generators
* Unix Makefiles               = Generates standard UNIX makefiles.
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
  Ninja                        = Generates build.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
```

(that's just on my Linux system, on Windows it is a whole other set of generators...)

and if we were to start testing them all to make sure cmake doesn't break anything, while is possible, sounds like something you'd do out of desperation when you run out of things to test.

Your reasoning aside, if you want to make sure that toxcore is buildable using the Ninja generator too, in addition to the already supported Unix Makefiles on Unix-like and MinGW Makefiles on Windows - that perfectly fine, especially given how minimal that change is, which is why I'm giving LGTM.

**Pull request merged**
