### PR TITLE
Add a simple conference test with 3 friends.

### PR DESCRIPTION
**Pull request by iphydf**
This tests that a message from tox1 is relayed via tox2 to tox3 when tox1
and tox3 are not friends.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/703)

### CODE REVIEW

**Comment by zoff99** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[auto_tests/simple_conference_test.c, line 121 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/703#-L3HdbaxvSkXBoly-NLe:-L3HdbaxvSkXBoly-NLf:bsk7st1) ([raw file](https://github.com/toktok/c-toxcore/blob/851376f830ea7a6c3bb80825213d5be8b4cd2b73/auto_tests/simple_conference_test.c#L121)):*
> ```C
>     fprintf(stderr, "Waiting for toxes to come online");
> 
>     while (!state1.self_online || !state2.self_online || !state3.self_online) {
> ```

loop may never end

---

*[auto_tests/simple_conference_test.c, line 135 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/703#-L3HdfhR4DLVWS7Y0N1L:-L3HdfhSn8e8LJMc_dW3:bsk7st1) ([raw file](https://github.com/toktok/c-toxcore/blob/851376f830ea7a6c3bb80825213d5be8b4cd2b73/auto_tests/simple_conference_test.c#L135)):*
> ```C
>     fprintf(stderr, "Waiting for friends to connect");
> 
>     while (!state1.friend_online || !state2.friend_online || !state3.friend_online) {
> ```

loop may never end

---

*[auto_tests/simple_conference_test.c, line 165 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/703#-L3Hdl5jsTh-3uytmKD8:-L3Hdl5jsTh-3uytmKD9:bsk7st1) ([raw file](https://github.com/toktok/c-toxcore/blob/851376f830ea7a6c3bb80825213d5be8b4cd2b73/auto_tests/simple_conference_test.c#L165)):*
> ```C
>     fprintf(stderr, "Waiting for invitation to arrive");
> 
>     while (!state1.joined || !state2.joined || !state3.joined) {
> ```

loop may never end

---

*[auto_tests/simple_conference_test.c, line 190 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/703#-L3HdpViwMcUEOb_NUlA:-L3HdpViwMcUEOb_NUlB:bsk7st1) ([raw file](https://github.com/toktok/c-toxcore/blob/851376f830ea7a6c3bb80825213d5be8b4cd2b73/auto_tests/simple_conference_test.c#L190)):*
> ```C
>     fprintf(stderr, "Waiting for messages to arrive");
> 
>     while (!state2.received || !state3.received) {
> ```

loop may never end

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/703)*

**Comment by Diadlo** [comment]
@zoff99 Probably, it's right behaviour. Infinity loop will produce timeout error

**Comment by iphydf** [comment]
Correct. Infinite loops are intentional. CTest will kill the test if it times out.

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/703#-:-L3IZ4MqsvLpwaJ-z-DM:b-jbsf8z)*

**Pull request merged**
