### PR TITLE
cleanup: Fix a few more clang-tidy warnings.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2406)

### CODE REVIEW

**Review by JFreegman — COMMENTED** [review]
> Reviewed 98 of 98 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2406)* status: 0 of 1 approvals obtained (waiting on @iphydf)

___
*[`toxcore/DHT.c` line 781 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2406#-NdPrOtN4rYmY69ho6Yx:-NdPrOtN4rYmY69ho6Yy:b-xcqi7e) ([raw file](https://github.com/TokTok/c-toxcore/blob/9df963d0521c48baebb979e74f46c4cb7725c0ab/toxcore/DHT.c#L781)):*
> ```C
>         const IPPTsPng *ipptp = NULL;
> 
>         if (net_family_is_ipv4(sa_family) || client->assoc4.timestamp >= client->assoc6.timestamp) {
> ```

Is this an intentional logic change? Previously, we set `ipptp = &client->assoc6;` after confirming that sa_family is ipv6, even if `client->assoc4.timestamp >= client->assoc6.timestamp`. Now we set `ipptp = &client->assoc4;` if `client->assoc4.timestamp >= client->assoc6.timestamp` even if  sa_family is ipv6.
___
*[`toxcore/tox.c` line 816 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2406#-NdPvMlT1I_crLvBvLXb:-NdPvMlT1I_crLvBvLXc:b1hvmj9) ([raw file](https://github.com/TokTok/c-toxcore/blob/9df963d0521c48baebb979e74f46c4cb7725c0ab/toxcore/tox.c#L816)):*
> ```C
>     if (tox->m == nullptr) {
>         switch (m_error) {
>             case MESSENGER_ERROR_PORT:
> ```

Intentional fallthrough? Should probably comment that

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2406)* status: 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[`toxcore/DHT.c` line 781 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2406#-NdPrOtN4rYmY69ho6Yx:-NdiYpPQ4_wwW1t0O160:bs9k24v) ([raw file](https://github.com/TokTok/c-toxcore/blob/9df963d0521c48baebb979e74f46c4cb7725c0ab/toxcore/DHT.c#L781)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Is this an intentional logic change? Previously, we set `ipptp = &client->assoc6;` after confirming that sa_family is ipv6, even if `client->assoc4.timestamp >= client->assoc6.timestamp`. Now we set `ipptp = &client->assoc4;` if `client->assoc4.timestamp >= client->assoc6.timestamp` even if  sa_family is ipv6.
</blockquote></details>

Good point. Undone.
___
*[`toxcore/tox.c` line 816 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2406#-NdPvMlT1I_crLvBvLXb:-NdiYtvz6YStUAa3nbdz:b-a1mfkf) ([raw file](https://github.com/TokTok/c-toxcore/blob/9df963d0521c48baebb979e74f46c4cb7725c0ab/toxcore/tox.c#L816)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Intentional fallthrough? Should probably comment that
</blockquote></details>

I usually consider "fallthrough" to be a case that does work and then doesn't break (which we don't allow). This fallthrough is effectively an "or" case. Should we document such cases (e.g. group.c:2146)?

**Comment by JFreegman** [comment]
> I usually consider "fallthrough" to be a case that does work and then doesn't break (which we don't allow). This fallthrough is effectively an "or" case. Should we document such cases (e.g. group.c:2146)?

Maybe I'm misremembering because I thought we already did that. It's probably not necessary.

**Review by JFreegman — APPROVED** [review]
> Reviewed 96 of 96 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2406)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
