### PR TITLE
Add test to check if tox_new/tox_kill leaks.

### PR DESCRIPTION
**Pull request by iphydf**
We create and destroy 20k tox instances and run a single tox_iterate on
it. This test is not comprehensive, but provides a simple check to see
whether the destruction properly cleans up memory and perhaps other
resources.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/341)

### CODE REVIEW

**Comment by Ansa89** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[auto_tests/resource_leak_test.c, line 3 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/341#-KZSjMqhFavHtrAYOenQ:-KZSjMqikvqJRQeuxMk7:b3qu9kx) ([raw file](https://github.com/toktok/c-toxcore/blob/3daa040ad93eab5c1980f8ad9bc4f6c618638f7f/auto_tests/resource_leak_test.c#L3)):*
> ```C
> #include "helpers.h"
> 
> #ifdef _BSD_SOURCE
> ```

According to `man sbrk(2)`, this should be (on glibc >= 2.12):
```C
_BSD_SOURCE || _SVID_SOURCE ||
                   (_XOPEN_SOURCE >= 500 ||
                       _XOPEN_SOURCE && _XOPEN_SOURCE_EXTENDED) &&
                   !(_POSIX_C_SOURCE >= 200112L || _XOPEN_SOURCE >= 600)
```
Maybe you can check for those macros only one time and define a `HAVE_SBRK 1` macro for later use.

---

*[auto_tests/resource_leak_test.c, line 23 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/341#-KZSkHJo3CBspp6im5m2:-KZSkHJo3CBspp6im5m3:b-38498v) ([raw file](https://github.com/toktok/c-toxcore/blob/3daa040ad93eab5c1980f8ad9bc4f6c618638f7f/auto_tests/resource_leak_test.c#L23)):*
> ```C
>     }
> 
> #if _BSD_SOURCE
> ```

Same as above, plus why not `#ifdef`?

---

*[auto_tests/resource_leak_test.c, line 25 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/341#-KZSn6VDe-f4kDQGa5iG:-KZSn6VE2YKDG3Aw7h_I:b1f33x) ([raw file](https://github.com/toktok/c-toxcore/blob/3daa040ad93eab5c1980f8ad9bc4f6c618638f7f/auto_tests/resource_leak_test.c#L25)):*
> ```C
> #if _BSD_SOURCE
>     // Low water mark.
>     char *hwm = NULL;
> ```

Why not `char *hwm = (char *)sbrk(0);`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/341)*

**Comment by iphydf** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[auto_tests/resource_leak_test.c, line 3 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/341#-KZSjMqhFavHtrAYOenQ:-KZSopeo7-DCSenFtk8U:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/3daa040ad93eab5c1980f8ad9bc4f6c618638f7f/auto_tests/resource_leak_test.c#L3)):*
<details><summary><i>Previously, Ansa89 wrote…</i></summary><blockquote>

According to `man sbrk(2)`, this should be (on glibc >= 2.12):
```C
_BSD_SOURCE || _SVID_SOURCE ||
                   (_XOPEN_SOURCE >= 500 ||
                       _XOPEN_SOURCE && _XOPEN_SOURCE_EXTENDED) &&
                   !(_POSIX_C_SOURCE >= 200112L || _XOPEN_SOURCE >= 600)
```
Maybe you can check for those macros only one time and define a `HAVE_SBRK 1` macro for later use.
</blockquote></details>

Done.

---

*[auto_tests/resource_leak_test.c, line 23 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/341#-KZSkHJo3CBspp6im5m2:-KZSoqLFtiCE5Bd0zS2v:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/3daa040ad93eab5c1980f8ad9bc4f6c618638f7f/auto_tests/resource_leak_test.c#L23)):*
<details><summary><i>Previously, Ansa89 wrote…</i></summary><blockquote>

Same as above, plus why not `#ifdef`?
</blockquote></details>

Done.

---

*[auto_tests/resource_leak_test.c, line 25 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/341#-KZSn6VDe-f4kDQGa5iG:-KZSotY7-FGKko1Vv2T6:by5h6dw) ([raw file](https://github.com/toktok/c-toxcore/blob/3daa040ad93eab5c1980f8ad9bc4f6c618638f7f/auto_tests/resource_leak_test.c#L25)):*
<details><summary><i>Previously, Ansa89 wrote…</i></summary><blockquote>

Why not `char *hwm = (char *)sbrk(0);`?
</blockquote></details>

Historical reasons. Changed now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/341)*

**Comment by Ansa89** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[auto_tests/resource_leak_test.c, line 41 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/341#-KZSqzzxIskN_n-nXri4:-KZSqzzxIskN_n-nXri5:bktav2f) ([raw file](https://github.com/toktok/c-toxcore/blob/56f2af126074c8f6765498d182dcbd071b993bc2/auto_tests/resource_leak_test.c#L41)):*
> ```C
>         tox_iterate(tox, NULL);
>         tox_kill(tox);
> #if _BSD_SOURCE
> ```

Change to `#if HAVE_SBRK`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/341)*

**Comment by iphydf** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[auto_tests/resource_leak_test.c, line 41 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/341#-KZSqzzxIskN_n-nXri4:-KZSrcO7_B4GxX16byXT:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/56f2af126074c8f6765498d182dcbd071b993bc2/auto_tests/resource_leak_test.c#L41)):*
<details><summary><i>Previously, Ansa89 wrote…</i></summary><blockquote>

Change to `#if HAVE_SBRK`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/341)*

**Comment by Ansa89** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/341#-:-KZSuUzj9fSEGyeoA8Fe:b-jbsf8z)*

**Pull request merged**
