### PR TITLE
Add a mutex lock/unlock inside every public API function.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1382)

### CODE REVIEW

**Comment by sudden6** [comment]
What problem does this solve?

Are you aware that this can have a serious performance impact when using a separate threads for tox and toxav?

With this change you rob the application developer of a method to implement more efficient locking for their use case, so until there's very good reasoning I'm against this.

**Comment by zoff99** [comment]
* it should help avoid more threading bugs in clients and bindings
* it's needed to fix #223 https://github.com/TokTok/c-toxcore/issues/854#issuecomment-375968747
* after ToxAV only uses public Tox API, there will still be threading issues without something like this
* see also: https://github.com/zoff99/c-toxcore/blob/zoff99/_0.1.10_2017_video_fix_10p/docs/toxav_threading.md

what still remains are some issues with callbacks. calling ToxAPI functions from within a callback should also be only allowed where it is guaranteed to be safe.
example: calling tox_friend_add_norequest() from within tox_callback_friend_request
not allowed calls should return an error.
as example: calling tox_iterate() from any callback

**Comment by sudden6** [comment]
> it should help avoid more threading bugs in clients and bindings

To me this looks currently like a bandaid because ToxAV threading is broken. I'll explain how I'd imagine threading works for toxcore/toxav further down.

> it's needed to fix #223 #854 (comment)

First issue is probably a copy paste error? In the second issue ToxAV is calling an internal API of Tox AFAICT so I'm not sure how locking the public API in toxcore should help here?

> https://github.com/zoff99/c-toxcore/blob/zoff99/_0.1.10_2017_video_fix_10p/docs/toxav_threading.md

This seems to describe the current way, right?


#### How I imagine threading in toxcore and toxav works

##### Needed Components

- Toxcore
  - Handles crypto and network layer up to the protocol level where the byte that determines the packet type sits
  - Is not thread-safe at all, if thread safety is needed calls to `tox_*` functions must be locked 
against `tox_iterate()` by the user
  - callbacks are emitted from the same thread as `tox_iterate()` currently runs in
  - calling functions other than constant functions (that don't alter the state of the Tox object) from a callback is forbidden
- ToxAV
  - Handles encoding/decoding
  - Handles AV packet payload encoding/decoding

- A thread-safe queue
  - Can enqueue and dequeue data in a thread-safe way (either via mutex or atomics)

##### General Idea

There are 4 thread-safe queues:
- AV data from toxcore to ToxAV
- AV data from ToxAV to toxcore
- Signaling from toxcore to ToxAV
- Signaling from ToxAV to toxcore

Signaling means actions like: Peer offline/online, Start/Stop Call, ...

We could theoretically mix AV and Signaling data, but for the explanation I think it's better this way.

When toxcore receives a packet which has the AV type, it puts the content into the queue and attaches the public key and the the group identifier (if it exists) as metadata. Same in the other direction, ToxAV puts encoded AV data into the queue and attaches the metadata of the intended recipient.

##### Special cases

An important case to handle properly is when toxcore enqueues an AV packet and immediately enqueues an event signaling that that peer went offline/ended the call. This situation can be solved by always processing stuff in the signaling queue first, or adding a counter as timestamp to the metadata. The second approach might also help when we need to synchronize audio and video data.

#### General remarks

This approach relies not on making toxcore thread-safe, but to use existing thread safe data structures (thread-safe queues) at the thread boundaries. As far as my experience goes, this is a more reliable approach, because the standard data structures (list, queue, ...) have thread-safe implementations since ages and are thus well documented and tested. The same can't be said about our code, thus I argue it's harder to make it properly thread-safe than building just a thread-safe queue.

From the performance side I'm pretty sure that this will work better than scattering locks all over toxcore to get it thread-safe, because here the locks are just needed at enqueue and dequeue operations and even there not necessarily (atomic queue). This approach can also scale to multiple ToxAV threads if we need that in the future.

A nice side effect of this approach is, that ToxAV and the queue are completely independent from toxcore and all three parts can be tested independently.

**Comment by sudden6** [comment]
IMO this change alone needs a version bump, because it changes the threading properties of c-toxcore.

**Comment by iphydf** [comment]
I've renamed it to `experimental_thread_safety` and put more words into the "don't rely on this" section. I'd like to avoid making this part of the supported API until we can show that toxav can be changed to use the public API only. The same goes for the per-packet-id handlers, which is not the direction I'd like to see toxcore go in long term.

**Comment by iphydf** [comment]
@sudden6 this change, being disabled by default, and not part of the "threading" documentation on c-toxcore, does not change the threading properties of c-toxcore, in the same way that adding `Camel_Case` typedefs to be aliases for the `UPPER_CASE` enums doesn't change their names. Removing this option would normally require a version bump, because a version bump is required in every case where we change the API incompatibly (which we would, if we changed the threading properties unconditionally or on-by-default). This PR doesn't change the API incompatibly.

**Comment by sudden6** [comment]
Right, forgot that it's off by default.

**Pull request merged**
