### PR TITLE
Fixed the bug when receipts for messages sent from the receipt callback never arrived.

### PR DESCRIPTION
**Pull request by yurivict**
https://github.com/TokTok/c-toxcore/issues/493

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/500)

### CODE REVIEW

**Comment by iphydf** [comment]
Fascinating. Can you add a test case that fails without this change?

**Comment by yurivict** [comment]
Are there any testcases of this kind? It requires 2 peers.

**Comment by nurupo** [comment]
Just create 2 Tox instances. Make sure to use `tox_new_log()` and `ck_assert_msg()`. You can find an empty test skeleton at [auto_tests/skeleton_test.c](https://github.com/TokTok/c-toxcore/blob/master/auto_tests/skeleton_test.c).

**Comment by iphydf** [comment]
@yurivict if you enable the checkbox, we can add the test case for you if you're unable to do so.

**Comment by yurivict** [comment]
"Allow edits from maintainers." is on.
Sorry, I can't do this right now.

**Comment by iphydf** [comment]
I won't have time to add a test case. Once you're available again, please add one.

**Comment by iphydf** [comment]
Let's merge it with a TODO for a test case.

**Comment by robinlinden** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/500#-:-L0_tMFtueSYwe2JnIrt:b-uwkowd)*

**Pull request merged**
