### PR TITLE
Fix most TSAN failures

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1346)

### CODE REVIEW

**Comment by zugz** [comment]
crypto_kill is also called in various places in friend_connection.c, did 
you check that the locking isn't needed there either?

I see what you mean about copying mutexes to avoid deleting them being 
invalid, but the current behaviour of destroying a crypto_connection 
mutex only on reallocating is used in a few places, so just removing it 
like this breaks things. Namely: create_crypto_connection doesn't 
initialise a fresh mutex if no reallocation is needed, because it 
expects there to already be one, and in various places the status is set 
to CRYPTO_CONN_NO_CONNECTION without the mutex being destroyed, because 
it's expected that it will be destroyed on reallocation.

The rest looks good.

**Comment by sudden6** [comment]
Reallocating structures with mutexes is also not going to work see: https://stackoverflow.com/questions/14614523/can-a-pthread-mutex-t-be-moved-in-memory so you found another area where fixes are needed :(

About `crypto_kill` you're right, I'll extract the part doing the actual cleanup and call that instead of `crypto_kill` in the appropriate part.

**Comment by sudden6** [comment]
I dropped the changes for `crypto_kill`, because this needs more thought and probably some restructuring in `net_crypto.c`. It's also only a false positive as far as I can tell, because when `tox_kill` is called, no other threads are allowed to run anymore.

**Comment by zugz** [comment]
There seem to be a couple of problems with the new handling of 
conn->mutex. I find it most convenient to describe these by means of 
patches; I hope that's ok. Please see zugz/fix_tsan.

**Comment by zugz** [comment]
(A)  There are a couple of problems in create_crypto_connections (fixed 
in my branch referred to above):

1. The connections_mutex isn't locked in the first 'for' block, even 
though it is touching crypto_connections and the mutex is unlocked 
there.

2. The two malloc fail error paths don't unlock the mutex.


(B)  I would remove the comment
"// free memory before destroying the pointer to prevent a leak",
since it seems pretty obvious what the point of the free is.


(C)  I am rather worried that the mutex might be destroyed in 
wipe_crypto_connection while another thread is locking it. At least, 
I don't see any obvious proof that this won't happen. This bug, if bug 
it is, already existed -- but now you destroy more frequently, which 
might tickle it.


(D)  It doesn't seem to be clear that wipe_crypto_connection won't get 
called in crypto_kill on an already wiped connection, leading to 
a double-free.


One way to deal with these last two issues would be to never destroy or 
free these mutexes -- so never shrink crypto_connections, and as before 
just set status to CRYPTO_CONN_NO_CONNECTION to indicate that a slot and 
its mutex can be reused for a new connection. If I understand the code 
correctly, crypto_connections is only used for actual 
friend_connections, so this grow-only behaviour shouldn't introduce or 
worsen an attack vector. It's a little inelegant, but better than 
risking undefined behaviour.

**Comment by sudden6** [comment]
I seem to break something with the last commit, need to investigate.

**Comment by sudden6** [comment]
Checking the return value of `crypto_connection_status(...)` was causing test fails. Since it wasn't checked before I removed it again, but AFAICT this is a definite bug.

**Comment by zugz** [comment]
Please see zugz/fix_tsan.

**Comment by sudden6** [comment]
> // REVIEW: why was the test
// (conn->status == CRYPTO_CONN_ESTABLISHED)
// removed here by commit cab510a5c4c9c22038c7c767df0afbcaef7dce6c?

This should be adressed by https://github.com/TokTok/c-toxcore/pull/1346/commits/78c1736f1f9da3cbb12bf52cf9124e6775220b27

> // REVIEW: are you sure we shouldn't set direct_connected and online_tcp_relays in this case anyway?

No, I'm not sure, but before that the values weren't set on some exit paths either, so I choose to keep it that way.

**Comment by zugz** [comment]
>> // REVIEW: are you sure we shouldn't set direct_connected and 
>> online_tcp_relays in this case anyway?
>
>No, I'm not sure, but before that the values weren't set on some exit 
>paths either, so I choose to keep it that way.

Previously they were set for all status values other than NO_CONNECTION. 

I haven't checked in detail, but it looks like this is important -- 
send_packet_to does get called for connections in other states, e.g. in 
handle_packet_connection.

So it looks like we should preserve this behaviour, i.e. return early 
only when conn==nullptr.

**Comment by sudden6** [comment]
Changed it as you suggested. Note that the required check if the connection is initialized is already performed in `get_crypto_connection(...)`.

**Comment by zugz** [comment]
* Sunday, 2019-12-08 at 07:16 -0800 - sudden6 <notifications@github.com>:

>> // REVIEW: why was the test
>// (conn->status == CRYPTO_CONN_ESTABLISHED)
>// removed here by commit cab510a5c4c9c22038c7c767df0afbcaef7dce6c?
>
>This should be adressed by https://github.com/TokTok/c-toxcore/pull/1346/commits/78c1736f1f9da3cbb12bf52cf9124e6775220b27

Not exactly, because crypto_connection_status returning true doesn't 
imply that the status is CRYPTO_CONN_ESTABLISHED. So probably this 
explicit test should be reintroduced in do_tcp. Also the documentation 
on crypto_connection_status is misleading.

I've gone through the whole PR again, and other than the above it all 
looks good.

**Comment by zugz** [comment]
One last little thing: I think you can now get rid of both the FIXMEs 
about checking the crypto_connection_status return value; in both cases, 
the tests for direct_connected and/or online_tcp_relays suffice.

**Comment by sudden6** [comment]
IMO the FIXME's should stay, the whole `net_crypto` thing is quite inconsistent in its internal API with regards to return values, so if it's sanitized in the future I don't want to miss these.

**Comment by zugz** [comment]
>IMO the FIXME's should stay

OK

**Pull request merged**
