### PR TITLE
Update rpm spec and use variables in cmake instead of hardcoded paths

### PR DESCRIPTION
**Pull request by Nyoroon**
Update rpm spec and use variables in cmake instead of hardcoded paths.

How to use:

0. `yum groupinstall -y 'Development Tools' && yum install -y epel-release rpm-build && rpmdev-setuptree`
1. `cmake ${TOXCORE_SOURCES}` to generate toxcore.spec from template
2. `spectool --get-files --sourcedir toxcore.spec` <- will not work before merge, use that from my branch: `git archive --prefix 'c-toxcore-0.1.10/' -o ~/rpmbuild/SOURCES/v0.1.10.tar.gz HEAD`
3. `rpmbuild -bb toxcore.spec`

Maybe setup autobuild on tags/commits?

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/624)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[other/rpm/toxcore.spec.in, line 53 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-Kzob4Zft05wjttqwEqb:-Kzob4Zft05wjttqwEqc:bnvbsl5) ([raw file](https://github.com/toktok/c-toxcore/blob/a0e36d3ec2f13c263592ce51587321b2624faa4a/other/rpm/toxcore.spec.in#L53)):*
> ```
> 
> %install
> %{__make} install DESTDIR=%{buildroot}
> ```

you can use `%make_install` for this step

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/624)*

**Comment by Nyoroon** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[other/rpm/toxcore.spec.in, line 53 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-Kzob4Zft05wjttqwEqb:-Kzof_Hl8IMP3Ts13-od:b-bty3v8) ([raw file](https://github.com/toktok/c-toxcore/blob/a0e36d3ec2f13c263592ce51587321b2624faa4a/other/rpm/toxcore.spec.in#L53)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

you can use `%make_install` for this step
</blockquote></details>

Sure. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/624)*

**Comment by Nyoroon** [comment]
Here's that spec built in COPR: https://copr.fedorainfracloud.org/coprs/smokedcheese/toxcore/packages/

**Comment by sudden6** [comment]
Reviewed 2 of 10 files at r1.
Review status: 2 of 10 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[other/bootstrap_daemon/tox-bootstrapd.service, line 11 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-L-O4JP9Np33WJmSR30i:-L-O4JP9Np33WJmSR30j:bxx4yw0) ([raw file](https://github.com/toktok/c-toxcore/blob/05c35462f3228e4814a29409bed38dcf76afcab3/other/bootstrap_daemon/tox-bootstrapd.service#L11)):*
> ```
> PIDFile=/var/run/tox-bootstrapd/tox-bootstrapd.pid
> WorkingDirectory=/var/lib/tox-bootstrapd
> ExecStart=/usr/local/bin/tox-bootstrapd --config /etc/tox-bootstrapd.conf
> ```

This change also affects non RPM builds, I don't think it's a good idea to install into `/usr/*` by default.

---

*[other/pkgconfig/libtoxav.pc.in, line 2 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-L-O4kKm1luj_OluggHs:-L-O4kKm1luj_OluggHt:bk5v4da) ([raw file](https://github.com/toktok/c-toxcore/blob/05c35462f3228e4814a29409bed38dcf76afcab3/other/pkgconfig/libtoxav.pc.in#L2)):*
> ```
> prefix=@CMAKE_INSTALL_PREFIX@
> libdir=${prefix}/lib
> ```

This change breaks autotools builds @robinli when do we want to switch to cmake only?

---

*[other/pkgconfig/libtoxcore.pc.in, line 3 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-L-O5A9QNduWXL7wXOgs:-L-O5A9QNduWXL7wXOgt:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/05c35462f3228e4814a29409bed38dcf76afcab3/other/pkgconfig/libtoxcore.pc.in#L3)):*
> ```
> prefix=@CMAKE_INSTALL_PREFIX@
> libdir=${prefix}/lib
> includedir=${prefix}/include
> ```

same

---

*[other/pkgconfig/toxav.pc.in, line 3 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-L-O5B85GMojsWeiSPf6:-L-O5B85GMojsWeiSPf7:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/05c35462f3228e4814a29409bed38dcf76afcab3/other/pkgconfig/toxav.pc.in#L3)):*
> ```
> prefix=@CMAKE_INSTALL_PREFIX@
> libdir=${prefix}/lib
> includedir=${prefix}/include
> ```

same

---

*[other/pkgconfig/toxcore.pc.in, line 3 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-L-O5CJ61YT_sPwd0Fkb:-L-O5CJ61YT_sPwd0Fkc:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/05c35462f3228e4814a29409bed38dcf76afcab3/other/pkgconfig/toxcore.pc.in#L3)):*
> ```
> prefix=@CMAKE_INSTALL_PREFIX@
> libdir=${prefix}/lib
> includedir=${prefix}/include
> ```

same

---

*[other/pkgconfig/toxdns.pc.in, line 3 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-L-O5DHlP1_DhOiSDCoW:-L-O5DHlP1_DhOiSDCoX:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/05c35462f3228e4814a29409bed38dcf76afcab3/other/pkgconfig/toxdns.pc.in#L3)):*
> ```
> prefix=@CMAKE_INSTALL_PREFIX@
> libdir=${prefix}/lib
> includedir=${prefix}/include
> ```

same

---

*[other/pkgconfig/toxencryptsave.pc.in, line 3 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-L-O5EGitK9Ki62_CtKC:-L-O5EGitK9Ki62_CtKD:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/05c35462f3228e4814a29409bed38dcf76afcab3/other/pkgconfig/toxencryptsave.pc.in#L3)):*
> ```
> prefix=@CMAKE_INSTALL_PREFIX@
> libdir=${prefix}/lib
> includedir=${prefix}/include
> ```

same

---

*[other/rpm/toxcore.spec.in, line 18 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-L-O5FoYY16G8Pj1gvjg:-L-O5FoYY16G8Pj1gvjh:b-ljg34g) ([raw file](https://github.com/toktok/c-toxcore/blob/5565184501df6dd272ebed0e9d395aa945006cf1/other/rpm/toxcore.spec.in#L18)):*
> ```
> 
> %description
> With the rise of governmental monitoring programs, Tox, a FOSS initiative, aims to be an easy to use, all-in-one communication platform that ensures their users full privacy and secure message delivery.
> ```

Limit to 80 chars per line maybe?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/624)*

**Comment by Nyoroon** [comment]
Review status: 2 of 10 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[other/pkgconfig/libtoxav.pc.in, line 2 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-L-O4kKm1luj_OluggHs:-L-O6L6nfA_WSREsytgX:b-o0730m) ([raw file](https://github.com/toktok/c-toxcore/blob/05c35462f3228e4814a29409bed38dcf76afcab3/other/pkgconfig/libtoxav.pc.in#L2)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

This change breaks autotools builds @robinli when do we want to switch to cmake only?
</blockquote></details>

Files for autotools are in project root (/libtoxcore.pc.in and /libtoxav.pc.in) AFAIK https://github.com/TokTok/c-toxcore/blob/master/configure.ac#L702

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/624)*

**Comment by sudden6** [comment]
Reviewed 6 of 10 files at r1.
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[other/pkgconfig/libtoxav.pc.in, line 2 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-L-O4kKm1luj_OluggHs:-L-QyfeuZ_rCmcLROKXK:b-xa3hge) ([raw file](https://github.com/toktok/c-toxcore/blob/05c35462f3228e4814a29409bed38dcf76afcab3/other/pkgconfig/libtoxav.pc.in#L2)):*
<details><summary><i>Previously, Nyoroon (Smoked Cheese) wrote…</i></summary><blockquote>

Files for autotools are in project root (/libtoxcore.pc.in and /libtoxav.pc.in) AFAIK https://github.com/TokTok/c-toxcore/blob/master/configure.ac#L702
</blockquote></details>

ok right, I wonder if it's good to have two versions of these files though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/624)*

**Comment by Nyoroon** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[other/rpm/toxcore.spec.in, line 18 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-L-O5FoYY16G8Pj1gvjg:-L0BRzgA7zIzVbqaIJTv:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/5565184501df6dd272ebed0e9d395aa945006cf1/other/rpm/toxcore.spec.in#L18)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Limit to 80 chars per line maybe?
</blockquote></details>

Done.

---

*[other/bootstrap_daemon/tox-bootstrapd.service, line 11 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-L-O4JP9Np33WJmSR30i:-L0BS13QW7i94ic-swkw:b-srmf2i) ([raw file](https://github.com/toktok/c-toxcore/blob/05c35462f3228e4814a29409bed38dcf76afcab3/other/bootstrap_daemon/tox-bootstrapd.service#L11)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

This change also affects non RPM builds, I don't think it's a good idea to install into `/usr/*` by default.
</blockquote></details>

Copied service file in rpm directory for distribution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/624)*

**Comment by Nyoroon** [comment]
How to build without cmake:
1. `cd other/rpm`
2. `make srpm`
3. `mock --rebuild *.src.rpm` or any other way to build srpm

**Comment by robinlinden** [comment]
Reviewed 8 of 10 files at r1, 3 of 5 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/624)*

**Comment by sudden6** [comment]
sorry, forgot about this, :lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-:-L0_nBu2VhOt1TCsAE7x:b-ltjtuk)*

**Comment by Nyoroon** [comment]
Rebased on last master.
Should we call package "toxcore" or "c-toxcore"?

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 5 files at r3, 1 of 2 files at r4, 4 of 9 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-:-L2UrfFhv0FLRXiWK1-8:b-jbsf8z)*

**Comment by iphydf** [comment]
"toxcore" is fine.

**Comment by iphydf** [comment]
@Nyoroon the circle ci build fails. If that breakage is intentional, please update the config.

**Comment by iphydf** [comment]
Looks good. Can you squash the two commits into a single commit?

**Comment by iphydf** [comment]
And also rebase on master.

**Comment by iphydf** [comment]
:lgtm_strong:

---

Review status: 4 of 8 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/624#-:-L2qXJy9HlS5Jx6cpdEB:b-jbsf8z)*

**Comment by iphydf** [comment]
Reviewed 2 of 5 files at r3, 1 of 2 files at r4, 1 of 9 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/624)*

**Pull request merged**
