### PR TITLE
Fix bootstrap crashes, still

### PR DESCRIPTION
**Pull request by cotox**
@iphydf This is the fix of PR #892.

PS, #892 didn't fix the crash issue.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/893)

### CODE REVIEW

**Comment by cotox** [comment]
Replay script of *the crash* (of PR #892),

* The crash of `DHT_bootstrap`

  Launch commands,

  ```bash
  ( mkdir -p _build_crash \
    && cd _build_crash \
    && cmake .. \
    && make \
    && ./DHT_bootstrap )
  ```

  The last lines in output,

  ```
  ...
  [ 99%] Built target DHT_bootstrap
  [100%] Built target Messenger_test
  Initialization: Success
  Keys loaded successfully.
  Public key: 841A6BDE1E92D657D5D86100CCE717180B29846F047D07791F82DA2329E6FE57
  Port: 33445
  Connected to other bootstrap node successfully.
  DHT_bootstrap: /home/cotox/tox-stuff/c-toxcore/toxcore/logger.c:106: logger_write: Assertion `!"NULL logger not permitted"' failed.
  [1]    5717 abort (core dumped) ...
  ```

* The crash of `tox-bootstrapd`

  Launch commands,

  ```bash
  ( mkdir -p _build_crash \
    && cd _build_crash \
    && cmake .. \
    && make \
    && ./tox-bootstrapd --foreground --log-backend=stdout --config=/etc/tox-bootstrapd.conf )
  ```

  The last lines in output,

  ```
  ...
  Running "tox-bootstrapd" version 2016010100.
  Successfully read:
  'pid_file_path': ./tox-bootstrapd.pid
  'keys_file_path': ./keys
  'port': 33445
  'enable_ipv6': false
  'enable_ipv4_fallback': true
  'enable_lan_discovery': true
  'enable_tcp_relay': true
  Read 2 TCP ports:
  Port #0: 3389
  Port #1: 33445
  'enable_motd': true
  'motd': tox-bootstrapd
  General config read successfully
  Set MOTD successfully.
  Keys are managed successfully.
  Initialized Tox TCP server successfully.
  Successfully added bootstrap node #0: node.tox.biribiri.org:33445 F404ABAA1C99A9D37D61AB54898F56793E1DEF8BD46B1038B9D822E8460FAB67
  List of bootstrap nodes read successfully.
  Public Key: 9A738332FC5C85C9FE3FD19FA825286E116FFF87DF13C92E17B4D75B51D12555
  Initialized LAN discovery successfully.
  Connected to another bootstrap node successfully.
  tox-bootstrapd: /home/cotox/tox-stuff/c-toxcore/toxcore/logger.c:106: logger_write: Assertion `!"NULL logger not permitted"' failed.
  [1]    10014 abort (core dumped) ...
  ```

**Comment by iphydf** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[other/DHT_bootstrap.c, line 148 at r1](https://reviewable.io/reviews/toktok/c-toxcore/893#-LD0ZOLsCnFd_xY3iCkQ:-LD0ZOLsCnFd_xY3iCkR:b-35xqif) ([raw file](https://github.com/toktok/c-toxcore/blob/21675ce0d2581597b0e0a727ab4cf6cfb796a037/other/DHT_bootstrap.c#L148)):*
> ```C
>         exit(1);
>     }
> ```

Undo removal of empty line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/893#-:-LD0ZLRn56RE8nV6QNq-:b-jbsf8z)*

**Comment by cotox** [comment]
@iphydf I've add a `print_log()`. I'm not sure is it right. Please review again. Thanks a lot.

@nurupo Thanks for your review in #891. I changed the algorithm cause 891 is [not go in right way](https://github.com/TokTok/c-toxcore/pull/891#issuecomment-390561615). Can you help me on this one?

**Comment by iphydf** [comment]
I'd prefer to have a fix committed, and then look at printing the log messages. The fix at the time I LGTM'd it was non-contentious.

**Comment by cotox** [comment]
OK, I rolled back.

**Comment by nurupo** [comment]
We didn't pass the logger into the network module, huh. Is there anything else that takes a logger?

Squash commits?

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/893#-:-LD2Piua6ZTpa8V0tkwS:bpot07v)*

**Comment by nurupo** [comment]
>Is there anything else that takes a logger?

Checked tox-bootstrapd's usage of `nullptr`, doesn't look like there is anything else that needs a logger.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/893#-:-LD2QV6b8WEXwCqOjeNO:b-7tchtf)*

**Comment by cotox** [comment]
> Is there anything else that takes a logger?
Should we output the log in DEBUG/TRACE?

**Comment by iphydf** [comment]
Please create this PR again, with a single commit, not 3.

**Comment by cotox** [comment]
OK. Sorry for bother.

**Pull request merged**
