### PR TITLE
Add new file kind for stickers.

### PR DESCRIPTION
**Pull request by SkyzohKey**
This pull-request introduce a new file kind for stickers, inline_images and voicemail.

**Unblocks**: 
- Antox/Antox#250
- qTox/qTox#402
- SkyzohKey/Konv#10

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/519)

### CODE REVIEW

**Comment by SkyzohKey** [comment]
Assigned people that contribute to clients, so we all can decide whether or not we need this. IMHO, as I made the PR (Ok, @Grayhatter did it a long time ago) i'm obviously for that getting merged.

**Comment by dvor** [comment]
Generally I like the idea of adding stickers to Tox.

Maybe it makes sense to add some size limits for stickers? This check can be done in toxcore for compatibility, e.g. refuse all sticker transfers that have file size bigger than some number.

What about other proposed features like animated stickers, sharing sticker packs with friends, etc.? IMO it would be better to think over and implement whole stickers feature together, instead of adding small peaces of functionality like that.

**Comment by GrayHatter** [comment]
https://github.com/SkyzohKey/c-toxcore/blob/dd37cd37fd490acd7c0ab9c7b8b57f1563187be4/toxcore/tox.h#L36-L40

**Comment by SkyzohKey** [comment]
@grayhatter i see, I'll push a fix commit soon

**Comment by iphydf** [comment]
Please enable the checkbox "Allow edits from maintainers." on the bottom right.

Also, I'd prefer to call this INLINE rather than STICKER. You could imagine short voice messages being of type INLINE as well, and showing up as playable message in the chat.

**Comment by iphydf** [comment]
Bumped to 0.1.9 because this seems to be controversial, so will require some more discussion.

**Comment by yurivict** [comment]
Where will sticker images come from in the clients? Are they copyright?

**Comment by SkyzohKey** [comment]
@GrayHatter Fixed.
@iphydf Checked the box + added all the types Grayhatter had already proposed.
@yurivict Please refer to the [stickers page](https://wiki.tox.chat/developers/feature_ideas/stickers) on the Tox wiki.

**Comment by iphydf** [comment]
@SkyzohKey you've deleted your repo?

**Comment by iphydf** [comment]
I think just an INLINE type would be enough.

**Comment by iphydf** [comment]
Can you make a PR with an INLINE type? And also, discuss it with antox etc?

**Pull request closed without merging**
