### PR TITLE
Add test for DHT pack_nodes and unpack_nodes

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/512)

### CODE REVIEW

**Comment by iphydf** [comment]
Please enable the checkbox "Allow edits from maintainers." on the bottom right.

**Comment by Diadlo** [comment]
Done

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[auto_tests/dht_test.c, line 686 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/512#-KhZ0-O3SqlOnQ1WLp5t:-KhZ0-O3SqlOnQ1WLp5u:b-g8a4kl) ([raw file](https://github.com/toktok/c-toxcore/blob/9bac656cc3494367f2b745f5e3cac1c309567c89/auto_tests/dht_test.c#L686)):*
> ```C
>     int unpacked_count = unpack_nodes(nodes_unpacked, size, &processed, data, length, tcp_enabled);
>     ck_assert_msg(unpacked_count == size, "Wrong unpack_nodes result");
>     ck_assert_msg(processed == packed_size, "unpack_nodes processed not all data");
> ```

"unpack_nodes did not process all data"

---

*[auto_tests/dht_test.c, line 691 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/512#-KhZ-xFRGCAYRG2KHeP9:-KhZ-xFRGCAYRG2KHePA:b-90ooza) ([raw file](https://github.com/toktok/c-toxcore/blob/9bac656cc3494367f2b745f5e3cac1c309567c89/auto_tests/dht_test.c#L691)):*
> ```C
>         const IP_Port *ipp1 = &nodes[i].ip_port;
>         const IP_Port *ipp2 = &nodes_unpacked[i].ip_port;
>         ck_assert_msg(ip_equal(&ipp1->ip, &ipp2->ip), "Unsucessful ip unpack");
> ```

"Unsuccessful" (3 times)

---

*[auto_tests/dht_test.c, line 719 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/512#-KhZ06Dt3U5K4Bx8buzH:-KhZ06Dt3U5K4Bx8buzI:b-7mo7f4) ([raw file](https://github.com/toktok/c-toxcore/blob/9bac656cc3494367f2b745f5e3cac1c309567c89/auto_tests/dht_test.c#L719)):*
> ```C
>     random_bytes(ip, size);
>     ipp->ip.family = family;
> ```

Remove empty line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/512)*

**Comment by robinlinden** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/512)*

**Comment by iphydf** [comment]
:lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/512#-:-KhZ6VGbOeqeHATjeOW-:bg7igkv)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/512#-:-KhZBwvu0ws1uDVKSW6u:b-jbsf8z)*

**Comment by robinlinden** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/512)*

**Pull request merged**
