### PR TITLE
Fixed the FreeBSD build failure due to the undefined MSG_NOSIGNAL.

### PR DESCRIPTION
**Pull request by yurivict**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/424)

### CODE REVIEW

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/424#-:-KaPE0Iyx_62zOFO-OeR:b-jbsf8z)*

**Comment by endoffile78** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/424#-:-KaPV2HRR1AjIn0J0nVQ:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/424#-:-KaceTZqJail8OZd1hZ3:b-jbsf8z)*

**Comment by sudden6** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/424)*

**Pull request merged**
