### PR TITLE
fix: Fix memory leak in the error path of loading savedata.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2424)

### CODE REVIEW

**Review by JFreegman — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2424)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by nurupo — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2424)* status: :shipit: complete! 2 of 1 approvals obtained

**Comment by nurupo** [comment]
Huh, how did this still use `free()` when all other parts of the code around it were changed to `mem_delete()`

**Comment by JFreegman** [comment]
> Huh, how did this still use `free()` when all other parts of the code around it were changed to `mem_delete()`

This is a 2 year old PR. I forgot to incorporate some recent changes into it, such as that, and groupchats.

**Comment by nurupo** [comment]
Ok, makes sense. Was confused how did iphy skip that during his `mem` refactor, but it's a new commit from a old PR.

**Pull request merged**
