### PR TITLE
cleanup: align group send err enum order

### PR DESCRIPTION
**Pull request by Green-Sky**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2731)

### CODE REVIEW

**Review by iphydf — APPROVED** [review]

**Comment by zoff99** [comment]
we should pin enums with values. now this PR changes the actual int value of the enum, doesnt it?

**Comment by zoff99** [comment]
@iphydf @Green-Sky can't we do something like this (at least of all public enums in tox.h and toxav.h) :

```
typedef enum Tox_Err_Group_Send_Private_Message {

    TOX_ERR_GROUP_SEND_PRIVATE_MESSAGE_OK = 0,
    TOX_ERR_GROUP_SEND_PRIVATE_MESSAGE_GROUP_NOT_FOUND = 1,
    TOX_ERR_GROUP_SEND_PRIVATE_MESSAGE_PEER_NOT_FOUND = 2,
    TOX_ERR_GROUP_SEND_PRIVATE_MESSAGE_TOO_LONG = 3,
    TOX_ERR_GROUP_SEND_PRIVATE_MESSAGE_EMPTY = 4,
    TOX_ERR_GROUP_SEND_PRIVATE_MESSAGE_BAD_TYPE = 5,
    TOX_ERR_GROUP_SEND_PRIVATE_MESSAGE_PERMISSIONS = 6,
    TOX_ERR_GROUP_SEND_PRIVATE_MESSAGE_FAIL_SEND = 7,
    TOX_ERR_GROUP_SEND_PRIVATE_MESSAGE_DISCONNECTED = 8

} Tox_Err_Group_Send_Private_Message;
```

the we can reorder how we like. with OK always must be (zero) "0"

**Comment by iphydf** [comment]
Enums can't be removed or reordered without breaking API or ABI, correct. This is why we're doing it now, before the release. What would be improved by pinning the numbers?

**Comment by zoff99** [comment]
other question is, what would be worse? with pinning the numbers will be fixed, even when we would delete an entry in the enum. now you can't delete an entry without having to break things

**Comment by iphydf** [comment]
With numbers, you can't delete members either, because each name is part of the API.

**Pull request merged**
