### PR TITLE
Separate FreeBSD Travis build in 2 stages

### PR DESCRIPTION
**Pull request by nurupo**
We need to pass different argument to the FreeBSD script for stage 1 and 2 so that it could do different things in each stage. The way you would usually do this is by adding a new variable to `env`, but we can't do that because in order for two jobs to share cache they must have identical `env` (among other things like compiler, os, etc.), so I call the scripts directly with an extra argument, as this avoid messing with `env`.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/635)

### CODE REVIEW

**Comment by nurupo** [comment]
The last commit was made purely to see if FreeBSD build succeeds, it should be removed before PR is merged.

**Comment by nurupo** [comment]
[It looks like it does work](https://travis-ci.org/TokTok/c-toxcore/builds/315212091).

**Comment by nurupo** [comment]
Should be ready for review.

**Comment by sudden6** [comment]
Do you think it makes sense to include a hash with the image like you did in the qTox repo? So that when the build scripts change, the image is automatically rebuilt.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/635#-:-L09Q2ZoBJP1QJmvgsI5:btmzg1z)*

**Comment by sudden6** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[.travis.yml, line 24 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/635#-L09RHlkpHguwJwgdZDg:-L09RHlkpHguwJwgdZDh:b757iha) ([raw file](https://github.com/toktok/c-toxcore/blob/21cad79a9c635a05098d4da33ffd5b4acd50a858/.travis.yml#L24)):*
> ```YAML
>     sudo: required
>     install:       other/travis/phase $JOB $ENV install       stage1
>     script:        other/travis/phase $JOB $ENV script        stage1
> ```

I think this can be removed, along with the script that does nothing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/635)*

**Comment by nurupo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[.travis.yml, line 24 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/635#-L09RHlkpHguwJwgdZDg:-L0B3mX-_2faR71lS355:b-tbk9fe) ([raw file](https://github.com/toktok/c-toxcore/blob/21cad79a9c635a05098d4da33ffd5b4acd50a858/.travis.yml#L24)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think this can be removed, along with the script that does nothing?
</blockquote></details>

No, neither of those can be removed. Without having `stage1` as an argument, the `phase` script wouldn't run the `freebsd-install-stage1` script. And the script with `exit 0` does something -- it terminates the `phase` script early, preventing it from running `toxcore-script`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/635)*

**Comment by sudden6** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[.travis.yml, line 24 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/635#-L09RHlkpHguwJwgdZDg:-L0B9XXbkhXXdmWNAtcY:b-5at9nj) ([raw file](https://github.com/toktok/c-toxcore/blob/21cad79a9c635a05098d4da33ffd5b4acd50a858/.travis.yml#L24)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

No, neither of those can be removed. Without having `stage1` as an argument, the `phase` script wouldn't run the `freebsd-install-stage1` script. And the script with `exit 0` does something -- it terminates the `phase` script early, preventing it from running `toxcore-script`.
</blockquote></details>

I'm talking specifically about the `script` line. If it's not there it shouldn't call anything right? Or is there something I'm missing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/635)*

**Comment by nurupo** [comment]
>Do you think it makes sense to include a hash with the image like you did in the qTox repo? So that when the build scripts change, the image is automatically rebuilt.

Don't think it would be as useful as in the qTox case, but I can add it. We don't need to rebuild the image if any of freebsd scripts are changed though, we have to watch only for changes in `freebsd-install-stage1`, since it's the only script that creates the VM image, other scripts just use it.

**Comment by nurupo** [comment]
Btw, in case you are confused with how the execution flow works

- Stage 1
  - install
    - `env.sh` <-- defines common variables and functions for `toxcore-script` to work
    - `env-freebsd.sh` <-- defines FreeBSD-specific common variables and functions for `toxcore-script` to work
    - `freebsd-install` <-- defines common variables and functions for `freebsd-install-stageN` scripts
    - `freebsd-install-stage1` <-- creates/updates FreeBSD VM image if needed
  - script
    - `env.sh`
    - `env-freebsd.sh`
    - `freebsd-script-stage1` <-- terminates the `phase` script early so that `toxcore-script` doesn't run in Stage 1
    - (if not for the `freebsd-script-stage1` above, `toxcore-script` would have ran here)
  - after_script
    - `env.sh`
    - `env-freebsd.sh`
- Stage 2
  - install
    - `env.sh`
    - `env-freebsd.sh`
    - `freebsd-install`
    - `freebsd-install-stage2` <-- copies toxcore's code inside FreeBSD VM so that `toxcore-script` could be run
  - script
    - `env.sh`
    - `env-freebsd.sh`
    - `toxcore-script` <-- builds toxcore inside FreeBSD
  - after_script
    - `env.sh`
    - `env-freebsd.sh`

**Comment by sudden6** [comment]
Is `toxcore-script` called by this line: https://github.com/nurupo/InsertProjectNameHere/blob/21cad79a9c635a05098d4da33ffd5b4acd50a858/.travis.yml#L68 if you don't do `exit 0`?

**Comment by nurupo** [comment]
Technically it would be called by https://github.com/nurupo/InsertProjectNameHere/blob/21cad79a9c635a05098d4da33ffd5b4acd50a858/.travis.yml#L24 because the earlier `script` command overwrites the later ones. If you remove that `script` command I pointed to, then yes, it would be called by the one you have pointed out.

We don't want to call `toxcore-script`, i.e. build toxcore, in Stage 1 yet because then it will be no different than what Travis does right now and it will exceed the 50 minute limit. The whole idea is to split VM image creating and toxcore building in 2 parts so that we wouldn't be hitting time limits.

**Comment by nurupo** [comment]
I think if you looked into what [`other/travis/phase`](https://github.com/TokTok/c-toxcore/blob/master/other/travis/phase) script does, it would make it a bit more clear to you.

Travis calls `phase`  script 3 or 4 times for every job, 1st time for `install`, second time for `script`, the third time for `after_script` and the fourth time for `after_failure` but only if the build failed. Actually, I'm not sure if it will call `after_script` if the build fails, it might skip it and go straight to `after_failure`, but that doesn't really matter since this PR doesn't deal with any of them.

**Comment by sudden6** [comment]
>because the earlier script command overwrites the later ones.

Didn't know that, now it's clear. Thx for the explanation :)

**Comment by nurupo** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[.travis.yml, line 24 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/635#-L09RHlkpHguwJwgdZDg:-L0BWEFDRxnL1rIgzNKX:b-xw9qyq) ([raw file](https://github.com/toktok/c-toxcore/blob/21cad79a9c635a05098d4da33ffd5b4acd50a858/.travis.yml#L24)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I'm talking specifically about the `script` line. If it's not there it shouldn't call anything right? Or is there something I'm missing?
</blockquote></details>

If you remove this `script` line the one that is defined later in the script will be used and it will call `toxcore-script` trying to build toxcore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/635)*

**Comment by sudden6** [comment]
:lgtm_strong: from my side

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/635#-:-L0BWtRt8A25WfifhRiB:bybplqg)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/635#-:-L0BahTufbH0iIJYfrOV:b-jbsf8z)*

**Comment by nurupo** [comment]
Want me to squash the commits?

**Comment by nurupo** [comment]
Well, I will squash them anyway.

**Comment by nurupo** [comment]
There.

**Comment by nurupo** [comment]
Rebased on top of @Diadlo's `fix_travis_test2` branch (https://github.com/TokTok/c-toxcore/pull/630) by @robinlinden's request on IRC.

**Comment by nurupo** [comment]
Oops, accidentally clicked on the wrong button.

Looks like Windows tests are crashing with stack traces and don't complete fast enough triggering Travis time limit. Did this happen before?

**Comment by nurupo** [comment]
Windows tests are also failing in https://github.com/TokTok/c-toxcore/pull/630, but on master they succeed.

**Comment by robinlinden** [comment]
That's really weird. They weren't failing when I LGTM'd it: https://travis-ci.org/TokTok/c-toxcore/builds/313983843

**Comment by nurupo** [comment]
Actually, it's not that they succeed on master, the tests also fail there, it's just that the jobs don't exceed 50 minutes on master. The test failure is ignored in Windows builds. Those stacktraces might also be Wine bugs, the Wine on Travis must be ancient.

**Comment by nurupo** [comment]
I don't rally understand how Windows jobs that were getting completed in 10 minutes now take over 50. The tests do fail in both cases, so the number of times tests get re-run should be the same. Also, test get killed after certain amount of time, so there shouldn't be any infinite loop keeping them running. I'm somewhat at loss. It would help if Travis didn't truncate the logs.

**Comment by nurupo** [comment]
There is this thing Travis says

>This job is running on our Trusty environment, which has been updated on Tuesday, December 12th, 2017. Read all about this on our blog and take note that you can add group: deprecated-2017Q4 in your .travis.yml file to use the previous image version.

but Windows jobs run in their own environment in Docker, which supposedly should be the same, so I don't think this would have affected them.

**Comment by nurupo** [comment]
Interesting, it looks like the job gets terminated at around 15 minutes of runtime because it outputs too much, but even though Travis says that, it keeps showing the job as running until it gets to 50 minutes.

>The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
>
>The job has been terminated

So it looks like the reason is not in exceeding 50 minute limit but in outputting too much.

**Comment by nurupo** [comment]
Looks like the issue was cased by a newer Docker version on the updated Travis Trusty images. Newer Docker changed networking behaviour in a way that causes toxcore's network module spamming more log messages than it used to. For now I have just made it use older Trusty image on Travis, but the proper fix would be to somehow limit the output of the tests so that total job log doesn't exceed 4mb.

**Comment by sudden6** [comment]
Restarted one failing job, because it was a strange apt error.

**Comment by nurupo** [comment]
Yay, Travis passed.

**Comment by robinlinden** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/635)*

**Comment by robinlinden** [comment]
Merged together with #630, #631, and #632 as Travis required all of them before passing and I'm unable to merge anything without Travis passing.

**Comment by nurupo** [comment]
@CLAassistant is such a necromancer.

**Pull request merged**
