### PR TITLE
Delete outdated files for building toxcore with automake.

### PR DESCRIPTION
**Pull request by pranomostro**
The automake build system is not used any more, so I believe one can safely delete the code
it uses (it isn't mentioned in the docs anymore as well).

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/969)

### CODE REVIEW

**Comment by pranomostro** [comment]
I see that the automake stuff is still in the travis build. Should I delete this PR?

**Comment by sudden6** [comment]
Can we port the NaCl to cmake and discontinue automake?

**Comment by zoff99** [comment]
@sudden6 why always this "discontinue autotools" talk? it doesnt hurt anybody. stop that please

**Comment by pranomostro** [comment]
@zoff99: I was confused because no docs mention it. It is clear to me now, so I'll close this.

**Comment by zoff99** [comment]
thanks. we will try to maintain it, as soon as we have the resouces to.

**Comment by sudden6** [comment]
@zoff99 I don't like having two build systems which do slightly different things for no reason. Since there's apparently a reason (`./do`) it seems now valid.

**Pull request closed without merging**
