### PR TITLE
Make toxcore compile on BSD

### LINKED ISSUE #881: Toxcore does not build with cmake on OpenBSD.
I've taken a look into toxcore/ccompat.h and this is what worries me:
```
#ifdef _WIN32
#include <malloc.h>
#elif defined(__FreeBSD__)
#include <stdlib.h>
#if !defined(alloca) && defined(__GNUC__)
#define alloca __builtin_alloca
#endif
#else
#include <alloca.h>
#endif
```
As far as I know <alloca.h> is a Linux-specific header (and perhaps also MacOS-specific header). That means toxcore works only at Windows, Linux and FreeBSD...
@iphydf Do you know that alloca(3) and malloc(3) are supposed to be at <stdlib.h> at any OS, including Windows and Linux? So this should work not only for FreeBSD:
```
-#ifdef _WIN32
-#include <malloc.h>
-#elif defined(__FreeBSD__)
 #include <stdlib.h>
 #if !defined(alloca) && defined(__GNUC__)
 #define alloca __builtin_alloca
 #endif
-#else
-#include <alloca.h>
-#endif
```
But quickly patching that doesn't help, I get a spam of undefined references: https://pastebin.com/raw/NbrasTWR
What have you done? You made toxcore completely non portable!

### PR DESCRIPTION
**Pull request by endoffile78**
Fixes #881

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/883)

### CODE REVIEW

**Comment by mazocomp** [comment]
@endoffile78 

toxcore/ccompat.h won't compile, for example, at NetBSD, I suggest:
```
#ifdef _WIN32
#include <malloc.h>
#elif defined(__linux__)
#include <alloca.h>
#else
#include <stdlib.h>
#if !defined(alloca) && defined(__GNUC__)
#define alloca __builtin_alloca
#endif
#endif
```

I am not sure about Mac OS, but according to https://www.manpagez.com/man/3/alloca/ Mac OS requires either <stdlib.h> or <alloca.h>, so this #ifdef maze should suit most.

**Comment by endoffile78** [comment]
@mazocomp Fixed.

**Comment by nurupo** [comment]
@endoffile78 could you test it on all build machines? It makes sense to do so for this PR.

e.g.

```bash
sed -i '/if: type IN (push, api, cron)/d' .travis.yml
git commit -am "Build all"
git push ...
```

Wait for Travis to build, fix any issues that arise, and if all good, post a link to the Travis build matrix in comments and remove the "Build all" commit with a forced-push.

**Comment by endoffile78** [comment]
https://travis-ci.org/TokTok/c-toxcore/builds/370653505

**Comment by nurupo** [comment]
The builds look good.

**Comment by mazocomp** [comment]
I am surpriced how long does it take to merge this simple change...

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/883#-:-LC9jBuM6YU5hf9eWL7I:b-jbsf8z)*

**Pull request merged**
