### PR TITLE
Create a separate build for running the format tests

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/374)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/374#-:-K_U2HIcMktb1qTMMWHk:b-jbsf8z)*

**Comment by iphydf** [comment]
This adds 1.5 minutes to the total build time. Can we put the formatting check at the beginning of the build (in addition to it being a test for the local use case)? That way, it'll terminate early with incorrect formatting.

The real fix is this: https://github.com/TokTok/github-tools/issues/36

**Comment by GrayHatter** [comment]
@iphydf I'm not sure what you're asking for here? can you enumerate the changes you want?

**Comment by iphydf** [comment]
- Remove the new build.
- Add `other/astyle/format-source` to early in the cmake build. format-source already exits with error on diff.

**Comment by iphydf** [comment]
Once you do that, rename the PR (and commit).

**Comment by iphydf** [comment]
Moved to #450.

**Pull request closed without merging**
