### PR TITLE
Add missing MAX_HOSTNAME_LENGTH doc.

### PR DESCRIPTION
**Pull request by cotox**
Added missing API description of add_tcp_relay().

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/953)

### CODE REVIEW

**Comment by iphydf** [comment]
:lgtm_strong:

Please make the PR title more descriptive. It ends up in our changelog and release notes.

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/953#-:-LFwc8IABa_mPHfdVY_k:bj1b80p)*

**Comment by iphydf** [comment]
This PR now needs rebase + conflict resolution.

**Comment by cotox** [comment]
@iphydf 

> Please make the PR title more descriptive. It ends up in our changelog and release notes.

- [x] Fixed.

> This PR now needs rebase + conflict resolution.

- [X] Fixed.

Please review again. Thanks a lot.

**Comment by cotox** [comment]
Hi @iphydf,

Please help me to merge the branch into mster. I can't do it, because it reports:

```
> git push toktok master
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "coverage/coveralls" is expected.
To github.com:TokTok/c-toxcore.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:TokTok/c-toxcore.git'
```

It seems `coverage/coveralls` stuck.

**Pull request merged**
