### PR TITLE
Remove csrc from the RTPHeader struct.

### PR DESCRIPTION
**Pull request by iphydf**
This is not used by anything in the code, so we shouldn't have it in the
header.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/750)

### CODE REVIEW

**Comment by Diadlo** [comment]
Why not make gtest an optional dependency and make this test an optional in cmake?

**Comment by sudden6** [comment]
removal :lgtm_strong: don't know about the tests

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/750#-:-L4MoDaKBb0ruf3JqJEq:b67eun5)*

**Comment by sudden6** [comment]
Reviewed 2 of 7 files at r1.
Review status: 2 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/750)*

**Comment by iphydf** [comment]
Added gtest to cmake. Not running it on travis.

**Comment by iphydf** [comment]
It's not required for compiling it, but maybe for compiling its tests.

**Comment by iphydf** [comment]
(some of the tests).

**Comment by nurupo** [comment]
I does make sense for a monolith test, but not much for others. Why is `rtp_test.cpp` in C++? Why do we use gtest when we use libcheck in all other tests? This looks very out of place in toxcore.

**Comment by iphydf** [comment]
Why C++ and gtest: it's much easier to write unit tests with it. libcheck is not much more than a glorified printf debugging library. Comparing values, printing them, etc. is spartanic. I'm not going to write more tests with libcheck, I'd rather get rid of it altogether.

Given the opposition, I've removed it from cmake again.

**Comment by iphydf** [comment]
gtest is back in #757, and libcheck is gone in #766.

**Pull request merged**
