### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/613)

### CODE REVIEW

**Comment by Diadlo** [comment]
Seems IPv6 is disabled in Travis. Yey, it's not toxcore issue!
travis-ci/travis-ci#8711

**Comment by sudden6** [comment]
not very familiar with the autotools part, but the rest :lgtm_strong:

---

Reviewed 4 of 5 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/613#-:-Kz9cJ7Ogj0IKEbjug2q:bnc50s5)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 4 of 5 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/613#-:-KzLPW1-3M_ZPth-21Qf:b-jbsf8z)*

**Comment by endoffile78** [comment]
:lgtm_strong:

---

Reviewed 4 of 5 files at r1, 8 of 8 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/613#-:-KzLRj6WDbVf9svfMwy2:b-jbsf8z)*

**Comment by nurupo** [comment]
I think the build flag and the define should have been named more explicitly as to hint that they enable/disable IPv6 only for tests, not for the entire toxcore.

**Pull request merged**
