### PR TITLE
Convert to and from network byte order in set/get nospam.

### LINKED ISSUE #205: nospam value is reversed in array returned by tox_self_get_address()
I have written following example code:

```
#include <stdio.h>
#include <stdlib.h>

#include <tox/tox.h>

int main(void)
{
    size_t i;
    uint8_t addr[TOX_ADDRESS_SIZE];
    char* nns="AABBCCDD";
    uint32_t ns;
    Tox* t;
    struct Tox_Options to;

    tox_options_default(&to);
    t=tox_new(&to, NULL);

    ns=tox_self_get_nospam(t);
    tox_self_get_address(t, addr);

    printf("current addr: ");
    for(i=0; i<TOX_ADDRESS_SIZE; i++)
        printf("%02X", addr[i]);
    putchar('\n');
    printf("current ns: %08X\n", ns);

    ns=strtoul(nns, NULL, 16);

    tox_self_set_nospam(t, ns);

    ns=tox_self_get_nospam(t);
    tox_self_get_address(t, addr);

    printf("current addr: ");
    for(i=0; i<TOX_ADDRESS_SIZE; i++)
        printf("%02X", addr[i]);
    putchar('\n');
    printf("current ns: %08X\n", ns);

    return 0;
}
```

When compiled with
    gcc -o tns tns.c -ltoxcore

and executed, this prints

```
current addr: 5A9712242692889C310A7227CD78D3D9F0F9F5AE9608DDD3640175419093A33368C3A8A5173B
current ns: A5A8C368
current addr: 5A9712242692889C310A7227CD78D3D9F0F9F5AE9608DDD3640175419093A333DDCCBBAAB13B
current ns: AABBCCDD
```

As you can see, the checksum (the addresses last 4 bytes-2) is reversed, instead `AABBCCDD` they are `DDCCBBAA`.

I am running Arch linux, Kernel 4.8.1, gcc 6.2.1, toxcore-toktok-git 3911-1.
If this is intended behaviour, ignore this.

### PR DESCRIPTION
**Pull request by iphydf**
Fixes #205.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/271)

### CODE REVIEW

**Comment by nurupo** [comment]
Does storing the nospam in network byte order internally break anything?
cc @irungentoo

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/271#-:-KWVXbYzSP-YCMaQjbXD:bos80kq)*

**Comment by GrayHatter** [comment]
:lgtm_strong:

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/271#-:-KWVbBzYZb6G1URYqDj7:b-jbsf8z)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/271#-:-KWVZLNdHGBGZrh0Ou0m:b-jbsf8z)*

**Comment by GrayHatter** [comment]
Moved to v0.0.5 -- the review wasn't approved in time.

**Pull request merged**
