### PR TITLE
Make outgoing Filetransfers round-robin.

### PR DESCRIPTION
**Pull request by zoff99**
… others)

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/765)

### CODE REVIEW

**Comment by zoff99** [comment]
#763

**Comment by SkyzohKey** [comment]
@zoff99 Please sign your commits using GPG ;)

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-:-L5Yxfow5mjU6uqOcx-j:b-jbsf8z)*

**Comment by robinlinden** [comment]
:lgtm_strong: with a few style nits. Mostly comments that don't add any value.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[toxcore/Messenger.c, line 1504 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5YyS3OmnXmt8oWOU6f:-L5YyS3OmnXmt8oWOU6g:b-1dc8sw) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1504)):*
> ```C
> }
> 
> int32_t max_s32(int32_t a, int32_t b)
> ```

This can be static.

---

*[toxcore/Messenger.c, line 1509 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5Yyx4WvzZsFKZ3AlIj:-L5Yyx4WvzZsFKZ3AlIk:b-1dc8sw) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1509)):*
> ```C
> }
> 
> uint16_t min_u16(uint16_t a, uint16_t b)
> ```

This can be static.

---

*[toxcore/Messenger.c, line 1536 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5Yz6kIYgt8VufI02LI:-L5Yz6kIYgt8VufI02LJ:b-7bnv3j) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1536)):*
> ```C
>     bool any_active_fts = false;
> 
>     // HINT: iterate over all possible FTs
> ```

This comment isn't really needed.

---

*[toxcore/Messenger.c, line 1540 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5YzA5E_5OdhRqwfeoj:-L5YzA5E_5OdhRqwfeok:b-7bnv3j) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1540)):*
> ```C
>         struct File_Transfers *const ft = &friendcon->file_sending[i];
> 
>         // HINT: is this an active FT?
> ```

This comment isn't really needed.

---

*[toxcore/Messenger.c, line 1545 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5YzBnqrgDGUYV1H7X9:-L5YzBnqrgDGUYV1H7XA:b-7bnv3j) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1545)):*
> ```C
>             --num;
> 
>             // HINT: is FT complete?
> ```

This comment isn't really needed.

---

*[toxcore/Messenger.c, line 1557 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5YzJ0Ceiy5jHA9xUop:-L5YzJ0Ceiy5jHA9xUoq:b-7bnv3j) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1557)):*
> ```C
>             }
> 
>             // HINT: decrease free slots by the number of slots this FT uses
> ```

This comment isn't really needed.

---

*[toxcore/Messenger.c, line 1558 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5YzOZbxgfz0ybzLhMS:-L5YzOZbxgfz0ybzLhMT:b-kps5ve) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1558)):*
> ```C
> 
>             // HINT: decrease free slots by the number of slots this FT uses
>             *free_slots = max_s32(0, (int32_t) * free_slots - ft->slots_allocated);
> ```

`(int32_t) * free_slots - ft->slots_allocated` looks odd. Maybe `(int32_t)*free_slots - ft->slots_allocated`? It seems to more in line with how we do dereferencing and casts elsewhere in the code.

---

*[toxcore/Messenger.c, line 1608 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5Z-7k-2U6-oqfJbOr4:-L5Z-7k-2U6-oqfJbOr5:b-7bnv3j) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1608)):*
> ```C
> static void do_reqchunk_filecb(Messenger *m, int32_t friendnumber, void *userdata)
> {
>     // HINT: no files to send
> ```

This comment isn't really needed.

---

*[toxcore/Messenger.c, line 1621 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5Z-WI-oAqLq4NSD2VN:-L5Z-WI-oAqLq4NSD2VO:b-7bnv3j) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1621)):*
> ```C
>                                   m->friendlist[friendnumber].friendcon_id));
> 
>     // HINT: need to keep "MIN_SLOTS_FREE" slots always free
> ```

This comment isn't really needed.

---

*[toxcore/Messenger.c, line 1626 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5Z-Vq1xFEo7h-nrdVK:-L5Z-Vq1xFEo7h-nrdVL:b-7bnv3j) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1626)):*
> ```C
>     bool any_active_fts = true;
>     uint32_t loop_counter = 0;
>     // HINT: maximum number of Filetransfer loops
> ```

This comment isn't really needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-:-L5Z-duiuAmWwH5YcM7I:b-f6i3ws)*

**Comment by iphydf** [comment]
Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[toxcore/Messenger.c, line 1504 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5YyS3OmnXmt8oWOU6f:-L5Z_Meyx93JRX-WHz-k:b-saw75z) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1504)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This can be static.
</blockquote></details>

Moved to util.

---

*[toxcore/Messenger.c, line 1509 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5Yyx4WvzZsFKZ3AlIj:-L5Z_NqrJN5wIrVBbLMm:bwhglds) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1509)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This can be static.
</blockquote></details>

Moved.

---

*[toxcore/Messenger.c, line 1536 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5Yz6kIYgt8VufI02LI:-L5Z_PM04tA1ZDSTa9kS:b-a2ujfl) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1536)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This comment isn't really needed.
</blockquote></details>

Changed.

---

*[toxcore/Messenger.c, line 1540 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5YzA5E_5OdhRqwfeoj:-L5Z_Q46N-c3FMdXmg17:b-a2ujfl) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1540)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This comment isn't really needed.
</blockquote></details>

Changed.

---

*[toxcore/Messenger.c, line 1545 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5YzBnqrgDGUYV1H7X9:-L5Z_Qra1H_kDVTwwNZH:b-a2ujfl) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1545)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This comment isn't really needed.
</blockquote></details>

Changed.

---

*[toxcore/Messenger.c, line 1557 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5YzJ0Ceiy5jHA9xUop:-L5Z_SH_YJzaqCJNHpp7:b-a2ujfl) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1557)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This comment isn't really needed.
</blockquote></details>

Changed.

---

*[toxcore/Messenger.c, line 1558 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5YzOZbxgfz0ybzLhMS:-L5Z_THvIuUkZUK4aSsz:b1w66fi) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1558)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`(int32_t) * free_slots - ft->slots_allocated` looks odd. Maybe `(int32_t)*free_slots - ft->slots_allocated`? It seems to more in line with how we do dereferencing and casts elsewhere in the code.
</blockquote></details>

astyle did this. We should move to clang-format.

---

*[toxcore/Messenger.c, line 1608 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5Z-7k-2U6-oqfJbOr4:-L5ZaDygKOBqXO9H8879:b-eowr3y) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1608)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This comment isn't really needed.
</blockquote></details>

Clarified.

---

*[toxcore/Messenger.c, line 1621 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5Z-WI-oAqLq4NSD2VN:-L5ZaFdG8Vsazvs5XhT1:b-eowr3y) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1621)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This comment isn't really needed.
</blockquote></details>

Clarified.

---

*[toxcore/Messenger.c, line 1626 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/765#-L5Z-Vq1xFEo7h-nrdVK:-L5ZaHUHtpDvqr4Y2msX:b-eowr3y) ([raw file](https://github.com/toktok/c-toxcore/blob/742a15bac1d90b3799ab4d5552f95d05b5da576c/toxcore/Messenger.c#L1626)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This comment isn't really needed.
</blockquote></details>

Clarified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/765)*

**Pull request merged**
