### PR TITLE
Add VP9 encoding and decoding support.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/719)

### CODE REVIEW

**Comment by iphydf** [comment]
Let's work on this one now.

**Comment by iphydf** [comment]
@sudden6 @robinlinden ready for review.

**Comment by sudden6** [comment]
Reviewed 1 of 3 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

*[toxav/video.c, line 202 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5ccEF8RMYGJF3L-2cd:-L5ccEF8RMYGJF3L-2ce:b8b8vhk) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L202)):*
> ```C
>     if (VPX_ENCODER_USED == VPX_VP9_CODEC) {
>         if ((cpu_used_value < -8) || (cpu_used_value > 8)) {
>             cpu_used_value = 8; // set to default (fastest) value
> ```

add a debug message that this setting was set to default because it's out of range

---

*[toxav/video.c, line 385 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5cZClnxgUGy_tqcaBz:-L5cZCloi5fldMNrATd2:b-e8oz4z) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L385)):*
> ```C
> void video_switch_decoder(VCSession *vc)
> {
>     if (vc->is_using_vp9 == true) {
> ```

1. why is this inverted, looks very strange if the flag changes it's meaning in the function. 2. if you really need to invert this do it like `vc->is_using_vp9 = !vc-is_using_vp9`

---

*[toxav/video.c, line 401 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5cZix_shlKTerGW9kN:-L5cZix_shlKTerGW9kO:b-kygf4l) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L401)):*
> ```C
> 
>     if (vc->is_using_vp9 == true) {
>         rc = vpx_codec_dec_init(&new_d, vpx_codec_vp8_dx(), &dec_cfg,
> ```

same, `using_vp9` is true, but vp8 is initialized?

---

*[toxav/video.c, line 423 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5ca_x7t4RrrylU-KU6:-L5ca_x7t4RrrylU-KU7:b-vg4m64) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L423)):*
> ```C
> 
>         if (cc_res != VPX_CODEC_OK) {
>             LOGGER_WARNING(vc->log, "Failed to turn on postproc");
> ```

unify language?, either use `turn on/off` or `enable/disable`

---

*[toxav/video.c, line 425 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5catySO7zdL1I0MZk9:-L5catyTVnA87wyOsFHa:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L425)):*
> ```C
>             LOGGER_WARNING(vc->log, "Failed to turn on postproc");
>         } else {
>             LOGGER_DEBUG(vc->log, "turn on postproc: OK");
> ```

same

---

*[toxav/video.c, line 432 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5caw5O5SB_CXyvm-V4:-L5caw5P0eOmEor-ku-m:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L432)):*
> ```C
> 
>         if (cc_res != VPX_CODEC_OK) {
>             LOGGER_WARNING(vc->log, "Failed to turn OFF postproc");
> ```

same

---

*[toxav/video.c, line 434 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5caxe8SFsu03O24gIV:-L5caxe8SFsu03O24gIW:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L434)):*
> ```C
>             LOGGER_WARNING(vc->log, "Failed to turn OFF postproc");
>         } else {
>             LOGGER_DEBUG(vc->log, "Disable postproc: OK");
> ```

same

---

*[toxav/video.c, line 476 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5cbSNn3ZZRt8Xt6f7X:-L5cbSNonI0xMSjaKaIJ:b-gg2zmx) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L476)):*
> ```C
> 
>     if (rc != VPX_CODEC_OK) {
>         if (rc == 5) { // Bitstream not supported by this decoder
> ```

replace number constant with the defined error types

---

*[toxav/video.c, line 479 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5cbYaZRZkcr5-5uv0p:-L5cbYaZRZkcr5-5uv0q:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L479)):*
> ```C
>             LOGGER_DEBUG(vc->log, "Switching VPX Decoder");
>             video_switch_decoder(vc);
>         } else if (rc == 7) {
> ```

same

---

*[toxav/video.c, line 488 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5cbZUhts9I7o62m6ZL:-L5cbZUhts9I7o62m6ZM:bdpll1q) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L488)):*
> ```C
>         rc = vpx_codec_decode(vc->decoder, p->data, full_data_len, nullptr, MAX_DECODE_TIME_US);
> 
>         if (rc != 5) {
> ```

same, is this even correct? shouldn't it be `VPX_CODEC_OK` aka 0?

---

*[toxav/video.c, line 605 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5cbzmFSnaQbNSi2UjP:-L5cbzmFSnaQbNSi2UjQ:b-8rnww5) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L605)):*
> ```C
>         if (VPX_ENCODER_USED == VPX_VP9_CODEC) {
>             if ((cpu_used_value < -8) || (cpu_used_value > 8)) {
>                 cpu_used_value = 8; // set to default (fastest) value
> ```

add a debug message, that this value was set to default, because it's out of range for this encoder?

---

*[toxav/video.h, line 43 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5c_hRAGLKV6lxCKv3O:-L5c_hRAGLKV6lxCKv3P:b5ubdsz) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.h#L43)):*
> ```objc
> #define VPX_DECODER_USED VPX_VP8_CODEC // this will switch automatically
> 
> #define VIDEO_SEND_X_KEYFRAMES_FIRST 3 // force the first n frames to be keyframes!
> ```

maybe add that this is done to get the first picture to the other end as fast as possible

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/719)*

**Comment by iphydf** [comment]
Review status: 1 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

*[toxav/video.c, line 202 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5ccEF8RMYGJF3L-2cd:-L5d-vYM-1wkv4WouZ3A:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L202)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

add a debug message that this setting was set to default because it's out of range
</blockquote></details>

Done.

---

*[toxav/video.c, line 385 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5cZClnxgUGy_tqcaBz:-L5d01LB4LIyBic95WXJ:b-pazodh) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L385)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

1. why is this inverted, looks very strange if the flag changes it's meaning in the function. 2. if you really need to invert this do it like `vc->is_using_vp9 = !vc-is_using_vp9`
</blockquote></details>

2. Done. 1. @zoff99 let's go over this code together.

---

*[toxav/video.c, line 423 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5ca_x7t4RrrylU-KU6:-L5d0n7ii1Quaoo3M484:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L423)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

unify language?, either use `turn on/off` or `enable/disable`
</blockquote></details>

Done.

---

*[toxav/video.c, line 425 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5catySO7zdL1I0MZk9:-L5d0ndD58LKdOYgkfFC:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L425)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---

*[toxav/video.c, line 432 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5caw5O5SB_CXyvm-V4:-L5d0oB_Q-3WLh9JoQod:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L432)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---

*[toxav/video.c, line 434 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5caxe8SFsu03O24gIV:-L5d0oxXkSBzGDoJfiPL:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L434)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---

*[toxav/video.c, line 476 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5cbSNn3ZZRt8Xt6f7X:-L5d18kCQq5LSOUlYF3I:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L476)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

replace number constant with the defined error types
</blockquote></details>

Done.

---

*[toxav/video.c, line 479 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5cbYaZRZkcr5-5uv0p:-L5d1964Vcv95pYhJRyC:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L479)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---

*[toxav/video.c, line 488 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5cbZUhts9I7o62m6ZL:-L5d19iY1mGIxCCCDVw4:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L488)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same, is this even correct? shouldn't it be `VPX_CODEC_OK` aka 0?
</blockquote></details>

Done.

---

*[toxav/video.c, line 605 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5cbzmFSnaQbNSi2UjP:-L5d1EykeI6kN2XBqez2:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.c#L605)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

add a debug message, that this value was set to default, because it's out of range for this encoder?
</blockquote></details>

Done.

---

*[toxav/video.h, line 43 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/719#-L5c_hRAGLKV6lxCKv3O:-L5d1TmzQPlM5wLHVRGh:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7ee5340f9ca8c373e58d606efac388541a2d4f92/toxav/video.h#L43)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

maybe add that this is done to get the first picture to the other end as fast as possible
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/719)*

**Comment by sudden6** [comment]
Reviewed 1 of 2 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/719)*

**Comment by iphydf** [comment]
Closing as obsolete. Will be superseded by @zoff99's future work.

**Pull request closed without merging**
