### PR TITLE
Always kill invalid file transfers when receiving file controls.

### PR DESCRIPTION
**Pull request by iphydf**
Previously, toxcore would send a kill control to the friend only if the
file control was valid. Determining which file transfer is used does not
depend on the specific file control. We can always kill it in that case.

Also, added some logging for file control logic, since there is no other
feedback on error (failure of the file control handler is swallowed).

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/390)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toxcore/Messenger.c, line 1616 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/390#-K_nNShz0wEqb9KZfocF:-K_nNShz0wEqb9KZfocG:b-1ma28q) ([raw file](https://github.com/toktok/c-toxcore/blob/5955de9e936d95614dd4106034ef21374dd591ef/toxcore/Messenger.c#L1616)):*
> ```C
> }
> 
> static struct File_Transfers *get_file_transfer(uint8_t receive_send, uint8_t filenumber,
> ```

`bool outgoing/incoming` instead of `receive_send`?

---

*[toxcore/Messenger.c, line 1638 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/390#-K_pOg--a3rSEp26ibM0:-K_pOg-0nPNwbqOLKmOu:b-2xs6mn) ([raw file](https://github.com/toktok/c-toxcore/blob/5955de9e936d95614dd4106034ef21374dd591ef/toxcore/Messenger.c#L1638)):*
> ```C
> /* return -1 on failure, 0 on success.
>  */
> static int handle_filecontrol(Messenger *m, int32_t friendnumber, uint8_t receive_send, uint8_t filenumber,
> ```

receive_send *needs* to become a bool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/390)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/Messenger.c, line 1616 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/390#-K_nNShz0wEqb9KZfocF:-K_yhDo5nA3ktPIkJIqk:b-6fm97l) ([raw file](https://github.com/toktok/c-toxcore/blob/7c4dd3b3fc3403dbdccff9213eed4162fd6ac28b/toxcore/Messenger.c#L1616)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

`bool outgoing/incoming` instead of `receive_send`?
</blockquote></details>

Maybe, but then we should rename it everywhere. Not in this PR.

---

*[toxcore/Messenger.c, line 1638 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/390#-K_pOg--a3rSEp26ibM0:-K_yh-BBUYAmb10vsOpn:bunfnzv) ([raw file](https://github.com/toktok/c-toxcore/blob/7c4dd3b3fc3403dbdccff9213eed4162fd6ac28b/toxcore/Messenger.c#L1638)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

receive_send *needs* to become a bool.
</blockquote></details>

Not at this point though. There is nothing before this call that checks whether the value is in `[0,1]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/390)*

**Comment by GrayHatter** [comment]
I'm not happy with the `receive_send` name.  but this :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/390#-:-Ka2RRvG0HL0-YMtpoPI:bhka1ue)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/390#-:-Ka7Iz5KHDPnfCiYwkA4:b-jbsf8z)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/390)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/390#-:-KaBS-iMG4UihjxNVNrs:bg7igkv)*

**Comment by nurupo** [comment]
:lgtm_strong:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/390#-:-KaK3ztImf5gu0pvBm99:b-jbsf8z)*

**Pull request merged**
