### PR TITLE
A minimal workable client

### PR DESCRIPTION
**Pull request by hqwrong**
Hi, guys,

This is a minimal workable client written for toxcore.  It's an example of tox client implementation and also a toy which newcomers to this project can play and start with, therefore getting familiar with this project.

It has following features:

1. Single-File and Small Codebase(Only 1.2k LOC);

2. Totaly Standalone ( No 3rd libary needed, only rely on Tox Lib and System&Stardard C Lib);

3. Covered most apis of Friend&Group, and more to go;

4. Fun to play with.(Colored text, Async REPL, e.t.c).

Note that English is not my first language, the code hasn't been heavily documented. Plz feel free to add/modify.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/874)

### CODE REVIEW

**Comment by nurupo** [comment]
You should add your client to the https://github.com/TokTok/toxins repository instead, or better yet make your own repository for the client. This repository already had a minimal client before called ntox, but we decided to remove it a few months ago in https://github.com/TokTok/c-toxcore/pull/709 in favor of toxic.

**Comment by hqwrong** [comment]
I think toxic and this minimal client served different purposes. toxic is for daily use, all features included but complicate(72 files & 20k LOC, so far),  not suitable for new developers to start with.

I'd like to keep it in my own repository, but how could newcomers know this repsitory's exsitence? Shoud I leave a reference in this repo's readme?

**Comment by iphydf** [comment]
If you put it into your own repo, you can submodule it in toxins. See toxvpn for an example of how to do this. If you do this, we'll make sure future changes don't break compilation and tests for your client.

**Comment by tox-user** [comment]
We might need some better way to list simple example projects for new developers.

**Comment by hqwrong** [comment]
How about I putting it into my own repo and adding a link under [Other resources ](https://github.com/TokTok/c-toxcore#other-resources) section of this repo's readme  to it?

**Comment by zoff99** [comment]
@hqwrong make a PR to the "website" repo like this:
https://github.com/TokTok/website/pull/120

to add your client to the integrations page.
there we are currently collecting everything that is done with Tox

**Comment by zoff99** [comment]
on that page there are are few "1-file clients" already

**Comment by hqwrong** [comment]
@zoff99 I'm a little confused here. The website you posted is toktok.ltd, right?  But the website this repo's description linked to is tox.chat, what's the difference?

**Comment by tox-user** [comment]
Adding it to the wiki and then linking to it in the readme is a great idea.

**Comment by zoff99** [comment]
@hqwrong please also make a PR to the "website" repo like this:
TokTok/website#120

**Comment by hqwrong** [comment]
- I've made my own repo: https://github.com/hqwrong/minitox

- A pr to the 'website' repo: https://github.com/TokTok/website/pull/122

- Add a link in the readme of this repo: https://github.com/TokTok/c-toxcore/pull/877

I don't have right to modify the wiki,  so leave it to you guys :)

Thanks.

**Comment by iphydf** [comment]
Can you add it as a submodule to the toxins repo? That way we can ensure it doesn't break when we change things.

**Comment by hqwrong** [comment]
@iphydf  Currently,I'm a bit occupied. I'll add it later.

**Pull request closed without merging**
