### PR TITLE
Add VLA compatibility macro for C89-ish compilers.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/452)

### CODE REVIEW

**Comment by iphydf** [comment]
@isotoxin can you review this change? It's one of the changes we need to make for MSVC compatibility. I believe this directly affects your use case.

**Comment by Zer0-One** [comment]
:lgtm: 

---

Reviewed 1 of 30 files at r1.
Review status: 1 of 30 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/452#-:-KayhixmqnKUvdcRlUIU:bg7igkv)*

**Comment by Zer0-One** [comment]
It'll work, but afaik `alloca()` is non-portable.

**Comment by endoffile78** [comment]
:lgtm_strong:

---

Reviewed 25 of 30 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/452#-:-Kb6FbCLk7IN1V7_TKWV:b-jbsf8z)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 26 of 30 files at r1, 5 of 7 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/452#-:-Kb7lPAT5E2jibmNOY9-:b-jbsf8z)*

**Comment by iphydf** [comment]
@isotoxin is this something you're interested in reviewing or should we just go ahead and merge it?

By the way, yesterday I realised (after someone linked to it) that you've done this already, almost in the same way. Perhaps this change is useful for you to adopt so you have fewer custom changes to maintain.

For background: I'm doing this because I want to support Windows properly, and currently our tests run on Wine (on Linux) and always fail. I want to run the tests on Appveyor (a Windows CI platform), and although it's probably possible to use mingw32 on that, I'd like to take this opportunity to improve support for MSVC, probably benefitting the isotoxin client.

**Comment by isotoxin** [comment]
Sorry guys. I dont know how I missed this PR... I was ill, probably so.
Of course I very interesting of this patch. And I check it soon.
Btw, there are many places in code, where constantly allocated arrays should be much better then vla. May be later I make such PR.

**Comment by isotoxin** [comment]
Only one remark:
I get latest toktok sources and found sort_client_list function in DHT.c: cmp_list is dynamic.

**Pull request merged**
