### PR TITLE
Hotfix: bootstrap crash

### PR DESCRIPTION
**Pull request by cotox**
Since 9706d9a0, both `tox-bootstrapd` and `DHT_bootstrap` will crash when an UDP request on the listen port.  Because the *logger* is disabled by default.  Which causes bootstrap stopped at `toxcore/logger.c:106: logger_write: Assertion '!"NULL logger not permitted"' failed.`.

Which means, any body can **make all the bootstrap nodes stop work** by just send an UDP request as,

```sh
echo "123" | nc -u -w 1 example.org 33445
```

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/891)

### CODE REVIEW

**Comment by nurupo** [comment]
Here is the related issue https://github.com/TokTok/c-toxcore/issues/879.

There was a workaround on [the bootstrap mailing list](https://lists.tox.chat/pipermail/bootstrap/2018-April/000003.html):

>2. Build Toxcore using cmake and add -DUSE_STDERR_LOGGER=ON flag when 
running the cmake command, otherwise your bootstrap node will likely 
crash at run time. On how to build toxcore using cmake see 
https://github.com/TokTok/c-toxcore/blob/master/INSTALL.md.

**Comment by nurupo** [comment]
I hoped @iphydf would make a proper fix for this really quick, but seeing how he did I can only guess that he doesn't have time for it, so a CMakeLists quick fix is appropriate for the time being, thanks for the PR.

Your fix works only if `BOOTSTRAP_DAEMON` is enabled, the system has `libconfig` installed and the system is not Windows. That's a bad fix. If I build `DHT_bootstrap` with `BOOTSTRAP_DAEMON=OFF`, my `DHT_bootstrap` will be crashing. You should do `add_definitions(-DUSE_STDERR_LOGGER=1)` unconditionally.

Also, have you tested the autotools build system, does the crash happen when building using it?

**Comment by cotox** [comment]
Hi @nurupo, 

> Also, have you tested the autotools build system, does the crash happen when building using it?

To be short, no. But I can do it later. (This is my first commit, I have to finish some applications.)

**Comment by cotox** [comment]
> Your fix works only if `BOOTSTRAP_DAEMON` is enabled, the system has `libconfig` installed and the system is not Windows. That's a bad fix. If I build `DHT_bootstrap` with `BOOTSTRAP_DAEMON=OFF`, my `DHT_bootstrap` will be crashing. You should do add `definitions(-DUSE_STDERR_LOGGER=1)` unconditionally.

As I read from [*auto tests* source code](https://github.com/TokTok/c-toxcore/blob/291a849a5a0afb4450bcd0d0c50b7aeccaac04f5/auto_tests/dht_test.c#L326-L328), I assume the logger should managed by programmer him/herself.

https://github.com/TokTok/c-toxcore/blob/291a849a5a0afb4450bcd0d0c50b7aeccaac04f5/auto_tests/dht_test.c#L326-L328

To keep following the design, I choose to add `definitions(-DUSE_STDERR_LOGGER=1)` on `BOOTSTRAP_DAEMON=ON` only.

But if I made misunderstanding, I can do the change as you said.

**Comment by cotox** [comment]
Patch directly on CMakefile.txt & confiure.ac causes logger on in whole toxcore, including static libs.

This PR is running in wrong way. Give it up.

> See PR #892

**Pull request closed without merging**
