### PR TITLE
 lan_discovery_test and version_test cleanup

### PR DESCRIPTION
**Pull request by hugbubby**
Another minor unit test PR. Big one coming up soon.

Removed a pointless declaration of a function in lan_discovery_test
and cleaned up the one error message there. Did an entire restructuring
of the version_test using macros that resulted in fewer lines of code but more
thorough testing.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/967)

### CODE REVIEW

**Comment by iphydf** [comment]
Squash all commits into one.

**Comment by hugbubby** [comment]
What did I do...

**Comment by iphydf** [comment]
Yes, but there is still a merge commit in there.

**Comment by hugbubby** [comment]
Fuck

I

I cant do it

**Comment by iphydf** [comment]
No worries, thanks for the contribution :).

**Pull request merged**
