### PR TITLE
stop unnecessary toxID pk leaking of 0x83 message

### PR DESCRIPTION
**Pull request by jackzhp**
this does not make any effective changes, but to stop unnecessary toxID pk leaking.

Conflicts:
	toxcore/onion_announce.c

The PR by now is only to stop unnecessary leaking of toxID pk. From the future perspective, might serve more purposes.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1108)

### CODE REVIEW

**Comment by iphydf** [comment]
Can you briefly explain why you're making this change?

**Comment by jackzhp** [comment]
the 0x83 message is defined as

     0x83 + nonce24 + pkPacket32 + encrypted120
	while encrypted120 = pingid32 + pkTarget32 + pkData32 + reqID8 + mac16

The message is used for 2 cases: to setup and to query.
When used to setup, pkPacket32 == pkTarget32 and pkData32 != 0.
When used to query, pkPacket32 is random, and pkData32 == 0

The change I made is only relevant to setup, pkTarget32 should be used, it is OK to use pkPacket32 since they are same(unnecessary leaking information). If we use pkTarget32(the change), then in the future pkPacket32 can be random as well.

**Comment by jackzhp** [comment]
This change effectively changes nothing.
Next I will make some changes and still compatible with old version, but would also be compatible to the case pkPacket32 can be random for the case of setup. The purpose is for future improvement of multi devices, that's to extend the map between pkTarget and DHT pk to the map between (pkTarget,deviceID) and (DHT pk, deviceID).

**Comment by jackzhp** [comment]
i am sorry since I am not familiar with git pull request & commits, so a big mess.

**Comment by jackzhp** [comment]
At onion_client.c, change the packet_public_key to random for setup as that for query. That change should not be made before this pull request is merged and being spread all over the world. 
Multidevices support had better be put off too for the same reason.

**Comment by ingvar1995** [comment]
@jackzhp Do we really need changes in announces for multidevices support? Why not use separate profiles linked together?

**Comment by jackzhp** [comment]
@ingvar1995 glad to see your message. Yes, we can link several different profile together, that's to say that one user is using several ids. I would say multi devices should mean one tox id mapped to several dht pk, while each device will use a different dht pk, and they share the same tox id.

Furthermore this pull request effectively, compared the original code, makes NO change at all. Let's name version 0 for the version without this modification, version1 for the version with this modification.  Then version1 is completely compatible with version0. And version 1 will also be compatible with version 2(even for setup case, pkPacket is not required to be pkTarget, The key to support multiple devices is to change pkTarget to pkTarget + deviceID. For single device, it is the map between pkTarget & pkDHT, for multiple device, it is the map between pkTarget+device and pkDHT+deviceID). 

With this "basic" modification, even 0x85/0x86, 0x18,0x19,0x1A are not modified, it can allow other implementation to utilize the network to support other type of IDs(the version 2) as it allow the detach of pkPacket and pkTarget. 

Give this basic modification effectively makes no change, I really hope you can accept it. Further modification, for whatever reason, if you do not want to accept it, I would not beg for it.

**Comment by ingvar1995** [comment]
I mean why not use separate tox ids and dht pk for different instances of the same profile? Are you sure using same tox id with different dht pk will work? How devices will communicate with each other? How friends will connect to the same tox id with different dht pks?

**Comment by jackzhp** [comment]
@ingvar1995 glad to see your message again. 
To support multi devices, multi tox id for the same profile is option#1, while one tox id with multi dht pk is option#2. This modification does not make any choice since this modification effectively makes no change. It does not affect option#1 at all, but it would allow option#2 becomes possible.

It would also allow other type of toxid(pkTarget) becomes possible since it does not require pkPacket of 0x83 message to be pkTarget(the pk specified by a toxid).

Clearly option#1 is a high level option, while option#2 is a low level option. option#1 might be much easier to implement on original toxcore, while option#2 is much easier for reimplementation based on tox protocol.

For option#2, if you reimplement the tox protocol, then all your questions are resolved. But how to modify c-toxcore for option#2. It is a little bit complicated, I would like to put the details off. Here, just briefly address your questions:

Q: Are you sure using same tox id with different dht pk will work?
A: yes, very sure. 

Q: How friends will connect to the same tox id with different dht pks?
A: between different friends, equivalently, between different Friend_Conn.
Each device with one Net_Crypto(dht pk) structure, they all share the same friend_connect(toxid) and onion_friend(toxid). For Friend_Conn & Onion_Friend, dht related stuff needs encapsulation, to allow 1 to many. 

Q: How devices will communicate with each other? 
This modification gets 0x83 & 0x84 ready, for reimplementation, the whole network support option#2.
while For toxcore, need more phases: DHT announce through 0x85 & 0x86(should be modified to allow deviceID), once received DHT pk for a device, auto connection as usual(0x18 should be modified a bit to indicate the deviceID). so devices are connected. Then I prefer to extend the protocol to allow synchronization between devices.

One more time, this modification makes no change effectively. You can review the code and you will see effectively makes no change at all. But this modification would allow option#2 prevail.

**Comment by ingvar1995** [comment]
I thought option#1 is better because it doesn't require nodes changes. I agree that it is also less difficult. That's why I asked about your option#2 - toxcore doesn't have enough devs for it I think

**Comment by ingvar1995** [comment]
Also a quiestion - how will this change affect friends search? For friends keys that you want to exchange seem to be different

**Comment by robinlinden** [comment]
This is a PR based off of the information in #1045.

**Comment by zoff99** [comment]
from what i have read the proposal says that in future multidevice support, all devices would have the same private key. that sounds like a bad idea (if i have understood it correctly).
if 1 devices private key gets compromised, it will affect all devices

**Comment by jackzhp** [comment]
@ingvar1995 friend search? what do you mean?

@zoff99  completely misunderstanding, for the key pairs, in tox, there are the key pair identifies the user (toxid), dht key pair, session key pairs, and many random key pairs. 

The proposal says same key pair used to identify the user(toxid), but different dht key pairs for different devices, not to mention each device uses different session key pairs. There is no same private key over different devices! The purpose of the proposal is to map different dht key pairs to the same toxid.

**Comment by jackzhp** [comment]
@zoff99 the modification in this PR by now, does not affect old versions. but only to prevent the leaking of toxid(pkTarget). It was unnecessary leaking to require pkPacket == pkTarget. We can let pkPacket to be random for both cases (setup & query). 

I mean for both cases(setup & query), in onion_client.c, in the function client_send_announce_request, when calling create_announce_request, the temp key pair could be used, rather than use toxid key pair for setup. toxid pk is delivered as pkTarget, it is unnecessary to leak it as pkPacket.

**Comment by jackzhp** [comment]
If one communication link is compromised, then only that link is compromised, toxid key pair will not be compromised. 

If one device is compromised, in my implementation, sensitive data (such as private keys) are encrypted, so even the file was stolen, the sensitive data are still protected. Here I assume for security wary user, no autologin(local user authentication) is chosen. When autologin is chosen, the piece of data used to authenticate local user and the code will give the hacker the access to the private key.

So for security wary user, user local authentication on a device should never choose auto. Even this, if the system is hacked, theoretically, the application is running as observed in a virtual machine, then the hacker has everything. Yes, you are right, since the feature is multi devices and all devices are equal, The feature is not a multilevel authorization system.

**Comment by zoff99** [comment]
**The proposal says same key pair [on many devices] used to identify the user(toxid)**

yes, that means if the private key on 1 device is stolen or compromised, all devices are affected.
sounds bad.

**Comment by jackzhp** [comment]
@zoff99 suppose you use different toxid on different devices. do you have user authentication on device? if you do, what if this authentication process compromised? if all devices use the same info to authenticate the same user so same result: once one is compromised, then all compromised. This issue is related to the user authentication.

Using the same toxid over different devices is not in this PR at all. By the way, the modification of this PR by now, has nothing to do with all these.

The modification of this PR is to handle 0x83 message "correctly".
0x83 + nonce24 + pkPacket32 + encrypted120
	while encrypted120 = pingid32 + pkTarget32 + pkData32 + reqID8 + mac16

pkPacket32 and nonce24 are used to decrypt. pkTarget is the pk in toxID.

This message is used for 2 cases: setup and query.
query: pingid32=0, pkData32=0, pkPacket32 is random, pkTarget32 is toxid.
setup:  pkData32 !=0, pingid32 might be 0, pkPacket32 == pkTarget32.

This modification is to use pkTarget32 always, and not to use pkPacket32 even they are same.
For the setup case, pkPacket32 == pkTarget32 is unnecessary leaking toxPK.

any expert is welcome! I really hope some experts can look at this to see whether this PR can do any harm. This PR by now is not tied to my proposal to multidevices support at all.

**Comment by ingvar1995** [comment]
@jackzhp See how announce requests are created in code (`client_send_announce_request function`). For self announce `nc_get_self_public_key(onion_c->c)` is used in both cases. For announces to friends `onion_friend->temp_public_key` and `onion_friend->real_public_key` are used.

**Comment by jackzhp** [comment]
@ingvar1995 glad to see your message. I am glad that eventually someone got to the real stuff.

There is no such thing as "self announce".  If I am not wrong(for this issue, very unlikely), you misunderstood it.  You can run the code, and test it, you are going to see. 

Your "self announce" is what I called "setup", and your "annouces to friends" is what I called "query". In fact, your view is wrong(not right) since DHT announce is done with 0x9C wrapped into 0x85 & 0x86 message, not with 0x83 & 0x84 message.

3 parties involved here: a user identified by toxID(pkTarget), a friend of this user, a middle man.
Both the user and the friend sends 0x83, and will receive 0x84 as response. 0x83 is sent to the middle man, the middle man responds with 0x84. The middle man is 0x83 & 0x85 receiver, and 0x84 & 0x86 sender.

Either 0x83 message is used by the user(toxID,pkTarget) to "setup" a forward mechanism with a middle man. The user has to send 0x83 twice, first time with pindid=0, 2nd with right pingid. pingid is generated by the middle man. The forward mechanism is intended to forward message to the user(pkTarget). Hence, I call it "setup".

Or 083 message is used by the friend to query whether a forward mechanism to the user(pkTarget) exists. Hence, I call it "query". If the forward mechanism exists, then use 0x9C wrapped into 0x85 to announce the friend's DHT pk, and the middle man will turn 0x85 into 0x86 and "forward" 0x86 to the user(pkTarget). 

Did I make this clear?

In more detail, the dht announcement is with 0x9C wrapped into 0x85, then 0x85 will be wrapped into 0x80(0x81(0x82(0x85))) and delivered to the middle man, once the middle man got 0x85, it turns 0x85 into 0x86, and forward 0x86 to pkTarget.  Onion means 0x80(0x81(0x82(0x85(0x9C)))) and 0x8C(0x8D(0x8E)))+0x86.

By the way, 0x83 is also wrapped into 0x80(0x81(0x82(0x83))) and delivered to the middle man, and 0x84 is attached to 0x8C(0x8D(0x8E))).

**Comment by ingvar1995** [comment]
`handle_announce_request` will be called on node in case `create_announce_request` was called on client with destination friend params (what you call query). That's all I know, I didn't go deeper on this.

**Comment by jackzhp** [comment]
@ingvar1995 could you please write 2 more sentences. what you just said is difficult to understand. In the function client_send_announce_request, when num==0, it is the case for setup, when num!=0, it is the query. 

int create_announce_request(uint8_t *packet, uint16_t max_packet_length, 
  const uint8_t *dest_client_id,   //the pk of middle man
  const uint8_t *public_key, //pkPacket, 
  const uint8_t *secret_key, //to generate shared key with the middle man
  const uint8_t *ping_id, 
  const uint8_t *client_id, //pkTarget, to specify the forward target of the forward mechanism 
  const uint8_t *data_public_key, //to specify the pkData, to be used for anyone to send message to the target
  uint64_t sendback_data //the request ID
)

The real parameter is pingid & pkData.
For setup case, twice, 1st time pingid=0, pkData!=0, 2nd time pingid!=0, pkData!=0.
For query case, pingid=0, pkData=0.

@ingvar1995 what do you mean? and do you have the right to do review and merge this PR?

**Comment by zugz** [comment]
It's essential to check that someone trying to announce a public key is in possession of the corresponding private key. We do this by requiring that the payload of the announce request is encrypted with the public key which is requested to be announced. This is explained in the spec. This PR would remove that crucial check, allowing anyone to announce any public key.

The "leak" you mention is I assume referring to the third node in the onion chain being able to see the public key being announced. But the third node in any case inevitably knows the DHT public key of the node the announce request is sent to, and this will be close (in XOR distance) to the public key being announced. So this doesn't leak much more information than is necessary. The intention of the onion is to have the third node unable to determine the DHT key of the sender of the packet along the onion route.

**Comment by jackzhp** [comment]
@zugz glad to see your message.

Yes, call it "announce request" is OK, since it is not about announce, but to setup a forward mechanism to forward "dht announce" from friends to the 0x83 sender(identified by the toxid pk, pkTarget). 

About the "leaking", Yes. it is between the 3rd node and the middle man(the 0x83 receiver, 0x84 sender, the "4th node" of the onion) when doing setup the "announce request"(the forward mechanism). And you are right, 0x83 message is to be sent by any user (with toxID pk) to the middle man whose dht pk is "close" to the toxID pk, but the 3rd node knows only that the toxID pk is "close" to the 4th node's dht pk which the 3rd node clearly knows. When we allow leaking, the 3rd might participate in blocking the toxID pk. If we prevent this leaking, only the middle man is able to block the toxID pk.

You saying that the middle man can require the target of the forward mechanism(0x83 sender) is indeed the owner of the toxID pk(in possession of its private key). Yes, if the middle man do not do this check up, then any adversary can claim to be the user with the toxID pk, and with this mechanism, the friends of this toxID would send their dht announce to the adversary. Though the adversary is not able to know their dht pk(in 0x9C) since it is encrypted in 0x85, but the adversary can see the toxID pk of the friends in 0x85. Hence, for the 0x83 receiver, this authentication of the sender of the 0x83 is indeed meaningful.

Honestly speaking, my current goal is to decouple the decryption and the authentication. When authentication is not possible, I just want to abandon it. I want to use other type of PK as toxID pk rather than ec25519. But the dht pk of the middle man is of ec25519. It is impossible for them to have the shared key to do decryption. Given the authentication is indeed needed, a simple modification can not achieve my goal. I would instead try to propose using a new message id such as 0x87.

0x87 will be similar to 0x83, but with some extension.

0x83 + nonce24 + pkPacket32 + encrypted120
	while encrypted120 = pingid32 + pkTarget32 + pkData32 + reqID8 + mac16

0x87 + epkPacket + nonce + encrypted
	while encrypted = epkTarget + sig + reqID8 + timestamp8  + mac
        or  encrypted = epkTarget + sig + reqID8 + timestamp8 + pingid32(!=0) + pkData32 + mac
The encrypted is decrypted with epkPacket & the dht pk of the 0x87 receiver.
The signature is on the sha256 of reqID8 + timestamp8 + nonce when pingid32=0, or on the sha256 of reqID8 + timestamp8 + pingid32 + pkData32 when pingid32!=0. 

epkPacket & epkTarget are extended PK, are starting with a variant size integer to indicate the PK type which is followed by PK. Both nonce size and signature structure are defined by the PK type. In this way, the decryption of the message is decoupled from authentication.

EC25519 PK is assigned with type 1, and sec256k1 PK is assigned with type 0, etc. 

any comments?

**Pull request closed without merging**
