### PR TITLE
Import new group chats.

### PR DESCRIPTION
**Pull request by iphydf**

### CODE REVIEW

**Comment by iphydf** [comment]
Closing this for now, as it's nowhere near ready for merging.

**Comment by Renha** [comment]
how long would it take for newgroupchats could be merged?

**Comment by GrayHatter** [comment]
@Renha minutes, once a working tests suite is confirmed to be working.

**Comment by Renha** [comment]
@GrayHatter how could it be done?

**Comment by isotoxin** [comment]
Btw, guys, I almost done fully-compatible-with-old-groupchats-and-api upgrade to old groupchats. This upgrade let clients keep history of groupchats and restore groupchats after clients (even all) restarts. So, should it make PR, or you ask me "Hey, new groupchats almost done, don't touch old ones"?

**Comment by iphydf** [comment]
New group chats have been almost done for 2 years, so go ahead and make a PR. Are you using the new conference API?

**Comment by isotoxin** [comment]
> Are you using the new conference API?
yes
> so go ahead and make a PR
ok, I will create PR soon (about a week)

**Comment by quininer** [comment]
@isotoxin You can describe how you implement it?

**Comment by Renha** [comment]
@isotoxin do you have moderators/administrators management, etc?

**Comment by isotoxin** [comment]
> @isotoxin do you have moderators/administrators management, etc?

I'm my own person (as I understand your question)

**Comment by isotoxin** [comment]
@quininer
> @isotoxin You can describe how you implement it?

Main: current (aka old) groupchats have unique ID. That is almost it! I just get access to this ID.
I can't describe other changes for now due some of them are on research stage. All changes will be described in PR

**Pull request closed without merging**
