### PR TITLE
Use apidsl for the crypto_core API.

### PR DESCRIPTION
**Pull request by iphydf**
This allows us to use apidsl features like namespaces to enforce a
naming standard.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/249)

### CODE REVIEW

**Comment by JFreegman** [comment]
:lgtm_strong:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/249#-:-KVuzNgd4OGOu2E_6_An:b-jbsf8z)*

**Comment by GrayHatter** [comment]
:lgtm_strong:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/249#-:-KWAoUpfo81KEIOI82Vb:b-jbsf8z)*

**Comment by SkyzohKey** [comment]
:lgtm_strong:

---

Reviewed 3 of 15 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/249#-:-KWIFKUumSZ_KQRvQq0B:b-jbsf8z)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/249)*

**Comment by tux3** [comment]
:lgtm_strong:

---

Reviewed 3 of 15 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/249#-:-KWKN1HJILAEOAvSPhOt:b-jbsf8z)*

**Comment by SkyzohKey** [comment]
@nurupo

**Comment by nurupo** [comment]
The comments, argument names and function names in this header file are maddening. Is changing them in scope of this PR?

---

Reviewed 3 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/249#-:-KWMa8M0y2qc_rdkuKUQ:b8exx8p)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/249#-:-KWMb44xmTlRCRV3SpDA:b-jbsf8z)*

**Comment by iphydf** [comment]
That is out of scope. We will certainly do it in one of the next PRs. I'd also like to put a namespace around all the functions. I'm leaning towards `crypto` even though that's somewhat taken by libsodium. Let me know if you have better/different ideas.

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/249#-:-KWNP4E7TwhgJvYwh9hD:bpnukhh)*

**Pull request merged**
