### PR TITLE
cleanup: Upgrade to clang-tidy-17 and fix some warnings.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2503)

### CODE REVIEW

**Review by nurupo — COMMENTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2503)* status: 0 of 1 approvals obtained (waiting on @iphydf)

___
*[`other/analysis/run-clang-tidy` line 110 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2503#-Nmc9PzQ3nn4olPn_n3H:-Nmc9PzQ3nn4olPn_n3I:balxrds) ([raw file](https://github.com/TokTok/c-toxcore/blob/766e62bc896695ad42697a532406ac1567826107/other/analysis/run-clang-tidy#L110)):*
> ```
> # TODO(iphydf): These two trip on list.c. Investigate why.
> CHECKS="$CHECKS,-clang-analyzer-core.NonNullParamChecker"
> CHECKS="$CHECKS,-clang-analyzer-unix.Malloc"
> ```

Want to note that, while not clang-tidy, [clang-analyze still trips on these](https://app.circleci.com/pipelines/github/TokTok/c-toxcore/6103/workflows/5635c38f-12c7-4d1c-a71c-3c4b0ea95cef/jobs/49896?invite=true#step-104-9503\_124):

```
./toxcore/list.c:233:9: warning: Array access (via field 'ids') results in a null pointer dereference [core.NullDereference]
    if (list->ids[i] != id) {
        ^~~~~~~~~~~~
./toxcore/list.c:249:5: warning: Use of memory after it is freed [unix.Malloc]
    memmove(list->data + i * list->element_size, list->data + (i + 1) * list->element_size,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Which is interesting, you'd think `clang-analyzer-core.*` are the same checks as what clang --analyze uses, but clearly clang-tidy no longer trips on these but clang --analyze still does.

Anyway, just something I wanted to point out, I don't think this is actionable or anything, i.e. I'm not requesting any changes here.
___
*[`other/bootstrap_daemon/src/tox-bootstrapd.c` line 228 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2503#-Nmc1pgUCRnBsIoqolAU:-Nmc1pgUCRnBsIoqolAV:bslde12) ([raw file](https://github.com/TokTok/c-toxcore/blob/b154175614d6289e06d92e2eae4444fb58b2ecae/other/bootstrap_daemon/src/tox-bootstrapd.c#L228)):*
> ```C
>         case CLI_STATUS_ERROR:
>             return 1;
>     }
> ```

1. Out of curiosity, what was the warning message for using `exit()` / rationale for avoiding to use it that the tool printed?

2. I do see a problem with a function calling `exit()` internally, as the caller might not expect the function to do so, but rather than lifting the `exit()` call into the `main()` function as an early return by having functions return the enum, I wonder if renaming `handle_command_line_arguments()` to `handle_command_line_arguments_or_die()` and similarly `daemonize()` to ` daemonize_or_die()` would be clearer and cleaner -- without needing the enum and switches. Wouldn't fix a warning if it's looking for `exit()` calls though, so if this is done to fix a warning then fair enough, let's keep this. (Though making code more clunky just to please static analysis tools is a bit annoying, shouldn't the tools work for us and not the other way around?).

**Review by nurupo — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2503)* status: 0 of 1 approvals obtained (waiting on @iphydf)

**Comment by nurupo** [comment]
*[`other/analysis/run-clang-tidy` line 110 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2503#-Nmc9PzQ3nn4olPn_n3H:-NmcE6rw2eMVXHcvRiRE:b-1cyz1p) ([raw file](https://github.com/TokTok/c-toxcore/blob/766e62bc896695ad42697a532406ac1567826107/other/analysis/run-clang-tidy#L110)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Want to note that, while not clang-tidy, [clang-analyze still trips on these](https://app.circleci.com/pipelines/github/TokTok/c-toxcore/6103/workflows/5635c38f-12c7-4d1c-a71c-3c4b0ea95cef/jobs/49896?invite=true#step-104-9503\_124):

```
./toxcore/list.c:233:9: warning: Array access (via field 'ids') results in a null pointer dereference [core.NullDereference]
    if (list->ids[i] != id) {
        ^~~~~~~~~~~~
./toxcore/list.c:249:5: warning: Use of memory after it is freed [unix.Malloc]
    memmove(list->data + i * list->element_size, list->data + (i + 1) * list->element_size,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Which is interesting, you'd think `clang-analyzer-core.*` are the same checks as what clang --analyze uses, but clearly clang-tidy no longer trips on these but clang --analyze still does.

Anyway, just something I wanted to point out, I don't think this is actionable or anything, i.e. I'm not requesting any changes here.
</blockquote></details>

Could also be the difference between the versions of clang used, Alpine vs Ubuntu (clang-analyze job is defined in `.circleci/config.yml`).

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2503)* status: 0 of 1 approvals obtained (waiting on @nurupo)

___
*[`other/analysis/run-clang-tidy` line 110 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2503#-Nmc9PzQ3nn4olPn_n3H:-NmcYVzH83yr9UKvaEtE:b-hvydhx) ([raw file](https://github.com/TokTok/c-toxcore/blob/766e62bc896695ad42697a532406ac1567826107/other/analysis/run-clang-tidy#L110)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Could also be the difference between the versions of clang used, Alpine vs Ubuntu (clang-analyze job is defined in `.circleci/config.yml`).
</blockquote></details>

Might also be different compile options. I can look into that later.
___
*[`other/bootstrap_daemon/src/tox-bootstrapd.c` line 228 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2503#-Nmc1pgUCRnBsIoqolAU:-NmcY_gp7yCLfd-nx8XK:b-tg4j0g) ([raw file](https://github.com/TokTok/c-toxcore/blob/b154175614d6289e06d92e2eae4444fb58b2ecae/other/bootstrap_daemon/src/tox-bootstrapd.c#L228)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

1. Out of curiosity, what was the warning message for using `exit()` / rationale for avoiding to use it that the tool printed?

2. I do see a problem with a function calling `exit()` internally, as the caller might not expect the function to do so, but rather than lifting the `exit()` call into the `main()` function as an early return by having functions return the enum, I wonder if renaming `handle_command_line_arguments()` to `handle_command_line_arguments_or_die()` and similarly `daemonize()` to ` daemonize_or_die()` would be clearer and cleaner -- without needing the enum and switches. Wouldn't fix a warning if it's looking for `exit()` calls though, so if this is done to fix a warning then fair enough, let's keep this. (Though making code more clunky just to please static analysis tools is a bit annoying, shouldn't the tools work for us and not the other way around?).
</blockquote></details>

clang-tidy doesn't like `exit()` because it's not thread-safe. There's no way to disable only `exit()` from that list of thread-unsafe functions. It's nice to have that analysis around the rest of the code.

**Review by nurupo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2503)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Pull request merged**
