### PR TITLE
Make Friend_Connections a module-private type.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/672)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[toxcore/friend_connection.h, line 66 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/672#-L2kwxaP62CqaAgENw9t:-L2kwxaP62CqaAgENw9u:b-2d028e) ([raw file](https://github.com/toktok/c-toxcore/blob/67674a04898b5449f212c0831c68b0acd5045259/toxcore/friend_connection.h#L66)):*
> ```objc
> typedef struct Friend_Connections Friend_Connections;
> 
> Net_Crypto *friendconn_net_crypto(const Friend_Connections *fr_c);
> ```

`friendconn_net_crypto` could be renamed to `friendconn_get_net_crypto` since it's a getter function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/672)*

**Comment by endoffile78** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/672#-:-L2kxJLbdXSRXUax8uzn:b-jbsf8z)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[toxcore/friend_connection.h, line 66 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/672#-L2kwxaP62CqaAgENw9t:-L2l-zHP8JoOI7W0l5OK:baeaoxb) ([raw file](https://github.com/toktok/c-toxcore/blob/67674a04898b5449f212c0831c68b0acd5045259/toxcore/friend_connection.h#L66)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`friendconn_net_crypto` could be renamed to `friendconn_get_net_crypto` since it's a getter function.
</blockquote></details>

I'm going to make a pass over the code with apidsl once this "make things private" stuff is done. Then apidsl will do the naming convention for us.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/672)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[toxcore/friend_connection.h, line 66 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/672#-L2kwxaP62CqaAgENw9t:-L2l2Y0K30UnVoRRvwwn:b32w1t) ([raw file](https://github.com/toktok/c-toxcore/blob/67674a04898b5449f212c0831c68b0acd5045259/toxcore/friend_connection.h#L66)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

I'm going to make a pass over the code with apidsl once this "make things private" stuff is done. Then apidsl will do the naming convention for us.
</blockquote></details>

Ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/672#-:-L2l2_IS1o2sQeH9O3hz:b-jbsf8z)*

**Pull request merged**
