### PR TITLE
Make conferences persistent across restarts and reconnects.

### PR DESCRIPTION
**Pull request by iphydf**
This is not new groupchats. This is just upgrade to old groupchats with
some advatages:
- Groupchats are now saved into tox_save
- Client can get groupchat unique id to save message log
- Auto restore groupchats after restart even your friend uses
non-upgraded version

Depends on #795.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/769)

### CODE REVIEW

**Comment by iphydf** [comment]
This is the review of #295. I'm going to make fixes here and eventually push it to #295 so that it can be merged from there.

**Comment by Diadlo** [comment]
@iphydf It's bad idea add extra commits to this PR (I'm talking about crypto_memcmp test)

**Comment by iphydf** [comment]
@Diadlo ignore that commit. Only review the one commit at the end. I have based it on the memcmp one because that PR fixes spurious test failures that are just annoying, not useful. The way to fix this problem is by reviewing #757.

**Comment by Diadlo** [comment]
Reviewed 7 of 8 files at r1, 2 of 13 files at r2, 12 of 13 files at r4, 1 of 1 files at r5.
Review status: 19 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[auto_tests/conference_test.c, line 62 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4geD7cg3vlbf6AmdzT:-L4geD7cg3vlbf6AmdzU:b-2rrqx) ([raw file](https://github.com/toktok/c-toxcore/blob/844d83a96e7e5e041c400e03fc54b8d2827af51a/auto_tests/conference_test.c#L62)):*
> ```C
>     // TODO(robinlinden): Fix tox_conference_join to disallow joining a
>     // conference we are already in.
> #if 0
> ```

I'm ok with with it if it will be declared behaviour. So remove `TODO` and test case?

---

*[toxcore/group.h, line 101 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4hGNEM-v00hBqCpwPK:-L4hGNEM-v00hBqCpwPL:bsma0fy) ([raw file](https://github.com/toktok/c-toxcore/blob/e02df48fdf425350fa9e67dea48e998a31432da2/toxcore/group.h#L101)):*
> ```objc
> 
>     void (*peer_on_join)(void *, int, int);
>     void (*peer_on_leave)(void *, int32_t, void *);
> ```

Why the second parameter is `int32_t` while in other pointers `int`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/769)*

**Comment by Diadlo** [comment]
Review status: 19 of 20 files reviewed at latest revision, 14 unresolved discussions.

---

*[toxcore/group.c, line 146 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mGSQivo_dr32u2uyx:-L4mGSQivo_dr32u2uyy:b-6fe7ut) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L146)):*
> ```C
>  *  return true if it succeeds.
>  */
> static bool realloc_conferences(Group_Chats *g_c, uint16_t num)
> ```

In other places (including comment before this function) entity called `group` but not `conference`

---

*[toxcore/group.c, line 231 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mIoV0G77ZEhQep4H8:-L4mIoV0G77ZEhQep4H9:bg3y7ty) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L231)):*
> ```C
>  * return -1 if group is not in list.
>  *
>  * TODO(irungentoo): make this more efficient and maybe use constant time comparisons?
> ```

Not sure about efficient, but already used constant time comparations.

---

*[toxcore/group.c, line 251 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mJ8SVEtuoKacjY6Ww:-L4mJ8SVEtuoKacjY6Wx:bicqucx) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L251)):*
> ```C
>         }
> 
>         if (crypto_memcmp(g_c->chats[i].identifier + 1, uid, GROUP_IDENTIFIER_LENGTH - 1) == 0) {
> ```

Why do we skip the first byte?

---

*[toxcore/group.c, line 257 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mJJ8dY1vmqhhg_lro:-L4mJJ8dY1vmqhhg_lrp:b-qhlwyf) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L257)):*
> ```C
> 
>     return -1;
> ```

Extra new line

---

*[toxcore/group.c, line 291 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mJw5UxcXwslX_1VWA:-L4mJw5UxcXwslX_1VWB:bwg0iqg) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L291)):*
> ```C
>             peer_number = 0;
> 
>             while (get_peer_index(g, peer_number) != -1) {
> ```

Why do we need random peer number? Why we can't use this algorithm always?

---

*[toxcore/group.c, line 399 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mMx5BgxxMJkh47rT3:-L4mMx5BgxxMJkh47rT4:bpfjkuy) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L399)):*
> ```C
> }
> 
> static void apply_changes_in_peers(Group_Chats *g_c, int32_t groupnumber, void *userdata)
> ```

I think, we should try to split this function on smaller

---

*[toxcore/group.c, line 430 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mMItoeUh37S6dyR4i:-L4mMItoeUh37S6dyR4j:b-hteg36) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L430)):*
> ```C
>             const Group_Peer *peer = &g->peers[i];
> 
>             if (peer->friendcon_id != ALMOST_DELETED_PEER && peer->gid >= 0) {
> ```

What about invert logic of `if` and use `continue`?

---

*[toxcore/group.c, line 433 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mMR54rBr8352SFNFW:-L4mMR54rBr8352SFNFX:b-ya81ng) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L433)):*
> ```C
>                 ++new_size_of_list;
> 
>                 if (empty_slots_in_list > 0) {
> ```

Same as above

---

*[toxcore/group.c, line 505 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mN6Bw6Z2kl5Lup3Nw:-L4mN6Bw6Z2kl5Lup3Nx:b-ya81ng) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L505)):*
> ```C
>             uint16_t *temp = (uint16_t *)realloc(g->peers_list, sizeof(uint16_t) * new_size_of_list);
> 
>             if (temp) {
> ```

Same as above

---

*[toxcore/group.c, line 511 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mN9wyENHl2vWGZqAI:-L4mN9wyENHl2vWGZqAJ:b-ya81ng) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L511)):*
> ```C
>                     const Group_Peer *peer = &g->peers[i];
> 
>                     if (peer->friendcon_id != ALMOST_DELETED_PEER && peer->gid >= 0) {
> ```

Same as above

---

*[toxcore/group.c, line 532 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mNKRXEcdiYHzeeFth:-L4mNKRY4NZQGb9WJp1M:b-n5fkg5) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L532)):*
> ```C
> 
>         /* Now notify client by calling callbacks */
>         if (g_c->group_namelistchange) {
> ```

Can be merged with next `if` confition

---

*[toxcore/group.c, line 534 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mNQ53P0lbDiQX-163:-L4mNQ54QLh6V9bfjt7a:b-ya81ng) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L534)):*
> ```C
>         if (g_c->group_namelistchange) {
>             if (some_changes) {
>                 if (!g->invite_called && !g->join_mode) {
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/769)*

**Comment by Diadlo** [comment]
It's a bit hard to review, if you don't answer on comments

**Comment by iphydf** [comment]
Review status: 11 of 13 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[toxcore/group.c, line 146 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mGSQivo_dr32u2uyx:-L4pIXLM_meVhQMpAodJ:bhw3nia) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L146)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

In other places (including comment before this function) entity called `group` but not `conference`
</blockquote></details>

I've renamed this because in the new-group-chats PR, this rename has to happen due to name collision. We should at some point (not in this PR) do a s/group/conference/g over this file.

---

*[toxcore/group.c, line 231 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mIoV0G77ZEhQep4H8:-L4pJlaflizhESzkjOyX:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L231)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Not sure about efficient, but already used constant time comparations.
</blockquote></details>

Done.

---

*[toxcore/group.c, line 251 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mJ8SVEtuoKacjY6Ww:-L4pJwkKehzl9Doed4rE:b-3ii8e4) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L251)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why do we skip the first byte?
</blockquote></details>

The first byte is the group chat type (TEXT/AV).

---

*[toxcore/group.c, line 257 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mJJ8dY1vmqhhg_lro:-L4pK5DzFF02zoFotibg:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L257)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Extra new line
</blockquote></details>

Done.

---

*[toxcore/group.c, line 291 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mJw5UxcXwslX_1VWA:-L4pKIyHYHrT3XgmVjaX:b-1zn2ts) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L291)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why do we need random peer number? Why we can't use this algorithm always?
</blockquote></details>

I don't know. @isotoxin why do we use random peer numbers?

---

*[toxcore/group.c, line 399 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mMx5BgxxMJkh47rT3:-L4pMt0FVRpx6UvVL8fu:b-y8ue08) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L399)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I think, we should try to split this function on smaller
</blockquote></details>

Split it into two.

---

*[toxcore/group.c, line 430 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mMItoeUh37S6dyR4i:-L4pNQqaOP3aR_JiX5bj:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L430)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What about invert logic of `if` and use `continue`?
</blockquote></details>

Done.

---

*[toxcore/group.c, line 433 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mMR54rBr8352SFNFW:-L4pO0jfU1_A8U09BSu8:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L433)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---

*[toxcore/group.c, line 505 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mN6Bw6Z2kl5Lup3Nw:-L4pO4cQiRqMaTA1Zmeb:b-deus3n) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L505)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

No loop to break out of. This would be possible if I broke out this code into a function, but I'm not happy to refactor the code too much before we fix all the bugs or document and test their behaviour.

---

*[toxcore/group.c, line 511 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mN9wyENHl2vWGZqAI:-L4pOT_wUoaOuwA07HmU:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L511)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---

*[toxcore/group.c, line 532 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mNKRXEcdiYHzeeFth:-L4pO_N8yvxLL0lESRbb:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L532)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Can be merged with next `if` confition
</blockquote></details>

Done.

---

*[toxcore/group.c, line 534 at r5](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4mNQ53P0lbDiQX-163:-L4pOq86jwNHkJc3GG2_:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/a7604c05c1cffe48a7009dd1f810f4faca8fc542/toxcore/group.c#L534)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---

*[toxcore/group.h, line 101 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L4hGNEM-v00hBqCpwPK:-L4pPLT1QfAYBLOXi9oF:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/e02df48fdf425350fa9e67dea48e998a31432da2/toxcore/group.h#L101)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why the second parameter is `int32_t` while in other pointers `int`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/769)*

**Comment by iphydf** [comment]
Sorry, forgot to publish.

**Comment by sudden6** [comment]
Review status: 11 of 13 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[toxcore/group.c, line 365 at r7](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L5B78H7QkpxnqKoAOHl:-L5B78H7QkpxnqKoAOHm:b-mu4k0z) ([raw file](https://github.com/toktok/c-toxcore/blob/cf26a25a9b70fd18c581ee40393ad23fdd898e24/toxcore/group.c#L365)):*
> ```C
>         uint16_t rmpeer = g->closest_peers[index];
>         g->closest_peers[index] = peerindex;
>         g->closest_peers_entry |= 1 << index;
> ```

with this line we need to ensure `DESIRED_CLOSE_CONNECTIONS < 31`, maybe add `#error` guard? Also it's better to shift an uint, because there are no problems with the sign bit

---

*[toxcore/group.c, line 3598 at r7](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L5B9Fc3O6hMauhkuyKD:-L5B9Fc3O6hMauhkuyKE:b-vrjhrk) ([raw file](https://github.com/toktok/c-toxcore/blob/cf26a25a9b70fd18c581ee40393ad23fdd898e24/toxcore/group.c#L3598)):*
> ```C
>                 }
> 
>                 g->next_join_check_time = now + 5000;
> ```

magic value `5000`, could be `KEEP_JOIN_ATTEMPT_DELAY_MS`?

---

*[toxcore/group.c, line 3600 at r7](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L5B94-fx9lTqzt0VPxU:-L5B94-fx9lTqzt0VPxV:b-j1r9nx) ([raw file](https://github.com/toktok/c-toxcore/blob/cf26a25a9b70fd18c581ee40393ad23fdd898e24/toxcore/group.c#L3600)):*
> ```C
>                 g->next_join_check_time = now + 5000;
> 
>                 if (!g->join_mode && !g->keep_leave && !g->disable_auto_join && g->numjoinpeers) {
> ```

invert condition and use continue

---

*[toxcore/group.h, line 62 at r7](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L5B8hd4-h5Uf-G0enPm:-L5B8hd4-h5Uf-G0enPn:bnjt4rc) ([raw file](https://github.com/toktok/c-toxcore/blob/cf26a25a9b70fd18c581ee40393ad23fdd898e24/toxcore/group.h#L62)):*
> ```objc
>     unsigned    nick_len : 8;
>     unsigned    group_number : 16;
>     unsigned    keep_connection : 8; /* keep connection even not in ring (count down every incoming ping packet) */
> ```

same as below

---

*[toxcore/group.h, line 116 at r7](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L5B7xIOnq4lIIoNdnBW:-L5B7xIOnq4lIIoNdnBX:b4fznn5) ([raw file](https://github.com/toktok/c-toxcore/blob/cf26a25a9b70fd18c581ee40393ad23fdd898e24/toxcore/group.h#L116)):*
> ```objc
>     unsigned lossy_message_number : 16;
> 
>     signed keep_join_index : 24;
> ```

I understand the 1 bit bitfields, but I don't think it makes sense to put `title_len keep_join_index and lossy_message_number` into the bitfield, or is this again transfered over the wire?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/769)*

**Comment by iphydf** [comment]
Review status: 11 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[toxcore/group.c, line 3598 at r7](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L5B9Fc3O6hMauhkuyKD:-L5Jy0iRXwQhxI6VPMJA:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/cf26a25a9b70fd18c581ee40393ad23fdd898e24/toxcore/group.c#L3598)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

magic value `5000`, could be `KEEP_JOIN_ATTEMPT_DELAY_MS`?
</blockquote></details>

Done.

---

*[toxcore/group.c, line 3600 at r7](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L5B94-fx9lTqzt0VPxU:-L5JyF3PSYn5hwvfHC_L:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/cf26a25a9b70fd18c581ee40393ad23fdd898e24/toxcore/group.c#L3600)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

invert condition and use continue
</blockquote></details>

Done.

---

*[toxcore/group.h, line 62 at r7](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L5B8hd4-h5Uf-G0enPm:-L5Jyon0b9sC-AsMbbNp:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/cf26a25a9b70fd18c581ee40393ad23fdd898e24/toxcore/group.h#L62)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same as below
</blockquote></details>

Done.

---

*[toxcore/group.h, line 116 at r7](https://reviewable.io:443/reviews/toktok/c-toxcore/769#-L5B7xIOnq4lIIoNdnBW:-L5Jyi05tS5T1ZSI5kBn:b7a87mx) ([raw file](https://github.com/toktok/c-toxcore/blob/cf26a25a9b70fd18c581ee40393ad23fdd898e24/toxcore/group.h#L116)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I understand the 1 bit bitfields, but I don't think it makes sense to put `title_len keep_join_index and lossy_message_number` into the bitfield, or is this again transfered over the wire?
</blockquote></details>

No, but it's 24 bits. I've changed the 8 and 16 bit ones to the appropriate types, but this one is a signed 24 bit int, and I don't know the effects of changing that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/769)*

**Pull request closed without merging**
