### PR TITLE
Setup autotools to read .so version info from a separate file

### PR DESCRIPTION
**Pull request by jin-eld**
We want to use the same libtool style .so versions in both build systems,
ideally both systems should read the version information from the same
configuration file.

This commit introduces an so.version configuration file and sets up
the autotools to use it.

The version numbers in so.version define the ABI compatibility and should be
updated prior to each release.

implements #323

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/420)

### CODE REVIEW

**Comment by jin-eld** [comment]
@cebe I tried adding your paste from https://github.com/TokTok/c-toxcore/issues/323#issuecomment-271957371  to cmake/ModulePackage.cmake (I did adapt the file name to so.version), but somehow it did not work, so this pull request handles only the autotools part. Would be great if you could follow up with a pull request of your own to finalize it for cmake.

**Comment by iphydf** [comment]
I reviewed it, looks fine to me, but I don't really know this stuff, so someone else can review and lgtm.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/420#-:-KaF09x9vUV5orX_S_3p:bw2hn19)*

**Comment by GrayHatter** [comment]
+@zer0-one good luck mate!xs

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[so.version, line 9 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/420#-KaH3SRMIBPh-HWDnOCf:-KaH3SRMIBPh-HWDnOCg:b-yvt409) ([raw file](https://github.com/toktok/c-toxcore/blob/5a0750b6c08532dfa2d9ff9fcf9c67def6f36c42/so.version#L9)):*
> ```
> #           incremented
> # age:      increment if interfaces have been added, set to zero if
> #           interfaces have been removed or changed
> ```

is this text correct?

---

*[toxav/Makefile.inc, line 46 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/420#-KaH3a-yhLYAw-QJ5_Kj:-KaH3a-yhLYAw-QJ5_Kk:b-lwevhh) ([raw file](https://github.com/toktok/c-toxcore/blob/5a0750b6c08532dfa2d9ff9fcf9c67def6f36c42/toxav/Makefile.inc#L46)):*
> ```Makefile
> if SET_SO_VERSION
> 
> EXTRA_libtoxav_la_DEPENDENCIES = ../so.version
> ```

newlines instead of indentation? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/420#-:-KaH3B1SVtKfPoaqnSDD:b-bhhhjt)*

**Comment by jin-eld** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[so.version, line 9 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/420#-KaH3SRMIBPh-HWDnOCf:-KaH7GQQ-EBOzQdsthoN:bel3w6p) ([raw file](https://github.com/toktok/c-toxcore/blob/5a0750b6c08532dfa2d9ff9fcf9c67def6f36c42/so.version#L9)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

is this text correct?
</blockquote></details>

Should be, you can counter check with https://www.gnu.org/software/libtool/manual/libtool.html#Updating-version-info

---

*[toxav/Makefile.inc, line 46 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/420#-KaH3a-yhLYAw-QJ5_Kj:-KaH8osDJv3u0oHHz9Ac:b-e69tfa) ([raw file](https://github.com/toktok/c-toxcore/blob/5a0750b6c08532dfa2d9ff9fcf9c67def6f36c42/toxav/Makefile.inc#L46)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

newlines instead of indentation? 
</blockquote></details>

Indenting "starting" lines does not work with automake, try indenting line 3 after the if BUILD_AV statement, you'll see that toxav won't be built any more, only indenting line continuations after a \ break is allowed; and of course the
make syntax requires indentation in cases like...

target:
[TAB]shell_code

...but that's not the case here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/420)*

**Comment by cebe** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[so.version, line 9 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/420#-KaH3SRMIBPh-HWDnOCf:-KaI6664Y2sv04hgbTqI:b6t8s8s) ([raw file](https://github.com/toktok/c-toxcore/blob/5a0750b6c08532dfa2d9ff9fcf9c67def6f36c42/so.version#L9)):*
<details><summary><i>Previously, jin-eld wrote…</i></summary><blockquote>

Should be, you can counter check with https://www.gnu.org/software/libtool/manual/libtool.html#Updating-version-info
</blockquote></details>

would be good to put that link into the file for reference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/420)*

**Comment by jin-eld** [comment]
Updated, added the link regarding libtool versioning as @cebe suggested.

**Comment by cebe** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/420#-:-KaJCgM5TqwLDhU_JzI0:b-jbsf8z)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/420#-:-KaJN0560LU9gAz9eKeK:b-jbsf8z)*

**Comment by cebe** [comment]
Sent a pull request for the cmake part to this branch: https://github.com/jin-eld/c-toxcore/pull/1
Alternatively we may merge this branch and I send a PR to the main repo.

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/420)*

**Comment by cebe** [comment]
@iphydf @jin-eld how do we proceed here? Please answer https://github.com/TokTok/c-toxcore/pull/420#issuecomment-272722270

**Comment by jin-eld** [comment]
@cebe sorry I did not yet have the time to test your PR in detail, will try to do it tonight

**Comment by iphydf** [comment]
Is this ready to merge?

For the future: don't use "reviewers", use "assignees". The "reviewers" list doesn't appear on the PR overview on github. This PR looks unassigned although it has "reviewers" assigned.

**Comment by jin-eld** [comment]
@iphydf No, not yet, I need to test @cebe 's PR vs my branch and add his commit (it handles the cmake part)

**Comment by jin-eld** [comment]
Integrated @cebe 's commits, this pull should be OK now.

**Comment by jin-eld** [comment]
@iphydf rebased to master

**Pull request merged**
