### PR TITLE
WIP: Add alpine Dockerfile and autoconfig scripts

### PR DESCRIPTION
**Pull request by Nyoroon**
How to build:
1. `cd other/bootstrap_daemon`
2. `docker build -t tox-bootstrapd -f docker/Dockerfile.alpine docker/`

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/636)

### CODE REVIEW

**Comment by nurupo** [comment]
There is already a PR adding Alpine Linux Docker container for `tox-bootstrpd` in https://github.com/TokTok/c-toxcore/pull/465.

**Comment by nurupo** [comment]
In any case, I don't think we are going to merge these PRs because there is no one who would maintain those Alpine Linux containers. I'm currently the one maintaining the `tox-bootstrapd` and the Debian Docker container for it. I'm not familiar with Alpine Linux nor I wish to learn it. If something breaks or if I need to modify something for it I will likely just delete it from the repository rather than figure out how to fix it. I will, of course, fix the things up in the Debian Dockerfile.

**Comment by nurupo** [comment]
Now that I look at it, the Debian container could use some updating, huh.

**Comment by Nyoroon** [comment]
I can maintain alpine image (as active user of it) and update Debian one.

**Comment by nurupo** [comment]
Got the Debian one updated in https://github.com/TokTok/c-toxcore/pull/637.

**Comment by sudden6** [comment]
I agree with @nurupo, it's better to stay with one image.

**Comment by Nyoroon** [comment]
Okay.

I'll made separate repo for it then.

**Pull request closed without merging**
