### PR TITLE
Avoid array out of bounds read in friend saving.

### LINKED ISSUE #345: Array out of bounds read in "save" function
`SAVED_FRIEND_REQUEST_SIZE` is defined as 1024, and during save, we read that many bytes from the friend request data, which is 1016 bytes long. See https://github.com/TokTok/c-toxcore/blob/68be33840a6a9b2677a6ab43068689c8e572e832/toxcore/Messenger.c#L2732.

This is a bug, and causes undefined behaviour in theory. In practice, this is neither a security vulnerability nor does it have any effect on observable behaviour.

**Security impact:** This is not a security vulnerability because the friend request data is immediately followed by the friend name data, which has sufficient length such that the out of bounds read will simply read into the same message.

**Behaviour impact:** This is not a behavioural flaw either, because if there is a friend request message, the name data will be all zeros. If there is no friend request message, it won't be read, and the name will be read correctly instead.

### PR DESCRIPTION
**Pull request by iphydf**
Fixes #345.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/346)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/Messenger.c, line 2732 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/346#-KZQNImkDav-xGt6iqU8:-KZQNImkDav-xGt6iqU9:brf69df) ([raw file](https://github.com/toktok/c-toxcore/blob/233b85fdf2340605fd4d8d1b7dfc482ab8accc6d/toxcore/Messenger.c#L2732)):*
> ```C
>             if (temp.status < 3) {
>                 memcpy(temp.info, m->friendlist[i].info,
>                        MIN(m->friendlist[i].info_size, MIN(SAVED_FRIEND_REQUEST_SIZE, MAX_FRIEND_REQUEST_DATA_SIZE)));
> ```

Why not precalculate `MIN(SAVED_FRIEND_REQUEST_SIZE, MAX_FRIEND_REQUEST_DATA_SIZE)`?
Maybe extract result of `MIN(..MIN())` into separate variable? IMO it will make reading easier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/346)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/346#-:-KZQOeHm8LE34rFzHrpS:b-jbsf8z)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[toxcore/Messenger.c, line 2732 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/346#-KZQNImkDav-xGt6iqU8:-KZQQ0LG8VsQ6HHWDoUu:bfuzmds) ([raw file](https://github.com/toktok/c-toxcore/blob/233b85fdf2340605fd4d8d1b7dfc482ab8accc6d/toxcore/Messenger.c#L2732)):*
>Why not precalculate MIN(SAVED_FRIEND_REQUEST_SIZE, MAX_FRIEND_REQUEST_DATA_SIZE)?

`MIN(SAVED_FRIEND_REQUEST_SIZE, MAX_FRIEND_REQUEST_DATA_SIZE)` should be precalculated by compiler at compile-time, it's a const expression.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/346#-:-KZQQEpmbsQzWOEUGIOn:b-jbsf8z)*

**Comment by nurupo** [comment]
@iphydf just curious, what's `aioobe`, the branch name? Array Index Out Off Bounds Error?

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[toxcore/Messenger.c, line 2732 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/346#-KZQNImkDav-xGt6iqU8:-KZQ_U2v1S_Sn3K3d1e2:bbbvu4w) ([raw file](https://github.com/toktok/c-toxcore/blob/233b85fdf2340605fd4d8d1b7dfc482ab8accc6d/toxcore/Messenger.c#L2732)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

>Why not precalculate MIN(SAVED_FRIEND_REQUEST_SIZE, MAX_FRIEND_REQUEST_DATA_SIZE)?

`MIN(SAVED_FRIEND_REQUEST_SIZE, MAX_FRIEND_REQUEST_DATA_SIZE)` should be precalculated by compiler at compile-time, it's a const expression.
</blockquote></details>

Thanks for explanation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/346#-:-KZQ_f-oP74Knqd5I0Qe:b-jbsf8z)*

**Comment by iphydf** [comment]
Yes: https://docs.oracle.com/javase/7/docs/api/java/lang/ArrayIndexOutOfBoundsException.html. There was no exception in C, and ASAN can't catch it, but in Java there would have been an AIOOBE.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxcore/Messenger.c, line 2732 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/346#-KZQNImkDav-xGt6iqU8:-KZRX7ydFPQETz514YNO:b-19ocb3) ([raw file](https://github.com/toktok/c-toxcore/blob/233b85fdf2340605fd4d8d1b7dfc482ab8accc6d/toxcore/Messenger.c#L2732)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Thanks for explanation
</blockquote></details>

Moved it to a variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/346#-:-KZRWqCJZJDKoMRdWTOf:bk5ursc)*

**Pull request merged**
