### PR TITLE
Move packing and unpacking DHT request packets to DHT module.

### PR DESCRIPTION
**Pull request by iphydf**
These definitely don't belong in a module called "crypto core". The DHT
module seems like the best place to put them, since they are sent to DHT
nodes.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/230)

### CODE REVIEW

**Comment by GrayHatter** [comment]
@iphydf do we want to just move this code from crypto_core.*?

Or do we want to fix the issue of, DHT uses this function to send pings and friend requests, where the onion only for friend requests (I hope, I didn't make sure). So each should have their own copy, with the latter existing in friend_requests.*?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/230#-:-KVcpkCiXFDi6kBV8N7-:b-phntl)*

**Comment by iphydf** [comment]
For now, I'm just trying to define the API for `crypto_core`. This is not part of the crypto API, so it needs to move out. When we get to defining the api for DHT, we can discuss this again.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/230#-:-KVjvqVrEm1vMwO01zTm:b-sanmmt)*

**Comment by GrayHatter** [comment]
ok sounds good 

:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/230#-:-KVkcWKEyQ5Vx2FW9Nri:bbsr5fy)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/230#-:-KWMmL6q-opM8Aq0AMq_:b-jbsf8z)*

**Pull request merged**
