### PR TITLE
Fix tox test

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/587)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[auto_tests/conference_test.c, line 104 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/587#-KuFm3IqSl_3VK7HYRDt:-KuFm3IqSl_3VK7HYRDu:byjoyaj) ([raw file](https://github.com/toktok/c-toxcore/blob/8a85e521ac3d94aa5bf765c2505ee704bafcceb0/auto_tests/conference_test.c#L104)):*
> ```C
>     {
>         TOX_ERR_GET_PORT error;
>         uint16_t port = tox_self_get_udp_port(toxes[0], &error);
> ```

All the `uint16_t port` should be const.

---

*[auto_tests/tox_test.c, line 336 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/587#-KuFmE6xWyI9TiXTjkvy:-KuFmE6xWyI9TiXTjkvz:b-80yds6) ([raw file](https://github.com/toktok/c-toxcore/blob/8a85e521ac3d94aa5bf765c2505ee704bafcceb0/auto_tests/tox_test.c#L336)):*
> ```C
>         uint16_t first_port = tox_self_get_udp_port(tox1, &error);
>         ck_assert_msg(33445 <= first_port && first_port <= 33545 - 2,
>                       "First Tox instance did not bind to udp port inside [33445, 33545].\n");
> ```

Upper bound in the assert is 33545 - 2.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/587)*

**Comment by Diadlo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[auto_tests/conference_test.c, line 104 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/587#-KuFm3IqSl_3VK7HYRDt:-KvZ6HD3GCjJopH41_FS:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/8a85e521ac3d94aa5bf765c2505ee704bafcceb0/auto_tests/conference_test.c#L104)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

All the `uint16_t port` should be const.
</blockquote></details>

Done.

---

*[auto_tests/tox_test.c, line 336 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/587#-KuFmE6xWyI9TiXTjkvy:-KvZ6Hi_-t-_8lytowjW:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/8a85e521ac3d94aa5bf765c2505ee704bafcceb0/auto_tests/tox_test.c#L336)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Upper bound in the assert is 33545 - 2.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/587)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/587#-:-Kvqf82Mc4oZeB5zyulc:b-jbsf8z)*

**Comment by robinlinden** [comment]
Please enable the checkbox "Allow edits from maintainers." on the bottom right.

**Comment by Diadlo** [comment]
@robinlinden Done

**Comment by SkyzohKey** [comment]
@iphydf @robinlinden Can this please be merged ?

**Comment by robinlinden** [comment]
@SkyzohKey I've been rerunning the CI every now and then as I can't merge this until it passes. I'll merge it when it does.

**Comment by Diadlo** [comment]
I have found another place, where port was compared with 33455. And change it to check range

**Comment by iphydf** [comment]
Can you fix the commit message: "asert" -> "assert". Also, rebase on master.

**Comment by Diadlo** [comment]
@iphydf Done

**Comment by SkyzohKey** [comment]
Is this ready to merge? If yes, feel free to apply the `PR:ready` label, or just merge it :)

**Pull request merged**
