### PR TITLE
Update the Tox banner displayed on the Readme.

### PR DESCRIPTION
**Pull request by SkyzohKey**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/830)

### CODE REVIEW

**Comment by nurupo** [comment]
Isn't this the logo of your new Universal Tox Client?

**Comment by SkyzohKey** [comment]
Nope, I'm just trying to rebrand Tox to make it more appealing for new users, and the old logo is too ''sharp''. My new Universal client just use that new logo because I'd like to avoid to switch later and introduce confusion

**Comment by sudden6** [comment]
Why are there playstation buttons in the background?

**Comment by SkyzohKey** [comment]
Those are just squares/circles/triangles Guy xD. I tought it would be prettier than a simple dark, and more original than the ''gradient hype''.. 😂

**Comment by nurupo** [comment]
Those are generally associated with gaming, so I'm not sure what message the logo is trying to convey. That Tox is a chat application for gamers? That can't be right though.

I'd also be careful with using the playstation buttons to avoid any possible lawsuits with Sony.

I'm also happy with the current branding and I don't think our current branding is causing any issues. Making new branding is like fixing something that is not broken.

**Comment by tox-user** [comment]
Nice logo! I would miss the current icon, but this one is pretty cool too. We need to hear feedback from more people. @SkyzohKey why do you think Tox needs rebranding? What else would it involve except changing the logo?

**Comment by SkyzohKey** [comment]
@tox-user IMHO Tox needs a full rebranding. This includes website, logo, making a responsive newsletter, refined user-interfaces, etc. The doc' needs to be polished (design), the wiki should be replaced by the doc, the blog should be integrated to the website. Many small issues that makes Tox feels less appealing that other IM softwares (ie. Wire, Tungsten, Ring, etc).

@nurupo Those are **not** PlayStation buttons, just basic shapes anyone can' make xD. You can't copyright a square, or a triangle, right?

Tox branding is pretty poor as I see it. We have no guidelines, stylesguide, or anything that could help the ''Tox'' brand to be rememberable easily. Tox branding **is** broken. I'm trying to fix that :)

**Comment by iphydf** [comment]
@SkyzohKey feel free to continue driving the discussion with the community, but there seems to be no consensus for now, so I'm closing this PR for the time being.

**Pull request closed without merging**
