### PR TITLE
Use per-instance `Mono_Time` instead of a global `unix_time`

### PR DESCRIPTION
**Pull request by iphydf**
This avoids some global state.

---

This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1038)

### CODE REVIEW

**Comment by nurupo** [comment]
I'm so confused, there is no explanation either in PR or the commit message as to why this is needed, what improvement this brings. At first I thought that you moved the Windows'es global state into a per-instance struct, but that's not the case.

Also, what is the point of the `base_time`?

**Comment by nurupo** [comment]
Oh, nevermind, diff of `mono_time.c` explains it all. You just removed the the global state struct, nothing else changed, the `base_time` was there alredy.

**Comment by zugz** [comment]
I'm having second thoughts on this. Could you explain why this is a positive change?

Mono_Time is meant to represent actual unix time. This is a global concept, so doesn't it actually make sense to use a global for it? Meanwhile making it per-instance increases code complexity.

Having it as a global also makes time manipulation in tests easier.

The only practical advantage I see of making it per-instance is to allow us to model relative clock differences between instances in tests, which I don't anticipate us actually wanting to do.

**Comment by iphydf** [comment]
@zugz PTAL. I've added a comment to explain the assumptions we want to make in the event loop.

**Comment by zugz** [comment]
:lgtm_strong:

**Pull request merged**
