### PR TITLE
Fix some memory or file descriptor leaks in test code.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/681)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[auto_tests/onion_test.c, line 306 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/681#-L2onMCVo0bLa-LxbL4c:-L2onMCVo0bLa-LxbL4d:b-jtgv4c) ([raw file](https://github.com/toktok/c-toxcore/blob/c6a66c8d9f95a2e16d378dd7d3afd63ba51fc544/auto_tests/onion_test.c#L306)):*
> ```C
>     if (!on->onion) {
>         free(on);
>         return NULL;
> ```

leaks `dht` and maybe neworking

---

*[auto_tests/onion_test.c, line 314 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/681#-L2onRlOKKSeM1j2TyAe:-L2onRlOKKSeM1j2TyAf:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/c6a66c8d9f95a2e16d378dd7d3afd63ba51fc544/auto_tests/onion_test.c#L314)):*
> ```C
>         kill_onion(on->onion);
>         free(on);
>         return NULL;
> ```

same

---

*[auto_tests/onion_test.c, line 324 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/681#-L2onZpT_LT0k_XllxAV:-L2onZpT_LT0k_XllxAW:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/c6a66c8d9f95a2e16d378dd7d3afd63ba51fc544/auto_tests/onion_test.c#L324)):*
> ```C
>         kill_onion(on->onion);
>         free(on);
>         return NULL;
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/681)*

**Comment by iphydf** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[auto_tests/onion_test.c, line 306 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/681#-L2onMCVo0bLa-LxbL4c:-L2pIj-EEwAAOyO1xe0x:b-5rnt89) ([raw file](https://github.com/toktok/c-toxcore/blob/c6a66c8d9f95a2e16d378dd7d3afd63ba51fc544/auto_tests/onion_test.c#L306)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

leaks `dht` and maybe neworking
</blockquote></details>

Yes, and yes. Fixed both.

---

*[auto_tests/onion_test.c, line 314 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/681#-L2onRlOKKSeM1j2TyAe:-L2pIhzV4S8X11xQ_VkN:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c6a66c8d9f95a2e16d378dd7d3afd63ba51fc544/auto_tests/onion_test.c#L314)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---

*[auto_tests/onion_test.c, line 324 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/681#-L2onZpT_LT0k_XllxAV:-L2pIiRaDjXlYplWB53k:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c6a66c8d9f95a2e16d378dd7d3afd63ba51fc544/auto_tests/onion_test.c#L324)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/681)*

**Comment by Diadlo** [comment]
I'm not sure, but what about `goto fail;` in every `if`? And place last `if` body after `return on;`

**Comment by endoffile78** [comment]
:lgtm_strong:

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/681#-:-L2pbKYdQlORlk5zrx_h:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:  and I also agree with @Diadlo, we should at least consider introducing this style.

---

Reviewed 1 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/681#-:-L2pi4WLrKTMPVWrWf9u:bvhzzo8)*

**Pull request merged**
