### PR TITLE
refactor: Use tox rng to seed the keypair generation.

### LINKED ISSUE #2649: create_extended_keypair should use Random and be made deterministic for fuzzing
crypto_sign_keypair generates random numbers and then derives a key. We should use `Random` for random numbers and derive the key from that. It's exactly the same in production builds, but in fuzzing this ensures that we can fuzz NGC properly.

### PR DESCRIPTION
**Pull request by iphydf**
Fixes #2649

---

This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2671)

### CODE REVIEW

**Comment by Green-Sky** [comment]
this makes key generation deterministic. Did you check how the fuzzer behaves with this?

**Comment by JFreegman** [comment]
> this makes key generation deterministic. 

How so?

**Comment by iphydf** [comment]
What behaviour do you want me to check regarding the fuzzer?

**Comment by Green-Sky** [comment]
Sorry, my real question was: "Is this intentional, with all its side effects" :)

**Comment by iphydf** [comment]
It has no side effects outside tests/fuzzing. Yes, it is intentional to make tests and fuzzers deterministic.

**Review by robinlinden — APPROVED** [review]

**Review by JFreegman — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2671)* status: <span>:shipit:</span> complete! 2 of 1 approvals obtained

**Pull request merged**
