### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by yangfl**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/611)

### CODE REVIEW

**Comment by redmanmale** [comment]
:lgtm_strong:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/611#-:-KyMCFxt1Jv_4yjn9uhs:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/611#-:-KyRA46t9xzAnwh0pssW:b-jbsf8z)*

**Comment by robinlinden** [comment]
@yangfl Please enable the checkbox "Allow edits from maintainers." on the bottom right.

**Comment by yangfl** [comment]
@robinlinden Didn't I enable it?

**Comment by robinlinden** [comment]
@yangfl Oh, yeah, sorry. Will merge once Travis passes.

**Comment by iphydf** [comment]
Thanks :) merged.

**Pull request merged**
