### PR TITLE
Add CMake knobs to suppress building tests

### PR DESCRIPTION
**Pull request by ismaell**
* BUILD_NTOX for nTox
* BUILD_AV_TEST for the toxav test

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/287)

### CODE REVIEW

**Comment by iphydf** [comment]
Thanks for your contribution, this is useful to have. I just have one minor remark. Let me know if you feel otherwise.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 468 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/287#-KXGXfPOrIEdeCC1lOP8:-KXGXfPPzatK1ukhnVhE:b-e5e6om) ([raw file](https://github.com/toktok/c-toxcore/blob/b13629a72586c650462c918c0802db06e1ed9352/CMakeLists.txt#L468)):*
> ```CMake
> option(BUILD_AV_TEST "Build toxav test" ON)
> if(NOT WIN32 AND BUILD_AV_TEST
>    AND BUILD_TOXAV AND SNDFILE_FOUND AND PORTAUDIO_FOUND AND OPENCV_FOUND)
> ```

Minor nit: put the `BUILD_*` on one line, and the `*_FOUND` ones on the next line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/287#-:-KXGXmUbiXDMnaDdgKeK:bikkjol)*

**Comment by iphydf** [comment]
Ok, thanks. This looks fine. Can you make it either 1 or 2 commits? The reordering doesn't need to be its own commit.

**Comment by iphydf** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/287#-:-KXIUYUW4KGvNPBBbHZy:bg7igkv)*

**Comment by GrayHatter** [comment]
@ismaell thanks mate! I've been commenting them out otherwise... this is already really helpful!!!

**Comment by ismaell** [comment]
@GrayHatter you're welcome.

**Pull request merged**
