### PR TITLE
Add Android build to CI.

### PR DESCRIPTION
**Pull request by zoff99**
also include fix for #457

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/459)

### CODE REVIEW

**Comment by zoff99** [comment]
solves #340

**Comment by iphydf** [comment]
This is insanely ugly, but it seems to work, so :lgtm_strong:. We can clean up this CI script later. Please squash your commits into one.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/459#-:-KbFAi6QhmGHR424QC4Q:b3lt38f)*

**Comment by iphydf** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/459)*

**Comment by zoff99** [comment]
can u squash em for me please? i checked that checkbox.

**Comment by zoff99** [comment]
also are you sure about that:  EPOLLRDHUP fix? is that working for all platforms?

**Comment by iphydf** [comment]
I am not sure about it, but it seems to work, and we'll replace that with libev at some point anyway, so right now I don't care much.

**Comment by zoff99** [comment]
@iphydf funny that you call it insanely ugly :-) since those are your EXACT commands :-) (from jvm-toxcore-c repo)

**Comment by iphydf** [comment]
jvm-toxcore-c scripts are also insanely ugly.

**Comment by zoff99** [comment]
i am happy they exist

**Pull request merged**
