### PR TITLE
Fix typos in docs

### PR DESCRIPTION
**Pull request by dartraiden**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/582)

### CODE REVIEW

**Comment by zugz** [comment]
Thanks for these fixes.

:lgtm:

**Comment by robinlinden** [comment]
Thank you! And please enable the checkbox "Allow edits from maintainers." on the bottom right.

**Comment by dartraiden** [comment]
Done.

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/582#-:-KsOO1GjKYiO_Wt4wsz7:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong: reviewable seems to be acting up...

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/582#-:-KsPeb_DKeoSY2EbGSom:b-oshu5f)*

**Comment by iphydf** [comment]
Oops. Can you reopen this PR?

**Pull request closed without merging**
