### PR TITLE
Update license headers and remove redundant file name comment.

### PR DESCRIPTION
**Pull request by iphydf**
"All rights reserved" was incorrect. The project was licensed under GPL3,
which means a lot of rights are licensed to everybody in the world, i.e.
not reserved to the "Tox Project".

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/431)

### CODE REVIEW

**Comment by fcore117** [comment]
Reviewed 90 of 90 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/431)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 90 of 90 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/util.c, line 5 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/431#-Kao-qXSPnZWRJAMJher:-Kao-qXSPnZWRJAMJhes:bv5njul) ([raw file](https://github.com/toktok/c-toxcore/blob/6d6a4e1e3a96c6fa3e5e07ed57912baf67691ff2/toxcore/util.c#L5)):*
> ```C
>  *
>  * This file is donated to the Tox Project.
>  * Copyright 2013  plutooo
> ```

You didn't remove this person's name from any other files. Is this intentional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/431#-:-Kao0JEm4hW2R8fl8i-7:b-jbsf8z)*

**Comment by iphydf** [comment]
Review status: 89 of 90 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/util.c, line 5 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/431#-Kao-qXSPnZWRJAMJher:-Kao1GrDaaSJjWYZplmO:bjxe625) ([raw file](https://github.com/toktok/c-toxcore/blob/6d6a4e1e3a96c6fa3e5e07ed57912baf67691ff2/toxcore/util.c#L5)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You didn't remove this person's name from any other files. Is this intentional?
</blockquote></details>

No, added back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/431)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/431)*

**Comment by nurupo** [comment]
*[testing/av_test.c, line 22 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/431#-KbJ5kMYfYOUswfE1jZF:-KbJ5kMZ_HN7Wr-5rnv3:b-rxzl7j) ([raw file](https://github.com/toktok/c-toxcore/blob/6d6a4e1e3a96c6fa3e5e07ed57912baf67691ff2/testing/av_test.c#L22)):*
> ```C
>  *   Compile with (Linux only; in newly created directory toxcore/dir_name):
>  *   gcc -o av_test ../toxav/av_test.c ../build/.libs/libtox*.a -lopencv_core \
>  *   -lopencv_highgui -lopencv_imgproc -lsndfile -pthread -lvpx -lopus -lsodium -lportaudio
> ```

Was this intentionally removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/431)*

**Comment by nurupo** [comment]
*[toxcore/crypto_core_mem.c, line 21 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/431#-KbJ6QKxZhGYQCCwfqOK:-KbJ6QKyhxeQo5xH47Aw:b6vqki3) ([raw file](https://github.com/toktok/c-toxcore/blob/8f96ca6d860ee6d2fb9a502b0e931b461edb3919/toxcore/crypto_core_mem.c#L21)):*
> ```C
> #ifdef HAVE_CONFIG_H
> #include "config.h"
> #endif
> ```

Unrelated change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/431)*

**Comment by nurupo** [comment]
*[toxav/ring_buffer.c, line 4 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/431#-KbJ7hI3D0v4SzeoINrD:-KbJ7hI4LVYyEudtibqb:b-lczkfm) ([raw file](https://github.com/toktok/c-toxcore/blob/8f96ca6d860ee6d2fb9a502b0e931b461edb3919/toxav/ring_buffer.c#L4)):*
> ```C
>  * Copyright © 2016-2017 The TokTok team.
>  * Copyright © 2013 Tox project.
>  * Copyright © 2013 plutooo
> ```

What pluto has to do with toxav?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/431)*

**Comment by nurupo** [comment]
*[toxcore/crypto_core_mem.c, line 21 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/431#-KbJ6QKxZhGYQCCwfqOK:-KbJ7qFNkPlx2He712js:b-jrr3gq) ([raw file](https://github.com/toktok/c-toxcore/blob/8f96ca6d860ee6d2fb9a502b0e931b461edb3919/toxcore/crypto_core_mem.c#L21)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Unrelated change.
</blockquote></details>

There are actually quite of few like this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/431)*

**Comment by nurupo** [comment]
Is the unicode copyright symbol somehow better than `(c)` or `(C)`?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/431#-:-KbJ7txQVw8B9x41BtQJ:b-91pwv7)*

**Pull request merged**
