### PR TITLE
cleanup: Remove more implicit bool conversions.

### PR DESCRIPTION
**Pull request by iphydf**
Also use `bool` type in place of `uint8_t` which was the old bool type
in toxcore before C99.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2103)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 14 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2103)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[toxcore/group.h, line 86 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcNrAgEHHIjsNtQc1A:-MwcNrAgEHHIjsNtQc1B:bjw7qp5) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/group.h#L86)):*
> ```objc
> 
> typedef struct Groupchat_Closest {
>     bool entry;
> ```

IDK what `entry` is supposed to mean in this context as a bool, maybe rename it?
___
*[toxcore/group.c, line 1043 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcP6usD1_QRhleVcc9:-MwcP6usD1_QRhleVccA:b-mpob3j) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/group.c#L1043)):*
> ```C
>     Group_Chats *g_c = (Group_Chats *)object;
> 
>     if (status != 0) {
> ```

bool -> int
___
*[toxcore/group.c, line 1055 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcPAEN4MEOQPPeEd8g:-MwcPAEN4MEOQPPeEd8h:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/group.c#L1055)):*
> ```C
>     Group_Chats *g_c = (Group_Chats *)object;
> 
>     if (status != 0) { /* Went online */
> ```

same
___
*[toxcore/group.c, line 1076 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcPImFBZh8tnqO-hwN:-MwcPImFBZh8tnqO-hwO:b-9hisn) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/group.c#L1076)):*
> ```C
>  */
> static int add_conn_to_groupchat(Group_Chats *g_c, int friendcon_id, Group_c *g, uint8_t reason,
>                                  uint8_t lock)
> ```

can `lock` be also converted to bool? and doxygen updated?
___
*[toxcore/Messenger.c, line 1080 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQ3GN9BEPB2VdaXJA:-MwcQ3GN9BEPB2VdaXJB:b1rt7ce) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L1080)):*
> ```C
> 
>     uint32_t temp_filenum;
>     bool send_receive;
> ```

nit: the name of this variable doesn't inidicate if `true` means `send` or `receive` can you add a comment or rename?
___
*[toxcore/Messenger.c, line 1198 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQGNRAKKSdaAnhNu-:-MwcQGNRAKKSdaAnhNu0:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L1198)):*
> ```C
> 
> non_null(1) nullable(6)
> static int send_file_control_packet(const Messenger *m, int32_t friendnumber, bool send_receive, uint8_t filenumber,
> ```

same
___
*[toxcore/Messenger.c, line 1243 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQIy37fkceb-KDU7j:-MwcQIy37fkceb-KDU7k:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L1243)):*
> ```C
> 
>     uint32_t temp_filenum;
>     bool send_receive;
> ```

same
___
*[toxcore/Messenger.c, line 1404 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQLU-0SXn8veNSN2K:-MwcQLU-0SXn8veNSN2L:bdjpqhu) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L1404)):*
> ```C
>     packet[1] = filenumber;
> 
>     if (length != 0) {
> ```

nit: I prefer to use `>` for things like lengths, or counts
___
*[toxcore/Messenger.c, line 1627 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQTW3A9afXrIaA-k9:-MwcQTW3A9afXrIaA-kA:b-j44djy) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L1627)):*
> ```C
> 
> non_null()
> static struct File_Transfers *get_file_transfer(bool receive_send, uint8_t filenumber,
> ```

ambigous variable name as above
___
*[toxcore/Messenger.c, line 1632 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQYjR35VBC7HBiqo3:-MwcQYjR35VBC7HBiqo4:b-3eo6ae) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L1632)):*
> ```C
>     struct File_Transfers *ft;
> 
>     if (!receive_send) {
> ```

flip if/else paths instead of negating?
___
*[toxcore/Messenger.c, line 1650 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQh9Z53ooEGM9VJCL:-MwcQhB78Uogbei6hSO4:b-4sm4qb) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L1650)):*
> ```C
>  */
> non_null(1, 6) nullable(8)
> static int handle_filecontrol(Messenger *m, int32_t friendnumber, bool receive_send, uint8_t filenumber,
> ```

ambigous variable name
___
*[toxcore/Messenger.c, line 2146 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQqHw8VL8ji7_KKWK:-MwcQqHw8VL8ji7_KKWL:b3krd) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L2146)):*
>
___
*[toxcore/Messenger.c, line 2170 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQuF3-jgZkDRGs-0U:-MwcQuF3-jgZkDRGs-0V:b-cwkjka) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L2170)):*
> ```C
>             }
> 
>             const bool send_receive = data[0] != 0;
> ```

ambiguous variable name
___
*[toxcore/onion_client.c, line 1081 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcRjC7B4p3iXJhqba_:-MwcRjC7B4p3iXJhqbaa:b-drlbif) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/onion_client.c#L1081)):*
> ```C
>         ++num_nodes;
> 
>         if (list_nodes[i].is_stored != 0) {
> ```

`is_stored` suggest a bool type, change name or type?

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2103)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf and @sudden6)

___
*[toxcore/group.h, line 86 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcNrAgEHHIjsNtQc1A:-MwcWV8D0seT_GsJXkkv:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/group.h#L86)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

IDK what `entry` is supposed to mean in this context as a bool, maybe rename it?
</blockquote></details>

Done.
___
*[toxcore/group.c, line 1055 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcPAEN4MEOQPPeEd8g:-MwcWXb08pPfDDde543U:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/group.c#L1055)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[toxcore/group.c, line 1076 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcPImFBZh8tnqO-hwN:-MwcWoGI5wsNP0FwQIm2:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/group.c#L1076)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

can `lock` be also converted to bool? and doxygen updated?
</blockquote></details>

Done.



_Code quote:_
```C
add_conn_to_groupchat
```
___
*[toxcore/Messenger.c, line 1198 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQGNRAKKSdaAnhNu-:-Mwc_GmSDekhL3RKYGCe:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L1198)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[toxcore/Messenger.c, line 1243 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQIy37fkceb-KDU7j:-Mwc_HY30WCyUKD-q-95:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L1243)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[toxcore/Messenger.c, line 1627 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQTW3A9afXrIaA-k9:-Mwc_OGd0eZyrrKrXR9y:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L1627)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

ambigous variable name as above
</blockquote></details>

Done.
___
*[toxcore/Messenger.c, line 1632 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQYjR35VBC7HBiqo3:-Mwc_P8_ANOkKfuSWw7m:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L1632)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

flip if/else paths instead of negating?
</blockquote></details>

Done.
___
*[toxcore/Messenger.c, line 1650 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQh9Z53ooEGM9VJCL:-Mwc_QQa7_KBUriKB7Ob:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L1650)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

ambigous variable name
</blockquote></details>

Done.
___
*[toxcore/Messenger.c, line 2146 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQqHw8VL8ji7_KKWK:-Mwc_Qut5VmplAL4-D-R:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L2146)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

>
</blockquote></details>

Done.
___
*[toxcore/Messenger.c, line 2170 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcQuF3-jgZkDRGs-0U:-Mwc_RbrCxVLMIm7RMFp:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/Messenger.c#L2170)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

ambiguous variable name
</blockquote></details>

Done.
___
*[toxcore/onion_client.c, line 1081 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcRjC7B4p3iXJhqba_:-Mwc_wUSC79arCVCJ6BC:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/onion_client.c#L1081)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`is_stored` suggest a bool type, change name or type?
</blockquote></details>

Done.

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2103)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @sudden6)

___
*[toxcore/group.c, line 1043 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcP6usD1_QRhleVcc9:-Mwca00IBFOZBxxp2G-a:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/454996750e63a32576ca71759d33dff7e99d000c/toxcore/group.c#L1043)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

bool -> int
</blockquote></details>

Done.

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, 1 of 2 files at r6, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2103)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[toxcore/Messenger.c, line 530 at r8](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcbDpmBdKezTD_7sfF:-MwcbDpmBdKezTD_7sfG:b-u97fxq) ([raw file](https://github.com/toktok/c-toxcore/blob/c926f9dbc35582b710c93d0406a89225cf746565/toxcore/Messenger.c#L530)):*
> ```C
> 
>     if (length > 0) {
>         memcpy(packet + 1, message, length);
> ```

IMO it should be safe to remove the condition altogether, no?
___
*[toxcore/Messenger.c, line 569 at r8](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcbJFe9R6nTUK9aCVc:-MwcbJFe9R6nTUK9aCVd:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/c926f9dbc35582b710c93d0406a89225cf746565/toxcore/Messenger.c#L569)):*
> ```C
> 
>     if (length > 0) {
>         memcpy(packet + 1, data, length);
> ```

same

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2103)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @sudden6)

___
*[toxcore/Messenger.c, line 530 at r8](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcbDpmBdKezTD_7sfF:-MwccwWm0L9uVaOdhGJY:b-mk707g) ([raw file](https://github.com/toktok/c-toxcore/blob/c926f9dbc35582b710c93d0406a89225cf746565/toxcore/Messenger.c#L530)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

IMO it should be safe to remove the condition altogether, no?
</blockquote></details>

Safe enough I guess. This one is checked in tox.c.
___
*[toxcore/Messenger.c, line 569 at r8](https://reviewable.io/reviews/toktok/c-toxcore/2103#-MwcbJFe9R6nTUK9aCVc:-Mwccz5QDMHj8wL4VifN:b-1umzt2) ([raw file](https://github.com/toktok/c-toxcore/blob/c926f9dbc35582b710c93d0406a89225cf746565/toxcore/Messenger.c#L569)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Probably safe enough. Who knows what craziness toxav is up to. Turned both into assert.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2103#-:-Mwce65a9uVuwG3v3muU:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
