### PR TITLE
Fix padding being in the wrong place in SAVED_FRIEND struct

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/313)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-:-KYkXBx9bqrc5IR8urZ-:b-jbsf8z)*

**Comment by iphydf** [comment]
Generally looks good. The reason I'm nitpicking a bit on this code is that ideally the tests are a kind of documentation, showing how things can be done. Global variables are not how things are done, despite most of our current tests saying so.

---

Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[auto_tests/save_friend_test.c, line 19 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-KYp6oCrHO1RAM2bDdpS:-KYp6oCrHO1RAM2bDdpT:b3h228y) ([raw file](https://github.com/toktok/c-toxcore/blob/5662fd73b569fb3cb10c5c882f54ba59379a3bf2/auto_tests/save_friend_test.c#L19)):*
> ```C
> #endif
> 
> static void set_random(Tox *m, bool (*function)(Tox *, const uint8_t *, size_t, TOX_ERR_SET_INFO *), size_t length)
> ```

Perhaps call this function `setter`. `function` is a bit too generic.

---

*[auto_tests/save_friend_test.c, line 25 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-KYp6c9YfrK8VsWgpn0p:-KYp6c9YfrK8VsWgpn0q:b23zh1i) ([raw file](https://github.com/toktok/c-toxcore/blob/5662fd73b569fb3cb10c5c882f54ba59379a3bf2/auto_tests/save_friend_test.c#L25)):*
> ```C
> 
>     for (i = 0; i < length; ++i) {
>         text[i] = ('A' + (rand() % 26));
> ```

This is non-portable. It won't do what you expect on EBCDIC. It also doesn't matter, because nobody ever displays or otherwise interprets these, so just use `rand()`.

---

*[auto_tests/save_friend_test.c, line 33 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-KYp6s6wjeobGuC4j2Yi:-KYp6s6wjeobGuC4j2Yj:bhm2po1) ([raw file](https://github.com/toktok/c-toxcore/blob/5662fd73b569fb3cb10c5c882f54ba59379a3bf2/auto_tests/save_friend_test.c#L33)):*
> ```C
> }
> 
> static uint8_t status_to_compare[TOX_MAX_STATUS_MESSAGE_LENGTH] = { 0 };
> ```

Put these two into a struct and pass a pointer to the struct as user data.

---

*[auto_tests/save_friend_test.c, line 53 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-KYp7-IRTsVEYgX1BetE:-KYp7-IRTsVEYgX1BetF:b-c2r9qy) ([raw file](https://github.com/toktok/c-toxcore/blob/5662fd73b569fb3cb10c5c882f54ba59379a3bf2/auto_tests/save_friend_test.c#L53)):*
> ```C
>     uint8_t address[TOX_ADDRESS_SIZE];
>     tox_self_get_address(tox1, address);
>     tox_friend_add_norequest(tox2, address, NULL);
> ```

Although this technically works because the public key is a prefix of the address, it's misleading. We want the public key here.

---

*[auto_tests/save_friend_test.c, line 71 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-KYp7NNWpwIkwMXOLaIe:-KYp7NNWpwIkwMXOLaIf:b-mjla9a) ([raw file](https://github.com/toktok/c-toxcore/blob/5662fd73b569fb3cb10c5c882f54ba59379a3bf2/auto_tests/save_friend_test.c#L71)):*
> ```C
>     tox_callback_friend_status_message(tox1, statuschange_callback);
> 
>     const uint32_t iteration_interval = tox_iteration_interval(tox1);
> ```

Also technically correct, because the iteration interval happens to always be the same, but you should really call it in every iteration: `c_sleep(tox_iteration_interval(tox1));`. You could also take the `min` of the two toxes iteration interval to be even more correct, but that doesn't really matter.

---

*[auto_tests/save_friend_test.c, line 87 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-KYp7gK69CYS7xSFkAmK:-KYp7gK69CYS7xSFkAmL:b1o8onz) ([raw file](https://github.com/toktok/c-toxcore/blob/5662fd73b569fb3cb10c5c882f54ba59379a3bf2/auto_tests/save_friend_test.c#L87)):*
> ```C
> 
>     while (true) {
>         if (memcmp(reference_name, name_to_compare, TOX_MAX_NAME_LENGTH) == 0 &&
> ```

When you got your struct with the name in it, also add a bool that says something like `received_name` and `received_status_message` that you can check here. Not really for efficiency, but these comparisons are slightly unclear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-:-KYp83HLI3lJbOz43cAb:bskjx72)*

**Comment by robinlinden** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[auto_tests/save_friend_test.c, line 19 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-KYp6oCrHO1RAM2bDdpS:-KYpB40phYA6ol4Bxbl4:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/5662fd73b569fb3cb10c5c882f54ba59379a3bf2/auto_tests/save_friend_test.c#L19)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Perhaps call this function `setter`. `function` is a bit too generic.
</blockquote></details>

Done.

---

*[auto_tests/save_friend_test.c, line 25 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-KYp6c9YfrK8VsWgpn0p:-KYpCutKr1Of6sDWKLKS:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/5662fd73b569fb3cb10c5c882f54ba59379a3bf2/auto_tests/save_friend_test.c#L25)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

This is non-portable. It won't do what you expect on EBCDIC. It also doesn't matter, because nobody ever displays or otherwise interprets these, so just use `rand()`.
</blockquote></details>

Done.

---

*[auto_tests/save_friend_test.c, line 33 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-KYp6s6wjeobGuC4j2Yi:-KYpLQ_nX0i9zqyi_hke:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/5662fd73b569fb3cb10c5c882f54ba59379a3bf2/auto_tests/save_friend_test.c#L33)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Put these two into a struct and pass a pointer to the struct as user data.
</blockquote></details>

Done.

---

*[auto_tests/save_friend_test.c, line 53 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-KYp7-IRTsVEYgX1BetE:-KYpCzQ42I9yK_eapXaW:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/5662fd73b569fb3cb10c5c882f54ba59379a3bf2/auto_tests/save_friend_test.c#L53)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Although this technically works because the public key is a prefix of the address, it's misleading. We want the public key here.
</blockquote></details>

Done.

---

*[auto_tests/save_friend_test.c, line 71 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-KYp7NNWpwIkwMXOLaIe:-KYpDNv5RaBcnUhcT3GC:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/5662fd73b569fb3cb10c5c882f54ba59379a3bf2/auto_tests/save_friend_test.c#L71)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Also technically correct, because the iteration interval happens to always be the same, but you should really call it in every iteration: `c_sleep(tox_iteration_interval(tox1));`. You could also take the `min` of the two toxes iteration interval to be even more correct, but that doesn't really matter.
</blockquote></details>

Done.

---

*[auto_tests/save_friend_test.c, line 87 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-KYp7gK69CYS7xSFkAmK:-KYpLS3U1vOq7Cs4qAJP:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/5662fd73b569fb3cb10c5c882f54ba59379a3bf2/auto_tests/save_friend_test.c#L87)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

When you got your struct with the name in it, also add a bool that says something like `received_name` and `received_status_message` that you can check here. Not really for efficiency, but these comparisons are slightly unclear.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/313)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-:-KYpU8JFezbOybjFVfqm:b-jbsf8z)*

**Comment by iphydf** [comment]
Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/313)*

**Comment by nurupo** [comment]
Reviewed 1 of 2 files at r2, 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/313)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/313#-:-KYwKu0y9-aaWmV_0War:b-jbsf8z)*

**Pull request merged**
