### PR TITLE
Add random testing program.

### PR DESCRIPTION
**Pull request by iphydf**
This can be used as a random stress test for toxcore.
Adjust the weights to make certain actions more or less likely.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/917)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 2 of 3 files at r1.
Review status: 0 of 1 LGTMs obtained

---

*[testing/random_testing.cc, line 80 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFfZKFj6juV2CWv_UFv:-LFfZKFkB8iFlzwjCHT3:b7bjfrd) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L80)):*
> ```cpp
> struct Action {
>   uint32_t weight;
>   char const *title;
> ```

Maybe use `std::string`?

---

*[testing/random_testing.cc, line 188 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFfZwkE1zVG08vKViJ5:-LFfZwkE1zVG08vKViJ6:b-wh2p79) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L188)):*
> ```cpp
> Random::Random()
>     : tox_selector(0, NUM_TOXES - 1),
>       friend_selector(0, NUM_TOXES - 2),
> ```

I think you made this `-2` to not select the executing function as target, right? We should allow that for additional coverage.

---

*[testing/random_testing.cc, line 211 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFf_SX97vJbW5RUWPl4:-LFf_SX97vJbW5RUWPl5:bxx33vh) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L211)):*
> ```cpp
> 
>   if (connection_status == TOX_CONNECTION_NONE) {
>     std::printf("Tox #%u lost friend %u!\n", state->id(), friend_number);
> ```

Huh, didn't now this was a possible way to output something in C++, but why not use the `std::cout` stream?

---

*[testing/random_testing.cc, line 373 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFfb4lvDcS26p6Tb6bz:-LFfb4lw33kQsdE4QmVe:b-1ef4fu) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L373)):*
> ```cpp
>   uint32_t action_number;
>   for (action_number = 0; action_number < MAX_ACTIONS; action_number++) {
>     if (!all_connected(toxes)) {
> ```

Use `&&` of nesting ifs?

---


*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/917)*

**Comment by iphydf** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[testing/random_testing.cc, line 80 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFfZKFj6juV2CWv_UFv:-LFg3NsD1gwakqvSBYse:b-p1a04z) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L80)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Maybe use `std::string`?
</blockquote></details>

Maybe, but why?

---

*[testing/random_testing.cc, line 188 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFfZwkE1zVG08vKViJ5:-LFg2UES7-3pnG7p9fSE:b-pwtro7) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L188)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think you made this `-2` to not select the executing function as target, right? We should allow that for additional coverage.
</blockquote></details>

You can't have yourself as a friend, so you can have at most NUM_TOXES - 1 friends.

---

*[testing/random_testing.cc, line 211 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFf_SX97vJbW5RUWPl4:-LFg2kZNAmHTscv8CiGF:b-o657dm) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L211)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Huh, didn't now this was a possible way to output something in C++, but why not use the `std::cout` stream?
</blockquote></details>

I like printf, and tox devs are familiar with it, so this code is more accessible to them. What's the reason for recommending iostream in this code, instead?

---


*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/917)*

**Comment by sudden6** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[testing/random_testing.cc, line 80 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFfZKFj6juV2CWv_UFv:-LFgBSWh8mRaVAbpVZpg:b-y3gcsl) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L80)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Maybe, but why?
</blockquote></details>

No raw pointers and no accidentally placing `\0` in the middle of a string

---

*[testing/random_testing.cc, line 188 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFfZwkE1zVG08vKViJ5:-LFg9WXv2hrQqz35X_Ma:b-d56f9e) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L188)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

You can't have yourself as a friend, so you can have at most NUM_TOXES - 1 friends.
</blockquote></details>

Right, sorry didn't think that through.

---

*[testing/random_testing.cc, line 211 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFf_SX97vJbW5RUWPl4:-LFg9laZ4WwD4VhTJvz2:b-bhnjxk) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L211)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

I like printf, and tox devs are familiar with it, so this code is more accessible to them. What's the reason for recommending iostream in this code, instead?
</blockquote></details>

IMO it makes the code more readable to have the variables at the right place in the output string.
```
std::cout << "Tox #" << std::to_string(state->id()) << " lost friend " << std::to_string(friend_number) << "!" << std::endl;
```

But I think in this case familiarity of the other devs with printf is a better argument.

---


*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/917)*

**Comment by iphydf** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[testing/random_testing.cc, line 80 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFfZKFj6juV2CWv_UFv:-LFgP2tl85HQyx-TRzVu:bezszzf) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L80)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

No raw pointers and no accidentally placing `\0` in the middle of a string
</blockquote></details>

These are raw pointers to read only data from string literals. It doesn't really make sense to heap-allocate mutable strings for these. I'd make it `constexpr` if I could.

---

*[testing/random_testing.cc, line 211 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFf_SX97vJbW5RUWPl4:-LFgOYm60QADvANjID-S:b-54snbz) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L211)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

IMO it makes the code more readable to have the variables at the right place in the output string.
```
std::cout << "Tox #" << std::to_string(state->id()) << " lost friend " << std::to_string(friend_number) << "!" << std::endl;
```

But I think in this case familiarity of the other devs with printf is a better argument.
</blockquote></details>

Acknowledged.

---

*[testing/random_testing.cc, line 373 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFfb4lvDcS26p6Tb6bz:-LFgOhsP6TJI9v3hPCe6:boja0c1) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L373)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Use `&&` of nesting ifs?
</blockquote></details>

The two conditions aren't really related. The first one is "check if some toxes have disconnected", the second one is performing an action "reconnect", which results in termination if it fails. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/917)*

**Comment by sudden6** [comment]
*[testing/random_testing.cc, line 80 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFfZKFj6juV2CWv_UFv:-LFgSzwl6A_XVx77zmYG:bgrlh7g) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L80)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

These are raw pointers to read only data from string literals. It doesn't really make sense to heap-allocate mutable strings for these. I'd make it `constexpr` if I could.
</blockquote></details>

One could make this string private and only allow a getter, but I guess this is overkill as well, so feel free to leave it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/917)*

**Comment by sudden6** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[testing/random_testing.cc, line 373 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFfb4lvDcS26p6Tb6bz:-LFgTMMjC2D1n2itTMIB:bkhydqs) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L373)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

The two conditions aren't really related. The first one is "check if some toxes have disconnected", the second one is performing an action "reconnect", which results in termination if it fails. Thoughts?
</blockquote></details>

To me this structure looks like there's something missing inside the first if level so I prefer to use `&&` to make it clear that nothing is missing. Also the `&&` structure makes it easier to perform a de morgan transformation `(!A and !B) == !(A or B)` in your head.

---


*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/917)*

**Comment by iphydf** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[testing/random_testing.cc, line 373 at r1](https://reviewable.io/reviews/toktok/c-toxcore/917#-LFfb4lvDcS26p6Tb6bz:-LFgbuTLD3Xl2fOmzpcw:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/1d18e2412b04a858c4059ee1a679fb0fe33815a2/testing/random_testing.cc#L373)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

To me this structure looks like there's something missing inside the first if level so I prefer to use `&&` to make it clear that nothing is missing. Also the `&&` structure makes it easier to perform a de morgan transformation `(!A and !B) == !(A or B)` in your head.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/917)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/917#-:-LFgeWLV0GLNyt5PkBuR:b-jbsf8z)*

**Pull request merged**
