### PR TITLE
Fix problems with initial connections and name-setting in conferences

### PR DESCRIPTION
**Pull request by zugz**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1035)

### CODE REVIEW

**Review by iphydf — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1035)* status: 0 of 1 LGTMs obtained

___
*[auto_tests/conference_test.c, line 105 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIWp5KeAuMyOdkMBULs:-LIWp5KeAuMyOdkMBULt:b-fceu2) ([raw file](https://github.com/toktok/c-toxcore/blob/10db307048885b1162e03e4c8eecf3cc3030e8cf/auto_tests/conference_test.c#L105)):*
> ```C
>     for (uint16_t i = 0; i < NUM_GROUP_TOX; ++i) {
>         for (uint16_t j = 0; j < NUM_GROUP_TOX; ++j) {
>             const int len = tox_conference_peer_get_name_size(toxes[i], 0, j, nullptr);
> ```

size_t or uint32_t
___
*[auto_tests/conference_test.c, line 154 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIWpAO_7gls_ykfhSYR:-LIWpAO_7gls_ykfhSYS:b-hxg7rd) ([raw file](https://github.com/toktok/c-toxcore/blob/10db307048885b1162e03e4c8eecf3cc3030e8cf/auto_tests/conference_test.c#L154)):*
> ```C
> 
>         char name[NAMELEN+1];
>         snprintf(name,NAMELEN+1,"Tox #%4d",tox_index[i]);
> ```

Run format-source.
___
*[toxcore/group.c, line 2043 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIWq1_J0eyoTPRH35lL:-LIWq1_J0eyoTPRH35lM:b-ry5h2s) ([raw file](https://github.com/toktok/c-toxcore/blob/10db307048885b1162e03e4c8eecf3cc3030e8cf/toxcore/group.c#L2043)):*
> ```C
> static bool check_message_info(uint32_t message_number, uint8_t message_id, Group_Peer *peer)
> {
>     bool ignore_older = (message_id == GROUP_MESSAGE_NAME_ID || message_id == GROUP_MESSAGE_TITLE_ID);
> ```

const bool
___
*[toxcore/group.c, line 2046 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIWs-jpBcw7ScMtDL7p:-LIWs-jpBcw7ScMtDL7q:bpuz2kq) ([raw file](https://github.com/toktok/c-toxcore/blob/10db307048885b1162e03e4c8eecf3cc3030e8cf/toxcore/group.c#L2046)):*
> ```C
> 
>     Message_Info *i;
>     for (i = peer->last_message_infos; i < peer->last_message_infos + peer->num_last_message_infos; ++i) {
> ```

Can you factor out this for-loop into a separate function returning `Message_Info*` or `nullptr`?
___
*[toxcore/group.c, line 2067 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIWrTQz1XlZ-9W7krx6:-LIWrTQz1XlZ-9W7krx7:b-tqb7x2) ([raw file](https://github.com/toktok/c-toxcore/blob/10db307048885b1162e03e4c8eecf3cc3030e8cf/toxcore/group.c#L2067)):*
> ```C
> 
>     for (Message_Info *j = peer->last_message_infos + peer->num_last_message_infos - 1; j > i; --j) {
>         *j = *(j-1);
> ```

This looks like memmove. Use memmove?

**Review by iphydf — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1035)* status: 0 of 1 LGTMs obtained

___
*[auto_tests/conference_test.c, line 155 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIX0g8o3fktaS3ey7A3:-LIX0g8o3fktaS3ey7A4:b-ki5k31) ([raw file](https://github.com/toktok/c-toxcore/blob/10db307048885b1162e03e4c8eecf3cc3030e8cf/auto_tests/conference_test.c#L155)):*
> ```C
>         char name[NAMELEN+1];
>         snprintf(name,NAMELEN+1,"Tox #%4d",tox_index[i]);
>         tox_self_set_name(toxes[i], name, NAMELEN, nullptr);
> ```

`name` needs a cast to 'const uint8_t *`.

**Review by iphydf — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1035)* status: 0 of 1 LGTMs obtained

___
*[auto_tests/conference_test.c, line 105 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIWp5KeAuMyOdkMBULs:-LIazlIrCOGA1UlJ1fkL:blzf5rm) ([raw file](https://github.com/toktok/c-toxcore/blob/10db307048885b1162e03e4c8eecf3cc3030e8cf/auto_tests/conference_test.c#L105)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

size_t or uint32_t
</blockquote></details>

Still (this comment is on line 105, regarding `len`).
___
*[auto_tests/conference_test.c, line 114 at r2](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIazuLOEUg-wuEX_0Kg:-LIazuLOEUg-wuEX_0Kh:b-208292) ([raw file](https://github.com/toktok/c-toxcore/blob/05b9d8a21e69106a98d2c3caf106048a81a5201c/auto_tests/conference_test.c#L114)):*
> ```C
>             snprintf(expected_name, NAMELEN + 1, NAME_FORMAT_STR, tox_index[j]);
>             ck_assert_msg(memcmp(name, expected_name, NAMELEN) == 0,
>                           "name of #%d according to #%d is \"" NAME_FORMAT "\"; expected \"%s\"",
> ```

`%u` since tox_indexes are unsigned.
___
*[auto_tests/conference_test.c, line 164 at r2](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIb-9cO9T6_ZS6qBPJD:-LIb-9cO9T6_ZS6qBPJE:befg0hj) ([raw file](https://github.com/toktok/c-toxcore/blob/05b9d8a21e69106a98d2c3caf106048a81a5201c/auto_tests/conference_test.c#L164)):*
> ```C
>         char name[NAMELEN + 1];
>         snprintf(name, NAMELEN + 1, NAME_FORMAT_STR, tox_index[i]);
>         tox_self_set_name(toxes[i], (const uint8_t *) name, NAMELEN, nullptr);
> ```

No space after cast.
___
*[toxcore/group.c, line 2042 at r2](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIb-FFMBuMA4QEnsuCb:-LIb-FFMBuMA4QEnsuCc:btvc65z) ([raw file](https://github.com/toktok/c-toxcore/blob/05b9d8a21e69106a98d2c3caf106048a81a5201c/toxcore/group.c#L2042)):*
> ```C
> }
> 
> Message_Info *find_message_slot_or_reject(uint32_t message_number, uint8_t message_id, Group_Peer *peer)
> ```

Make this internal linkage.
___
*[toxcore/group.c, line 2048 at r2](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIb-Pmr1zIYhzGvnJ0H:-LIb-Pmr1zIYhzGvnJ0I:ben26c1) ([raw file](https://github.com/toktok/c-toxcore/blob/05b9d8a21e69106a98d2c3caf106048a81a5201c/toxcore/group.c#L2048)):*
> ```C
>     Message_Info *i;
> 
>     for (i = peer->last_message_infos; i < peer->last_message_infos + peer->num_last_message_infos; ++i) {
> ```

You can write `for (Message_Info *i = ...) {` and instead of `break`, write `return i` and instead of `return nullptr`, write `break`, and at the bottom `return nullptr`.
___
*[toxcore/group.c, line 2072 at r2](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIb-nmaDKT4AuTUBB1u:-LIb-nmaDKT4AuTUBB1v:bykfc7o) ([raw file](https://github.com/toktok/c-toxcore/blob/05b9d8a21e69106a98d2c3caf106048a81a5201c/toxcore/group.c#L2072)):*
> ```C
> static bool check_message_info(uint32_t message_number, uint8_t message_id, Group_Peer *peer)
> {
>     Message_Info *i = find_message_slot_or_reject(message_number, message_id, peer);
> ```

`Message_Info *const i = ...`
___
*[toxcore/group.c, line 2121 at r2](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIb0Se7Ey6eb_DfBPep:-LIb0Se8615HmNww0SYb:b-7s4sqq) ([raw file](https://github.com/toktok/c-toxcore/blob/05b9d8a21e69106a98d2c3caf106048a81a5201c/toxcore/group.c#L2121)):*
> ```C
> 
>     if (g->number_joined != -1 && count_close_connected(g) >= DESIRED_CLOSE_CONNECTIONS) {
>         int fr_close_index = friend_in_close(g, g->number_joined);
> ```

const

**Review by iphydf — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1035)* status: 0 of 1 LGTMs obtained

___
*[auto_tests/conference_test.c, line 21 at r3](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIbxDqE9Eb3vL5egSe_:-LIbxDqE9Eb3vL5egSea:b-7v4miz) ([raw file](https://github.com/toktok/c-toxcore/blob/ed89dc79aaac37132a21dd5eb8a4e2b681366235/auto_tests/conference_test.c#L21)):*
> ```C
> #define GROUP_MESSAGE "Install Gentoo"
> 
> #define NAME_FORMAT_STR "Tox #%4d"
> ```

`%4u`
___
*[toxcore/group.c, line 2143 at r3](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIbxWo1AMSHkR82qOPX:-LIbxWo1AMSHkR82qOPY:bllger9) ([raw file](https://github.com/toktok/c-toxcore/blob/ed89dc79aaac37132a21dd5eb8a4e2b681366235/toxcore/group.c#L2143)):*
> ```C
> 
>     uint32_t message_number;
>     memcpy(&message_number, data + sizeof(uint16_t), sizeof(message_number));
> ```

Can you use `net_unpack_u32` here?

**Review by iphydf — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1035)* status: 0 of 1 LGTMs obtained

___
*[auto_tests/conference_test.c, line 108 at r3](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIbxgE197kLODpNiEol:-LIbxgE197kLODpNiEom:bidm3cf) ([raw file](https://github.com/toktok/c-toxcore/blob/ed89dc79aaac37132a21dd5eb8a4e2b681366235/auto_tests/conference_test.c#L108)):*
> ```C
>         for (uint16_t j = 0; j < NUM_GROUP_TOX; ++j) {
>             const size_t len = tox_conference_peer_get_name_size(toxes[i], 0, j, nullptr);
>             ck_assert_msg(len == NAMELEN, "name of #%u according to #%u has incorrect length %u", tox_index[j], tox_index[i], len);
> ```

Now you need to cast `len` to `(unsigned int)` to fit into `%u`.

**Comment by zugz** [comment]
* Sunday, 2018-07-29 at 21:34 +0000 - iphydf <notifications@github.com>:

>*[toxcore/group.c, line 2143 at r3](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIbxWo1AMSHkR82qOPX:-LIbxWo1AMSHkR82qOPY:bllger9) ([raw file](https://github.com/toktok/c-toxcore/blob/ed89dc79aaac37132a21dd5eb8a4e2b681366235/toxcore/group.c#L2143)):*
>> ```C
>>
>>     uint32_t message_number;
>>     memcpy(&message_number, data + sizeof(uint16_t), sizeof(message_number));
>> ```
>
>Can you use `net_unpack_u32` here?

This was existing code, just moved. I can change it, but maybe it would 
make more sense to convert the whole codebase to use net_unpack_* in one 
go, in a separate PR?

**Review by iphydf — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 3 files at r2, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1035#-:-LIoJm08DioGgIpiWUcg:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by robinlinden — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 3 files at r2, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1035#-:-LIqz53F9b3NevklrxZj:b-jbsf8z)* status: :shipit: complete! 2 of 1 LGTMs obtained

___
*[auto_tests/conference_test.c, line 132 at r4](https://reviewable.io/reviews/toktok/c-toxcore/1035#-LIqw3QqCasTlf_4KWsX:-LIqvumF72Hh3uUiq0FN:barwybj) ([raw file](https://github.com/toktok/c-toxcore/blob/111877e5bfd1bf61de5e5768db6ea3351bf6de61/auto_tests/conference_test.c#L132)):*
> ```C
>             const size_t len = tox_conference_peer_get_name_size(toxes[i], 0, j, nullptr);
>             ck_assert_msg(len == NAMELEN, "name of #%u according to #%u has incorrect length %u", state[j].id, state[i].id,
>                           (unsigned int) len);
> ```

Nit: no space between cast and variable.

**Comment by zugz** [comment]
* Wednesday, 2018-08-01 at 19:35 +0000 - Robin Lindén <notifications@github.com>:

>Nit: no space between cast and variable.

Done.

Also improved connectedness detetection, and signed the commit.

**Review by robinlinden — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1035)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Pull request merged**
