### PR TITLE
Make BUILD_TOXAV an option and fail if dependencies are missing

### LINKED ISSUE #482: CMake can't detect and compile ToxAV on OSX
CMake thinks VPX or OPUS can't be found on OSX so it ignores and/or over-rides `-DBUILD_TOXAV=ON`.

Either way, the CMake file shouldn't ignore it's instructions, when -DBUILD_TOXAV is set to ON, it shouldn't decide it doesn't want to. Regardless of if it thinks VPX and OPUS is available.

### PR DESCRIPTION
**Pull request by cebe**
fixes #482

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/483)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

**Comment by cebe** [comment]
This seems to fail on windows, need to look into how it could be fixed...

**Comment by GrayHatter** [comment]
@cebe seems to work fine on travis. Was appveyor ever fixed? And if yes, did you rebase on that fix?

**Comment by cebe** [comment]
appveyor fails with the error message I added so it is definitively related.  https://ci.appveyor.com/project/iphydf/c-toxcore/build/1.0.138#L254

**Comment by iphydf** [comment]
Check the checkbox that allows collaborators to push to the PR branch. Also, rebase (appveyor should work now).

**Comment by cebe** [comment]
rebased.

**Comment by nurupo** [comment]
The AppVeyor can't build libtoxav, as cmake doesn't know where to look for opus and vpx libraries when there is no pkg-config, as I have mentioned in https://github.com/TokTok/c-toxcore/pull/477#issuecomment-283906298. You can just add `-DBUILD_TOXAV=OFF` to the AppVeyor cmake command and let someone else to fix this in a separate PR.

**Comment by nurupo** [comment]
Btw, autotools won't build toxav if opus and vpx are not found. Are we fine with changing this behavior only in cmake but keeping it in autotools?

**Comment by nurupo** [comment]
I'm not very happy with this PR. I think the change has to be done in https://github.com/TokTok/c-toxcore/blob/master/cmake/Dependencies.cmake instead of CMakeLists.txt. Something along the lines of

```cmake
option(BUILD_TOXAV "Whether to build the tox AV library" ON)

if(BUILD_TOXAV)
  pkg_use_module(OPUS                 opus         REQUIRED)
  pkg_use_module(VPX                  vpx          REQUIRED)
endif()
```

`pkg_use_module()` would need to pass the `REQUIRED` into `pkg_search_module()` [[1]](https://github.com/TokTok/c-toxcore/blob/ce0bf232d1b2c01df056df9a030e10ba5252832f/cmake/ModulePackage.cmake#L39), [[2]](https://cmake.org/cmake/help/v3.0/module/FindPkgConfig.html).

**Comment by nurupo** [comment]
Also, with the PR as it is now, if you specify `-DBUILD_TOXAV=OFF`, libtoxav would still be built if you have opus and vpx, which is probably not what you want when you set `BUILD_TOXAV` to `OFF`.

**Comment by nurupo** [comment]
Oh, I see, the `BUILD_TOXAV` was already in CMakeLists.txt before. So my last comment is incorrect, it won't build libtoxav if you set `BUILD_TOXAV` to `OFF`.

**Comment by nurupo** [comment]
:lgtm_strong:

I guess it's okay as it is.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/483#-:-KeWxomD8qvpx64Wy7bd:b-trh12r)*

**Comment by cebe** [comment]
> You can just add -DBUILD_TOXAV=OFF to the AppVeyor cmake command and let someone else to fix this in a separate PR.

done.

> Btw, autotools would skip building of toxav if opus or vpx are not found. Are we fine with changing this behavior only in cmake but keeping it in autotools?

I do not know enough about autotools to change it. If you want autotools to behave the same, someone else has to do that.

**Comment by GrayHatter** [comment]
This is NOT what I wanted for uTox.

While better, this was supposed to allow the user to override the cmake options. E.g. on the osx-crosscompile env we're using to build uTox-OSX on linux, tokcore can't find the vpx or opus libs, but they're available.

Is the solution to add `-DFORCE_BUILD_TOXAV`, or to drop `SEND_ERROR`?

**Comment by cebe** [comment]
where are they, if they are available? This fix makes it clear where the error is, so the build systems does not assume you did not want Opus or VPX if it can not find them.

If there is a problem with finding the libs, the depencency finder of cmake should be fixed to support that case.

**Pull request merged**
