### PR TITLE
Update ruby on travis

### PR DESCRIPTION
**Pull request by Diadlo**
Should fix https://travis-ci.org/TokTok/c-toxcore/jobs/290699354#L1660

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/603)

### CODE REVIEW

**Comment by sudden6** [comment]
I think you also need e98297134a98d34a37650ba3eaba07058d5b1120 for it to work.

**Comment by Diadlo** [comment]
@sudden6 Maybe it too, but current error the same -- wrong ruby version. Do you have an ideas?

**Comment by sudden6** [comment]
@Diadlo you need to move the update of ruby before calling `brew` for the first time.

**Comment by robinlinden** [comment]
@Diadlo `brew update` before anything else should do it. See https://github.com/uTox/uTox/pull/1094

**Comment by sudden6** [comment]
hmm, maybe we should revert the corresponding commits from qTox too.

**Pull request closed without merging**
