### PR TITLE
Do not compile and install DHT_bootstrap if it was disabled in configure

### LINKED ISSUE #319: toxcore installs `DHT_bootstrap` even though `--disable-daemon` is passed to `./configure`
on toxcore c8d7cf5002b1a8ccdf09a91cbd1bbdc11cf96753

I was told that it also affects irungentoo/toxcore

### PR DESCRIPTION
**Pull request by jin-eld**
closes #319

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/324)

### CODE REVIEW

**Comment by robinlinden** [comment]
Can you make this change in [CMakeLists.txt](https://github.com/TokTok/c-toxcore/blob/master/CMakeLists.txt#L438) too? I think most people compiling c-toxcore are using CMake for it.

**Comment by nurupo** [comment]
This PR is invalid as DHT_bootstrap and tox-bootstrapd (the DHT bootstrap daemon) are different things.

**Comment by jin-eld** [comment]
If it is like @nurupo says, then the actual issue is #319 is invalid? I talked to @iphydf before implementing the fix, so I guess there was some confusion on all sides.

@robinlinden Regarding cmake - I can't, I am not familiar with it, I offered iphydf to help out with the autoconf bugs, if the same problem exists in the cmake build, then someone who is familiar with it should fix it too.

**Comment by iphydf** [comment]
@zetok as person filing the issue may have thoughts on this.

**Comment by iphydf** [comment]
So what do we do about this? @zetok, @nurupo.

**Comment by zetok** [comment]
@nurupo what is `DHT_bootstrap` supposed to do then? Is it needed in a default library install?

Given that there are no docs, the simple assumption is that `DHT_bootstrap` is not needed for anything and should be removed.

It doesn't really matter which switch would cause it to stop being build/installed when it's not needed, as long as there's such switch.

Right now there's no switch AFAIK.

**Comment by nurupo** [comment]
>@nurupo what is DHT_bootstrap supposed to do then?

DHT_bootstrap is a simple DHT bootstrap node program which existed since early days of toxcore and was always built together with toxcore for as long as I can remember. It's not a new behavior of the default toxcore build/install.

>Is it needed in a default library install?

I don't have any strong opinion on that matter. Many libraries produce executable binaries in their default build, many also do not. Maybe some other Tox developers have a strong opinion on that?

>Given that there are no docs, the simple assumption is that DHT_bootstrap is not needed for anything and should be removed.

What "docs" you are talking about?

>It doesn't really matter which switch would cause it to stop being build/installed when it's not needed, as long as there's such switch.

Sure, I don't mind it having a separate build switch, just don't lump it under the same switch as the daemon.

**Comment by jin-eld** [comment]
So from the above discussion: I'll add another switch for it to keep it separate from the daemon. Do we want to compile it by default (i.e. should the switch default be enabled or disabled)?

**Comment by iphydf** [comment]
I'd suggest adding a new flag and enabling it by default iff the actual bootstrap daemon is also enabled by default. For cmake, see CMakeLists.txt:448. Look for `option(BOOTSTRAP_DAEMON`. You can do a similar thing for `DHT_bootstrap`, if you like. That would be enabled by default.

**Comment by zetok** [comment]
@nurupo 
>> Is it needed in a default library install?
> 
> I don't have any strong opinion on that matter. Many libraries produce executable binaries in their default build, many also do not. Maybe some other Tox developers have a strong opinion on that?

Question is, is it useful for anything? The yes/no answer to that question is also the answer to the question whether it is needed in a default install.

>What "docs" you are talking about?

The ones that are missing. Any documentation on using/something `DHT_bootstrap`.

**Comment by nurupo** [comment]
>and enabling it by default iff the actual bootstrap daemon is also enabled by default

People often confuse the two, the DHT_bootstrap and the bootstrap daemon, thinking that DHT_bootstrap is the daemon and asking the help for the DHT daemon, for whoever tries to help them to figure out later that they are not actually using the daemon. That's one of the reasons why I did't want a single flag which will enable both of them.

>The ones that are missing. Any documentation on using/something DHT_bootstrap.

Yeah, there is no documentation on DHT_bootstrap aside from the help/usage example when you run it with no arguments. Anyone willing to make manpages for DHT_bootstrap and tox-bootstrapd?

**Comment by jin-eld** [comment]
Updated. 

Added an option --disable-dht-bootstrap (default: enabled) as discussed above.
The --enable-daemon option stays unchanged.

**Comment by robinlinden** [comment]
It might be easier to remember the options if both are --enable-x instead of mixing disabling and enabling features. I'm fine with the default being to not build it though.

**Comment by iphydf** [comment]
I think `AC_ARG_ENABLE` generates both `--enable-` and `--disable-` options, so it doesn't really matter. I have no opinion - @zetok and @nurupo decide.

**Comment by zetok** [comment]
I don't really care about the naming, as long as there is an option and it's documented.

@jin-eld could you add docs about the switch to the `INSTALL.md` under `Advanced configure options` ?

I don't think though that it should be enabled by default though, since it doesn't seem to have any use.

If the default is set to `enable`, "packaged" toxcore in Gentoo is going to have it disabled anyways – defaulting to `enabled` will just add a bit more work for me.

**Comment by iphydf** [comment]
This looks done. @zetok @nurupo?

**Comment by zetok** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/324#-:-K_Eg3bvYUATlUm2tc6z:b-jbsf8z)*

**Comment by iphydf** [comment]
Looks fine. I believe @nurupo's concerns are addressed. This PR is ready to be merged (modulo coveralls, which is currently [broken](https://github.com/eddyxu/cpp-coveralls/issues/108) for C/C++).

**Comment by iphydf** [comment]
Coveralls is fixed (#377). Please rebase on master so the build is restarted.

**Comment by nurupo** [comment]
:lgtm_strong:

What does cmake do? Should we also backport this behaviour to our cmake configuration?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/324#-:-K_a1YfeD2w_kz3ajJ9J:b-lfzuu5)*

**Comment by iphydf** [comment]
It's probably a good idea, yes.

**Pull request merged**
