### PR TITLE
style: Run restyled on Travis and Circle CI scripts.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1515)

### CODE REVIEW

**Comment by nurupo** [comment]
It breaks the alignment in some cases by removing what it thinks are redundant spaces :\

Also CI fails, autotools-linux can't find nacl.

**Comment by iphydf** [comment]
Fixed the autotools build.

**Comment by nurupo** [comment]
Still fails. Looks like it's passing configure options as arguments to make.

```
make: unrecognized option '--with-nacl-headers=/home/travis/cache/include/amd64'
make: unrecognized option '--disable-ipv6'
make: unrecognized option '--enable-nacl'
make: unrecognized option '--enable-daemon'
make: unrecognized option '--enable-logging'
make: unrecognized option '--with-log-level=TRACE'
```

**Comment by nurupo** [comment]
Also, don't really like this change. Can we keep the formatting as it is? Aside from whatever shellcheck suggests to fix.

**Comment by iphydf** [comment]
Clearly I don't know bash :) fixed now.

**Comment by iphydf** [comment]
Regarding disabling formatters: I'd rather accept some slightly not-so-nice formatting in favour of automatised and consistent formatting.

**Comment by nurupo** [comment]
>Clearly I don't know bash :)

Bash arrays are PIA to use and make the code less readable as not many know how to use them. Not sure why you even bothered changing `CONFIG_FLAGS` from a string to an array if the string solution worked, but oh well.

**Pull request merged**
