### PR TITLE
Restrict packet kinds that can be sent through onion path.

### PR DESCRIPTION
**Pull request by kurnevsky**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/872)

### CODE REVIEW

**Comment by sudden6** [comment]
I think it's a good idea to limit onion packets to only a restricted set.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[toxcore/onion.c, line 474 at r1](https://beta.reviewable.io/reviews/toktok/c-toxcore/872#-LA7YLrQ1Ag6kDclW_WI:-LA7YLrQ1Ag6kDclW_WJ:bn8elmg) ([raw file](https://github.com/toktok/c-toxcore/blob/6b97acb773622f9abca5ef305cd55bdef1ecc484/toxcore/onion.c#L474)):*
> ```C
>     }
> 
>     if (len <= SIZE_IPPORT) {
> ```

Since there's a check for the exact length above, I don't think this is necessary.

---

*[toxcore/onion.c, line 478 at r1](https://beta.reviewable.io/reviews/toktok/c-toxcore/872#-LA7ZZyjB0P8bGbehzeO:-LA7ZZyjB0P8bGbehzeP:bk0x5kx) ([raw file](https://github.com/toktok/c-toxcore/blob/6b97acb773622f9abca5ef305cd55bdef1ecc484/toxcore/onion.c#L478)):*
> ```C
>     }
> 
>     if (plain[SIZE_IPPORT] != NET_PACKET_ANNOUNCE_REQUEST &&
> ```

In my opinion it would be better to write pack/unpack functions like `ipport_pack/unpack` instead of modifying the plain packet structure. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/872#-:-LA7_FlnCEwhYevRocVh:b-j1251r)*

**Comment by kpp** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/onion.c, line 478 at r1](https://beta.reviewable.io/reviews/toktok/c-toxcore/872#-LA7ZZyjB0P8bGbehzeO:-LA8LVR_9MPcza0ZQNOA:b-silgyn) ([raw file](https://github.com/toktok/c-toxcore/blob/6b97acb773622f9abca5ef305cd55bdef1ecc484/toxcore/onion.c#L478)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

In my opinion it would be better to write pack/unpack functions like `ipport_pack/unpack` instead of modifying the plain packet structure. 
</blockquote></details>

Right. Let's wait for @kurnevsky to help you with this code for a month while you will be stopping him from fixing 0-day vulnerability.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/872)*

**Comment by sudden6** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/onion.c, line 478 at r1](https://beta.reviewable.io/reviews/toktok/c-toxcore/872#-LA7ZZyjB0P8bGbehzeO:-LA8lotL1FAzQMRIBEVf:b-aldmnq) ([raw file](https://github.com/toktok/c-toxcore/blob/6b97acb773622f9abca5ef305cd55bdef1ecc484/toxcore/onion.c#L478)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Right. Let's wait for @kurnevsky to help you with this code for a month while you will be stopping him from fixing 0-day vulnerability.
</blockquote></details>

? I think a proper fix is better than possibly introducing new problems with a bandaid fix.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/872)*

**Comment by SkyzohKey** [comment]
@sudden6 merge this asap and release a new version. Then work on a clean fix. Dont let a flaw in the wild juste because of review.

**Comment by kurnevsky** [comment]
*[toxcore/onion.c, line 474 at r1](https://beta.reviewable.io/reviews/toktok/c-toxcore/872#-LA7YLrQ1Ag6kDclW_WI:-LA8zKAM5uz7imytkLXQ:bl4dpbi) ([raw file](https://github.com/toktok/c-toxcore/blob/6b97acb773622f9abca5ef305cd55bdef1ecc484/toxcore/onion.c#L474)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Since there's a check for the exact length above, I don't think this is necessary.
</blockquote></details>

Above we check only that length of decrypted data is the same as length of encrypted minus mac bytes. There is check "length <= 1 + SEND_3" yet above, but it checks only that packet has enough length for onion return.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/872)*

**Comment by kurnevsky** [comment]
*[toxcore/onion.c, line 478 at r1](https://beta.reviewable.io/reviews/toktok/c-toxcore/872#-LA7ZZyjB0P8bGbehzeO:-LA90kKeCuDcNuSZGDz3:b-r4zq94) ([raw file](https://github.com/toktok/c-toxcore/blob/6b97acb773622f9abca5ef305cd55bdef1ecc484/toxcore/onion.c#L478)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

? I think a proper fix is better than possibly introducing new problems with a bandaid fix.
</blockquote></details>

It's the way the whole c-toxcore implemented - it doesn't parse packets to structs, it just works with bytes. So I suggest not to refactor it here - refactoring will bring much bigger diff.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/872)*

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/onion.c, line 478 at r1](https://beta.reviewable.io/reviews/toktok/c-toxcore/872#-LA7ZZyjB0P8bGbehzeO:-LA9Gn0i6XdDQIKQtrRZ:b-ye8l9a) ([raw file](https://github.com/toktok/c-toxcore/blob/6b97acb773622f9abca5ef305cd55bdef1ecc484/toxcore/onion.c#L478)):*
<details><summary><i>Previously, kurnevsky (Evgeny Kurnevsky) wrote…</i></summary><blockquote>

It's the way the whole c-toxcore implemented - it doesn't parse packets to structs, it just works with bytes. So I suggest not to refactor it here - refactoring will bring much bigger diff.
</blockquote></details>

This code needs lots of refactoring later. I think we can defer it for now given the relative urgency.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/872)*

**Comment by sudden6** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/onion.c, line 474 at r1](https://beta.reviewable.io/reviews/toktok/c-toxcore/872#-LA7YLrQ1Ag6kDclW_WI:-LA9KUXgCdu6o4xVXtum:b1ke8pv) ([raw file](https://github.com/toktok/c-toxcore/blob/6b97acb773622f9abca5ef305cd55bdef1ecc484/toxcore/onion.c#L474)):*
<details><summary><i>Previously, kurnevsky (Evgeny Kurnevsky) wrote…</i></summary><blockquote>

Above we check only that length of decrypted data is the same as length of encrypted minus mac bytes. There is check "length <= 1 + SEND_3" yet above, but it checks only that packet has enough length for onion return.
</blockquote></details>

ok, didn't see this, maybe that could be an issue in other functions too, but no need to fix that in this PR

---

*[toxcore/onion.c, line 478 at r1](https://beta.reviewable.io/reviews/toktok/c-toxcore/872#-LA7ZZyjB0P8bGbehzeO:-LA9L419BR07rQucaEIt:b-e4ny5t) ([raw file](https://github.com/toktok/c-toxcore/blob/6b97acb773622f9abca5ef305cd55bdef1ecc484/toxcore/onion.c#L478)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

This code needs lots of refactoring later. I think we can defer it for now given the relative urgency.
</blockquote></details>

ok for me then

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/872)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/872#-:-LA9gf17Bo0lgwVFD8qE:b-jbsf8z)*

**Comment by SkyzohKey** [comment]
@iphydf Can this be merged asap? Then please release the 0.2.2 in emergency. Now that the flaw is disclosed, it needs to be fixed the fastest. Persistent groupchats can wait 0.2.3 so that this can be fixed. And clients can update their static builds

**Comment by zoff99** [comment]
does this mean all running nodes (including bootstrap nodes and echobot and groupbot) need to be updated aswell to fix this vulnerability?
or can old nodes be tolerated in the wild?

**Comment by sudden6** [comment]
If I understood this correctly, old nodes have to be updated in order to be protected, but will still work.

**Comment by kurnevsky** [comment]
@zoff99 old nodes have to be updated, but it will be enough to have only one updated node in onion path (3 nodes) to be protected. Unfortunately it's not enough to update only your node to be protected yourself.

**Comment by kurnevsky** [comment]
Sorry, accidently closed pr.
@zoff99 right, it'd be nice to have a way to get node version for this purpose.

**Comment by tox-user** [comment]
Review is very important just as with any other code, so let's not forget about that please. In the future we should think of a way for people to disclose vulnerabilities in a more secure way that doesn't put users in danger and doesn't cause everyone to panic and think of not reviewing the code. I'm not criticizing anyone here. I know that in this situation you are all doing the best you can :). It's just something that we should try to do better in the future.

**Comment by kpp** [comment]
It is possible to send BootstrapInfo to all public nodes. There is a u32 as integer version of toxcore lib.

**Comment by zoff99** [comment]
@iphydf how can we make sure a malicous node (custom source code) can not use this or any future vulnerability?

**Comment by nurupo** [comment]
Disclaimer: I'm not very familiar with the onion module, so my review is pretty useless. I can't confirm if there is a vulnerability, or if this patch is complete or if it's correct to limit onion routing to only two of those packet kinds. What I can say, however, is that this patch looks correct as far as C code goes and it makes sense.

:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/872#-:-LAF7EPf9HYHRJQ6Eofb:bkojgw3)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/872#-:-LAFMPl9549fLg2CmhU7:b-jbsf8z)*

**Comment by robinlinden** [comment]
Thank you for both reporting and fixing this! :)
I'm out of time tonight, but I'll push a release with this and #867 (if done, otherwise I'll cherry-pick the commit that fixes with autotools build from it) tomorrow evening.

**Comment by nurupo** [comment]
@kurnevsky Could you explain why is it not enough to update only your node to be protected yourself?

The issue is that onion module doesn't filter which packet kinds it allows to be onion-routed. This results in the case that when Alice sends Announce Request packet to Bob, which contains Alice's permanent public key and an onion path to contact her back, Bob can use that onion path to send Alice a NAT Ping request, which is not meant to be sent over onion but the onion module nevertheless allows it, asking her to ping a specific DHT node. If that node is controlled by Bob and it's in Alice's Close List (the node's DHT public key is close to Alice's DHT public key), then she will ping it, disclosing to Bob her IP. This also means that if Alice uses patched toxcore, she will drop the NAT Ping request and will never ping Bob's DHT node, preventing Alice from disclosing her IP address to Bob, i.e. it's enough for Alice to update her toxcore in order to protect herself. But you are saying that it's not enough, which makes me question my understanding of the issue.

**Comment by kurnevsky** [comment]
@nurupo you are right, that's why I suggested to restrict packet kinds. In the future we could verify onion paths (that it has at least one updated node), but it seems there is no easy way to get version of dht node. Anyway tox network should be updated (at least partly) to add such check.

**Pull request merged**
