### PR TITLE
Fix logging condition for IPv6 client timestamp updates.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/388)

### CODE REVIEW

**Comment by GrayHatter** [comment]
lol OOPS

:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/388#-:-K_pVQqXBSDHyJyZzM-q:b4z6es5)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/388#-:-Ka7J7DolyumGDZgkDit:b-jbsf8z)*

**Comment by borkblep** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/388)*

**Comment by fcore117** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/388)*

**Comment by cleverca22** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/388)*

**Comment by cleverca22** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/388#-:-KaDPUyU7wc2ZSnPzCNi:b-jbsf8z)*

**Comment by nurupo** [comment]
Nice catch of a copy-paste error.

:lgtm_strong:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/388#-:-KaJvoB2st_PjFs3SqPY:b-roxspg)*

**Pull request merged**
