### PR TITLE
Remove assoc

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/242)

### CODE REVIEW

**Comment by iphydf** [comment]
Also remove the option from `other/travis/toxcore-script`.

**Comment by iphydf** [comment]
:lgtm: 

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/242#-:-KVqPePmixzwarprUPUK:bg7igkv)*

**Comment by nurupo** [comment]
I grepped the repository to see if all assoc things were removed and apparently there are variables called `assoc4` and `assoc6` in the [DHT.h](https://github.com/TokTok/c-toxcore/blob/master/toxcore/DHT.h#L140), but they were added before any `assoc.[c|h]` existed and seem to be used just to store IP addresses https://github.com/TokTok/c-toxcore/commit/9de295374decd78fd676574bd38243479dfd6054, i.e. irrelevant to the assoc we are trying to remove.

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/242#-:-KVsfYFah0oE9WyyW3gu:b-jbsf8z)*

**Comment by iphydf** [comment]
@endoffile78 can you rebase this and fix the conflict? (Sorry about that)

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/242#-:-KVuD2ad8-ZVo1yt91ja:b-jbsf8z)*

**Pull request merged**
