### PR TITLE
Make DHT a module-private type.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/688)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm_strong:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/688#-:-L2rUv-bCchJZyONw5Wa:b-jbsf8z)*

**Comment by sudden6** [comment]
Reviewed 12 of 15 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[toxcore/DHT.c, line 131 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/688#-L2toStuImOIYO-Rzw39:-L2toStvYlvfvYHqzAOX:bn1t7jr) ([raw file](https://github.com/toktok/c-toxcore/blob/6f64811551625a10c6f84adef09c605eb80f62d3/toxcore/DHT.c#L131)):*
> ```C
> const Client_data *dht_get_close_client(const DHT *dht, uint32_t client_num)
> {
>     return &dht->close_clientlist[client_num];
> ```

check for out of bounds read necessary? If not add a comment stating that this function doesn't check bounds

---

*[toxcore/DHT.c, line 140 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/688#-L2to_xw5eeXEmBCxBME:-L2to_xw5eeXEmBCxBMF:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/6f64811551625a10c6f84adef09c605eb80f62d3/toxcore/DHT.c#L140)):*
> ```C
> DHT_Friend *dht_get_friend(DHT *dht, uint32_t friend_num)
> {
>     return &dht->friends_list[friend_num];
> ```

same

---

*[toxcore/DHT.c, line 144 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/688#-L2tobGBVfd9fryJiMfn:-L2tobGBVfd9fryJiMfo:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/6f64811551625a10c6f84adef09c605eb80f62d3/toxcore/DHT.c#L144)):*
> ```C
> const uint8_t *dht_get_friend_public_key(const DHT *dht, uint32_t friend_num)
> {
>     return dht->friends_list[friend_num].public_key;
> ```

same

---

*[toxcore/LAN_discovery.c, line 359 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/688#-L2tp09bNqoDNTB0-7Ho:-L2tp09bNqoDNTB0-7Hp:b-u10yv9) ([raw file](https://github.com/toktok/c-toxcore/blob/da739a9438bab75b1ad18cb96208069895b88d2b/toxcore/LAN_discovery.c#L359)):*
> ```C
>     char ip_str[IP_NTOA_LEN] = { 0 };
>     ip_ntoa(&source.ip, ip_str, sizeof(ip_str));
>     LOGGER_DEBUG(dht->log, "Found node in LAN: %s", ip_str);
> ```

Intended change or accidentally removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/688)*

**Comment by iphydf** [comment]
Review status: 12 of 16 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[toxcore/DHT.c, line 131 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/688#-L2toStuImOIYO-Rzw39:-L2wH_u2PVjYE9hXZ-wc:btdtn5x) ([raw file](https://github.com/toktok/c-toxcore/blob/6f64811551625a10c6f84adef09c605eb80f62d3/toxcore/DHT.c#L131)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

check for out of bounds read necessary? If not add a comment stating that this function doesn't check bounds
</blockquote></details>

Added an assert. Proper bound checking can be added later, but it requires the caller to check the return type. In this PR, I'm avoiding logic changes.

---

*[toxcore/DHT.c, line 140 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/688#-L2to_xw5eeXEmBCxBME:-L2wHj23_4R8CfAB7igt:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/6f64811551625a10c6f84adef09c605eb80f62d3/toxcore/DHT.c#L140)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---

*[toxcore/DHT.c, line 144 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/688#-L2tobGBVfd9fryJiMfn:-L2wHjWfSEp6-6F0moEV:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/6f64811551625a10c6f84adef09c605eb80f62d3/toxcore/DHT.c#L144)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---

*[toxcore/LAN_discovery.c, line 359 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/688#-L2tp09bNqoDNTB0-7Ho:-L2wHNnC5htMtfCa6tLY:b-gy3x8l) ([raw file](https://github.com/toktok/c-toxcore/blob/da739a9438bab75b1ad18cb96208069895b88d2b/toxcore/LAN_discovery.c#L359)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Intended change or accidentally removed?
</blockquote></details>

Intentional, and also removed the filter in `auto_tests/helpers.h`. Why: because this is complete spam and doesn't help regular debugging at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/688)*

**Comment by endoffile78** [comment]
:lgtm_strong:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/688#-:-L2wJ5Lzawee7Hy8rN1g:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: 4 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/688#-:-L3-qVwRwCLYJGknrOsb:b-jbsf8z)*

**Pull request merged**
