### PR TITLE
Remove the use of the 'hh' format specifier.

### PR DESCRIPTION
**Pull request by iphydf**
It's not supported in mingw.

See https://github.com/TokTok/c-toxcore/issues/786.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/809)

### CODE REVIEW

**Comment by nurupo** [comment]
There were a few more files using `hh`, not just `messenger_test.c`. In fact, the issue you are referring to suggests that there might be memory corruption in `hex_string_to_bin()` function of `misc_tools.c`, which is crashing the `messenger_test` in Wine.

```
$ grep -i 'hh' * -R --colour --line-number 
auto_tests/onion_test.c:84:        printf("%02hhX", client_id[j]);
auto_tests/messenger_test.c:264:        sprintf(msg, "Failed to load back stored buffer: 0x%02hhx%02hhx%02hhx%02hhx%02hhx%02hhx%02hhx%02hhx @%zu/%zu, code %d",
auto_tests/messenger_test.c:307:        sprintf(msg, "Failed to load back stored buffer: 0x%02hhx%02hhx%02hhx%02hhx%02hhx%02hhx%02hhx%02hhx @%zu/%zu, code %d",
auto_tests/dht_test.c:423:        printf("%02hhX", public_key[j]);
other/bootstrap_daemon/src/config.c:319:        sscanf(pos, "%2hhx", &ret[i]);
other/bootstrap_daemon/src/tox-bootstrapd.c:112:        index += sprintf(buffer + index, "%02hhX", public_key[i]);
other/DHT_bootstrap.c:159:        printf("%02hhX", self_public_key[i]);
other/DHT_bootstrap.c:160:        fprintf(file, "%02hhX", self_public_key[i]);
other/fun/cracker.c:27:        printf("%02hhX", client_id[j]);
other/fun/sign.c:59:            printf("%02hhX", pk[i]);
other/fun/sign.c:65:            printf("%02hhX", sk[i]);
other/fun/strkey.c:55:        fprintf(stdout, "%hhX", key[i]);
other/fun/strkey.c:89:            sscanf(pos, "%2hhx", &desired_bin[i]);
Binary file other/tox.png matches
testing/Messenger_test.c:77:        printf("%hhX", public_key[j]);
testing/Messenger_test.c:160:        printf("%hhX", address[i]);
testing/misc_tools.c:63:        sscanf(pos, "%2hhx", &ret[i]);
testing/DHT_test.c:57:        printf("%02hhX", public_key[j]);
testing/DHT_test.c:64:    printf("routes_requests_ok: %hhu\n", h->routes_requests_ok);
testing/DHT_test.c:68:    printf("\nsend_nodes_ok: %hhu\n", h->send_nodes_ok);
testing/DHT_test.c:72:    printf("\ntesting_requests: %hhu\n", h->testing_requests);
testing/DHT_test.c:165:        printf("%hhX", data[i]);
testing/DHT_test.c:204:        printf("%hhX", self_public_key[i]);
```

**Comment by iphydf** [comment]
@nurupo I've removed all `%hh` now.

**Comment by nurupo** [comment]
I'm not very familiar with special format strings like hex formatting, so I'm not very qualified to review this. Are you sure you can just drop `hh` in `%02hhX` and get the same output being printed?

Btw, I think the compiler is happy with just one `h`, it's two of them `hh` that the compiler doesn't know what to do.

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 43 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/809#-L7IHn1rxbrqaOYnhCzk:-L7IHn1rxbrqaOYnhCzl:bu0gv1y) ([raw file](https://github.com/toktok/c-toxcore/blob/0ea89768dcb3ab2e92256b0d6662ce99ab91277a/.travis.yml#L43)):*
> ```YAML
> #   group: deprecated-2017Q4
> #   services:
> #   - docker
> ```

You might want to enable both Windows arches, for some reason one of them complains about those formats more than another.

---

*[other/fun/strkey.c, line 89 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/809#-L7IJmUWPw3eY-vgFKqe:-L7IJmUWPw3eY-vgFKqf:bkqz7kx) ([raw file](https://github.com/toktok/c-toxcore/blob/0ea89768dcb3ab2e92256b0d6662ce99ab91277a/other/fun/strkey.c#L89)):*
> ```C
> 
>         for (i = 0; i < len; pos += 2) {
>             sscanf(pos, "%02x", &desired_bin[i]);
> ```

You are not using an intermediate `unsigned int` here for `sscanf` like you did in the bootstrap daemon or misc_tools.c? Not sure what is the purpose of it anyway, but I see you do this in one case but not in another very similar (the same) case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/809#-:-L7IKeMqIgN99h1P0sS_:bt2u8az)*

**Comment by iphydf** [comment]
Review status: 17 of 19 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 43 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/809#-L7IHn1rxbrqaOYnhCzk:-L7JbXCsqj8M5nqU3Cib:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/0ea89768dcb3ab2e92256b0d6662ce99ab91277a/.travis.yml#L43)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

You might want to enable both Windows arches, for some reason one of them complains about those formats more than another.
</blockquote></details>

Done.

---

*[other/fun/strkey.c, line 89 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/809#-L7IJmUWPw3eY-vgFKqe:-L7JbXv-dQjg3wsovKRt:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/0ea89768dcb3ab2e92256b0d6662ce99ab91277a/other/fun/strkey.c#L89)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

You are not using an intermediate `unsigned int` here for `sscanf` like you did in the bootstrap daemon or misc_tools.c? Not sure what is the purpose of it anyway, but I see you do this in one case but not in another very similar (the same) case.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/809)*

**Comment by iphydf** [comment]
Yes, because these are all `unsigned char`, so it's the same. It becomes different if you pass in a value larger than `UCHAR_MAX`, because then the cast to `unsigned char` done in `printf` matters.

---

Review status: 17 of 19 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/809#-:-L7Jb_MMVZv_cnJB2hwm:b9t7gpg)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/809#-:-L7K2iHFB-ytp8yqB6Sv:b-jbsf8z)*

**Comment by nurupo** [comment]
I noticed that it also doesn't know what the extra `l` in `%lld` is, [at least in here](https://github.com/TokTok/c-toxcore/blob/bd62d11860a4e6e540f7116f0ef6c56b28b18837/toxcore/Messenger.c#L1761), maybe somewhere more too, and [it doesn't like](https://travis-ci.org/TokTok/c-toxcore/jobs/351934515) that we use `%ld` to print `time_t` which is `long long int` on 64-bit arch.

**Comment by nurupo** [comment]
I think you use `%I64u` and `%I64d`, but I can't find them in standard headers.

Even a recent-ish mingw does this

```
$ cat test.c 
#include <stdio.h>

int main() {
  long long foo = 9999999999;
  printf("Here it is %lld\n", foo);
  return 0;
}
$ i686-w64-mingw32-gcc test.c -o test -Wformat
test.c: In function ‘main’:
test.c:5:24: warning: unknown conversion type character ‘l’ in format [-Wformat=]
   printf("Here it is %lld\n", foo);
                        ^
test.c:5:10: warning: too many arguments for format [-Wformat-extra-args]
   printf("Here it is %lld\n", foo);
          ^~~~~~~~~~~~~~~~~~~
test.c:5:24: warning: unknown conversion type character ‘l’ in format [-Wformat=]
   printf("Here it is %lld\n", foo);
                        ^
test.c:5:10: warning: too many arguments for format [-Wformat-extra-args]
   printf("Here it is %lld\n", foo);
          ^~~~~~~~~~~~~~~~~~~
$ i686-w64-mingw32-gcc --version
i686-w64-mingw32-gcc (GCC) 7.2-win32 20180123
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Pull request merged**
