### PR TITLE
add comment to func cryptpacket_received

### PR DESCRIPTION
**Pull request by hqwrong**
see #851

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/859)

### CODE REVIEW

**Comment by sudden6** [comment]
Can you limit the line length to the same with as the rest of the code uses?

**Comment by hqwrong** [comment]
@sudden6 done

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[toxcore/net_crypto.c, line 2759 at r1](https://beta.reviewable.io/reviews/toktok/c-toxcore/859#-L9960ymDDp4vfpU5YuI:-L9960ymDDp4vfpU5YuJ:b-933cs7) ([raw file](https://github.com/toktok/c-toxcore/blob/a96b5705f271d374195b68554b150f0efc9d3eb7/toxcore/net_crypto.c#L2759)):*
> ```C
>  * return 0 on success.
>  *
>  * Note: The condition `buffer_end - buffer_start < pakcet_number - buffer_start` is
> ```

typo `packet_number`

---

*[toxcore/net_crypto.c, line 2765 at r1](https://beta.reviewable.io/reviews/toktok/c-toxcore/859#-L9966SBCgLNCb-0hYnz:-L9966SBCgLNCb-0hYo-:bxy165d) ([raw file](https://github.com/toktok/c-toxcore/blob/a96b5705f271d374195b68554b150f0efc9d3eb7/toxcore/net_crypto.c#L2765)):*
> ```C
>  * It CANNOT be simplified to `packet_number < buffer_start`, as it will fail
>  * when `buffer_end < buffer_start`.
>  *
> ```

please remove empty lines

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/859)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/859#-:-L9BTN4G3hlwtapTth0A:b-jbsf8z)*

**Pull request merged**
