### PR TITLE
Manually serialise RTPHeader struct instead of memcpy.

### PR DESCRIPTION
**Pull request by iphydf**
---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/721)

### CODE REVIEW

**Comment by iphydf** [comment]
@sudden6 ready for review.

**Comment by sudden6** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxav/rtp.c, line 61 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/721#-L4GIIOYaEejtlN2w50N:-L4GIIOYaEejtlN2w50O:b-d9npui) ([raw file](https://github.com/toktok/c-toxcore/blob/de522e03a8d146a93019c7f4805fc4e5652c8341/toxav/rtp.c#L61)):*
> ```C
>     p += net_pack_u16(p, header->offset_lower);
>     p += net_pack_u16(p, header->data_length_lower);
>     assert(p == rdata + 80);
> ```

where does the value `80` come from? header size? maybe add a comment linking it to the header definition?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/721)*

**Comment by iphydf** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxav/rtp.c, line 61 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/721#-L4GIIOYaEejtlN2w50N:-L4GRmxsJixLvL6ERDt7:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/de522e03a8d146a93019c7f4805fc4e5652c8341/toxav/rtp.c#L61)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

where does the value `80` come from? header size? maybe add a comment linking it to the header definition?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/721)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/721#-:-L4GV50KjcPiILUt0JbU:b-jbsf8z)*

**Comment by zoff99** [comment]
*where does the value 80 come from? header size? maybe add a comment linking it to the header definition?*

maybe actually use sizeof() instead of the raw number

**Comment by iphydf** [comment]
@zoff99 I'm using the raw number (from a macro) and checking that sizeof equals that number. In the future, sizeof can differ because we no longer memcpy it into the packet.

**Comment by sudden6** [comment]
Reviewed 4 of 5 files at r4.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[toxav/rtp.h, line 172 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/721#-L4H_9je0Biy90eAbYaZ:-L4H_9je0Biy90eAbYa_:b-s3jm7p) ([raw file](https://github.com/toktok/c-toxcore/blob/ee33532822e1f6b5af4aa852d45562ffe5f62121/toxav/rtp.h#L172)):*
> ```objc
>  * Deserialise an RTPHeader from bytes received over the network.
>  *
>  * @param rdata A byte array of length RTP_HEADER_SIZE.
> ```

the actual function parameter is `data`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/721)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 7 of 9 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 4 of 5 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/721#-:-L4Hb58s7FS4J42Cvcqj:b-jbsf8z)*

**Comment by sudden6** [comment]
Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxav/rtp.h, line 70 at r6](https://reviewable.io:443/reviews/toktok/c-toxcore/721#-L4HiMSXC-i5S4Sx-DJD:-L4HiMSYrzrsUYeJolSu:b-thmbzg) ([raw file](https://github.com/toktok/c-toxcore/blob/f845d8bfa4738552d43dbb537431aab92ca72b86/toxav/rtp.h#L70)):*
> ```objc
>     uint16_t cc: 4; /* Contributing sources count */
> 
>     uint16_t ma: 1; /* Marker */
> ```

is there a reason why the base type is 16bit and not 8bit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/721)*

**Comment by iphydf** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[toxav/rtp.h, line 172 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/721#-L4H_9je0Biy90eAbYaZ:-L4IjN4PFA1vXuaQKq6f:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/ee33532822e1f6b5af4aa852d45562ffe5f62121/toxav/rtp.h#L172)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

the actual function parameter is `data`
</blockquote></details>

Done.

---

*[toxav/rtp.h, line 70 at r6](https://reviewable.io:443/reviews/toktok/c-toxcore/721#-L4HiMSXC-i5S4Sx-DJD:-L4IjLtUstvl9SMAKhNu:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/f845d8bfa4738552d43dbb537431aab92ca72b86/toxav/rtp.h#L70)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

is there a reason why the base type is 16bit and not 8bit?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/721)*

**Comment by sudden6** [comment]
Reviewed 2 of 3 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/721)*

**Comment by nurupo** [comment]
1. Why is the test in C++?
2. Why is the test using `gtest`?
3. Why is the test not plugged into CMake?

**Pull request merged**
