### PR TITLE
cleanup: Remove implicit bool conversions.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2621)

### CODE REVIEW

**Review by JFreegman — COMMENTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2621)* status: 0 of 1 approvals obtained (waiting on @iphydf)

___
*[`toxcore/group_chats.c` line 3918 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2621#-NpW2o8v83voGuIhmOzL:-NpW2o8v83voGuIhmOzM:b-ivd7r8) ([raw file](https://github.com/TokTok/c-toxcore/blob/0185de13b426987f4288d7014838adb9b2415b40/toxcore/group_chats.c#L3918)):*
> ```C
>         // the topic version should never change when the topic lock is disabled except when
>         // the founder changes the topic prior to enabling the lock
>         if (peer->role != GR_FOUNDER || topic_info->version != chat->shared_state.topic_lock + 1) {
> ```

Why is this being changed? While I can see people having a preference for one or the other, personally I find that the former logic easier to parse.
___
*[`toxcore/group_moderation.c` line 553 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2621#-NpW5CpF5ixLv_4NSQkB:-NpW5CpF5ixLv_4NSQkC:b-n4w04m) ([raw file](https://github.com/TokTok/c-toxcore/blob/0185de13b426987f4288d7014838adb9b2415b40/toxcore/group_moderation.c#L553)):*
> ```C
>     if (moderation->shared_state_version > 0) {
>         if ((creds->version < moderation->sanctions_creds.version)
>                 && (creds->version != 0 || moderation->sanctions_creds.version != UINT32_MAX)) {
> ```

Same question as above.
___
*[`toxcore/net_crypto.c` line 2730 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2621#-NpW7fUi87hLSF850KZx:-NpW7fUi87hLSF850KZy:b-ya81ng) ([raw file](https://github.com/TokTok/c-toxcore/blob/511bfe39c8e801cfa48071f9f481b05f3e52435d/toxcore/net_crypto.c#L2730)):*
> ```C
> 
>                 /* When switching from TCP to UDP, don't change the packet send rate for CONGESTION_EVENT_TIMEOUT ms. */
>                 if (!(direct_connected && conn->last_tcp_sent + CONGESTION_EVENT_TIMEOUT > temp_time)) {
> ```

Same as above
___
*[`toxcore/onion_client.c` line 1936 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2621#-NpW7xbW8QJqvJofOVdW:-NpW7xbW8QJqvJofOVdX:b-acrn58) ([raw file](https://github.com/TokTok/c-toxcore/blob/0185de13b426987f4288d7014838adb9b2415b40/toxcore/onion_client.c#L1936)):*
> ```C
>         && (paths->last_path_used_times[pathnum] == 0
>             || !mono_time_is_timeout(
>                 mono_time, paths->last_path_used[pathnum], ONION_PATH_TIMEOUT));
> ```

This entire clause is insane. We should think about refactoring it.

**Comment by nurupo** [comment]
Looked only over the bootstrap daemon changes. Some changes I'm happy with, e.g. the functions returning 0/1 changing to return false/true is a very welcome change, but some I'm not happy with, like `if (!pointer)` -> `if (pointer == nullptr)` and some others.

**Review by nurupo — COMMENTED** [review]
Looked only over the bootstrap daemon changes. Some changes I'm happy with, e.g. the functions returning 0/1 changing to return false/true is a very welcome change, but some I'm not happy with, like if (!pointer) -> if (pointer == nullptr) and some others.

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2621)* status: 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[`toxcore/group_chats.c` line 3918 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2621#-NpW2o8v83voGuIhmOzL:-NpWC7Mx958QomOKRzr5:b-896fix) ([raw file](https://github.com/TokTok/c-toxcore/blob/0185de13b426987f4288d7014838adb9b2415b40/toxcore/group_chats.c#L3918)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Why is this being changed? While I can see people having a preference for one or the other, personally I find that the former logic easier to parse.
</blockquote></details>

Done.
___
*[`toxcore/group_moderation.c` line 553 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2621#-NpW5CpF5ixLv_4NSQkB:-NpWCEJmAJkWRE7jEQne:b-896fix) ([raw file](https://github.com/TokTok/c-toxcore/blob/0185de13b426987f4288d7014838adb9b2415b40/toxcore/group_moderation.c#L553)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Same question as above.
</blockquote></details>

Done.
___
*[`toxcore/net_crypto.c` line 2730 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2621#-NpW7fUi87hLSF850KZx:-NpWCN0dCdeQLIuUcoio:b-896fix) ([raw file](https://github.com/TokTok/c-toxcore/blob/511bfe39c8e801cfa48071f9f481b05f3e52435d/toxcore/net_crypto.c#L2730)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`toxcore/onion_client.c` line 1936 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2621#-NpW7xbW8QJqvJofOVdW:-NpWEiir1iLLG1-83rcB:b5gzyrn) ([raw file](https://github.com/TokTok/c-toxcore/blob/0185de13b426987f4288d7014838adb9b2415b40/toxcore/onion_client.c#L1936)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

This entire clause is insane. We should think about refactoring it.
</blockquote></details>

I looked at it a bit. That raised more questions than I want to resolve for this PR.

**Comment by iphydf** [comment]
> Looked only over the bootstrap daemon changes. Some changes I'm happy with, e.g. the functions returning 0/1 changing to return false/true is a very welcome change, but some I'm not happy with, like `if (!pointer)` -> `if (pointer == nullptr)` and some others.

Please mark the ones you're not happy with and want reverted.

The `!pointer` change is necessary if we ever want to have a stronger type system enforcement on this code. We do this everywhere in toxcore except in the bootstrap node, because pointers aren't booleans, and implicit conversions are fundamentally tricky. If we can completely eliminate those, at least in some kind of overlay type system, reasoning about what type a value has becomes much more straightforward. E.g. in `if (forwarding) {...}` it's entirely unclear whether the branch is about whether we want forwarding or not (bool), whether there's at least 1 forwarding (uint), whether forwarding failed (int return from a posix function non-zero), an allocation failed (pointer), or some other variety of truthiness.

**Review by nurupo — CHANGES_REQUESTED** [review]
> Reviewed 9 of 19 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2621)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf and @JFreegman)

___
*[`other/bootstrap_daemon/src/config.c` line 407 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2621#-NpX3wOE2iTsoInZo462:-NpX3wOE2iTsoInZo463:b-hecsfp) ([raw file](https://github.com/TokTok/c-toxcore/blob/bc182e4426c166adcb6f1d4382b67b2804833aba/other/bootstrap_daemon/src/config.c#L407)):*
> ```C
>         free(bs_public_key_bin);
> 
>         if (address_resolved == 0) {
> ```

This was more readable before.

How about the following?

```
bool address_resolved;
...
address_resolved = dht_bootstrap_from_address(dht, bs_address, enable_ipv6, net_htons(bs_port), bs_public_key_bin) == 0;
...
if (!address_resolved) {
```

I would prefer to not have this ` == 0` and let do the int-to-bool conversion do the trick, but I take it you want an explicit conversion.
___
*[`toxcore/onion_client.c` line 1928 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2621#-NpX8gvI-cBW_pAVqw5O:-NpX8gvI-cBW_pAVqw5P:b-z53jwy) ([raw file](https://github.com/TokTok/c-toxcore/blob/bc182e4426c166adcb6f1d4382b67b2804833aba/toxcore/onion_client.c#L1928)):*
> ```C
> non_null()
> static bool path_is_stable(const Mono_Time *mono_time, const Onion_Client_Paths *paths,
>     uint32_t pathnum, const Onion_Node *node)
> ```

Pad the arguments with spaces to match where they start on the 1st line?

**Review by JFreegman — APPROVED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2621)* status: <span>:shipit:</span> complete! 1 change requests, 1 of 1 approvals obtained (waiting on @iphydf)

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2621)* status: <span>:shipit:</span> complete! 1 change requests, 1 of 1 approvals obtained (waiting on @JFreegman and @nurupo)

___
*[`other/bootstrap_daemon/src/config.c` line 407 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2621#-NpX3wOE2iTsoInZo462:-NpbMK0O6FUTzjf_g3ZL:b-po1fbv) ([raw file](https://github.com/TokTok/c-toxcore/blob/bc182e4426c166adcb6f1d4382b67b2804833aba/other/bootstrap_daemon/src/config.c#L407)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

This was more readable before.

How about the following?

```
bool address_resolved;
...
address_resolved = dht_bootstrap_from_address(dht, bs_address, enable_ipv6, net_htons(bs_port), bs_public_key_bin) == 0;
...
if (!address_resolved) {
```

I would prefer to not have this ` == 0` and let do the int-to-bool conversion do the trick, but I take it you want an explicit conversion.
</blockquote></details>

Changed dht_bootstrap_from_address to return bool, instead.
___
*[`toxcore/onion_client.c` line 1928 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2621#-NpX8gvI-cBW_pAVqw5O:-NpbMzOr5lahL7UYTUxy:bnkpu40) ([raw file](https://github.com/TokTok/c-toxcore/blob/bc182e4426c166adcb6f1d4382b67b2804833aba/toxcore/onion_client.c#L1928)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Pad the arguments with spaces to match where they start on the 1st line?
</blockquote></details>

Tell that to astyle and/or clang-format.

**Comment by nurupo** [comment]
Somehow I can't review just the first commit in Reviewable, in "Review each commit separately" mode each commit should be a separate revision, yet the DHT.h changes somehow got lumped together with the formatting changes into r3 :\

**Review by nurupo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2621)* status: <span>:shipit:</span> complete! 2 of 1 approvals obtained (waiting on @iphydf and @JFreegman)

___
*[`toxcore/onion_client.c` line 1928 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2621#-NpX8gvI-cBW_pAVqw5O:-Npc0sCz6qsBg0VngBXV:bv2tmg5) ([raw file](https://github.com/TokTok/c-toxcore/blob/bc182e4426c166adcb6f1d4382b67b2804833aba/toxcore/onion_client.c#L1928)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Tell that to astyle and/or clang-format.
</blockquote></details>

I noticed the other function in that file were doing that, so pointed it out.

Looks like this has been fixed now that the code was astyled.

**Comment by nurupo** [comment]
>Somehow I can't review just the first commit in Reviewable, in "Review each commit separately" mode each commit should be a separate revision, yet the DHT.h changes somehow got lumped together with the formatting changes into r3 :\

I guess the "Review each commit separately" mode just doesn't work, it's still in the "combine commits" mode, and it put both the updated 1st commit + the code formatting 2nd commit as rev3, so I'm unable to see what you changed since my last review as the 2nd commit clutters all of the changes I'm looking for, I want to ignore the 2nd commit and see only 1st commit changes. So annoying. Reviewable is great when it works, but meh when it doesn't.

**Pull request merged**
