### PR TITLE
test: Add some support functions to make writing fuzzers easier.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2184)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2184)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[testing/fuzzing/fuzz_support.h, line 15 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2184#-MzBRDg5CKJ41T0o-KF2:-MzBRDg5CKJ41T0o-KF3:b-kzxnd9) ([raw file](https://github.com/toktok/c-toxcore/blob/2e8bd61067589c657e277b4f96e30c749d892e37/testing/fuzzing/fuzz_support.h#L15)):*
> ```objc
>     std::size_t size;
> 
>     uint8_t consume1() {
> ```

could use these in the network_adapter code too
___
*[testing/fuzzing/fuzz_support.h, line 32 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2184#-MzBQk_X-K8eYVnu-yMN:-MzBQk_X-K8eYVnu-yMO:bqvoq46) ([raw file](https://github.com/toktok/c-toxcore/blob/2e8bd61067589c657e277b4f96e30c749d892e37/testing/fuzzing/fuzz_support.h#L32)):*
> ```objc
> #define CONSUME1(DECL, INPUT) \
>     if (INPUT.size < 1) {     \
>         return;               \
> ```

please add a bit of documentation to point out that this macro does return from the sourounding function. Even better would be if that would not be needed at all

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2184)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @sudden6)

___
*[testing/fuzzing/fuzz_support.h, line 15 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2184#-MzBRDg5CKJ41T0o-KF2:-MzBTYGmAH0hkAC6roce:bjwsfl5) ([raw file](https://github.com/toktok/c-toxcore/blob/2e8bd61067589c657e277b4f96e30c749d892e37/testing/fuzzing/fuzz_support.h#L15)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

could use these in the network_adapter code too
</blockquote></details>

Could, yes, but that's written in C, and I want to rewrite that completely when moving it to the `Network *ns` stuff I'm working on.
___
*[testing/fuzzing/fuzz_support.h, line 32 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2184#-MzBQk_X-K8eYVnu-yMN:-MzBTfLf55QVVNe77uLP:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/2e8bd61067589c657e277b4f96e30c749d892e37/testing/fuzzing/fuzz_support.h#L32)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

please add a bit of documentation to point out that this macro does return from the sourounding function. Even better would be if that would not be needed at all
</blockquote></details>

Done.

**Review by sudden6 — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2184)* status: 1 change requests, 0 of 1 approvals obtained

___
*[testing/fuzzing/fuzz_support.h, line 15 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2184#-MzBRDg5CKJ41T0o-KF2:-MzBYQTi5nQ8XBU_t3te:b-rsu3mq) ([raw file](https://github.com/toktok/c-toxcore/blob/2e8bd61067589c657e277b4f96e30c749d892e37/testing/fuzzing/fuzz_support.h#L15)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Could, yes, but that's written in C, and I want to rewrite that completely when moving it to the `Network *ns` stuff I'm working on.
</blockquote></details>

ok, makes sense

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2184#-:-MzBdgrmDe76Ora_Vld0:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
