### PR TITLE
test: Add "infer" CI check to github, remove from circle.

### PR DESCRIPTION
**Pull request by iphydf**
This now uses our own built image with the current master of infer.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2529)

### CODE REVIEW

**Review by nurupo — APPROVED** [review]
You have performed the grand violation of tokstyle -- user error. Or at least so cimple says. Please correct the user.

Mergeable is failing, but was updated to accept multiline commit messages, so would probably pass on the next run.

Other than that, LGTM.

---

As a side note, it's weird that the page for Mergeable check on this PR says:

>description must exclude '\[ \]'

How come we can't use `[]` in commit description? What if the description is referencing an array? Would prefer not to have any restrictions like that.

**Comment by iphydf** [comment]
`[]` is allowed, `[ ]` is not. I think that's acceptable. The latter is an empty checkbox in markdown.

**Comment by nurupo** [comment]
Wait, why are we disallowing Markdown checkboxes in git commit messages? Markdown has nothing to do with git commit messages. Git commit messages are plaintext, not Markdown, and should not be interpreted as Markdown...

**Comment by iphydf** [comment]
> Wait, why are we disallowing Markdown checkboxes in git commit messages? Markdown has nothing to do with git commit messages. Git commit messages are plaintext, not Markdown, and should not be rendered as Markdown... This makes no sense to me.

We're not. That checker only applies to the pull request description, not the commit message.

**Pull request merged**
