### PR TITLE
Add crypto_memzero for temp buffer

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/491)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/491#-:-KeLImDIKuj04JlebfbW:b-jbsf8z)*

**Comment by Zer0-One** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/491#-:-KeM3XUUnJkeoWFN-uFw:b-jbsf8z)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/491#-:-KeN3fH8FNmPTwAK5Gs0:b-jbsf8z)*

**Comment by nurupo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/491)*

**Comment by iphydf** [comment]
Rebase?

**Comment by iphydf** [comment]
Check the checkbox that allows collaborators to push to the PR branch.

**Comment by Diadlo** [comment]
Done

**Pull request merged**
