### PR TITLE
Made save format platform-independent

### LINKED ISSUE #215: The current tox save format is non-portable
I can't find explicit alignment of SAVED_FRIEND struct
This structure is written into tox_save file as is. That is why very important to provide same alignment of this struct across all clients. What happens if I set default align to 1 byte for toxcore?
Ok, you answer me: "all good guys build toxcore using in-lib scripts and they always get same align"
But I build toxcore using msvc and I'm bad guy. Do you know, that it is very bad practice - save structures to file as is, without portable serialization?

### PR DESCRIPTION
**Pull request by robinlinden**
Fixes #215.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/281)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[toxcore/Messenger.c, line 2654 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWhHzubNwc90X2tnMSt:-KWhHzubNwc90X2tnMSu:b-70bsor) ([raw file](https://github.com/toktok/c-toxcore/blob/0dc750c8bc6b8156eb31099a078d7f4d0213dee8/toxcore/Messenger.c#L2654)):*
> ```C
> {
>     uint32_t size = 0;
> #define SIZE_OF_FIELD(NAME) size += sizeof(temp.NAME)
> ```

You could instead copy/paste the exact COPY_VALUE/COPY_ARRAY sequence and define them as adding sizeof to a `uint32_t data`. That way, it is indeed copy/paste, but it's clean copy/paste. Right now it's a derived copy/paste that can get out of sync. There isn't even a comment saying that it's the same as something else.

---

*[toxcore/Messenger.c, line 2723 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWhJlQSqcrT6H3aexSC:-KWhJlQSqcrT6H3aexSD:b-uu3rfq) ([raw file](https://github.com/toktok/c-toxcore/blob/0dc750c8bc6b8156eb31099a078d7f4d0213dee8/toxcore/Messenger.c#L2723)):*
> ```C
>         if (m->friendlist[i].status > 0) {
>             struct SAVED_FRIEND temp;
>             memset(&temp, 0, saved_friend_size());
> ```

This is now wrong. `temp` is in fact of size `sizeof temp` or `sizeof(struct SAVED_FRIEND)`. Remove this line and change the declaration to `struct SAVED_FRIEND temp = { 0 };`.

---

*[toxcore/Messenger.c, line 2808 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWhKdaRSqS0Q-Gz3IGs:-KWhKdaRSqS0Q-Gz3IGt:b-rhmu4w) ([raw file](https://github.com/toktok/c-toxcore/blob/0dc750c8bc6b8156eb31099a078d7f4d0213dee8/toxcore/Messenger.c#L2808)):*
> ```C
> 
>     for (i = 0; i < num; ++i) {
>         struct SAVED_FRIEND temp;
> ```

Add initialiser: `= { 0 }`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281)*

**Comment by iphydf** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281)*

**Comment by robinlinden** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[toxcore/Messenger.c, line 2654 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWhHzubNwc90X2tnMSt:-KWjAikK2kybUTOrj8z-:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/0dc750c8bc6b8156eb31099a078d7f4d0213dee8/toxcore/Messenger.c#L2654)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> You could instead copy/paste the exact COPY_VALUE/COPY_ARRAY sequence and define them as adding sizeof to a `uint32_t data`. That way, it is indeed copy/paste, but it's clean copy/paste. Right now it's a derived copy/paste that can get out of sync. There isn't even a comment saying that it's the same as something else.
</details>
Done.

---

*[toxcore/Messenger.c, line 2723 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWhJlQSqcrT6H3aexSC:-KWinVQjvCZRw7C19Hdi:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/0dc750c8bc6b8156eb31099a078d7f4d0213dee8/toxcore/Messenger.c#L2723)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> This is now wrong. `temp` is in fact of size `sizeof temp` or `sizeof(struct SAVED_FRIEND)`. Remove this line and change the declaration to `struct SAVED_FRIEND temp = { 0 };`.
</details>
Done.

---

*[toxcore/Messenger.c, line 2808 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWhKdaRSqS0Q-Gz3IGs:-KWioZSgLBhU5UL0lqXD:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/0dc750c8bc6b8156eb31099a078d7f4d0213dee8/toxcore/Messenger.c#L2808)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Add initialiser: `= { 0 }`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[toxcore/Messenger.c, line 2654 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWjOacDo8K1-ZU8uucC:-KWjOacDo8K1-ZU8uucD:bn9wcs5) ([raw file](https://github.com/toktok/c-toxcore/blob/c2af1e6e8292c831503cb514ac30d872566035d6/toxcore/Messenger.c#L2654)):*
> ```C
> {
>     uint32_t data = 0;
>     struct SAVED_FRIEND *temp = { 0 };
> ```

`const struct SAVED_FRIEND temp = { 0 };`

---

*[toxcore/Messenger.c, line 2657 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWjOeKaS2eaLhqTNfRC:-KWjOeKaS2eaLhqTNfRD:b22a9df) ([raw file](https://github.com/toktok/c-toxcore/blob/c2af1e6e8292c831503cb514ac30d872566035d6/toxcore/Messenger.c#L2657)):*
> ```C
> 
> #define COPY_VALUE(NAME)                            \
>     data += sizeof(temp->NAME)
> ```

`sizeof(temp.NAME)`

Also, I'd suggest putting these on one line, given they are so trivial.

---

*[toxcore/Messenger.c, line 2680 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWjOnrxh4KqUHNAp5jx:-KWjOnrxh4KqUHNAp5jy:bctw32d) ([raw file](https://github.com/toktok/c-toxcore/blob/c2af1e6e8292c831503cb514ac30d872566035d6/toxcore/Messenger.c#L2680)):*
> ```C
> #undef COPY_VALUE
> #undef COPY_ARRAY
>     
> ```

Remove spaces at end of lines. Perhaps set up your editor to not do this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281)*

**Comment by robinlinden** [comment]
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[toxcore/Messenger.c, line 2654 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWjOacDo8K1-ZU8uucC:-KWjPdd3QsAaHlNrnezV:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c2af1e6e8292c831503cb514ac30d872566035d6/toxcore/Messenger.c#L2654)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> `const struct SAVED_FRIEND temp = { 0 };`
</details>
Done.

---

*[toxcore/Messenger.c, line 2657 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWjOeKaS2eaLhqTNfRC:-KWjPcXUHxW84uW5uUZo:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c2af1e6e8292c831503cb514ac30d872566035d6/toxcore/Messenger.c#L2657)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> `sizeof(temp.NAME)`
> 
> Also, I'd suggest putting these on one line, given they are so trivial.
</details>
Done.

---

*[toxcore/Messenger.c, line 2680 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWjOnrxh4KqUHNAp5jx:-KWjPZsFpIkzgjQtyw__:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c2af1e6e8292c831503cb514ac30d872566035d6/toxcore/Messenger.c#L2680)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Remove spaces at end of lines. Perhaps set up your editor to not do this.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281)*

**Comment by iphydf** [comment]
:lgtm_strong:

But, since I wrote about half of this, others should sign off as well.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-:-KWjSQhXDWTysTcVyt02:b-1792vf)*

**Comment by JFreegman** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[toxcore/Messenger.c, line 2656 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWjXyyWq_CvOwBlJY5e:-KWjXyyXOn5yLMxrlGld:b-nh6oig) ([raw file](https://github.com/toktok/c-toxcore/blob/ca5b9c724aff76d8b9680d2dce6cd0ebc0b7bc11/toxcore/Messenger.c#L2656)):*
> ```C
>     const struct SAVED_FRIEND temp = { 0 };
> 
> #define COPY_VALUE(NAME) data += sizeof(temp.NAME)
> ```

These two defines don't appear to be copying anything. Need better names.

---

*[toxcore/Messenger.c, line 2802 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWjXcwNWhm1LprfFTBr:-KWjXcwOTjfy4onhsF62:b-p5yccs) ([raw file](https://github.com/toktok/c-toxcore/blob/ca5b9c724aff76d8b9680d2dce6cd0ebc0b7bc11/toxcore/Messenger.c#L2802)):*
> ```C
> static int friends_list_load(Messenger *m, const uint8_t *data, uint32_t length)
> {
>     if (length % friend_size() != 0) {
> ```

You should assign friend_size() to a variable so you don't have to call it numerous times in the same function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281)*

**Comment by robinlinden** [comment]
Review status: 1 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[toxcore/Messenger.c, line 2656 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWjXyyWq_CvOwBlJY5e:-KWjby0_C4Fxy3oRiTdk:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/ca5b9c724aff76d8b9680d2dce6cd0ebc0b7bc11/toxcore/Messenger.c#L2656)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary>
> These two defines don't appear to be copying anything. Need better names.
</details>
Done.

---

*[toxcore/Messenger.c, line 2802 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWjXcwNWhm1LprfFTBr:-KWjc19OgLt-VpuFsqVo:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/ca5b9c724aff76d8b9680d2dce6cd0ebc0b7bc11/toxcore/Messenger.c#L2802)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary>
> You should assign friend_size() to a variable so you don't have to call it numerous times in the same function.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281)*

**Comment by iphydf** [comment]
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[toxcore/Messenger.c, line 2659 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWmn8wfXy2nkLZQP6rm:-KWmn8wgEm1bczNjxhQE:biis4i6) ([raw file](https://github.com/toktok/c-toxcore/blob/4d9a2f6f47fff3a93cf064aea3b6e8a36c2cb1fb/toxcore/Messenger.c#L2659)):*
> ```C
> #define ARRAY_MEMBER(NAME) data += sizeof(temp.NAME)
> 
>     // Exactly the same in friend_load, friend_save, and friend_size:
> ```

This is no longer true now. Please make it true again.

---

*[toxcore/Messenger.c, line 2802 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWmnCulQihLDvuDql6G:-KWmnCulQihLDvuDql6H:b-6dfsmp) ([raw file](https://github.com/toktok/c-toxcore/blob/4d9a2f6f47fff3a93cf064aea3b6e8a36c2cb1fb/toxcore/Messenger.c#L2802)):*
> ```C
> static int friends_list_load(Messenger *m, const uint8_t *data, uint32_t length)
> {
>     const uint32_t friend_size = friend_size();
> ```

You can't reuse the name. Same in haskell: `let foo = foo ()` will fail to compile. (Another reason not to put it in a variable: you have to make up a new name - @jfreegman suggest a name :))

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281)*

**Comment by JFreegman** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-:-KWnpdAMRUlQpg4EkSHd:b-jbsf8z)*

**Comment by robinlinden** [comment]
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[toxcore/Messenger.c, line 2659 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWmn8wfXy2nkLZQP6rm:-KWoKYJwttuzlvIOHVw5:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/4d9a2f6f47fff3a93cf064aea3b6e8a36c2cb1fb/toxcore/Messenger.c#L2659)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> This is no longer true now. Please make it true again.
</details>
Done.

---

*[toxcore/Messenger.c, line 2802 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWmnCulQihLDvuDql6G:-KWoKZwOi1gCguJDYGj3:b-naoo4y) ([raw file](https://github.com/toktok/c-toxcore/blob/4d9a2f6f47fff3a93cf064aea3b6e8a36c2cb1fb/toxcore/Messenger.c#L2802)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> You can't reuse the name. Same in haskell: `let foo = foo ()` will fail to compile. (Another reason not to put it in a variable: you have to make up a new name - @jfreegman suggest a name :))
</details>
Reverted to using a function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281)*

**Comment by iphydf** [comment]
What could be avoided?

The test was modified to put the network test last. All other tests in tox_one_test are hermetic and don't rely on networking to work.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-:-KX1ELN3ZfAg_nysMBxF:b-oo1bw1)*

**Comment by nurupo** [comment]
>What could be avoided?

The alignment issue this Pr fixes. It exists because toxcore was made to memcpy the struct into the savedata array as it is, instead of memcpy'ing its members. This could be avoided if we memcpy'ed the struct members into the savedata, instead of memcpy'ing the struct itself. Obviously, we can't redo this now, as it would break all existing savedata files and we better use some json/msgpack format if we are going to break it. So the takeaway form this is to remember to never memcpy a struct in real code.

>The test was modified to put the network test last. All other tests in tox_one_test are hermetic and don't rely on networking to work.

Ok.

:lgtm_strong:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-:-KX3-YXBaeVyQBSiRmnc:b53gav7)*

**Comment by GrayHatter** [comment]
:lgtm: 

I didn't verify that this wont eat existing save files.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/Messenger.c, line 2656 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-KWjXyyWq_CvOwBlJY5e:-KX3F93_L3PaTFvYfg8k:bb6ywmx) ([raw file](https://github.com/toktok/c-toxcore/blob/ca5b9c724aff76d8b9680d2dce6cd0ebc0b7bc11/toxcore/Messenger.c#L2656)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Done.
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/281#-:-KX3FbsKN1HkFcyOnv4V:b7utbzx)*

**Pull request merged**
