### PR TITLE
Network cleanup3

### LINKED ISSUE #124: Don't include OS specific headers in .h files
Currently, `network.h` includes a whole lot of platform specific headers (like `u.h`, `windows.h`, and `unistd.h`). We should confine these to a single file (or a few files).

I suggest we create a thin abstraction on the OS facilities for networking, and another on the ones for the monotonic clock. We could then have one file per platform kind (e.g. `${module}_win32.c`, `_unix.c`, `_osx.c`, `_posix.c`, ...) and conditionally compile them according to preprocessor symbols, just like we do already. The downside is that it's a little bit more declaration overhead, because currently those `#ifdef`s are inside functions that will need to be redefined for each platform. The advantage is that there are no or few `#ifdef`s in the code itself, and the platform specific code is in a set of small files instead of (as it is now) in a 1100 line file mixing platform abstractions with application code.

### PR DESCRIPTION
**Pull request by Diadlo**
Fix #124

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/514)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 18 of 19 files at r1, 1 of 10 files at r2.
Review status: 8 of 21 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by sudden6** [comment]
Review status: 8 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/onion.c, line 620 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/514#-KfDkTks7-iwbJmYjXwQ:-KfDkTks7-iwbJmYjXwR:bsgi6kq) ([raw file](https://github.com/toktok/c-toxcore/blob/4be6714e7ab3f42605aae437df81ec850d866fa1/toxcore/onion.c#L620)):*
> ```C
> 
>     if (onion->recv_1_function &&
>             send_to.ip.family != TOX_AF_INET &&
> ```

I found no resources about a c-toxcore coding style, but are you sure these indentations are correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by sudden6** [comment]
Reviewed 1 of 19 files at r1.
Review status: 8 of 22 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by Diadlo** [comment]
Review status: 7 of 22 files reviewed at latest revision, all discussions resolved.

---

*[toxcore/onion.c, line 620 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/514#-KfDkTks7-iwbJmYjXwQ:-KfDls22Iwol7mv7TBYo:b-v3ad41) ([raw file](https://github.com/toktok/c-toxcore/blob/4be6714e7ab3f42605aae437df81ec850d866fa1/toxcore/onion.c#L620)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I found no resources about a c-toxcore coding style, but are you sure these indentations are correct?
</blockquote></details>

c-toxcore use [astyle](https://github.com/TokTok/c-toxcore/tree/master/other/astyle).
It generate exactly this indentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by sudden6** [comment]
Reviewed 9 of 10 files at r2.
Review status: 7 of 22 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toxcore/network.c, line 145 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/514#-KfDni3MsEHZQ2mxPSIn:-KfDni3MsEHZQ2mxPSIo:b-b1tze9) ([raw file](https://github.com/toktok/c-toxcore/blob/ba515813945c31be90f2ba0159ac222dce2dedb4/toxcore/network.c#L145)):*
> ```C
> 
> const IP4 ip4_loopback = {
>     { 0, 0, 0, 1 }
> ```

Shouldn't v4 loopback be 127.0.0.1?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by sudden6** [comment]
Reviewed 12 of 14 files at r8.
Review status: 7 of 22 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by Diadlo** [comment]
Review status: 7 of 23 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toxcore/network.c, line 145 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/514#-KfDni3MsEHZQ2mxPSIn:-KfDu3d3i7JvOlyjBI6r:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/ba515813945c31be90f2ba0159ac222dce2dedb4/toxcore/network.c#L145)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Shouldn't v4 loopback be 127.0.0.1?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by sudden6** [comment]
Reviewed 1 of 3 files at r5, 2 of 14 files at r8.
Review status: 7 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by sudden6** [comment]
Reviewed 10 of 10 files at r9.
Review status: 12 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by sudden6** [comment]
Reviewed 3 of 3 files at r10.
Review status: 14 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by sudden6** [comment]
Reviewed 12 of 12 files at r11, 10 of 10 files at r12.
Review status: 12 of 23 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by sudden6** [comment]
Reviewed 3 of 3 files at r13.
Review status: 15 of 23 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by sudden6** [comment]
Reviewed 3 of 3 files at r14.
Review status: 15 of 23 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by sudden6** [comment]
Reviewed 3 of 3 files at r15.
Review status: 15 of 23 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by sudden6** [comment]
Reviewed 5 of 5 files at r16, 1 of 1 files at r17, 3 of 6 files at r18.
Review status: 20 of 23 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[toxcore/LAN_discovery.c, line 256 at r18](https://reviewable.io:443/reviews/toktok/c-toxcore/514#-KfHfxbrqanyTD8lUk5G:-KfHfxbrqanyTD8lUk5H:b-zd1xj) ([raw file](https://github.com/toktok/c-toxcore/blob/4c3815287591197aaffc5e2ec88274d4bca9b0c3/toxcore/LAN_discovery.c#L256)):*
> ```C
>             ip.ip6.uint32[1] = 0;
>             ip.ip6.uint32[2] = net_htonl(0xFFFF);
>             ip.ip6.uint32[3] = INADDR_BROADCAST;
> ```

Travis fails here

---

*[toxcore/LAN_discovery.c, line 261 at r18](https://reviewable.io:443/reviews/toktok/c-toxcore/514#-KfHg--bMKhRlITYlaFI:-KfHg--bMKhRlITYlaFJ:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/4c3815287591197aaffc5e2ec88274d4bca9b0c3/toxcore/LAN_discovery.c#L261)):*
> ```C
>         if (family_broadcast == TOX_AF_INET) {
>             ip.family = TOX_AF_INET;
>             ip.ip4.uint32 = INADDR_BROADCAST;
> ```

same

---

*[toxcore/network.h, line 415 at r16](https://reviewable.io:443/reviews/toktok/c-toxcore/514#-KfHf83JcwdPh6JgNjL6:-KfHf83JcwdPh6JgNjL7:b-29s0gk) ([raw file](https://github.com/toktok/c-toxcore/blob/ec2511495262cd822088d22eda91c071d6746968/toxcore/network.h#L415)):*
> ```objc
> int bind_to_port(Socket sock, int family, uint16_t port);
> 
> /* Send SIZE bytes of BUF to socket SOCK. Returns the number sent or -1.
> ```

`number of bytes sent` is better

---

*[toxcore/network.h, line 421 at r16](https://reviewable.io:443/reviews/toktok/c-toxcore/514#-KfHfGnFIW1RkrPzb8l6:-KfHfGnFIW1RkrPzb8l7:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/ec2511495262cd822088d22eda91c071d6746968/toxcore/network.h#L421)):*
> ```objc
> 
> /* Read SIZE bytes into BUF from socket SOCK.
>  * Returns the number read or (size_t)(-1) for errors.
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/514)*

**Comment by sudden6** [comment]
Sorry for the message spam, I lost a war against reviewable...

**Comment by Diadlo** [comment]
I will reopen it

**Pull request closed without merging**
