### PR TITLE
fix: add missing ngc constants getter declarations and definitions

### PR DESCRIPTION
**Pull request by Green-Sky**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2383)

### CODE REVIEW

**Comment by Green-Sky** [comment]
should be a simple merge (if the ci plays nice...)
@JFreegman last chance to rename `TOX_GROUP_MAX_PASSWORD_SIZE` to `TOX_GROUP_MAX_PASSWORD_LENGTH`

**Comment by JFreegman** [comment]
> should be a simple merge (if the ci plays nice...) @JFreegman last chance to rename `TOX_GROUP_MAX_PASSWORD_SIZE` to `TOX_GROUP_MAX_PASSWORD_LENGTH`

We should make a list of API breaking changes and save them all for the same commit.

**Review by JFreegman — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2383)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by Green-Sky** [comment]
> We should make a list of API breaking changes and save them all for the same commit.

for 0.3.0 ? :)

technically, the ngc api has still not been part of a release yet, so ... we could still change it now.

**Comment by JFreegman** [comment]
> > We should make a list of API breaking changes and save them all for the same commit.
> 
> for 0.3.0 ? :)
> 
> technically, the ngc api has still not been part of a release yet, so ... we could still change it now.

But it has been part of client releases, which means clients need to make a new release if we break the API

**Pull request merged**
