### PR TITLE
add configurable limit on number of stored frozen peers

### LINKED ISSUE #1306: Persistent conference's offline peer list always grows and never decreases
I have been looking for changes in v0.2.9 to write a blog post about and noticed that  https://github.com/TokTok/c-toxcore/pull/1266 added API calls for listing offline peers, yet there is no call for deleting an offline peer, which implies that toxcore is the one managing offline peers, which makes one wonder under what condition does toxcore delete offline peers since they are, well, offline, and can be indefinitely offline, never to come back. When asked about when does toxcore delete peers from the offline peer list, @zugz has said that it doesn't, that it grows indefinitely and that its growth is not limited in toxcore, meaning it can be used to DOS a target user or an entire conference.

### PR DESCRIPTION
**Pull request by zugz**
closes #1306

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1309)

### CODE REVIEW

**Comment by nurupo** [comment]
___
*[toxcore/group.c, line 1293 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1309#-LZ2EQ_XAU7Y4tgBok7Q:-LZ2EQ_XAU7Y4tgBok7R:b-j7rvo) ([raw file](https://github.com/toktok/c-toxcore/blob/170f99b5d9a455a835d5512f4ea70ae4959d7b9f/toxcore/group.c#L1293)):*
> ```C
>     }
> 
>     g->maxfrozen = maxfrozen;
> ```

Shouldn't the `g->frozen` array be resized to make sure it can fit the requested `maxfrozen`?

**Comment by nurupo** [comment]
___
*[toxcore/group.c, line 781 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1309#-LZ2GXiLAnQytEbgpegE:-LZ2Ft1SDFUUbvLBWvwH:b86std2) ([raw file](https://github.com/toktok/c-toxcore/blob/170f99b5d9a455a835d5512f4ea70ae4959d7b9f/toxcore/group.c#L781)):*
> ```C
>  * return true if any frozen peers are removed.
>  */
> static bool remove_old_frozen(Group_c *g)
> ```

The function is called `remove_old_frozen`, which implies some kind of deallocation. If it doesn't actually deallocate any memory, perhaps it should be renamed more appropriately, like `trim_frozen` or something, idk, I'm horrible at naming things.

**Comment by sudden6** [comment]
@nurupo what's your state on this? If there are no further issues, I'll go ahead an merge it.

**Comment by zugz** [comment]
Reviewables isn't working for me at the moment, so I'm responding here 
by email to nurupo's review.

* Saturday, 2019-03-09 at 21:26 -0800 - nurupo <notifications@github.com>:

>You should update `g->numfrozen` after you actually shrunk the array, 

Done.

>Just to make sure, can the 2nd arg here ever be 0? Because `realloc()` 
>with new size being 0 is an undefined behavior.

According to the manpage, realloc is equivalent to free if size is 0, 
which is what we want.

>What's "XXX"?

It's sometimes used to warn about something surprising/unpleasant. But 
I've changed it to "NOTE".

**Comment by zugz** [comment]
* Sunday, 2019-03-17 at 11:40 -0700 - zugz <notifications@github.com>:

>* Saturday, 2019-03-09 at 21:26 -0800 - nurupo <notifications@github.com>:
>>Just to make sure, can the 2nd arg here ever be 0? Because `realloc()`
>>with new size being 0 is an undefined behavior.
>
>According to the manpage, realloc is equivalent to free if size is 0,
>which is what we want.

Sorry, that only goes for the glibc implementation. Thanks to robinli 
for setting me right on this.

maxfrozen can indeed be set to 0. I've pushed a commit which handles 
this, and also correctly handles numfrozen being 0 on load.

Thanks for pointing this out!

**Comment by nurupo** [comment]
Looks good to me. At least just the the code you have added, when considered locally as in the diff. Can't say anything about the global picture, about how it ties in with the whole conferences thing, if the changes you have made are complete and are done right, since I'm not familiar with conferences code.

**Comment by zugz** [comment]
@nurupo: I realised freeze_peer wasn't correctly handling the case that 
delpeer fails (which would be due to a realloc failure). I've just 
pushed a commit to fix this; would you mind checking your approval still 
applies?

**Comment by zugz** [comment]
>nurupo requested changes on this pull request.
>
>Shouldn't that increment be above the if-statement? Otherwise you grow `g->frozen` by one but don't increment `g->numfrozen` accordingly.

g->numfrozen is the number of frozen peers. If we can't delete the peer, 
we shouldn't freeze it.

This does mean that g->numfrozen will be less than the allocated size of 
g->frozen in this case. But we never guaranteed that it would be, so 
I don't see why that would be a problem.

**Comment by sudden6** [comment]
@zugz I think you need to rebase this on master in order to get CI fixed.

**Pull request merged**
