### PR TITLE
Generate only one large library "libtoxcore".

### PR DESCRIPTION
**Pull request by iphydf**
This library contains all the code for the old libtoxcore, libtoxav,
libtoxdns, and libtoxencryptsave. The build for toxav is still optional,
and disabling it causes libtoxcore to simply not contain those symbols
and the pkg-config file to not include opus and vpx as dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/442)

### CODE REVIEW

**Comment by cebe** [comment]
@iphydf can you explain what you are doing here and why?

**Comment by iphydf** [comment]
@cebe I've added a top level comment to the CMakeLists.txt explaining what it does. Why: avoiding the ABI mess that is toxcore.

**Comment by robinlinden** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/442)*

**Comment by SkyzohKey** [comment]
:lgtm_strong:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-:-KcsQiLSvYPuefrCM8ph:b-jbsf8z)*

**Comment by iphydf** [comment]
@cebe can you take a look at this?

**Comment by cebe** [comment]
@iphydf on a coarse overview it looks okay to me. But I have no idea how pkgconfig works and also have not tested anything of this. Just looked at the changes in the diff.

---

Reviewed 6 of 11 files at r1, 2 of 3 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 386 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-KoiRDK7Hf3kTLnjG2SK:-KoiRDK7Hf3kTLnjG2SL:b-745v4y) ([raw file](https://github.com/toktok/c-toxcore/blob/f4e27f4988377ce7de6e0b68202733225a4fd582/CMakeLists.txt#L386)):*
> ```CMake
> find_program(SPECTEST NAMES
>   tox-spectest
>   ../.stack-work/install/x86_64-linux/lts-2.22/7.8.4/bin/tox-spectest)
> ```

what is this? looks super specific to a certain environment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-:-KoiShBoxlBZewbVTiES:b5mbfbc)*

**Comment by zoff99** [comment]
how do you activate this?
CI with this PR still builds all the sperate tox libs

**Comment by iphydf** [comment]
@zoff99 it's always activated when building with CMake.

**Comment by zoff99** [comment]
@iphydf making cmake and autotools build even more different is a bad idea.
it will break builds  :-(

**Comment by Diadlo** [comment]
@iphydf What if someone wants to link his app *without* toxav, and simultaneously link *with* toxav for another app, for example?

**Comment by iphydf** [comment]
@Diadlo do you or someone you know have that use case? Otherwise, YAGNI.

**Comment by iphydf** [comment]
@zoff99 I agree. So after this we should make autotools do the same.

**Comment by Diadlo** [comment]
@iphydf It's just like interface segregation. I just don't understand, why you want to merge all function of public API in one library, if they logically different

**Comment by iphydf** [comment]
@Diadlo I'll happily split it out again if and when toxav does not depend on toxcore internals.

The alternative is to have libraries split along the layer boundaries, so we end up having the many-small-libs situation, which we had before. That has different pros and cons. I hope toxav will eventually become independent of toxcore internals (@mannol has plans for this). At that point, I'd like toxav to be a separate repository, developed independently. In the meantime, the split is headaches for developers for no reason.

**Comment by iphydf** [comment]
Oh, and why that is an alternative: because then toxav can correctly depend on toxnetcrypto and other things it uses. Right now, toxav is lying because it says it only depend on toxcore, while actually it depends on its internals. If we expose the internals correctly (through libraries), we can have everything separated.

**Comment by robinlinden** [comment]
Reviewed 1 of 11 files at r1, 2 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[CMakeLists.txt, line 323 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-L1TZZWMpVAJGpsBdvwh:-L1TZZWMpVAJGpsBdvwi:bpshfa6) ([raw file](https://github.com/toktok/c-toxcore/blob/8ac463ff187182f99e4f0ca98fc7a72e1c359238/CMakeLists.txt#L323)):*
> ```CMake
>     toxav/video.h)
>   target_link_modules(toxav toxgroup ${OPUS_LIBRARIES} ${VPX_LIBRARIES})
>   #message("*** toxav_LINK_MODULES: ${toxav_LINK_MODULES}")
> ```

This should probably be removed.

---

*[CMakeLists.txt, line 359 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-L1TZcmHBmmmJIdrHA4D:-L1TZcmHBmmmJIdrHA4E:bpshfa6) ([raw file](https://github.com/toktok/c-toxcore/blob/8ac463ff187182f99e4f0ca98fc7a72e1c359238/CMakeLists.txt#L359)):*
> ```CMake
> # Link it to all dependencies.
> foreach(sublib ${toxcore_SUBLIBS})
>   #message("*** toxcore_LINK_MODULES += ${${sublib}_LINK_MODULES}  # ${sublib}_LINK_MODULES")
> ```

This should probably be removed.

---

*[cmake/ModulePackage.cmake, line 154 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-L1TcfEYODmDatEvzZpU:-L1TcfEYODmDatEvzZpV:bpshfa6) ([raw file](https://github.com/toktok/c-toxcore/blob/8ac463ff187182f99e4f0ca98fc7a72e1c359238/cmake/ModulePackage.cmake#L154)):*
> ```CMake
> 
>   foreach(dep ${ARGN})
>     #message("*** Processing dep ${dep} for ${target}")
> ```

This should probably be removed.

---

*[cmake/ModulePackage.cmake, line 165 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-L1TciCbvA-LTi_H7syd:-L1TciCbvA-LTi_H7sye:bpshfa6) ([raw file](https://github.com/toktok/c-toxcore/blob/8ac463ff187182f99e4f0ca98fc7a72e1c359238/cmake/ModulePackage.cmake#L165)):*
> ```CMake
>         list(FIND LINK_MODULES ${dep} _index)
>         if(_index EQUAL -1)
>           #message("*** Adding ${dep} to ${target}_LINK_MODULES.")
> ```

This should probably be removed.

---

*[cmake/StrictAbi.cmake, line 36 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-L1Tcl38seyrXW6TSz1s:-L1Tcl38seyrXW6TSz1t:bwrrzh1) ([raw file](https://github.com/toktok/c-toxcore/blob/8ac463ff187182f99e4f0ca98fc7a72e1c359238/cmake/StrictAbi.cmake#L36)):*
> ```CMake
>       OUTPUT_STRIP_TRAILING_WHITESPACE)
>     string(REPLACE "\n" ";" sublib_SYMS ${sublib_SYMS})
>   
> ```

Stray whitespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/442)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[CMakeLists.txt, line 386 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-KoiRDK7Hf3kTLnjG2SK:-L1ULkPOvI_A1fF3wHay:b-azrdr0) ([raw file](https://github.com/toktok/c-toxcore/blob/f4e27f4988377ce7de6e0b68202733225a4fd582/CMakeLists.txt#L386)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

what is this? looks super specific to a certain environment.
</blockquote></details>

It's specific to toktok-stack, which is available to everyone (it's a github repo).

---

*[CMakeLists.txt, line 323 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-L1TZZWMpVAJGpsBdvwh:-L1ULh_8gIkesvU9z3vY:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/8ac463ff187182f99e4f0ca98fc7a72e1c359238/CMakeLists.txt#L323)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This should probably be removed.
</blockquote></details>

Done.

---

*[CMakeLists.txt, line 359 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-L1TZcmHBmmmJIdrHA4D:-L1ULiaQi44mfdi4ZG3u:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/8ac463ff187182f99e4f0ca98fc7a72e1c359238/CMakeLists.txt#L359)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This should probably be removed.
</blockquote></details>

Done.

---

*[cmake/ModulePackage.cmake, line 154 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-L1TcfEYODmDatEvzZpU:-L1ULwqbEyqyL5VTERI3:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/8ac463ff187182f99e4f0ca98fc7a72e1c359238/cmake/ModulePackage.cmake#L154)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This should probably be removed.
</blockquote></details>

Done.

---

*[cmake/ModulePackage.cmake, line 165 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-L1TciCbvA-LTi_H7syd:-L1ULxCl8BuYv_dpd9Mt:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/8ac463ff187182f99e4f0ca98fc7a72e1c359238/cmake/ModulePackage.cmake#L165)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This should probably be removed.
</blockquote></details>

Done.

---

*[cmake/StrictAbi.cmake, line 36 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-L1Tcl38seyrXW6TSz1s:-L1UM2XSj0DqiELAWPC8:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/8ac463ff187182f99e4f0ca98fc7a72e1c359238/cmake/StrictAbi.cmake#L36)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Stray whitespace.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/442)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/442#-:-L1UMQ7YQZ_eeZKiZbjm:b-jbsf8z)*

**Pull request merged**
