### PR TITLE
Remove `TOX_DEBUG` and have asserts always enabled.

### PR DESCRIPTION
**Pull request by iphydf**
These are cheap asserts. I've also replaced the fprintf's with
`LOGGER_ERROR` calls.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/381)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm: except for the load_state() function... WTF is that?

+@grayhatter +@nurupo 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/381#-:-K_hXQXNjdNWIQQ5xbQw:b-28h78)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/381#-:-K_kS8FZsXa17Q9iRjVq:bg7igkv)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/381#-:-Ka29SFr1UngrGUtAbaH:bg7igkv)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 2 of 8 files at r1, 2 of 4 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/381#-:-Ka7YTLTloRcSWKp40sa:b-jbsf8z)*

**Comment by iphydf** [comment]
@GrayHatter @robinlinden PTAL: merge required additional change: I added another instance of `#ifdef TOX_DEBUG` in Messenger.c in #392 that I now removed again.

**Comment by robinlinden** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/381)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/381#-:-KaFA2Z2vkCe_xx_2ZNt:bg7igkv)*

**Comment by nurupo** [comment]
:lgtm_strong:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/381#-:-KaJqdVQUei4ueQXFDT6:b-jbsf8z)*

**Pull request merged**
