### PR TITLE
Use `const` more in C code.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/782)

### CODE REVIEW

**Comment by zoff99** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/782)*

**Comment by endoffile78** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/DHT.c, line 238 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/782#-L5aTnIDHoxKkhpxcsFq:-L5aTnIDHoxKkhpxcsFr:bvsqwt6) ([raw file](https://github.com/toktok/c-toxcore/blob/1fa7af3e3e16fc973c0d8414c8db0b47e1a11039/toxcore/DHT.c#L238)):*
> ```C
>     encrypt_precompute(public_key, secret_key, shared_key);
> 
>     if (num != (uint32_t) - 1) {
> ```

Why not just use `UINT32_MAX`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/782)*

**Comment by iphydf** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/DHT.c, line 238 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/782#-L5aTnIDHoxKkhpxcsFq:-L5cvIbsfEwL33jeGLwQ:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/1fa7af3e3e16fc973c0d8414c8db0b47e1a11039/toxcore/DHT.c#L238)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Why not just use `UINT32_MAX`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/782)*

**Comment by robinlinden** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/friend_connection.c, line 91 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/782#-L5cyVNtL603ablke9xT:-L5cyVNtL603ablke9xU:bcf9uka) ([raw file](https://github.com/toktok/c-toxcore/blob/db85e6dc8b7f863a72575fc84c5b07584b45c6b3/toxcore/friend_connection.c#L91)):*
> ```C
> 
> 
> /* return true if the friendcon_id is not valid.
> ```

This returns true if it's valid now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/782)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/friend_connection.c, line 91 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/782#-L5cyVNtL603ablke9xT:-L5d-HSeIp_BcMSRy2F_:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/db85e6dc8b7f863a72575fc84c5b07584b45c6b3/toxcore/friend_connection.c#L91)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This returns true if it's valid now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/782)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/782#-:-L5d-NLI6pjJuuab5nVK:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/782#-:-L5d4FzcPZKjGkCfcrhx:b-jbsf8z)*

**Pull request merged**
