### PR TITLE
tweak vp8 videocodec

### PR DESCRIPTION
**Pull request by zoff99**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/573)

### CODE REVIEW

**Comment by nurupo** [comment]
@mannol what's your input on this? I'm totally unfamiliar with vp8, I assume that you are more familiar than most of us here.

**Comment by Diadlo** [comment]
@zoff99 Are you sure that increase `kf_max_dist` will not lead to problems on low bandwidth? More oftec keyframes requeres more bundwith

**Comment by mannol** [comment]
Haven't tried myself but i think this will help with video quality. Regarding bandwidth: it should be controlled by the bitrate primarily. Even though this will probably increase bandwidth usage, it's still not as important factor for it as the bitrate (didn't measure myself but I'm sure that's the case).

**Comment by zoff99** [comment]
@Diadlo actually in my tests it requires less bandwidth. why? with these simple tweaks i can now set a lower video bitrate and it will work ok. before with low bitrate setting the video corrputed always and never recovered.
tests are diffcult because these is only 1 client for low bandwidth (android 3G connection) now (its not Antox)

@mannol there is no documentation what clients should set as video bitrate. i made some experiments and this is my result.
i also tried some other settings:

* cfg.g_error_resilient -> still does not work even with VP9
* cfg.g_lag_in_frames -> results in no video
* cfg.g_threads -> any value results in no video
* cfg.rc_dropframe_thresh = 25 -> works, but i see no difference
* cfg.kf_max_dist

what i have not yet tried:

* vpx_codec_control(&new_c, VP8E_SET_CPUUSED, 16);  -> here VP8 can take up to "16" maybe that will help? make it user configurable? now we use "8"

```
VP8E_SET_CPUUSED 
Codec control function to set encoder internal speed settings. 
Changes in this value influences, among others, the encoder's
selection of motion estimation methods. Values greater than 0 will
increase encoder speed at the expense of quality.

NoteValid range for VP8: -16..16
Valid range for VP9: -8..8

```

**Comment by sudden6** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxav/video.c, line 83 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/573#-Kqy4WDhMN-G6L5qM8Jc:-Kqy4WDhMN-G6L5qM8Jd:b-mh0sqw) ([raw file](https://github.com/toktok/c-toxcore/blob/6ab1e04f2bcce83edda26258480241e874212729/toxav/video.c#L83)):*
> ```C
>        Perhaps vp9 has solved it?*/
> #if 0
>     /* zoff: this does still not work */
> ```

maybe add year+month when last tested?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/573)*

**Comment by zoff99** [comment]
this:
```
cfg.kf_max_dist = 10;
```
should be exposed as a tox option, so that clients can set this as they find suits best
(without forking and recompiling)

**Comment by zoff99** [comment]
anymore thoughts on this?
@dvor will try to test this on the iPhone app, and we see if it improves video over 3g connection

**Comment by iphydf** [comment]
Can you improve the commit and PR message? What does this do, what improvements can we expect? The PR title is going to end up in the changelog, so ideally it's understandable by client devs.

**Comment by zoff99** [comment]
@iphydf this is obsoleted by #629

**Comment by iphydf** [comment]
Obsoleted by #629.

**Pull request closed without merging**
