### PR TITLE
Merge irungentoo/master into toktok

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/918)

### CODE REVIEW

**Comment by nurupo** [comment]
>Files changed: 0

I'm confused. We already have fix for this in our repo.

Is this just for the sake of having this exact commit hash in the repo?

**Comment by iphydf** [comment]
Yes. Every time I look at the toktok repo and I see "1 commit behind irungentoo/master", I need to remember which commit that was, and that we already have that change.

**Comment by nurupo** [comment]
So, what will happen if irungentoo makes 20 more commits? We will merge them too?

**Comment by nurupo** [comment]
This just doesn't make much sense to me.

**Comment by iphydf** [comment]
Yes, if irungentoo makes 20 commits tomorrow, we will merge them following our regular review process.

**Comment by nurupo** [comment]
@robinlinden @Diadlo what do you guys think?

**Comment by Diadlo** [comment]
Why not merge 20 commits, if they are useful? If useless, we may not merge them.
But I don't see any reason to merge empty commit

**Comment by sudden6** [comment]
IMO we can merge this, it's also slightly annoying me.

**Comment by tox-user** [comment]
This commit isn't useful in any way. Why pay attention to a repository that isn't maintained?

**Comment by iphydf** [comment]
Does this commit harm in any way? Why are we spending 3 days discussing it? irungentoo/toxcore obviously is maintained. Security fixes are ported back to it. It's frozen otherwise, but its security status is maintained.

**Comment by tox-user** [comment]
I don't mind if you merge this. I just wanted to know if you think it's a good idea to pay attention to every small change that happens in irungentoo/toxcore.

**Comment by iphydf** [comment]
Yes, I do think that we should pay attention to every small change in iru/toxcore, especially because nothing happens there, so *if* something happens, it must be important. If I see "behind iru/toxcore", I'll want to check what happened there. This PR makes it so I don't need to think about it anymore, until the next (likely important) change happens.

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: 0 of 1 LGTMs obtained (waiting on @nurupo)

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/918#-:-LFYUjfGByIDEyaFhqmv:b-jbsf8z)*

**Comment by nurupo** [comment]
Alright.
:lgtm_strong:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/918#-:-LFYZH7179M8LDsRr87d:b-olmrxy)*

**Pull request merged**
