### PR TITLE
Remove empty line in Messenger.c

### PR DESCRIPTION
**Pull request by LittleVulpix**
Found by chance by Nurupo when browsing the file. Doesn't affect anything, but might as well get rid of it...

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/486)

### CODE REVIEW

**Comment by LittleVulpix** [comment]
@nurupo found this when helping me understand some logic in toxcore.

**Comment by cebe** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/486#-:-Ke0ayEdutWQF7RIeEAm:b-jbsf8z)*

**Comment by nurupo** [comment]
:lgtm_strong: I don't think we need tests for this one.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/486#-:-Ke0c_gN7oq8NbB0Iq3k:bjt9ywk)*

**Comment by nurupo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/486)*

**Pull request merged**
