### PR TITLE
Split out conference type (text/av) from identifier.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1016)

### CODE REVIEW

**Comment by zugz** [comment]
Looks good, except that now the field is called 'identifier' while elsewhere 
in the code it's called a 'uid'. I think it would be clearer if the field were 
also called 'uid'.

I'd also suggest renaming 'uid' to 'id', to avoid the potential for 
misunderstanding it as "user ID" and to fit the spec, which uses this 
terminology ('id' for the group public key and 'identifier' for the 33-byte 
type+id).

**Comment by iphydf** [comment]
@zugz would you suggest renaming the public API function as well?

**Comment by iphydf** [comment]
Anyway, I've renamed identifier to uid.

**Comment by zugz** [comment]
* Saturday, 2018-07-21 at 15:07 -0700 - iphydf <notifications@github.com>:

>@zugz would you suggest renaming the public API function as well?

i.e. the ones you added a couple of weeks ago in 90a63e8? Yes, for the 
same reasons. Unless you have a reason to prefer "uid"?

**Comment by iphydf** [comment]
@zugz done.

**Comment by iphydf** [comment]
Should we revert "id" back to "identifier"?

**Comment by zugz** [comment]
>Should we revert "id" back to "identifier"?

I'd say it's better to have new terminology for the new concept, to 
minimise confusion between versions. It also means we don't have to 
change the spec.

:lgtm_strong:

**Pull request merged**
