### PR TITLE
cleanup: correct a few nullable annotations

### PR DESCRIPTION
**Pull request by JFreegman**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2685)

### CODE REVIEW

**Review by nurupo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2685)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[`toxcore/group_chats.c` line 1812 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2685#-NqZRQEcDPlvCT_26ecP:-NqZRQEcDPlvCT_26ecQ:bdfq3if) ([raw file](https://github.com/TokTok/c-toxcore/blob/fbe3c19cf5e94f6a354a1d4df45e9c44dd2d5d11/toxcore/group_chats.c#L1812)):*
> ```C
> 
>     if (length > 0) {
>         if (!unpack_gc_sync_announce(chat, data, length)) {
> ```

`unpack_gc_sync_announce()` is marked as `non_null()`, i.e. all pointers passed to it MUST be non-null.
___
*[`toxcore/group_chats.c` line 2275 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2685#-NqZQgaR9rYtngiMv2gP:-NqZQgaR9rYtngiMv2gQ:bet5czm) ([raw file](https://github.com/TokTok/c-toxcore/blob/fbe3c19cf5e94f6a354a1d4df45e9c44dd2d5d11/toxcore/group_chats.c#L2275)):*
> ```C
> 
>         uint16_t password_length;
>         net_unpack_u16(data, &password_length);
> ```

`net_unpack()` is marked as `non_null()`, i.e. all pointers passed to it MUST be non-null.

Also, if the `data` is NULL, `net_unpack()` would crash trying to access the 0x0 address.

**Review by JFreegman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2685)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nurupo)

___
*[`toxcore/group_chats.c` line 1812 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2685#-NqZRQEcDPlvCT_26ecP:-NqZS7NVE7sItfqK5VzL:b5al5v0) ([raw file](https://github.com/TokTok/c-toxcore/blob/fbe3c19cf5e94f6a354a1d4df45e9c44dd2d5d11/toxcore/group_chats.c#L1812)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

`unpack_gc_sync_announce()` is marked as `non_null()`, i.e. all pointers passed to it MUST be non-null.
</blockquote></details>

If length is > 0 then the pointer will always be non-null (unless there's a very serious bug in network.c)
___
*[`toxcore/group_chats.c` line 2275 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2685#-NqZQgaR9rYtngiMv2gP:-NqZSLX59O0-XUv42v0u:b-qto2so) ([raw file](https://github.com/TokTok/c-toxcore/blob/fbe3c19cf5e94f6a354a1d4df45e9c44dd2d5d11/toxcore/group_chats.c#L2275)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

`net_unpack()` is marked as `non_null()`, i.e. all pointers passed to it MUST be non-null.

Also, if the `data` is NULL, `net_unpack()` would crash trying to access the 0x0 address.
</blockquote></details>

Again, we do a length check right above that. There's no reason to null check after a length check. It should be noted that changing these annotations doesn't modify the way the program behaves. It's just a guideline.

**Review by nurupo — COMMENTED** [review]
Does the length being non-zero guarantee that the `data` is not NULL? In that case these changes would make sense.

But if the `length` is user-provided, then no.

> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2685#-:-NqZSIQQDOXxOJ5Df3rv:b-f87naa)* status: 1 change requests, 0 of 1 approvals obtained

**Review by iphydf — APPROVED** [review]

**Comment by JFreegman** [comment]
> Does the length being non-zero guarantee that the `data` is not NULL? In that case these changes would make sense.
> 
> But if the `length` is user-provided, then no.
> 
> > _[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2685#-:-NqZSIQQDOXxOJ5Df3rv:b-f87naa)_ status: 1 change requests, 0 of 1 approvals obtained

There should never be an instance where a non-zero length is paired with a null data pointer. That would indicate a serious bug. These notations are for telling static analyzers what to expect, and if they see something unexpected, they'll tell us about it. Since both these functions are able to handle both null and non-null data pointers, analyzers shouldn't complain if they see either case.

If there were a bug and we passed a null pointer to `net_unpack()` for example, then the analyzer would warn us for that specific case.

**Comment by nurupo** [comment]
>These notations are for telling static analyzers what to expect, and if they see something unexpected, they'll tell us about it. Since both these functions are able to handle both null and non-null data pointers, analyzers shouldn't complain if they see either case.

Yep. And there are actually a lot more of these attributes we could use, for example marking which arguments are read-only and which are read-write, or which argument is expecting a null-terminated C-string https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html

**Comment by nurupo** [comment]
Too bad we can't use those in the API as they are not really portable.

**Pull request merged**
