### PR TITLE
WIP: video fix

### PR DESCRIPTION
**Pull request by zoff99**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/628)

### CODE REVIEW

**Comment by zoff99** [comment]
work starts at: "WIP: sending part tweaked. works fine"  275678b

**Comment by sudden6** [comment]
@zoff99 please do a `git rebase origin master` to clean up the commit history.

**Comment by zoff99** [comment]
git sucks isn't there a gui for that?

**Comment by zoff99** [comment]
#629

**Comment by nurupo** [comment]
There are GUIs for git.

**Pull request closed without merging**
