### PR TITLE
Refactor PACKET_ID numbers to be more consistant

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/302)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/net_crypto.h, line 78 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/302#-KY5Zg0DtL0Y3So2yPSq:-KY5Zg0DtL0Y3So2yPSr:bp1p2ew) ([raw file](https://github.com/toktok/c-toxcore/blob/fea9901b6eecd9b73fd8f4a8e004e807283a0d2d/toxcore/net_crypto.h#L78)):*
> ```objc
> 
> /* All packets starting with a byte in this range are considered lossless packets. */
> #define PACKET_ID_LOSSLESS_RANGE_START   16
> ```

Changed from 160 to 16, a typo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/302)*

**Comment by GrayHatter** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/net_crypto.h, line 78 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/302#-KY5Zg0DtL0Y3So2yPSq:-KY5a7CMVaKOKWTcXSCW:b-x50q9m) ([raw file](https://github.com/toktok/c-toxcore/blob/fea9901b6eecd9b73fd8f4a8e004e807283a0d2d/toxcore/net_crypto.h#L78)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Changed from 160 to 16, a typo?
</blockquote></details>

fixed, thank you

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/302)*

**Comment by iphydf** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxcore/Messenger.c, line 1741 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/302#-KYBa_hzx6f-jWaJ0n6f:-KYBa_hzx6f-jWaJ0n6g:bdl1gel) ([raw file](https://github.com/toktok/c-toxcore/blob/e0f63918e8f14c82910416090cd7cb36bbb1f0f1/toxcore/Messenger.c#L1741)):*
> ```C
> 
>     if (packet[0] >= PACKET_ID_LOSSY_AV_START && packet[0] <= PACKET_ID_LOSSY_AV_LAST) {
>         uint8_t index = packet[0] % PACKET_AV_BLOCK_SIZE;
> ```

I suggest factoring out `m->friendlist[friend_num].lossy_rtp_packethandlers[index]` as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/302)*

**Comment by GrayHatter** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxcore/Messenger.c, line 1741 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/302#-KYBa_hzx6f-jWaJ0n6f:-KYCsV09AQf1yjev4IzX:b-j08zts) ([raw file](https://github.com/toktok/c-toxcore/blob/e0f63918e8f14c82910416090cd7cb36bbb1f0f1/toxcore/Messenger.c#L1741)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

I suggest factoring out `m->friendlist[friend_num].lossy_rtp_packethandlers[index]` as well.
</blockquote></details>

partially done in the next pull PTAL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/302)*

**Comment by GrayHatter** [comment]
rolled into #282

**Pull request closed without merging**
