### PR TITLE
Don't error on warnings by default

### PR DESCRIPTION
**Pull request by nurupo**
Having `-Werror` set by default causes users' builds to fail because toxcore is not warning-free. Failing on errors is appropriate for the development phase, when running it in CI, but it doesn't make much sense to fail builds for users and let them figure out that they need to pass `-DWARNINGS=OFF` to make the library build.

Also, we should really address these warnings by fixing the code that causes them.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/294)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 75 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/294#-KXc90nh3IlFTmKLd72L:-KXc90nh3IlFTmKLd72M:b-dkssxk) ([raw file](https://github.com/toktok/c-toxcore/blob/363bc02e1b931793b6ac9f5fca54eb68530eec01/CMakeLists.txt#L75)):*
> ```CMake
>   add_cflag("-pedantic")
> 
>   option(ERROR_ON_WARNING "Make compilation error on a warning" OFF)
> ```

Perhaps move this out of the outer if block, so it doesn't depend on extra warnings being disabled. You may want `-Werror` with default warnings (or extra ones set through `CFLAGS`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/294)*

**Comment by iphydf** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/294)*

**Comment by nurupo** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 75 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/294#-KXc90nh3IlFTmKLd72L:-KXcAjj0i95rFCLZ1sBw:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/363bc02e1b931793b6ac9f5fca54eb68530eec01/CMakeLists.txt#L75)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Perhaps move this out of the outer if block, so it doesn't depend on extra warnings being disabled. You may want `-Werror` with default warnings (or extra ones set through `CFLAGS`).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/294)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/294#-:-KXdTzffN_ERhRHLtCPJ:bg7igkv)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/294#-:-KXg27G6Zg8jJQ03L9We:b-jbsf8z)*

**Comment by iphydf** [comment]
There is a really nice reasoning in the PR body. Can you put that into the comment?

**Comment by nurupo** [comment]
Done.

**Pull request merged**
