### PR TITLE
Minor simplification in `file_seek` code.

### PR DESCRIPTION
**Pull request by iphydf**
Details in comments.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/391)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxcore/Messenger.c, line 1331 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/391#-K_nM5BGtfYeEAyY0iDM:-K_nM5BHvStVltHIDc7e:bnpcdke) ([raw file](https://github.com/toktok/c-toxcore/blob/65341c736d812caa3b8ab1daf52eccb40330f28d/toxcore/Messenger.c#L1331)):*
> ```C
>     }
> 
>     uint32_t temp_filenum;
> ```

Can we simplify this and remove some duplicated variables?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/391)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toxcore/Messenger.c, line 1331 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/391#-K_nM5BGtfYeEAyY0iDM:-K_nO8er0n8WbXdpHTim:b-w3ooxz) ([raw file](https://github.com/toktok/c-toxcore/blob/65341c736d812caa3b8ab1daf52eccb40330f28d/toxcore/Messenger.c#L1331)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Can we simplify this and remove some duplicated variables?
</blockquote></details>

Agree. We can change current `filenumber` instead of copying

---

*[toxcore/Messenger.c, line 1337 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/391#-K_nNzNIg6Xth3eL347n:-K_nNzNJaT4SOaHWYhU4:b-adf3m7) ([raw file](https://github.com/toktok/c-toxcore/blob/65341c736d812caa3b8ab1daf52eccb40330f28d/toxcore/Messenger.c#L1337)):*
> ```C
>     } else {
>         // Not receiving.
>         return -4;
> ```

What about early break?
```
if (filenumber < (1 << 16)) {
    // Not receiving
    return -4
}

/* Suggestion:   s/temp_filenum/filenumber/ */
temp_filenum = (filenumber >> 16) - 1; 
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/391)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/Messenger.c, line 1331 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/391#-K_nM5BGtfYeEAyY0iDM:-K_yhNl7Jp0a563aIlpv:buwb8xs) ([raw file](https://github.com/toktok/c-toxcore/blob/beea5082e990380fd3bcfec72eb5bf714ff84eba/toxcore/Messenger.c#L1331)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Agree. We can change current `filenumber` instead of copying
</blockquote></details>

It's not safe to do so.

---

*[toxcore/Messenger.c, line 1337 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/391#-K_nNzNIg6Xth3eL347n:-K_yhrqP_578tjY6Z7Qu:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/beea5082e990380fd3bcfec72eb5bf714ff84eba/toxcore/Messenger.c#L1337)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What about early break?
```
if (filenumber < (1 << 16)) {
    // Not receiving
    return -4
}

/* Suggestion:   s/temp_filenum/filenumber/ */
temp_filenum = (filenumber >> 16) - 1; 
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/391)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/391#-:-Ka0LS7LnSGq4-r8lJUD:bg7igkv)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/391#-:-Ka3qMcuVCCDQFQ5-YMv:b-jbsf8z)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/391#-:-Ka79-teiLJjwWI2NJu7:b-jbsf8z)*

**Comment by nurupo** [comment]
Huh, that's interesting dead code. Why did @irungentoo add the sending else branch in there if it never sends?

:lgtm_strong:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/391#-:-KaJzxf5E05mrCfEF1ef:bcwjefj)*

**Pull request merged**
