### PR TITLE
Revert "Add correction message type"

### PR DESCRIPTION
**Pull request by Diadlo**
This reverts commit e16d3894c5979fcfe1c57bf7dadc455ce690baf9 and
commit c5976e37eaadf663dc3d0c18376ea023355048f3.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/748)

### CODE REVIEW

**Comment by iphydf** [comment]
:lgtm_strong:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/748#-:-L4LTij8V2Ou1LQIG9dG:b-jbsf8z)*

**Comment by iphydf** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/748)*

**Comment by LittleVulpix** [comment]
Out of curiosity, why was this reverted?

**Comment by SkyzohKey** [comment]
Same question as @LittleVulpix

**Comment by Diadlo** [comment]
@LittleVulpix @SkyzohKey Read discussion in #685 from [this comment](https://github.com/TokTok/c-toxcore/pull/685#issuecomment-362378350)

**Comment by LittleVulpix** [comment]
Thanks @Diadlo , yeah I think that's fair - though it would have been better if this was linked in the PR summary (instead of just the fact that it's reverting a commit) so that it would be apparent what the motivation was. Still thanks for the explanation!

**Comment by Diadlo** [comment]
@LittleVulpix Yes, you are right, I'm sorry

**Pull request merged**
