### PR TITLE
Add files generated by global to .gitignore

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/642)

### CODE REVIEW

**Comment by Diadlo** [comment]
Please, use global gitignore for files specific to your editor

**Comment by iphydf** [comment]
I'm not really opposed to this, but don't have a strong opinion in favour.

**Comment by Diadlo** [comment]
I'm against it. User-specific files shouldn't be in the project .gitignore

**Comment by iphydf** [comment]
Ok, let's skip this then. I have no strong opinion, but someone else does, and nobody else weighed in. Reopen if you want to continue the discussion.

**Pull request closed without merging**
