### PR TITLE
Change toxencryptsave API to never overwrite pass keys.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/334)

### CODE REVIEW

**Comment by zetok** [comment]
Formatting could be perhaps improved, but aside from that public API looks fine. :lgtm_strong: 

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxencryptsave/toxencryptsave.h, line 244 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/334#-KZ4jFuXTsO7WjFZRhhQ:-KZ4jFuXTsO7WjFZRhhR:bi306mr) ([raw file](https://github.com/toktok/c-toxcore/blob/970a2ca5dcbc3f4779229d3d8593a095e9de4969/toxencryptsave/toxencryptsave.h#L244)):*
> ```objc
>  *
>  * The Tox_Pass_Key structure is hidden in the implementation. It can be created
>  * using tox_pass_key_derive or tox_pass_key_derive_with_salt and must be deallocated using tox_pass_key_free.
> ```

Formatting? Also functions' args could be formatted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/334#-:-KZ4jRelAICTjvt8RifD:bi7iw7e)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/334#-:-KZ7qDLcrRbMPOzAb1ZB:b-jbsf8z)*

**Comment by iphydf** [comment]
Assigned toxbot to avoid accidentally pushing this since it's green. Also to make it not green so I don't get distracted by green PRs that can't be merged.

**Comment by iphydf** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxencryptsave/toxencryptsave.h, line 244 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/334#-KZ4jFuXTsO7WjFZRhhQ:-K_yi673h5c6BQ_xbIuL:b81tzii) ([raw file](https://github.com/toktok/c-toxcore/blob/970a2ca5dcbc3f4779229d3d8593a095e9de4969/toxencryptsave/toxencryptsave.h#L244)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Formatting? Also functions' args could be formatted.
</blockquote></details>

Formatting needs to be fixed in apidsl. For that, apidsl needs to become smarter and know more about the semantics of a comment. For now, I'd like to leave it like this to keep the .api file nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/334)*

**Comment by robinlinden** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/334)*

**Comment by SkyzohKey** [comment]
Is this PR ready-to-merge ?

**Comment by iphydf** [comment]
It's an API break, so it's waiting for 0.2, which is a bit more than a month away.

---

Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/334#-:-KbFYKCxg0kMXIlppvA3:b-r7tnx9)*

**Comment by robinlinden** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/334)*

**Pull request merged**
