### PR TITLE
Build types for CMake

### PR DESCRIPTION
**Pull request by WarningX**
CMakeLists.txt (cmake) now support release and debug builds.
Extend AddCompilerFlag.cmake about functions that allow easily to add compile flags for different build types. These build types are integrated in the CMakeLists.txt file. This make cmake builds more straight forward.

`cmake -DCMAKE_BUILD_TYPE=Release` optimized build without any warnings. 

`cmake -DCMAKE_BUILD_TYPE=Debug` not optimized build with debug information. Enable all debug Warnings.

`cmake` minimal configuration, no optimization, minimal debug information

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/562)

### CODE REVIEW

**Comment by iphydf** [comment]
I'm a bit confused by this PR. Is it ready for review?

**Comment by WarningX** [comment]
It is ready for review.

**Comment by robinlinden** [comment]
First of all, thank you for the contribution, but I doubt this will get merged. It adds a lot of complexity for, from what I can tell, no benefit.

What's better about this way of doing it?

**Comment by iphydf** [comment]
Here are about 20 commits. We usually have 1 commit per PR. It looks like there are a few separate things here, e.g. documentation. Perhaps it makes sense to split it to make it easier to merge pieces rather than the whole thing.

Separately, please ensure that the indentation of cmake files is correct: 2-space indent per level.

**Comment by iphydf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 81 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/562#-L4RCviwYjzCsAv_93BB:-L4RCviwYjzCsAv_93BC:b-t0v4bh) ([raw file](https://github.com/toktok/c-toxcore/blob/da724c8347718f012597b72dba16fb79bde3e047/CMakeLists.txt#L81)):*
> ```CMake
>   elseif(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
>     set(CMAKE_C_FLAGS_DEBUG "-g3")
>     set(CMAKE_CXX_FLAGS_DEBUG "-g3")
> ```

Also add `-gdwarf-2` for MINGW.

---

*[CMakeLists.txt, line 103 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/562#-L4RDBVKTTk8FRGdSnTx:-L4RDBVKTTk8FRGdSnTy:b-dp8j65) ([raw file](https://github.com/toktok/c-toxcore/blob/da724c8347718f012597b72dba16fb79bde3e047/CMakeLists.txt#L103)):*
> ```CMake
>   
>   # Disable all warnings for release
>   add_release_flag("-w")
> ```

Why completely remove all warnings in release mode?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/562)*

**Comment by iphydf** [comment]
@WarningX can you squash all your commits into one?

**Comment by iphydf** [comment]
@WarningX also, I think travis builds a minimal build now. Is that intentional?

**Comment by iphydf** [comment]
I think the default should be debug. Why is there a minimal configuration?

**Comment by iphydf** [comment]
@WarningX: Why is cmake 3 required?

**Comment by iphydf** [comment]
@WarningX I've fixed the things I noted, but this PR is broken. It sometimes completely forgets all flags, maybe it forgets the build type, I don't know. It happens when you run "make" after making a change to the CMakeLists.txt file. I'm done with this PR for now. I'll keep merging master into it on a best-effort basis, but if I end up changing the build too much so this PR no longer works, I'll close it. I generally like it, but it doesn't work reliably at the moment. Let me know when you have time to help fix it.

**Comment by nurupo** [comment]
You can already use `CMAKE_BUILD_TYPE=Release` or `CMAKE_BUILD_TYPE=Debug` though, [it's cmake's built-in](https://cmake.org/cmake/help/v3.10/variable/CMAKE_BUILD_TYPE.html), it will auto-magically add debug or release flags for everything you build when you specify one of those. I'm confused as to what this PR add on top of that?

**Comment by iphydf** [comment]
Closing conflicting and unmaintained PR. Please reopen if you'd like to discuss it again.

**Pull request closed without merging**
