### PR TITLE
cleanup: Small improvements found by PVS Studio.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2666)

### CODE REVIEW

**Review by nurupo — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2666)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[`toxcore/group_chats.c` line 2601 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2666#-NqAaWEy6g8YE7GVrSrh:-NqAaWEy6g8YE7GVrSri:brqeand) ([raw file](https://github.com/TokTok/c-toxcore/blob/a95803a18f1c1a0321978c3f494ebb40be714f6f/toxcore/group_chats.c#L2601)):*
> ```C
> {
>     static_assert(sizeof(GC_Peer) < 2048, "GC_Peer is too large for stack allocation");
>     GC_Peer self = {0};
> ```

Why is it stack-allocated now and we have the assert in case it the struct becomes too large... that feels like the step in the wrong direction, no?

Is it simply because the heap allocation is unnecessary in here since the object doesn't outlive the function scope, or is there a greater reason for this?

**Review by JFreegman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2666)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nurupo)

___
*[`toxcore/group_chats.c` line 2601 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2666#-NqAaWEy6g8YE7GVrSrh:-NqAdXli7H-Aqp8pJQfS:bui3zcw) ([raw file](https://github.com/TokTok/c-toxcore/blob/a95803a18f1c1a0321978c3f494ebb40be714f6f/toxcore/group_chats.c#L2601)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Why is it stack-allocated now and we have the assert in case it the struct becomes too large... that feels like the step in the wrong direction, no?

Is it simply because the heap allocation is unnecessary in here since the object doesn't outlive the function scope, or is there a greater reason for this?
</blockquote></details>

To add to this, what is the significance of 2048 bytes? I seem to recall that we try to keep stack allocations well below a certain threshold for musl builds but I can't remember what it is.

**Comment by iphydf** [comment]
2048 is half a memory page, so it was a nice round number. I could make the assert check for tox max packet size instead, which is what we frequently stack-allocate everywhere, but there's no relationship between peer struct size and packet size, other than that both can be stack allocated.

**Comment by nurupo** [comment]
Um. Kindly pointing out that my questions weren't rhetorical :D

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2666)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nurupo)

___
*[`toxcore/group_chats.c` line 2601 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2666#-NqAaWEy6g8YE7GVrSrh:-NqKPmUb6mYauKdS-2Oo:b-cqtd21) ([raw file](https://github.com/TokTok/c-toxcore/blob/a95803a18f1c1a0321978c3f494ebb40be714f6f/toxcore/group_chats.c#L2601)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

To add to this, what is the significance of 2048 bytes? I seem to recall that we try to keep stack allocations well below a certain threshold for musl builds but I can't remember what it is.
</blockquote></details>

musl builds can't have stacks larger than 131072 bytes. So if we have a call stack 64 levels deep, and every level allocates 2KB, then we run out on musl.

Indeed it's just because the object doesn't outlive the function scope.

**Review by nurupo — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2666)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Pull request merged**
