### PR TITLE
feat: Merge moderation portion of new groupchats codebase

### PR DESCRIPTION
**Pull request by JFreegman**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2168)

### CODE REVIEW

**Review by iphydf — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2168)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[toxcore/group_moderation.c, line 29 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhZwjgDaCibYYTysNW:-MyhZwjgDaCibYYTysNX:bk5isb6) ([raw file](https://github.com/toktok/c-toxcore/blob/ce1cc36b0c62736e42fdbefb1c29dba64619cd07/toxcore/group_moderation.c#L29)):*
> ```C
> 
> static_assert(MOD_SANCTIONS_CREDS_SIZE <= 49900,
>               "MOD_SANCTIONS_CREDS_SIZE must be <= 49900");
> ```

That's what the expression says, but is there a reason for it?
___
*[toxcore/group_moderation.c, line 31 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myh_---4ZIq8MNi3GFN:-Myh_---4ZIq8MNi3GFO:bbwh3l7) ([raw file](https://github.com/toktok/c-toxcore/blob/ce1cc36b0c62736e42fdbefb1c29dba64619cd07/toxcore/group_moderation.c#L31)):*
> ```C
>               "MOD_SANCTIONS_CREDS_SIZE must be <= 49900");
> static_assert(MOD_MAX_NUM_SANCTIONS * MOD_SANCTION_PACKED_SIZE + MOD_SANCTIONS_CREDS_SIZE <= 49900,
>               "MOD_MAX_NUM_SANCTIONS must be abel to fit inside the maximum allowed payload size)");
> ```

"able"
___
*[toxcore/group_moderation.c, line 37 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myh_MYp2kkN7wrjlBMx:-Myh_MYp2kkN7wrjlBMy:bdz5lk4) ([raw file](https://github.com/toktok/c-toxcore/blob/ce1cc36b0c62736e42fdbefb1c29dba64619cd07/toxcore/group_moderation.c#L37)):*
> ```C
> int mod_list_unpack(Moderation *moderation, const uint8_t *data, uint16_t length, uint16_t num_mods)
> {
>     if (length < num_mods * MOD_LIST_ENTRY_SIZE || num_mods > MOD_MAX_NUM_MODERATORS) {
> ```

Is `length` sometimes `> num_mods * MOD_LIST_ENTRY_SIZE`?
___
*[toxcore/group_moderation.c, line 47 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myh_U_cADej5FQCokQQ:-Myh_U_cADej5FQCokQR:b-93v63g) ([raw file](https://github.com/toktok/c-toxcore/blob/ce1cc36b0c62736e42fdbefb1c29dba64619cd07/toxcore/group_moderation.c#L47)):*
> ```C
>     }
> 
>     uint8_t **tmp_list = (uint8_t **)calloc(num_mods, sizeof(uint8_t *));
> ```

`calloc` needs `<stdlib.h>`.
___
*[toxcore/group_moderation.c, line 80 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myh_soX9qJs6K3WsL5x:-Myh_soX9qJs6K3WsL5y:bgolivh) ([raw file](https://github.com/toktok/c-toxcore/blob/ce1cc36b0c62736e42fdbefb1c29dba64619cd07/toxcore/group_moderation.c#L80)):*
> ```C
> }
> 
> void mod_list_get_data_hash(uint8_t *hash, const uint8_t *packed_mod_list, size_t length)
> ```

I'd like to avoid using `size_t` going forward, since it's platform dependent. Which `uint??_t` is most appropriate here?
___
*[toxcore/group_moderation.c, line 82 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhnYLJ3E-ygMdDQ-z-:-MyhnYLJ3E-ygMdDQ-z0:b-478m55) ([raw file](https://github.com/toktok/c-toxcore/blob/ce1cc36b0c62736e42fdbefb1c29dba64619cd07/toxcore/group_moderation.c#L82)):*
> ```C
> void mod_list_get_data_hash(uint8_t *hash, const uint8_t *packed_mod_list, size_t length)
> {
>     crypto_hash_sha256(hash, packed_mod_list, length);
> ```

`crypto_core` has a function wrapping this one.
___
*[toxcore/group_moderation.c, line 252 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhaO9G1XQjbuu9S2lf:-MyhaO9G1XQjbuu9S2lg:btcvkww) ([raw file](https://github.com/toktok/c-toxcore/blob/ce1cc36b0c62736e42fdbefb1c29dba64619cd07/toxcore/group_moderation.c#L252)):*
> ```C
>     uint16_t packed_len = 0;
> 
>     for (uint16_t i = 0; i < num_sanctions && i < MOD_MAX_NUM_SANCTIONS; ++i) {
> ```

What happens to the other sanctions that aren't packed? When does that happen?
___
*[toxcore/group_moderation.c, line 308 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhahdgEnjo7gAmhGl8:-MyhahdgEnjo7gAmhGl9:bjrphtg) ([raw file](https://github.com/toktok/c-toxcore/blob/ce1cc36b0c62736e42fdbefb1c29dba64619cd07/toxcore/group_moderation.c#L308)):*
> ```C
> 
>     net_unpack_u32(data + len_processed, &creds->version);
>     len_processed += sizeof(uint32_t);
> ```

You could do `len_processed += net_unpack_...`. Is that a good idea?
___
*[toxcore/group_moderation.c, line 757 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhnPDz1eDVy3QeLOow:-MyhnPDz1eDVy3QeLOox:bk3u35e) ([raw file](https://github.com/toktok/c-toxcore/blob/ce1cc36b0c62736e42fdbefb1c29dba64619cd07/toxcore/group_moderation.c#L757)):*
> ```C
>     }
> 
>     return crypto_sign_detached(sanction->signature, nullptr, packed_data, packed_len - SIGNATURE_SIZE,
> ```

Let's make `crypto_core` functions for these, so we can disable them in fuzzing.

**Review by iphydf — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2168)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[toxcore/group_moderation.c, line 261 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhsPXz2v4aEZcmf2oi:-MyhsPXz2v4aEZcmf2oj:bro466v) ([raw file](https://github.com/toktok/c-toxcore/blob/ce1cc36b0c62736e42fdbefb1c29dba64619cd07/toxcore/group_moderation.c#L261)):*
> ```C
>         memcpy(data + packed_len, sanctions[i].setter_public_sig_key, SIG_PUBLIC_KEY_SIZE);
>         packed_len += SIG_PUBLIC_KEY_SIZE;
>         net_pack_u64(data + packed_len, sanctions[i].time_set);
> ```

How soon after creating a sanction do we send the system time over the network?
___
*[toxcore/group_moderation.c, line 569 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myhrj5I15j4sX4fb0RM:-Myhrj5I15j4sX4fb0RN:b-4nnx38) ([raw file](https://github.com/toktok/c-toxcore/blob/ce1cc36b0c62736e42fdbefb1c29dba64619cd07/toxcore/group_moderation.c#L569)):*
> ```C
> static bool sanctions_list_remove_index(Moderation *moderation, uint16_t index, const Mod_Sanction_Creds *creds)
> {
>     if (index >= moderation->num_sanctions || moderation->num_sanctions == 0) {
> ```

The lhs of this `||` is always true if the rhs is true, so the rhs is not needed.

**Review by JFreegman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2168)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[toxcore/group_moderation.h, line 33 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhnsWB61m5uJtnSpDS:-MyhxuLp7ykmA2UnXpc0:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.h#L33)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

This 49900 number appears a lot. Maybe it should get a name?
</blockquote></details>

Done.
___
*[toxcore/group_moderation.h, line 70 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myho61b7FnrA4VrGpKM:-Myhy0PM1uRUbh5hRGeX:br90gr) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.h#L70)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

We should probably agree on a naming standard for "array with size". In this struct, we have 2 standards: `$name with num_$name` and `${name}_list with num_${name}s`. In other places, we have `$name with ${name}_length` or `$name with ${name}_size`. Which standard should we pick?
</blockquote></details>

I like $name with ${name}_size. With that said, I don't think that should be done in this PR because it requires changes in group_chats.c. We can make an issue for it.
___
*[toxcore/group_moderation.h, line 90 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhorXpCzFa5C4PCtBl:-Myhz_ufBGW5p8UnPxe9:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.h#L90)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

It might be worth adding a `mod_list_packed_size` function to help compute this number.
</blockquote></details>

Done.
___
*[toxcore/group_moderation.h, line 97 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhpKDr7v4d_LYKoW1T:-Myhzel11E0K1buS74H5:b-gvgtv6) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.h#L97)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Where is `GC_MOD_LIST_HASH_SIZE` defined?
</blockquote></details>

Done. Outdated comment.
___
*[toxcore/group_moderation.c, line 29 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhZwjgDaCibYYTysNW:-Myi-YGM8s6FQQGUYtSZ:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L29)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

That's what the expression says, but is there a reason for it?
</blockquote></details>

Done.
___
*[toxcore/group_moderation.c, line 31 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myh_---4ZIq8MNi3GFN:-Myi-avEC8mxBtE0bmrQ:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L31)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

"able"
</blockquote></details>

Done.
___
*[toxcore/group_moderation.c, line 37 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myh_MYp2kkN7wrjlBMx:-Myi-lcLBaeJJIijaLNg:b-35ju0i) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L37)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Is `length` sometimes `> num_mods * MOD_LIST_ENTRY_SIZE`?
</blockquote></details>

It shouldn't be but it's not impossible. Assert instead?
___
*[toxcore/group_moderation.c, line 47 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myh_U_cADej5FQCokQQ:-Myi-x7D1gtnIdPcoX-K:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L47)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

`calloc` needs `<stdlib.h>`.
</blockquote></details>

Done.
___
*[toxcore/group_moderation.c, line 75 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myhq1Jv--JZ46rHH24j:-Myi0I4JCeIXHLR8_vvv:blgjiuf) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L75)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

This line mildly disagrees with the comment in the header. Is it necessary to have this (silent) max num moderator stuff everywhere? I'd rather make it an invariant, check it in the places that might do things to violate it, and assert it elsewhere where we rely on it.
</blockquote></details>

Done. Not really necessary as long as we never allow that value to be exceeded when adding to the list.
___
*[toxcore/group_moderation.c, line 80 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myh_soX9qJs6K3WsL5x:-Myi0Y4d1t0dG_38-8kR:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L80)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

I'd like to avoid using `size_t` going forward, since it's platform dependent. Which `uint??_t` is most appropriate here?
</blockquote></details>

Done.
___
*[toxcore/group_moderation.c, line 82 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhnYLJ3E-ygMdDQ-z-:-Myi1owO66sHCqM8pcYz:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L82)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

`crypto_core` has a function wrapping this one.
</blockquote></details>

Done.
___
*[toxcore/group_moderation.c, line 252 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhaO9G1XQjbuu9S2lf:-Myi25RI7FrlKEEPow-Z:b-pgn751) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L252)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

What happens to the other sanctions that aren't packed? When does that happen?
</blockquote></details>

Done. Removed the limit.
___
*[toxcore/group_moderation.c, line 261 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhsPXz2v4aEZcmf2oi:-Myi2BO8E9raB_XOnVeW:b-3fwjhg) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L261)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

How soon after creating a sanction do we send the system time over the network?
</blockquote></details>

Within at least the next call to `tox_iterate()`. Should be noted this isn't used currently, but it's easier to leave it in than take it out and add it back later.
___
*[toxcore/group_moderation.c, line 308 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhahdgEnjo7gAmhGl8:-Myi2aFH4oClfZ81lwqQ:b-tatnyu) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L308)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

You could do `len_processed += net_unpack_...`. Is that a good idea?
</blockquote></details>

I could. But if we go that route I think we should do it uniformly throughout toxcore in a separate PR.
___
*[toxcore/group_moderation.c, line 569 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myhrj5I15j4sX4fb0RM:-Myi3mQZ1hA2fHEqtpu_:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L569)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

The lhs of this `||` is always true if the rhs is true, so the rhs is not needed.
</blockquote></details>

Done.
___
*[toxcore/group_moderation.c, line 757 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhnPDz1eDVy3QeLOow:-Myi7alG2Ym4NbwDpybQ:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L757)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Let's make `crypto_core` functions for these, so we can disable them in fuzzing.
</blockquote></details>

Done.

**Review by iphydf — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2168)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf and @JFreegman)

___
*[toxcore/group_moderation.c, line 37 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myh_MYp2kkN7wrjlBMx:-MyiHEgCEYAvoT77qTBr:b-9hvggo) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L37)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

It shouldn't be but it's not impossible. Assert instead?
</blockquote></details>

What about `if (length != ...) { return -1; }`?
___
*[toxcore/group_moderation.c, line 75 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-Myhq1Jv--JZ46rHH24j:-MyiHWEhCZxq7WuuEnx6:b-ji7jx4) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L75)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Done. Not really necessary as long as we never allow that value to be exceeded when adding to the list.
</blockquote></details>

In theory, this pack function works just fine with any number of mods. The sizing function above gives the correct byte size, so it'll work.
___
*[toxcore/group_moderation.c, line 252 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhaO9G1XQjbuu9S2lf:-MyiHw09AouHxKcGKYNR:b-1p3jbb) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L252)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Done. Removed the limit.
</blockquote></details>

Might still want to `return -1` on invalid `num_sanctions`. E.g. if `num_sanctions == 10000`, this function will overflow `packed_len`.
___
*[toxcore/group_moderation.c, line 261 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyhsPXz2v4aEZcmf2oi:-MyiIGRe7Fu3y9qTkzZg:bjcxuwr) ([raw file](https://github.com/toktok/c-toxcore/blob/9cbeeec368c6e162ad9e3628c5e8d7c02fad43e7/toxcore/group_moderation.c#L261)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Within at least the next call to `tox_iterate()`. Should be noted this isn't used currently, but it's easier to leave it in than take it out and add it back later.
</blockquote></details>

Then we should make sure to tell users that mods who set (many) sanctions can be tracked across groups and across tox IDs.
___
*[toxcore/group_moderation.c, line 13 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyiHKx1CMcAeR0AmAIZ:-MyiHKx1CMcAeR0AmAI_:b-7mo7f4) ([raw file](https://github.com/toktok/c-toxcore/blob/fa84ea34668dd106d955a863fc3cfbe5a77cd28d/toxcore/group_moderation.c#L13)):*
> ```C
> 
> #include <assert.h>
> ```

Remove empty line.
___
*[toxcore/group_moderation.c, line 30 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyiH6qt3Ksn6hyvUglM:-MyiH6qt3Ksn6hyvUglN:b6pg09d) ([raw file](https://github.com/toktok/c-toxcore/blob/fa84ea34668dd106d955a863fc3cfbe5a77cd28d/toxcore/group_moderation.c#L30)):*
> ```C
>               "MOD_MAX_NUM_SANCTIONS must be able to fit inside the maximum allowed payload size)");
> static_assert(MOD_MAX_NUM_MODERATORS * MOD_LIST_ENTRY_SIZE <= MAX_PACKET_SIZE_NO_HEADERS,
>               "MOD_MAX_NUM_MODERATORS must be able to fit insize the maximum allowed payload size)");
> ```

Each of these has a ")" at the end of the string. Probably not intentional.
___
*[toxcore/group_moderation.c, line 32 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2168#-MyiHjj5C1IMPQMpgU_t:-MyiHjj5C1IMPQMpgU_u:bzdyr6v) ([raw file](https://github.com/toktok/c-toxcore/blob/fa84ea34668dd106d955a863fc3cfbe5a77cd28d/toxcore/group_moderation.c#L32)):*
> ```C
>               "MOD_MAX_NUM_MODERATORS must be able to fit insize the maximum allowed payload size)");
> 
> uint16_t mod_list_packed_size(const Moderation *moderation)
> ```

nit: move this to right above `mod_list_pack`, because that's the function it's associated with (same in the header file).

**Pull request closed without merging**
