### PR TITLE
 Make Net_Crypto a module-private type.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/689)

### CODE REVIEW

**Comment by endoffile78** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[auto_tests/onion_test.c, line 482 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rWfTUv9Trz5TLS5HK:-L2rWfTVidis1ByQHJrf:b37fi1s) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/auto_tests/onion_test.c#L482)):*
> ```C
>     printf("adding friend\n");
>     int frnum_f = onion_addfriend(onions[NUM_FIRST]->onion_c,
>                                   nc_get_self_secret_key(onion_get_net_crypto(onions[NUM_LAST]->onion_c)));
> ```

You are passing`self_secret_key` when you should be passing `self_public_key`

---

*[auto_tests/onion_test.c, line 484 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rWqxqsgbF-bZPNM51:-L2rWqxqsgbF-bZPNM52:b37fi1s) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/auto_tests/onion_test.c#L484)):*
> ```C
>                                   nc_get_self_secret_key(onion_get_net_crypto(onions[NUM_LAST]->onion_c)));
>     int frnum = onion_addfriend(onions[NUM_LAST]->onion_c,
>                                 nc_get_self_secret_key(onion_get_net_crypto(onions[NUM_FIRST]->onion_c)));
> ```

You are passing`self_secret_key` when you should be passing `self_public_key`

---

*[toxcore/onion_client.c, line 591 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rY-7OWqsKkAEB7ybG:-L2rY-7Pqv91r5dZFV5x:b-hv7s3z) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L591)):*
> ```C
>     if (num == 0) {
>         len = create_announce_request(request, sizeof(request), dest_pubkey, nc_get_self_public_key(onion_c->c),
>                                       nc_get_self_public_key(onion_c->c), ping_id, nc_get_self_public_key(onion_c->c),
> ```

The second `nc_get_self_public_key` should be `nc_get_self_secret_key`

---

*[toxcore/onion_client.c, line 851 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rYH4L8gJIJcbmaQoN:-L2rYH4L8gJIJcbmaQoO:bxxx5r2) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L851)):*
> ```C
> 
>     if (num == 0) {
>         len = decrypt_data(public_key, nc_get_self_public_key(onion_c->c),
> ```

You are passing the public key when you need to be passing the secret key.

---

*[toxcore/onion_client.c, line 918 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rYPkfSguJpTDMc6zu:-L2rYPkfSguJpTDMc6zv:bjfbemo) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L918)):*
> ```C
> 
>     VLA(uint8_t, plain, SIZEOF_VLA(temp_plain) - DATA_IN_RESPONSE_MIN_SIZE);
>     len = decrypt_data(temp_plain, nc_get_self_public_key(onion_c->c),
> ```

You are passing the public key when you need to be passing the secret key

---

*[toxcore/onion_client.c, line 1072 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rYZQbYy2GEn7tOQtt:-L2rYZQbYy2GEn7tOQtu:bm7pu1e) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L1072)):*
> ```C
>     memcpy(packet, nc_get_self_public_key(onion_c->c), CRYPTO_PUBLIC_KEY_SIZE);
>     int len = encrypt_data(onion_c->friends_list[friend_num].real_public_key,
>                            nc_get_self_public_key(onion_c->c), nonce, data,
> ```

You are passing the public key when you should be passing the secret key.

---

*[toxcore/onion_client.c, line 1128 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rYfQMo7Rwo_pH389W:-L2rYfQMo7Rwo_pH389X:bm7pu1e) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L1128)):*
> ```C
>     memcpy(temp + CRYPTO_PUBLIC_KEY_SIZE, nonce, CRYPTO_NONCE_SIZE);
>     int len = encrypt_data(onion_c->friends_list[friend_num].real_public_key,
>                            nc_get_self_public_key(onion_c->c), nonce, data,
> ```

You are passing the public key when you should be passing the secret key.

---

*[toxcore/onion_client.c, line 1160 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rYgrbhLTVUqC4ArI_:-L2rYgrbhLTVUqC4ArIa:bm7pu1e) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L1160)):*
> ```C
> 
>     uint8_t plain[DHTPK_DATA_MAX_LENGTH];
>     int len = decrypt_data(packet, nc_get_self_public_key(onion_c->c),
> ```

You are passing the public key when you should be passing the secret key.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/689)*

**Comment by sudden6** [comment]
besides @endoffile78 remarks, :lgtm_strong: 

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-:-L2tr4Q4_G0zwBiIJIU7:bzcibe8)*

**Comment by iphydf** [comment]
Review status: 3 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[auto_tests/onion_test.c, line 482 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rWfTUv9Trz5TLS5HK:-L2wKJxU5JmMqMsWghBV:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/auto_tests/onion_test.c#L482)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

You are passing`self_secret_key` when you should be passing `self_public_key`
</blockquote></details>

Done.

---

*[auto_tests/onion_test.c, line 484 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rWqxqsgbF-bZPNM51:-L2wKKUGS1QyhKsa1nha:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/auto_tests/onion_test.c#L484)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

You are passing`self_secret_key` when you should be passing `self_public_key`
</blockquote></details>

Done.

---

*[toxcore/onion_client.c, line 591 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rY-7OWqsKkAEB7ybG:-L2wKM3i4Or6mpHw9tai:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L591)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

The second `nc_get_self_public_key` should be `nc_get_self_secret_key`
</blockquote></details>

Done.

---

*[toxcore/onion_client.c, line 851 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rYH4L8gJIJcbmaQoN:-L2wKN63oSTx7CAJ1Owg:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L851)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

You are passing the public key when you need to be passing the secret key.
</blockquote></details>

Done.

---

*[toxcore/onion_client.c, line 918 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rYPkfSguJpTDMc6zu:-L2wKNx9FNCUyddjX_WY:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L918)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

You are passing the public key when you need to be passing the secret key
</blockquote></details>

Done.

---

*[toxcore/onion_client.c, line 1072 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rYZQbYy2GEn7tOQtt:-L2wKOi6AMqJOEoeQeZ2:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L1072)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

You are passing the public key when you should be passing the secret key.
</blockquote></details>

Done.

---

*[toxcore/onion_client.c, line 1128 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rYfQMo7Rwo_pH389W:-L2wKPQsOn6veK9vra1p:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L1128)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

You are passing the public key when you should be passing the secret key.
</blockquote></details>

Done.

---

*[toxcore/onion_client.c, line 1160 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rYgrbhLTVUqC4ArI_:-L2wKQBY9RhJHtJrR2-U:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L1160)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

You are passing the public key when you should be passing the secret key.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/689)*

**Comment by endoffile78** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/onion_client.c, line 1128 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rYfQMo7Rwo_pH389W:-L2wLb36g3Vr9y_IBFUq:b-4eh7bj) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L1128)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This one wasn't fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/689)*

**Comment by iphydf** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/onion_client.c, line 1128 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-L2rYfQMo7Rwo_pH389W:-L2zdZOkyO1F6Nb6qiFw:bk5zzkm) ([raw file](https://github.com/toktok/c-toxcore/blob/c5e68428bf78d71a4f42fd725f019362245cd5ca/toxcore/onion_client.c#L1128)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

This one wasn't fixed.
</blockquote></details>

\*siiiiigh\* done.

Don't do many things at the same time, especially not unrelated things. This is iphy being bad at multitasking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/689)*

**Comment by endoffile78** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/689#-:-L2zrex9wq9stIczUvDH:b-jbsf8z)*

**Pull request merged**
