### PR TITLE
cleanup: const a few tox pointers for groupchat API

### PR DESCRIPTION
**Pull request by JFreegman**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2379)

### CODE REVIEW

**Review by Green-Sky — COMMENTED** [review]
:lgtm_strong:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2379#-:-NRxib7d5wO9axnz8baU:b-jbsf8z)* status: 0 of 1 approvals obtained

**Review by iphydf — CHANGES_REQUESTED** [review]
@robinlinden pointed out, correctly, that we tend to use `const` in the public API to mean deep-immutable. What do you think? Should all Tox parameters be `const` everywhere?

**Comment by JFreegman** [comment]
> @robinlinden pointed out, correctly, that we tend to use `const` in the public API to mean deep-immutable. What do you think? Should all Tox parameters be `const` everywhere?

Is there ever a valid reason for it not to be const?

**Comment by iphydf** [comment]
If we only make the tox functions const that don't modify things inside the tox state, then it helps client code ensure that if they pass a `const Tox*` anywhere, then no mutations on internal state will happen.

**Comment by iphydf** [comment]
@JFreegman I think the documentation aspect of "const means no changes happen to the object" in a broad sense is useful in the public API. Maybe someday I'll write a linter to enforce something like that, but I'm not sure what the syntax and semantics of that should be.

**Comment by iphydf** [comment]
Closing this for now. Reopen if you want to discuss reasoning for what "const" should express in the public API.

**Pull request closed without merging**
