### PR TITLE
refactor: Make tox mutex non-recursive.

### PR DESCRIPTION
**Pull request by iphydf**
Instead, unlock it before entering client callback code.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2652)

### CODE REVIEW

**Review by robinlinden — APPROVED** [review]
Guess we're missing a test that sets the conference title and a test that actually uses the experimental thread safety option?

**Review by nurupo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2652)* status: <span>:shipit:</span> complete! 1 change requests, 1 of 1 approvals obtained (waiting on @iphydf)

___
*[`toxcore/tox.c` line 89 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2652#-Nq50bo92qh3rlrXTsVa:-Nq50bo92qh3rlrXTsVb:baa0kmj) ([raw file](https://github.com/TokTok/c-toxcore/blob/a18412aeb4c027fcab21f28c726c42581131f6a5/toxcore/tox.c#L89)):*
> ```C
> 
>     if (tox->log_callback != nullptr) {
>         tox->log_callback(tox, (Tox_Log_Level)level, file, line, func, message, userdata);
> ```

Is locking not needed here?

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2652)* status: <span>:shipit:</span> complete! 1 change requests, 1 of 1 approvals obtained (waiting on @nurupo)

___
*[`toxcore/tox.c` line 89 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2652#-Nq50bo92qh3rlrXTsVa:-Nq516kTEGFitA-etZg5:bulz42n) ([raw file](https://github.com/TokTok/c-toxcore/blob/a18412aeb4c027fcab21f28c726c42581131f6a5/toxcore/tox.c#L89)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Is locking not needed here?
</blockquote></details>

More accurately, unlocking is not needed here. The log callback happens in really any kind of situation, and client could should never call tox functions inside the log callback.

**Comment by nurupo** [comment]
*[`toxcore/tox.c` line 89 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2652#-Nq50bo92qh3rlrXTsVa:-Nq54-Yi7JIcU1B1TY_c:b-c9z5io) ([raw file](https://github.com/TokTok/c-toxcore/blob/a18412aeb4c027fcab21f28c726c42581131f6a5/toxcore/tox.c#L89)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

More accurately, unlocking is not needed here. The log callback happens in really any kind of situation, and client could should never call tox functions inside the log callback.
</blockquote></details>

Is this documented somewhere? I don't see a mentioning of this where the callback is defined in tox.h.

Also, for what purpose does the callback pass `Tox *tox` to the user if it's not to be used? (I guess to use of operator== on `tox` against some other Tox instance might be a valid use-case?)

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2652)* status: <span>:shipit:</span> complete! 1 change requests, 1 of 1 approvals obtained (waiting on @nurupo)

___
*[`toxcore/tox.c` line 89 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2652#-Nq50bo92qh3rlrXTsVa:-Nq56ubt6u_YL-ZjOjJR:b5wzyeh) ([raw file](https://github.com/TokTok/c-toxcore/blob/a18412aeb4c027fcab21f28c726c42581131f6a5/toxcore/tox.c#L89)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Is this documented somewhere? I don't see a mentioning of this where the callback is defined in tox.h.

Also, for what purpose does the callback pass `Tox *tox` to the user if it's not to be used? (I guess to use of operator== on `tox` against some other Tox instance might be a valid use-case?)
</blockquote></details>

Passing Tox to log callbacks was a mistake. Added a comment to the log_callback docs.

**Comment by nurupo** [comment]
*[`toxcore/tox.c` line 89 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2652#-Nq50bo92qh3rlrXTsVa:-Nq59BLKAp-roqfC8-FE:b-2gnaj7) ([raw file](https://github.com/TokTok/c-toxcore/blob/a18412aeb4c027fcab21f28c726c42581131f6a5/toxcore/tox.c#L89)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Passing Tox to log callbacks was a mistake. Added a comment to the log_callback docs.
</blockquote></details>

Do we want to remove `Tox *tox` from `tox_log_cb` when we break the API in the future? If so, might be worth noting this somewhere so that we don't forget, e.g. create an issue mentioning it or add a note to `tox_log_cb` tox.h for ourselves.

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2652)* status: <span>:shipit:</span> complete! 1 change requests, 1 of 1 approvals obtained (waiting on @nurupo)

___
*[`toxcore/tox.c` line 89 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2652#-Nq50bo92qh3rlrXTsVa:-Nq5B0jJ0Khtcc0JRs_C:b-896fix) ([raw file](https://github.com/TokTok/c-toxcore/blob/a18412aeb4c027fcab21f28c726c42581131f6a5/toxcore/tox.c#L89)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Do we want to remove `Tox *tox` from `tox_log_cb` when we break the API in the future? If so, might be worth noting this somewhere so that we don't forget, e.g. create an issue mentioning it or add a note to `tox_log_cb` tox.h for ourselves.
</blockquote></details>

Done.

**Review by nurupo — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2652)* status: <span>:shipit:</span> complete! 2 of 1 approvals obtained

**Pull request merged**
