### PR TITLE
Add projects link to Readme.

### PR DESCRIPTION
**Pull request by SkyzohKey**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/616)

### CODE REVIEW

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/616#-:-KzN-kmAMPNd9exnkkWW:b-jbsf8z)*

**Comment by fcore117** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/616)*

**Comment by zoff99** [comment]
what about:
https://github.com/zoff99/java_toxclient_example
and
https://github.com/zoff99/ToxBlinkenwall
?

**Comment by zoff99** [comment]
@SkyzohKey can you also but it here:
image

**Comment by zoff99** [comment]
@SkyzohKey but where should that list be? can you start something?

**Comment by SkyzohKey** [comment]
@zoff99 On it's own repo, like ie. https://github.com/enaqx/awesome-react :)

**Comment by iphydf** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/616#-:-L1ZZFMrRv6uRjCTUQC_:b-jbsf8z)*

**Pull request merged**
