### PR TITLE
Clarify/Improve test_some test

### PR DESCRIPTION
**Pull request by hugbubby**
Same thing as last time, another mild pull request as I go. A few better error messages, more logical sleep() call placements, comments, etc. For one of the test_basic functions I randomized the time between messages and the sizes in which portions of message are sent, for more coverage. 

Did not modify large chunk of the test_some function because I didn't understand the second half of it. Maybe I'll come back later once I've figured out what it's doing.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/922)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[auto_tests/TCP_test.c, line 110 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_-eZLBLu-c66KIlvi:-LF_-eZLBLu-c66KIlvj:b89xvcb) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L110)):*
> ```C
>                   "The attempt to send the last byte of handshake failed.");
> 
>     c_sleep(100);
> ```

Why 100?

---

*[auto_tests/TCP_test.c, line 118 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_-kEIBPtuGjlzyIJd:-LF_-kEIBPtuGjlzyIJe:b-reesj2) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L118)):*
> ```C
>     uint8_t response_plain[TCP_HANDSHAKE_PLAIN_SIZE];
>     ck_assert_msg(net_recv(sock, response, TCP_SERVER_HANDSHAKE_SIZE) == TCP_SERVER_HANDSHAKE_SIZE,
>                   "Could/Did not receive a server response to the initial handshake.");
> ```

nit: "did" lowercase.

---

*[auto_tests/TCP_test.c, line 140 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_-qFt0iRP6J3n06Pj:-LF_-qFt0iRP6J3n06Pk:b8phnkc) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L140)):*
> ```C
>     uint32_t i = 0;
> 
>     while (i < sizeof(r_req)) {
> ```

`for (uint32_t i = 0; i < sizeof(r_req);) { ...`

This limits the scope of `i` to the loop.

---

*[auto_tests/TCP_test.c, line 141 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_04aU5p1FqjHveOUK:-LF_04aU5p1FqjHveOUL:b-nyj3if) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L141)):*
> ```C
> 
>     while (i < sizeof(r_req)) {
>         uint8_t msg_length = rand() % 5 + 1; // msg_length = 1-5
> ```

1-5 = -4. What you mean is: msg_length is between 1 and 5.

---

*[auto_tests/TCP_test.c, line 151 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_0Gi22ZA_gggUpnmk:-LF_0Gi22ZA_gggUpnml:b-ljyrlq) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L151)):*
> ```C
>         i += msg_length;
> 
>         c_sleep(rand() % 10 + 45); // Wait 45-55 milliseconds
> ```

Why the random jitter?

---

*[auto_tests/TCP_test.c, line 155 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_0T9_1S1mXaPIEJsl:-LF_0T9_1S1mXaPIEJsm:b-oegvto) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L155)):*
> ```C
>     }
> 
>     // Receiving the second resonse and verifying its validity
> ```

"response"

---

*[auto_tests/TCP_test.c, line 173 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_0ZfyAjpT88m1Sn9w:-LF_0ZfyAjpT88m1Sn9x:bjxlzyw) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L173)):*
> ```C
>     ck_assert_msg(public_key_cmp(packet_resp_plain + 2, f_public_key) == 0, "Server sent the wrong public key.");
> 
>     //Closing connections.
> ```

nit: space after `//`

---

*[auto_tests/TCP_test.c, line 316 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_0lRwAxq6-DTCnkHk:-LF_0lRwAxq6-DTCnkHl:bundc16) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L316)):*
> ```C
>     ck_assert_msg(public_key_cmp(data + 2, con1->public_key) == 0, "Key in response packet wrong.");
> 
>     uint8_t test_packet[512] = {16, 17, 16, 86, 99, 127, 255, 189, 78}; //What is this packet????
> ```

No idea :). @irungentoo: do you remember what this packet means?

---


*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/922)*

**Comment by hugbubby** [comment]
Fixed all the comments. Will push in a bit. The jitter was some dumb useless idea I don't remember the reason for.

Question - Are these sleep(50) calls inbetween sending and receiving even necessary? We're literally operating the both the server and the client in the same C program. Why can't we just do net_send() and do_TCP_server() one right after another?

**Comment by hugbubby** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[auto_tests/TCP_test.c, line 110 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_-eZLBLu-c66KIlvi:-LFaiMKZA9eHOqTBnfEi:b9aqios) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L110)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Why 100?
</blockquote></details>

Old file did it.

---

*[auto_tests/TCP_test.c, line 140 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_-qFt0iRP6J3n06Pj:-LFahulb6aC5Jzuv6W90:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L140)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

`for (uint32_t i = 0; i < sizeof(r_req);) { ...`

This limits the scope of `i` to the loop.
</blockquote></details>

Done.

---

*[auto_tests/TCP_test.c, line 141 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_04aU5p1FqjHveOUK:-LFahvYr4W65UePCf-GU:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L141)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

1-5 = -4. What you mean is: msg_length is between 1 and 5.
</blockquote></details>

Done.

---

*[auto_tests/TCP_test.c, line 151 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_0Gi22ZA_gggUpnmk:-LFai-Tp6j2TMPOhhShh:bxz1j0f) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L151)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Why the random jitter?
</blockquote></details>

Idk, dumb idea to RANDOMIZE TIME BETWEEN SENDS

EXTRA DURABILITY

---

*[auto_tests/TCP_test.c, line 155 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_0T9_1S1mXaPIEJsl:-LFai4r28ZmtAv5Gwwc3:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L155)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

"response"
</blockquote></details>

Done.

---

*[auto_tests/TCP_test.c, line 316 at r1](https://reviewable.io/reviews/toktok/c-toxcore/922#-LF_0lRwAxq6-DTCnkHk:-LFaiGEhAk2BtRg-rS2D:b-duwd8h) ([raw file](https://github.com/toktok/c-toxcore/blob/7246a0acd48fbb9405b880d1b5c2f2143eba13fc/auto_tests/TCP_test.c#L316)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

No idea :). @irungentoo: do you remember what this packet means?
</blockquote></details>

Imagine being such a chad you directly read and write packets in raw uint8 arrays

---


*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/922)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/922#-:-LFd2I-g3kExcVTnZV-T:b-jbsf8z)*

**Pull request merged**
