### PR TITLE
fix: reduce memory usage in group chats by 75%

### PR DESCRIPTION
**Pull request by Green-Sky**
Significantly reduced the memory usage of groups since all message slots are preallocated for every peer for send and receive buffers of buffer size (hundreds of MiB **peak** when save contained a lot of peers to try to connect to)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2801)

### CODE REVIEW

**Comment by Green-Sky** [comment]
image

**Comment by JFreegman** [comment]
I agree that the buffer sizes should be reduced significantly, but I'm not so sure about what the ideal size is. The size determines how quickly connections will drop in the case of network congestion. It could probably be a lot lower than 2k unless we plan on implementing file transfers.

**Comment by Green-Sky** [comment]
> It could probably be a lot lower than 2k unless we plan on implementing file transfers.

I will test that. But even with ft, you want to increase the iterate rate and use lossy.

**Review by iphydf — APPROVED** [review]

**Review by JFreegman — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2801)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Review by iphydf — CHANGES_REQUESTED** [review]
Please change the pr and commit message to something more meaningful. E.g. "reduce memory usage by x%" and then put the implementation detail into the description.

**Review by iphydf — APPROVED** [review]

**Pull request merged**
