### PR TITLE
WIP: DHT-based new group chats without TCP support (UDP only)

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/217)

### CODE REVIEW

**Comment by GrayHatter** [comment]
master is the development branch?

**Comment by iphydf** [comment]
This is mainly here to keep it in mind. This still needs some work I hope @JFreegman can help with.

**Comment by zetok** [comment]
Where is the design doc / stuff?

**Comment by alexeysvrv** [comment]
When will be rewiew and integration new groupchats?

**Comment by GrayHatter** [comment]
@alexeysvrv currently, the soonest will be after I fix `net_crypto` I have no eta on that as there's a list of other things I need to finish first.

**Comment by Randl** [comment]
What's the state if this one?

**Comment by Zer0-One** [comment]
@GrayHatter @JFreegman @iphydf

**Comment by JFreegman** [comment]
Current state: limbo. No news to report.

**Comment by GrayHatter** [comment]
Still needs net_crypto to be fixed.

I'm working on that, but my understanding is that there are no plans to merge those fixes to toktok

**Comment by szh7379** [comment]
Looking forward to the merging day.

**Comment by ingvar1995** [comment]
Please close this PR because it is outdated and doesn't work. It's confusing to keep old broken PR's like this.

**Comment by iphydf** [comment]
This PR is no longer under active development. For new development, see #847. If you'd like to contribute, please contact @ingvar1995 or come chat on `#toktok` on Freenode IRC.

**Pull request closed without merging**
