### PR TITLE
Add option to disable local peer discovery

### LINKED ISSUE #221: Option to disable local peer detection
Always-on local peer detection apparently can lead to a VPN leak, so having an option to disable it would be nice. (A warning in the tooltip might be a good idea, as well.)

See also qTox/qTox#2965 and irungentoo/toxcore#1530.

### PR DESCRIPTION
**Pull request by endoffile78**
Close #221 

This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/296)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/296#-:-KXwYjW_qXL02WchVV7e:b-jbsf8z)*

**Comment by iphydf** [comment]
:lgtm: 

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/296#-:-KY0MjfuHSpAGFTDRjR7:bg7igkv)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/296#-:-KY1CUrUxNTDI6RR1f6Q:bg7igkv)*

**Comment by nurupo** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[other/bootstrap_daemon/src/tox-bootstrapd.c, line 247 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/296#-KYSF9StAuwDBiEQGPzM:-KYSF9StAuwDBiEQGPzN:blob3f1) ([raw file](https://github.com/toktok/c-toxcore/blob/8f320c8714ba7c5bf742e42d91a95227708f76c0/other/bootstrap_daemon/src/tox-bootstrapd.c#L247)):*
> ```C
>     }
> 
>     DHT *dht = new_DHT(NULL, net, true, true);
> ```

This breaks bootstrap daemon badly.

If you look below, you would see that the daemon has option variable for enabling the LAN discovery, which comes from parsing a configuration file defined by the user, yet you enable it here unconditionally.

Also, the daemon does the LAN discovery on its own, since it wasn't handled by DHT. Does DHT now also do the LAN discovery and it's unnecessary to do it manually?

Here is the code portion from below that I refer to

```C
    if (enable_lan_discovery) {
        LANdiscovery_init(dht);
        write_log(LOG_LEVEL_INFO, "Initialized LAN discovery successfully.\n");
    }
 
    while (1) {
        do_DHT(dht);
 
        if (enable_lan_discovery && is_timeout(last_LANdiscovery, LAN_DISCOVERY_INTERVAL)) {
            send_LANdiscovery(htons_port, dht);
            last_LANdiscovery = unix_time();
        }
        ...
    }
```

---

*[toxcore/friend_connection.c, line 842 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/296#-KYSEGFaBqhCo2fFmvuZ:-KYSEGFaBqhCo2fFmvu_:bdwna8o) ([raw file](https://github.com/toktok/c-toxcore/blob/8f320c8714ba7c5bf742e42d91a95227708f76c0/toxcore/friend_connection.c#L842)):*
> ```C
> static void LANdiscovery(Friend_Connections *fr_c)
> {
>     if (fr_c->last_LANdiscovery + LAN_DISCOVERY_INTERVAL < unix_time() && fr_c->dht->local_discovery_enabled) {
> ```

Why is this check necessary? This looks like a hacky way of disabling LAN discovery. Instead of disabling LAN discovery by adding a condition into `LANdiscovery()` function, it should be disabled so that this function wouldn't be called by toxcore in the first place.

---

*[toxcore/tox.api.h, line 464 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/296#-KYSDIr_ApwkvY3Ok-9z:-KYSDIramlqahFP8Y1Xx:boarw8p) ([raw file](https://github.com/toktok/c-toxcore/blob/8f320c8714ba7c5bf742e42d91a95227708f76c0/toxcore/tox.api.h#L464)):*
> ```objc
>      * Enable finding peers on your local network.
>      *
>      * Disabling this will cause tox to not look for peers on your local network.
> ```

It appears that we capitalize "Tox" in comments to `udp_enabled` and `static class options {`. It's good to be consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/296)*

**Comment by nurupo** [comment]
Ok, I have taken a closer look at this PR and I can say that the way you disable LAN discovery is not the proper way. LAN discovery is used exclusively by `friend_connection.h`, which is used exclusively by `Messenger.c`. You shouldn't touch DHT at all, it's not involved in LAN discovery. You shouldn't even store that option in the Messenger. The Messenger should pass it into `new_friend_connections()` inside `new_messenger()` function, and `new_friend_connections()` should store it in `Friend_Connections` struct.

**Comment by nurupo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[other/bootstrap_daemon/src/tox-bootstrapd.c, line 247 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/296#-KYSF9StAuwDBiEQGPzM:-KYSUwcBnx5fEpzGLc2n:b-va5ytx) ([raw file](https://github.com/toktok/c-toxcore/blob/8f320c8714ba7c5bf742e42d91a95227708f76c0/other/bootstrap_daemon/src/tox-bootstrapd.c#L247)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

This breaks bootstrap daemon badly.

If you look below, you would see that the daemon has option variable for enabling the LAN discovery, which comes from parsing a configuration file defined by the user, yet you enable it here unconditionally.

Also, the daemon does the LAN discovery on its own, since it wasn't handled by DHT. Does DHT now also do the LAN discovery and it's unnecessary to do it manually?

Here is the code portion from below that I refer to

```C
    if (enable_lan_discovery) {
        LANdiscovery_init(dht);
        write_log(LOG_LEVEL_INFO, "Initialized LAN discovery successfully.\n");
    }
 
    while (1) {
        do_DHT(dht);
 
        if (enable_lan_discovery && is_timeout(last_LANdiscovery, LAN_DISCOVERY_INTERVAL)) {
            send_LANdiscovery(htons_port, dht);
            last_LANdiscovery = unix_time();
        }
        ...
    }
```
</blockquote></details>

Ok, it appears that this `local_discovery_enabled` argument of `new_DHT()` doesn't affect local discovery at all if you are not using Messenger. As I said in my other comment, `new_DHT()` shouldn't deal with lan discovery, so it shouldn't be taking this boolean in the first place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/296)*

**Comment by nurupo** [comment]
Fixed this in https://github.com/TokTok/c-toxcore/pull/306.

**Comment by iphydf** [comment]
Closing in favour of #306.

**Pull request closed without merging**
