### PR TITLE
travis-ci: add "apt" cache

### PR DESCRIPTION
**Pull request by chipitsine**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/267)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/267#-:-KWOz-TlHIBtzefIIzHK:b-jbsf8z)*

**Comment by robinlinden** [comment]
Actually, are you sure this even does anything? See: https://github.com/travis-ci/travis-ci/issues/5876

**Comment by robinlinden** [comment]
:lgtm_cancel: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/267#-:-KWP8VAKB6b6K3vGpQMF:b8b79qu)*

**Comment by iphydf** [comment]
@chipitsine where is this documented?

**Comment by chipitsine** [comment]
after I pass .travis.yml to https://lint.travis-ci.org/, it complains on several things, but is keeps silence on "apt: true"

**Comment by GrayHatter** [comment]
@chipitsine right, but where is the documentation showing what adding `apt: true` does, or is supposed to do?

**Comment by chipitsine** [comment]
I'll make test repo and will look at the travis sources. Please, be patient.

**Comment by chipitsine** [comment]
it does not work, nevermind

**Comment by GrayHatter** [comment]
Thanks anyways, any kind of help is always welcome.

Thanks for the help mate!!

**Pull request closed without merging**
