### PR TITLE
Add tutorial and "danger: experimental" banner to README.

### PR DESCRIPTION
**Pull request by iphydf**
Acting on suggestions in #426.

@paragonie-scott @zx2c4 @runn1ng @DebugReport @wfn

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/433)

### CODE REVIEW

**Comment by zx2c4** [comment]
Looks like a good start. You could add, "this library has known cryptographic weaknesses that have not been addressed and a security model that has not been fully specified."

**Comment by iphydf** [comment]
Also @lvh.

**Comment by iphydf** [comment]
Updated with additional links to not yet addressed issues.

**Comment by runn1ng** [comment]
I am not entirely sure why am I mentioned here :) but I am all for it

**Comment by wfn** [comment]
Warning text looks good to me. :)

The "**use this library at your own risk.**" comment could be decoupled from the conditional "Until it has received a clean bill of health" clause, as it feels like something which could be kept on all the time. In that case, the "use this library" standalone sentence could be preceded with a stronger statement, maybe something like "Until it has received a clean bill of health from independent computer security experts, it should not be deemed production-ready." (But maybe you can think of something better than "production-ready"). This is probably nitpicking, though - overall looks good!

**Comment by lvh** [comment]
LGTM :)

**Comment by nurupo** [comment]
There is also https://wiki.tox.chat/developers/client_examples/echo_bot

**Comment by sonOfRa** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/433)*

**Comment by sonOfRa** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/433#-:-Kai6jDD8THkuEyrv3-8:b-jbsf8z)*

**Comment by Zer0-One** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/433#-:-Kaj818xiRsOKAVfKrEt:b-jbsf8z)*

**Comment by GrayHatter** [comment]
I'm strongly opposed to this pull. It's a mistake for obvious reasons. In addition to the fack that it's demonstrably false. It's only going to confuse users, and serves only to spread FUD

**Comment by sonOfRa** [comment]
>There is nothing inherently dangerous about using Tox as far as I know

Exactly. As far as we know. Now, since we aren't audited, don't have a thread model, and have a huge codebase that we only partially understand, I think the word "dangerous" is completely and absolutely warranted here.

**Comment by sonOfRa** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/433#-:-Kakg4pahLLKk1j1Q_tu:b-jbsf8z)*

**Comment by GrayHatter** [comment]
> I think the word "dangerous" is completely and absolutely warranted here.

It's not. Dangerous is a sticker you'd apply to a table saw. Not a pair of safety glasses.

**Comment by Zer0-One** [comment]
@iphydf 
This could be merged as-is, but I also think that the banner is an eyesore. I'm ok with warning people that toxcore is unaudited, and even with calling it experimental, but a banner like that is going to give people the impression that toxcore might nuke your system on accident, spill oil into the ocean, club seals, etc.

tl;dr, i think we can do without the big annoying banner

**Comment by sonOfRa** [comment]
> There is no "until". No software is risk-free whether or not it's experimental and whether or not an audit has been done.

Why are you arguing such nitty semantics here? Of course, nothing is risk-free, but this is a matter of risk-management. An audit severely reduces the risks associated with using such a piece of software.

> I'm ok with warning people that toxcore is unaudited, and even with calling it experimental, but a banner like that is going to give people the impression that toxcore might nuke your system on accident, spill oil into the ocean, club seals, etc.

Yes, but the point is that it kind of can. The vulnerability that sparked this discussion works as follows: If you steal Alice's long-term secret key, you can not only pretend that you are Alice to everyone else. You can also pretend _to Alice_ that you are everyone else.

Personally, I was unaware this vulnerability existed. And, according to that issue's reporter, this was discovered at what was merely a cursory glance, and with beneficial intent! Someone who analyzes the Tox protocol with malicious intent may be significantly more rigorous and not share those problems with us.

So until we have a proper threat model, I think this eyesore should stay. When we come to a point where we actually have a properly defined threat model, and have assessed (without external audit) that we actually protect against the threats in that model, we can think about using a less-flashy warning. When we have assessed it (with external audit), we can think about removing it completely.

**Comment by GrayHatter** [comment]
> Yes, but the point is that it kind of can. The vulnerability that sparked this discussion works as follows: If you steal Alice's long-term secret key, you can not only pretend that you are Alice to everyone else. You can also pretend to Alice that you are everyone else.

Right, we knew you would be fucked if someone stole your secret key. That was an intentional design decision by irungentoo. His intent was never to have tox protect you from that. (Let's not forget that the original design of tox was supposed to be anonymous and semi transient, with a key never really living too long)

> Personally, I was unaware this vulnerability existed. And, according to that issue's reporter, this was discovered at what was merely a cursory glance

Sure, they know that secret key auth can allow you to mitm if you don't use ephemeral keys. That's not hard to work out, so it says nothing about the work it would take to find a real security bug. Per irungentoo "That's it, I thought someone had found an actual security issue". In other news your car's air bags wont protect you if your car catches on fire.

**Comment by cebe** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[README.md, line 18 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/433#-KakPnI5jADr3GTn1DIC:-KamLf1rC9zVVq2LlPWE:b-n8ljyp) ([raw file](https://github.com/toktok/c-toxcore/blob/2a4f1d73a13c43ecfa2851cc5d29b62d394af0cd/README.md#L18)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

There is nothing inherently dangerous about using Tox as far as I know. The word "warning" would be more accurate.
</blockquote></details>

Fully agree, that sign is ridiculous, there is no nuclear radiation in tox, it may just not fit for all purposes. Remove this sign and I'm okay with merging it for now.

---

*[README.md, line 25 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/433#-KakPBTJ8UObQKuzcMQH:-KamM9zZAd3LJDc-Hfzo:byo07zh) ([raw file](https://github.com/toktok/c-toxcore/blob/2a4f1d73a13c43ecfa2851cc5d29b62d394af0cd/README.md#L25)):*
> use this library at your own risk.

this is already given by the license, using open source software is always "at your own risk". We may state that here again but not "until" but just "use this library at your own risk."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/433)*

**Comment by iphydf** [comment]
@sonOfRa @Zer0-One PTAL

**Comment by cebe** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/433)*

**Comment by sonOfRa** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/433#-:-KamtgQ3inMqxVLCGSQD:b-jbsf8z)*

**Comment by robinlinden** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 18 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/433#-KakPnI5jADr3GTn1DIC:-KamyraM34DW0Bn3aJOQ:bqyb39s) ([raw file](https://github.com/toktok/c-toxcore/blob/2a4f1d73a13c43ecfa2851cc5d29b62d394af0cd/README.md#L18)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

Fully agree, that sign is ridiculous, there is no nuclear radiation in tox, it may just not fit for all purposes. Remove this sign and I'm okay with merging it for now.
</blockquote></details>

Updated with a nicer banner with the text "warning" instead of "danger" and with a more appropriate symbol.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/433#-:-KamzkmCSf-DfYGHjbd_:bg7igkv)*

**Comment by JFreegman** [comment]
@sonOfRa 
>Exactly. As far as we know. Now, since we aren't audited, don't have a thread model, and have a huge codebase that we only partially understand, I think the word "dangerous" is completely and absolutely warranted here.

It will always be "as far as we know". An audit and a threat model is not a guarantee of anything, and neither is understanding the code base. All we're arguing here is the degree of risk, and I have no reason to believe that Tox as it stands puts users in danger. 

>Why are you arguing such nitty semantics here? Of course, nothing is risk-free, but this is a matter of risk-management. An audit severely reduces the risks associated with using such a piece of software.

It's not nitty. It's a false and misleading statement.

**Comment by jin-eld** [comment]
:lgtm_strong:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/433#-:-KanWvf4DRJrIG17UpCg:b-jbsf8z)*

**Comment by cebe** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/433#-:-KanY6nPIlvWRCf85xhR:bg7igkv)*

**Comment by GrayHatter** [comment]
fuck

**Pull request merged**
