### PR TITLE
Fix list malloc(0) bug

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/510)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxcore/list.c, line 121 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/510#-Kf25gGK92_M6dLlxXT0:-Kf25gGLvQteu0zW-o7q:b-7g7m95) ([raw file](https://github.com/toktok/c-toxcore/blob/c381d9b08b2a38713f1d34a075c377418be3dd8e/toxcore/list.c#L121)):*
> ```C
> {
>     if (new_size == 0) {
>         list->data = NULL;
> ```

the memory should also get freed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/510)*

**Comment by Diadlo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxcore/list.c, line 121 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/510#-Kf25gGK92_M6dLlxXT0:-Kf2pZXwY2F5Ljk9205h:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/c381d9b08b2a38713f1d34a075c377418be3dd8e/toxcore/list.c#L121)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

the memory should also get freed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/510)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/510#-:-Kf2qkXFBTQUGVqYqw4R:b-jbsf8z)*

**Comment by iphydf** [comment]
Enable the checkbox allowing pushes from collaborators.

**Comment by Diadlo** [comment]
@iphydf Done

**Pull request merged**
