### PR TITLE
fix: use correct sample size in toxav_basic_test

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1845)

### CODE REVIEW

**Comment by sudden6** [comment]
We must use the exact buffer sizes, otherwise ASAN and friends will not detect overreads.

**Review by JFreegman — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1845)* status: 0 of 1 approvals obtained (waiting on @sudden6)

___
*[auto_tests/toxav_basic_test.c, line 105 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1845#-MsaY4f2AKf1kvVEEGju:-MsaY4f2AKf1kvVEEGjv:bmhtcgf) ([raw file](https://github.com/toktok/c-toxcore/blob/835e7ef3bb7fb04be5087a1605d74e63fa4db0b6/auto_tests/toxav_basic_test.c#L105)):*
> ```C
> static bool toxav_audio_send_frame_helper(ToxAV *av, uint32_t friend_number, Toxav_Err_Send_Frame *error)
> {
>     const static int16_t PCM[960] = {0};
> ```

Where does the value `960` come from? is it defined somewhere?

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1845)* status: 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[auto_tests/toxav_basic_test.c, line 105 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1845#-MsaY4f2AKf1kvVEEGju:-Msagk0B5whL-p1fkU5Z:b-ujfrj3) ([raw file](https://github.com/toktok/c-toxcore/blob/835e7ef3bb7fb04be5087a1605d74e63fa4db0b6/auto_tests/toxav_basic_test.c#L105)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Where does the value `960` come from? is it defined somewhere?
</blockquote></details>

I don't know, I just reused it from the previous test.

**Review by JFreegman — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1845)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @JFreegman)

**Pull request merged**
