### PR TITLE
Use <stdlib.h> for alloca on FreeBSD.

### PR DESCRIPTION
**Pull request by iphydf**
https://www.freebsd.org/cgi/man.cgi?alloca

Some additional fixed had to be done as the Windows build started failing once I fixed the freebsd build.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/723)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/723#-:-L3UbP252cybtiio-i0E:b-jbsf8z)*

**Comment by sudden6** [comment]
Reviewed 7 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[other/travis/toxcore-script, line 13 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/723#-L3Uc1QsuF-6b8xtVMtP:-L3Uc1QsuF-6b8xtVMtQ:be0nw3o) ([raw file](https://github.com/toktok/c-toxcore/blob/e6c04ef0287a69c453f129778ef35932e0dff4b2/other/travis/toxcore-script#L13)):*
> ```
> }
> 
> # Try some combinations of cmake options.
> ```

why is this removed? not needed anymore?

---

*[toxcore/Messenger.c, line 2261 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/723#-L3UcExsUYjXCVASKehK:-L3UcExsUYjXCVASKehL:bm3gq83) ([raw file](https://github.com/toktok/c-toxcore/blob/9e2d1c233b702ca4d00ebe3b32616421a30493df/toxcore/Messenger.c#L2261)):*
> ```C
>             uint8_t filenumber = data[0];
> 
> #if UINT8_MAX > MAX_CONCURRENT_FILE_PIPES
> ```

What happens in the case of `UINT8_MAX < MAX_CONCURRENT_FILE_PIPES`? looks a bit like a hack to pass tests for me

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/723)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[toxcore/Messenger.c, line 2261 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/723#-L3UcExsUYjXCVASKehK:-L3UdK5yzpfkmCbh_NCw:b-tm2dfo) ([raw file](https://github.com/toktok/c-toxcore/blob/9e2d1c233b702ca4d00ebe3b32616421a30493df/toxcore/Messenger.c#L2261)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

What happens in the case of `UINT8_MAX < MAX_CONCURRENT_FILE_PIPES`? looks a bit like a hack to pass tests for me
</blockquote></details>

This is not to pass tests. The condition below is always false if the cpp condition is false. filenumber is a uint8_t, so can never be larger than 255. This causes compiler warnings and I'd like to avoid those. This has nothing to do with tests.

If `UINT8_MAX < MAX...`, then that means we can't even index the highest filenumber. I don't think that's possible without changing the type of filenumber in a lot of places.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/723)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[other/travis/toxcore-script, line 13 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/723#-L3Uc1QsuF-6b8xtVMtP:-L3UdtQ9P6CPEnkYfU54:bj8l10z) ([raw file](https://github.com/toktok/c-toxcore/blob/e6c04ef0287a69c453f129778ef35932e0dff4b2/other/travis/toxcore-script#L13)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

why is this removed? not needed anymore?
</blockquote></details>

It has never caught any bugs, and seriously slows down windows and freebsd builds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/723)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/Messenger.c, line 2261 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/723#-L3UcExsUYjXCVASKehK:-L3UebSCz4M532dxeYS1:bjyqbjw) ([raw file](https://github.com/toktok/c-toxcore/blob/9e2d1c233b702ca4d00ebe3b32616421a30493df/toxcore/Messenger.c#L2261)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

This is not to pass tests. The condition below is always false if the cpp condition is false. filenumber is a uint8_t, so can never be larger than 255. This causes compiler warnings and I'd like to avoid those. This has nothing to do with tests.

If `UINT8_MAX < MAX...`, then that means we can't even index the highest filenumber. I don't think that's possible without changing the type of filenumber in a lot of places.
</blockquote></details>

Ok, can we enforce `UINT8_MAX >= MAX_CONCURRENT_FILE_PIPES` by a `#error` + comment? Would make sense against accidental changes IMO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/723)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/Messenger.c, line 2261 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/723#-L3UcExsUYjXCVASKehK:-L3UgBht3nQ17VhYWVsl:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/9e2d1c233b702ca4d00ebe3b32616421a30493df/toxcore/Messenger.c#L2261)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Ok, can we enforce `UINT8_MAX >= MAX_CONCURRENT_FILE_PIPES` by a `#error` + comment? Would make sense against accidental changes IMO.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/723)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/723#-:-L3Uh-DmYwDdAZpxI2i9:b-jbsf8z)*

**Pull request merged**
