### PR TITLE
chore: Add a .clang-format that mostly agrees with astyle.

### LINKED ISSUE #1990: Add a .clang-format config that matches the astyle config as closely as possible.
At some point we can then switch to it, but in the meantime, it would format the C++ code according to the toxcore style.

### PR DESCRIPTION
**Pull request by iphydf**
Fixes #1990.

---

This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2075)

### CODE REVIEW

**Review by JFreegman — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2075)* status: 0 of 1 approvals obtained (waiting on @sudden6)

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 19 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2075)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[CMakeLists.txt, line 95 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2075#-MwGNbPDBVdnoIWw7oW3:-MwGNbPDBVdnoIWw7oW4:b-kkoqwg) ([raw file](https://github.com/toktok/c-toxcore/blob/68f4e5c0fa642acbdf9665c2c552b0b781992334/CMakeLists.txt#L95)):*
> ```CMake
> if(EXECUTION_TRACE)
>   set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -finstrument-functions")
> endif()
> ```

what do these changes have to do with formatting?
___
*[testing/BUILD.bazel, line 49 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2075#-MwGNpz112ovYrga7U2W:-MwGNpz112ovYrga7U2X:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/68f4e5c0fa642acbdf9665c2c552b0b781992334/testing/BUILD.bazel#L49)):*
> ```Starlark
> 
> cc_library(
>     name = "trace",
> ```

same

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2075)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @sudden6)

___
*[CMakeLists.txt, line 95 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2075#-MwGNbPDBVdnoIWw7oW3:-MwGn8Tw6BrUYT_1iE9w:b9fveld) ([raw file](https://github.com/toktok/c-toxcore/blob/68f4e5c0fa642acbdf9665c2c552b0b781992334/CMakeLists.txt#L95)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

what do these changes have to do with formatting?
</blockquote></details>

Moved to a separate PR.
___
*[testing/BUILD.bazel, line 49 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2075#-MwGNpz112ovYrga7U2W:-MwGnA2i1keNasbm-aLu:b-816h6l) ([raw file](https://github.com/toktok/c-toxcore/blob/68f4e5c0fa642acbdf9665c2c552b0b781992334/testing/BUILD.bazel#L49)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Same.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2075#-:-MwNFVHo3jM65X5tesmu:b-jbsf8z)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
