### PR TITLE
cleanup: Remove implicit conversions from `uint32_t` to `bool`.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2097)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2097)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[toxcore/DHT.c, line 1385 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2097#-MwYUTnk7tvhUO3pe2Hx:-MwYUTnk7tvhUO3pe2Hy:boumhn) ([raw file](https://github.com/toktok/c-toxcore/blob/7e1c7629589685401b6f76df7dd1631a160f36ac/toxcore/DHT.c#L1385)):*
> ```C
>     int nodes_length = 0;
> 
>     if (num_nodes != 0) {
> ```

semantically, `>` would make more sense here
___
*[toxcore/TCP_connection.c, line 315 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2097#-MwYV5lZ-nMZDYht8v2i:-MwYV5lZ-nMZDYht8v2j:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/7e1c7629589685401b6f76df7dd1631a160f36ac/toxcore/TCP_connection.c#L315)):*
> ```C
>         uint8_t connection_id = con_to->connections[i].connection_id;
> 
>         if (tcp_con_num != 0 && status == TCP_CONNECTIONS_STATUS_ONLINE) {
> ```

same
___
*[toxcore/TCP_connection.c, line 347 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2097#-MwYV6y76x1yHiwnA2cc:-MwYV6y76x1yHiwnA2cd:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/7e1c7629589685401b6f76df7dd1631a160f36ac/toxcore/TCP_connection.c#L347)):*
> ```C
>             uint8_t status = con_to->connections[i].status;
> 
>             if (tcp_con_num != 0 && status == TCP_CONNECTIONS_STATUS_REGISTERED) {
> ```

same
___
*[toxcore/TCP_connection.c, line 1515 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2097#-MwYVION4-ZFLzktE__T:-MwYVION4-ZFLzktE__U:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/7e1c7629589685401b6f76df7dd1631a160f36ac/toxcore/TCP_connection.c#L1515)):*
> ```C
> 
>             if (tcp_con->status == TCP_CONN_CONNECTED
>                     && !tcp_con->onion && tcp_con->lock_count != 0
> ```

same
___
*[toxcore/TCP_connection.c, line 1552 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2097#-MwYVH77AQUH7Lg25gR-:-MwYVH77AQUH7Lg25gR0:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/7e1c7629589685401b6f76df7dd1631a160f36ac/toxcore/TCP_connection.c#L1552)):*
> ```C
> 
>         if (tcp_con->status == TCP_CONN_CONNECTED) {
>             if (tcp_con->onion || tcp_con->lock_count != 0) {  // connection is in use so we skip it
> ```

same

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2097)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @sudden6)

___
*[toxcore/DHT.c, line 1385 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2097#-MwYUTnk7tvhUO3pe2Hx:-MwYi_W-6ZxDagtxow2J:bhv6uxn) ([raw file](https://github.com/toktok/c-toxcore/blob/7e1c7629589685401b6f76df7dd1631a160f36ac/toxcore/DHT.c#L1385)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

semantically, `>` would make more sense here
</blockquote></details>

Would you want to always see `> 0` when comparing `uint32_t` (or any unsigned ints) against `0`?
___
*[toxcore/TCP_connection.c, line 315 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2097#-MwYV5lZ-nMZDYht8v2i:-MwYilCB2ADsJVl29FSk:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7e1c7629589685401b6f76df7dd1631a160f36ac/toxcore/TCP_connection.c#L315)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[toxcore/TCP_connection.c, line 347 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2097#-MwYV6y76x1yHiwnA2cc:-MwYk6PJCaPKFvxlxB27:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7e1c7629589685401b6f76df7dd1631a160f36ac/toxcore/TCP_connection.c#L347)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[toxcore/TCP_connection.c, line 1515 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2097#-MwYVION4-ZFLzktE__T:-MwYk7A3BDZQVee3lbwS:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7e1c7629589685401b6f76df7dd1631a160f36ac/toxcore/TCP_connection.c#L1515)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[toxcore/TCP_connection.c, line 1552 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2097#-MwYVH77AQUH7Lg25gR-:-MwYk7XxCwk0wnyyP0gs:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7e1c7629589685401b6f76df7dd1631a160f36ac/toxcore/TCP_connection.c#L1552)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by JFreegman — APPROVED** [review]
> Reviewed 7 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2097)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @sudden6)

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2097#-:-MwaaGys3hHFHitfDCjC:b-jbsf8z)* status: :shipit: complete! 2 of 1 approvals obtained

___
*[toxcore/DHT.c, line 1385 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2097#-MwYUTnk7tvhUO3pe2Hx:-Mwa_zi75Om59T94lWvt:b-tmbabe) ([raw file](https://github.com/toktok/c-toxcore/blob/7e1c7629589685401b6f76df7dd1631a160f36ac/toxcore/DHT.c#L1385)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Would you want to always see `> 0` when comparing `uint32_t` (or any unsigned ints) against `0`?
</blockquote></details>

No, I think there's no general rule we can apply here.

**Pull request merged**
