### PR TITLE
Simplify Travis-CI FreeBSD build

### PR DESCRIPTION
**Pull request by nurupo**
I went ahead and updated FreeBSD to use 11.2 image because the 11.1 was giving

>WARNING: FreeBSD 11.1-RELEASE is approaching its End-of-Life date.
>It is strongly recommended that you upgrade to a newer
>release within the next 2 months.

message. I had to reduce the 8 mirrors down to 2, because apparently only 2 of them have 11.2 release. They must be syncing once per month or rarer. We could add more mirrors as more of them get the release.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/986)

### CODE REVIEW

**Comment by nurupo** [comment]
I went ahead and updated FreeBSD to use 11.2 image because the 11.1 was giving

>WARNING: FreeBSD 11.1-RELEASE is approaching its End-of-Life date.
>It is strongly recommended that you upgrade to a newer
>release within the next 2 months.

message. I had to reduce the 8 mirrors down to 2, because apparently only 2 of them have 11.2 release. They must be syncing once per month or rarer. We could add more mirrors as more of them get the release.

**Comment by nurupo** [comment]
Here is the build https://travis-ci.org/TokTok/c-toxcore/builds/402243877.

**Review by iphydf — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/986)* status: 0 of 1 LGTMs obtained (waiting on @iphydf)

___
*[.travis/cmake-freebsd-stage2, line 18 at r1](https://reviewable.io/reviews/toktok/c-toxcore/986#-LHCKk-fAPzvzZe2X_eK:-LHCKk-fAPzvzZe2X_eL:b-4pzi0j) ([raw file](https://github.com/toktok/c-toxcore/blob/fe9ba95433d635ae87d3dff65608feffae9edb2f/.travis/cmake-freebsd-stage2#L18)):*
> ```
> 
>   # Extract the cached image
>   tar -Sxzvf $IMAGE_NAME.tgz
> ```

Put variables into double quotes to avoid potential double parsing of values with spaces in them.

**Comment by nurupo** [comment]
Hm, the build suddenly started failing, it wasn't doing that before. `poweroff` as root disconnects us from ssh but for some reason the VM still keeps running until the build times out, it doesn't "poweroff" properly.

**Comment by nurupo** [comment]
Sending `poweroff` over ssh doesn't work but sending it to the qemu tty does. Go figure what the issue is. I would have tried to reproduce the ssh poweroff issue on my local machine, but I have 4GiB of disk space left which won't be enough. Sending poweroff to tty works and I don't see any downsides to it, do let's just roll with that.

**Review by nurupo — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/986)* status: 0 of 1 LGTMs obtained

___
*[.travis/cmake-freebsd-stage2, line 18 at r1](https://reviewable.io/reviews/toktok/c-toxcore/986#-LHCKk-fAPzvzZe2X_eK:-LHPTlzd-CquMDvxte6a:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/fe9ba95433d635ae87d3dff65608feffae9edb2f/.travis/cmake-freebsd-stage2#L18)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Put variables into double quotes to avoid potential double parsing of values with spaces in them.
</blockquote></details>

Done.

**Review by nurupo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/986)* status: 0 of 1 LGTMs obtained

___
*[.travis/cmake-freebsd-stage1, line 0 at r2](https://reviewable.io/reviews/toktok/c-toxcore/986#-LHPUBbH73OOEpE9shg1:-LHPUBbH73OOEpE9shg2:bnz5sse) ([raw file](https://github.com/toktok/c-toxcore/blob/3c116f93497ba373ade43048d80e56fff785e25d/.travis/cmake-freebsd-stage1#L0)):*
>File appears to be binary.

Good job reviewable.

**Review by iphydf — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/986)* status: 0 of 1 LGTMs obtained

___
*[.travis/cmake-freebsd-stage1, line  at r2](https://reviewable.io/reviews/toktok/c-toxcore/986#-LHPUBbH73OOEpE9shg1:-LHUocOL9fR2GbSsNcsq:bk8xniv) ([raw file](https://github.com/toktok/c-toxcore/blob/3c116f93497ba373ade43048d80e56fff785e25d/.travis/cmake-freebsd-stage1#L)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

>File appears to be binary.

Good job reviewable.
</blockquote></details>

It's because there is a literal ESC byte in this script instead of an escape sequence for it.

**Review by iphydf — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/986#-:-LHUoxMd31XRr3mEzEI3:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by nurupo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/986)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[.travis/cmake-freebsd-stage1, line  at r2](https://reviewable.io/reviews/toktok/c-toxcore/986#-LHPUBbH73OOEpE9shg1:-LHV3w0-7xytlzV7nFEY:bvhsuzk) ([raw file](https://github.com/toktok/c-toxcore/blob/3c116f93497ba373ade43048d80e56fff785e25d/.travis/cmake-freebsd-stage1#L)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

It's because there is a literal ESC byte in this script instead of an escape sequence for it.
</blockquote></details>

That was my guess.

**Comment by nurupo** [comment]
Rebased on master.

**Pull request merged**
