### PR TITLE
Improve gtest finding, support local checkout.

### PR DESCRIPTION
**Pull request by iphydf**
Also fix library dependency order for monolith test.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/774)

### CODE REVIEW

**Comment by iphydf** [comment]
Build is broken.

**Comment by iphydf** [comment]
This PR fixes the build.

**Comment by Diadlo** [comment]
> `cmake_minimum_required(VERSION 2.8.6)`

> ser(CMAKE_C_STNADARD ...)

I'm not sure, but seems this feature is unavaliable on 2.8.8

**Comment by iphydf** [comment]
Upped requirement to 3.1.0.

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/774#-:-L53pKDe2JPCtj2moctY:b-jbsf8z)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/774#-:-L53s7kD57XfpdiZ_E7b:b-jbsf8z)*

**Pull request merged**
