### PR TITLE
net_crypto give handle_data_packet_helper a better name

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/299)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/299#-:-KY5_vulX9xwjX5ESJBb:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/299#-:-KY9sS5D5eIv8ERE5GMp:b-jbsf8z)*

**Comment by GrayHatter** [comment]
@iphydf

**Comment by iphydf** [comment]
I can't merge it. Please rebase.

**Comment by nurupo** [comment]
@GrayHatter so, why is this a better name? What `core` means here?

**Pull request merged**
