### PR TITLE
Replace redundant packet type check in handler with assert.

### PR DESCRIPTION
**Pull request by yurivict**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/434)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/DHT.c, line 2538 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/434#-KaUrnrRVskUNW33KGaN:-KaUrnrRVskUNW33KGaO:b-1etbol) ([raw file](https://github.com/toktok/c-toxcore/blob/27a97a8280813ec05a5209811c40ab23203bb292/toxcore/DHT.c#L2538)):*
> ```C
>     DHT *dht = (DHT *)object;
> 
>     if (packet[0] == NET_PACKET_CRYPTO) {
> ```

How about:
```c
if (packet[0] != NET_PACKET_CRYPTO) {
    assert(!"unexpected packet kind");
    return 1;
}
```

The check is redundant, but removing it makes the function's correctness non-local. It's a function precondition, and we currently don't have a good way to express those. Perhaps add a `// TODO` comment saying that function preconditions should be expressed better (e.g. with an assert-like macro we define for that purpose).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/434)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/434)*

**Comment by yurivict** [comment]
This is a very shallow check, it merely checks that the handler is plugged at the right slot, which it obviously is. Also no other handlers perform such check. I suggest it is deleted.

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/DHT.c, line 2538 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/434#-KaUrnrRVskUNW33KGaN:-Kaae6y_LeMvVtI60cDE:b-e6hnls) ([raw file](https://github.com/toktok/c-toxcore/blob/27a97a8280813ec05a5209811c40ab23203bb292/toxcore/DHT.c#L2538)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

How about:
```c
if (packet[0] != NET_PACKET_CRYPTO) {
    assert(!"unexpected packet kind");
    return 1;
}
```

The check is redundant, but removing it makes the function's correctness non-local. It's a function precondition, and we currently don't have a good way to express those. Perhaps add a `// TODO` comment saying that function preconditions should be expressed better (e.g. with an assert-like macro we define for that purpose).
</blockquote></details>

Can you just turn it into an assert then? "which it obviously is" is not a good criterion to remove a check. The fact that it's not checked elsewhere probably means we should check it there as well. It *is* a function precondition, because it won't work correctly if the handler was plugged into the wrong slot. The problem with not checking it at all is that if somehow we end up changing some code that ends up putting it into the wrong slot, it might fail silently doing some incorrect thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/434)*

**Comment by yurivict** [comment]
```assert(packet[0] == NET_PACKET_CRYPTO);``` might be better.

**Comment by iphydf** [comment]
Yes, that's what I meant.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/434#-:-KaaiUIUCOPJyZNfB0pU:bs5ed97)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/434#-:-KaalusLXg7nYxmxTTvy:b-jbsf8z)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/434)*

**Comment by iphydf** [comment]
Can you enable the checkbox that lets collaborators push to your PR branch? That way, I can rebase it on master and then merge after CI completes.

**Comment by iphydf** [comment]
Please rebase on master.

**Comment by piling** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/434#-:-KaroPJ8qsuIQL89OpRc:b-jbsf8z)*

**Comment by iphydf** [comment]
@yurivict can you rebase this on master and enable the checkbox (on the right) to allow us to rebase it again if necessary?

**Comment by iphydf** [comment]
@yurivict also squash the two commits in one, and give it an appropriate title.

**Comment by iphydf** [comment]
@yurivict I'd like to push this before tomorrow. Will you have time to either click the checkbox on the right, or squash and rebase these commits on master?

**Comment by yurivict** [comment]
I am sorry I have been busy lately to engage in this. Where is the button you talk about?

**Comment by dvor** [comment]
@yurivict I guess he is talking about this checkmark

i

**Comment by yurivict** [comment]
It doesn't show such button on my screen:
github-no-button

**Comment by yurivict** [comment]
It says "this pull request can be merged by project collaborators". Why don't you just do this?

**Comment by dvor** [comment]
@yurivict we want to update pull request with required changes before merging it.

Try scrolling to the top of the page. There should be block as on my screenshot where you will find needed checkmark.

**Comment by yurivict** [comment]
Ok, found it.

**Comment by iphydf** [comment]
"This pull request can be merged" is a lie. If I try, it actually doesn't work. That's a github bug.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/434#-:-KbSF1DUyaX9WE1Gb5J9:b4xyn6u)*

**Pull request merged**
