### PR TITLE
WIP: investigating auto_tox_many_tcp_test failure

### PR DESCRIPTION
**Pull request by zugz**
Currently just a minimised version of the test which consistently fails (i.e. 
times out).

This version of the test has 7 TCP-servers who have UDP enabled, and one 
further tox with UDP disabled who connects via one of the TCP servers, while 
the TCP servers bootstrap off the first but don't connect via TCP. The TCP 
servers send friend requests to the other peer, and not all of the friend 
requests get through.

It's important that the friend requests are made this way round - the other 
way works fine.

I don't currently see what the problem could be.

I tried applying this test to old toxcores to test if it's a regression - the 
earliest I got it to compile against was 0a61d110 (4 Jan 2017), and it failed 
there too.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1148)

### CODE REVIEW

**Comment by zugz** [comment]
I tracked down the immediate cause of the problem isolated by this 
version of the test: handle_tcp_onion() gives a zero IP_Port to 
handle_announce_response(), and this zero IP_Port is considered not to 
be a lan ip by ip_is_lan(). The consequence is that if a tox instance is 
connected to the local test tox network only via a TCP node, then it 
will ignore the nodes that TCP node suggests in onion announce 
responses, because of the ip_is_lan tests in client_ping_nodes(). Hence 
this tox will announce only to the TCP node, and having only one 
announce location is insufficient for others to find it, because of the 
num_good test in send_onion_data().

I'm not sure right now what the correct fix is, possibly it is just to 
check for zero along with checking for lan ips.

However, even after fixing this problem, if the number of toxes in the 
test is increased far enough the test still fails (20 is ok, 40 is not), 
for some presumably entirely different reason I haven't yet tried to 
diagnose.

**Comment by iphydf** [comment]
Does it make sense to add this test to the auto tests?

**Comment by zugz** [comment]
* Monday, 2020-04-13 at 11:15 -0700 - iphydf <notifications@github.com>:

> Does it make sense to add this test to the auto tests?

Yes. I'll make a clear PR incorporating it into the existing test.

**Comment by iphydf** [comment]
This test isn't timing out anymore.

**Pull request closed without merging**
