### PR TITLE
Make the monolith test a C++ binary.

### PR DESCRIPTION
**Pull request by iphydf**
This way, developers compile toxcore, toxav, and toxencryptsave as C++ at
least once at home, reducing the likelyhood of running into travis
failures where we compile as C++ in the windows build.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/711)

### CODE REVIEW

**Comment by nurupo** [comment]
This PR seems to have some unrelated changes in it.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 464 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/711#-L3L7n9LD0BO17WvxpRL:-L3L7n9LD0BO17WvxpRM:b-ezn3j8) ([raw file](https://github.com/toktok/c-toxcore/blob/28d4fd4c5ee34f435988f3f6f7ed08b10c9e1247/CMakeLists.txt#L464)):*
> ```CMake
> if(BUILD_TOXAV)
>   add_c_executable(auto_monolith_test
>     auto_tests/monolith_test.cpp
> ```

Wouldn't this change make C++ compiler required for building toxav? This is a bit undesirable since it's not actually necessary for building toxav. For example, when building toxcore in Docker you generally want to install as few packages as necessary to save time and disk space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/711#-:-L3L7bjhqOJJ0vxSYjgH:b-tdo5kq)*

**Comment by iphydf** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 464 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/711#-L3L7n9LD0BO17WvxpRL:-L3LBboRd_1DaZZhj8vt:b-8z88gl) ([raw file](https://github.com/toktok/c-toxcore/blob/28d4fd4c5ee34f435988f3f6f7ed08b10c9e1247/CMakeLists.txt#L464)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Wouldn't this change make C++ compiler required for building toxav? This is a bit undesirable since it's not actually necessary for building toxav. For example, when building toxcore in Docker you generally want to install as few packages as necessary to save time and disk space.
</blockquote></details>

As you have noted, cmake requires a C++ compiler regardless. I agree, it'll add a few seconds to the build, maybe up to 10 on a slow system/network, but adding more ifs around it adds maintenance cost for rare and negligible benefit (libstdc++ is 1.5M). We can reconsider if this actually becomes a problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/711)*

**Comment by nurupo** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 464 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/711#-L3L7n9LD0BO17WvxpRL:-L3LRCaIQ7p-yXg9tQey:b-707uld) ([raw file](https://github.com/toktok/c-toxcore/blob/6898fbc286245d8fa37f85c0c3abcd4c7dcd540c/CMakeLists.txt#L464)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

As you have noted, cmake requires a C++ compiler regardless. I agree, it'll add a few seconds to the build, maybe up to 10 on a slow system/network, but adding more ifs around it adds maintenance cost for rare and negligible benefit (libstdc++ is 1.5M). We can reconsider if this actually becomes a problem.
</blockquote></details>

CMake requires C++ compiler regardless? I didn't know that. I only noted that this change will now make toxcore's cmake require C++ compiler, when before this change that wasn't the case. If CMake, and I'm not talking about toxcore's cmake setup but the actual CMake software, does indeed require C++ compiler for C projects, then alright. I was under the impression it didn't.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/711)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 464 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/711#-L3L7n9LD0BO17WvxpRL:-L3LTi5fgVA0CLZasbZt:bfw4181) ([raw file](https://github.com/toktok/c-toxcore/blob/6898fbc286245d8fa37f85c0c3abcd4c7dcd540c/CMakeLists.txt#L464)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

CMake requires C++ compiler regardless? I didn't know that. I only noted that this change will now make toxcore's cmake require C++ compiler, when before this change that wasn't the case. If CMake, and I'm not talking about toxcore's cmake setup but the actual CMake software, does indeed require C++ compiler for C projects, then alright. I was under the impression it didn't.
</blockquote></details>

Yeah, you are right, CMake does require C++ compiler for C projects, just did a fast test in a docker container:

```sh
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:19 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/root/c-toxcore/build/CMakeFiles/CMakeOutput.log".
See also "/root/c-toxcore/build/CMakeFiles/CMakeError.log".
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/711#-:-L3LTyyl5TQT5Z34rP72:b-jbsf8z)*

**Comment by nurupo** [comment]
:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[CMakeLists.txt, line 464 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/711#-L3L7n9LD0BO17WvxpRL:-L3LU_URvFvTnk3Sb-Yi:b-x44onb) ([raw file](https://github.com/toktok/c-toxcore/blob/6898fbc286245d8fa37f85c0c3abcd4c7dcd540c/CMakeLists.txt#L464)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Yeah, you are right, CMake does require C++ compiler for C projects, just did a fast test in a docker container:

```sh
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:19 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/root/c-toxcore/build/CMakeFiles/CMakeOutput.log".
See also "/root/c-toxcore/build/CMakeFiles/CMakeError.log".
```
</blockquote></details>

Wait a moment, C++ compiler is required only because we don't specify the programming lanauge of the `toxcore` project in

```CMake
project(toxcore)
```

If you set it to

```CMake
project(toxcore C)
```
 then it doesn't look for C++ compiler. I wonder if there is a way to add a language on a condition, like we have this `COMPILE_AS_CXX`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/711#-:-L3LV5G6SubEuAoYe_op:b8b79qu)*

**Comment by iphydf** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 463 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/711#-L3LZ0dcw4UWoE4Hdg6X:-L3OCAAs_rkDV7QZUYog:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/6898fbc286245d8fa37f85c0c3abcd4c7dcd540c/CMakeLists.txt#L463)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

> add_c_executable

Adding CXX executable using `add_c_executable` function. Perhaps the function doesn't live up to its name and the name should be changed?
</blockquote></details>

Done.

---

*[CMakeLists.txt, line 464 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/711#-L3L7n9LD0BO17WvxpRL:-L3OCFPle_kKjcMX1VGg:b-1s5lro) ([raw file](https://github.com/toktok/c-toxcore/blob/6898fbc286245d8fa37f85c0c3abcd4c7dcd540c/CMakeLists.txt#L464)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

[Found it. You can optionally enable C++](https://cmake.org/cmake/help/v3.0/command/enable_language.html). So we could have toxcore as a C project by default but enable C++ if `COMPILE_AS_CXX` is specified.

```CMake
project(toxcore C)

if(COMPILE_AS_CXX)
    language_enable(CXX)
endif()
```

You will also need to put a `if(COMPILE_AS_CXX)` around `add_cxx_flag()`.

So, what do you say about this (about making the C++ compiler optional)? Should probably be a separate PR, so I will let this go through.
</blockquote></details>

Maybe separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/711)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/711#-:-L3PKlnPkA5JUac2N7Sj:b-jbsf8z)*

**Pull request merged**
