### PR TITLE
Clarify that the pass key `new` function can fail.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/409)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/409#-:-Ka0vagIqxO0TlSqly5u:bg7igkv)*

**Comment by robinlinden** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/409)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toxencryptsave/toxencryptsave.api.h, line 168 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/409#-Ka8cIgnEfCiBckg_bAD:-Ka8cIgnEfCiBckg_bAE:bamtutz) ([raw file](https://github.com/toktok/c-toxcore/blob/1cfcda98f620623706d4228f2768946f2d4f6947/toxencryptsave/toxencryptsave.api.h#L168)):*
> ```objc
>  * @param ciphertext_len The length of the cipher text array. At least $PASS_ENCRYPTION_EXTRA_LENGTH.
>  * @param passphrase The user-provided password. Can be empty or NULL.
>  * @param passphrase_len The length of the password. Must be 0 if passphrase is NULL.
> ```

Does it really have to be `0`? IMO it would be better to ignore it if `passphrase` is `NULL`

---

*[toxencryptsave/toxencryptsave.api.h, line 204 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/409#-Ka8c4JUSTbuPCUtX8gE:-Ka8c4JUSTbuPCUtX8gF:buysnt3) ([raw file](https://github.com/toktok/c-toxcore/blob/1cfcda98f620623706d4228f2768946f2d4f6947/toxencryptsave/toxencryptsave.api.h#L204)):*
> ```objc
>    * initialise it, use one of the derive_* functions below.
>    *
>    * In case of allocation failure, this function returns NULL.
> ```

Only on allocation failure? Else it would be better to write `In case of failure`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/409)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toxencryptsave/toxencryptsave.api.h, line 168 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/409#-Ka8cIgnEfCiBckg_bAD:-Ka8cg37vvkfeMP0Bake:b-lh4bmq) ([raw file](https://github.com/toktok/c-toxcore/blob/1cfcda98f620623706d4228f2768946f2d4f6947/toxencryptsave/toxencryptsave.api.h#L168)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Does it really have to be `0`? IMO it would be better to ignore it if `passphrase` is `NULL`
</blockquote></details>

Why do you think it would be better? If you pass NULL, but a non-zero length, you indicate that you want the function to read more than 0 bytes from the password, which is invalid. Reading exactly 0 bytes from a NULL pointer is valid.

---

*[toxencryptsave/toxencryptsave.api.h, line 204 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/409#-Ka8c4JUSTbuPCUtX8gE:-Ka8nkwojkswYFFm26pK:btm47qd) ([raw file](https://github.com/toktok/c-toxcore/blob/1cfcda98f620623706d4228f2768946f2d4f6947/toxencryptsave/toxencryptsave.api.h#L204)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Only on allocation failure? Else it would be better to write `In case of failure`.
</blockquote></details>

Allocation failure is the only possible failure here. The only thing this function will ever do (in this version of the API) is call `malloc`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/409)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toxencryptsave/toxencryptsave.api.h, line 168 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/409#-Ka8cIgnEfCiBckg_bAD:-Ka9DAa-sFD01KbcyLjm:b-xnvs6v) ([raw file](https://github.com/toktok/c-toxcore/blob/1cfcda98f620623706d4228f2768946f2d4f6947/toxencryptsave/toxencryptsave.api.h#L168)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Why do you think it would be better? If you pass NULL, but a non-zero length, you indicate that you want the function to read more than 0 bytes from the password, which is invalid. Reading exactly 0 bytes from a NULL pointer is valid.
</blockquote></details>

If the function throws an error when `passphrase == NULL` AND ` passphrase != 0` it's ok for me.

---

*[toxencryptsave/toxencryptsave.api.h, line 204 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/409#-Ka8c4JUSTbuPCUtX8gE:-Ka9DRNbSbpKb4Xg4fmB:bdfvc1g) ([raw file](https://github.com/toktok/c-toxcore/blob/1cfcda98f620623706d4228f2768946f2d4f6947/toxencryptsave/toxencryptsave.api.h#L204)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Allocation failure is the only possible failure here. The only thing this function will ever do (in this version of the API) is call `malloc`.
</blockquote></details>

Removing `allocation` from the sentence also removes the thought "are there any other failure modes I have to care for?" from the API users mind, which is IMO a good thing. But if you don't see this as a problem leave it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/409)*

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[toxencryptsave/toxencryptsave.api.h, line 168 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/409#-Ka8cIgnEfCiBckg_bAD:-Ka9RVj_W5ol5Jz3wYHW:bsudxaf) ([raw file](https://github.com/toktok/c-toxcore/blob/1cfcda98f620623706d4228f2768946f2d4f6947/toxencryptsave/toxencryptsave.api.h#L168)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

If the function throws an error when `passphrase == NULL` AND ` passphrase != 0` it's ok for me.
</blockquote></details>

Actually, this is incorrect. I just checked. The API is inconsistent: it returns an error when passphrase is NULL here. `tox_pass_key_derive_with_salt` on the other hand accepts it. Amended.

---

*[toxencryptsave/toxencryptsave.api.h, line 204 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/409#-Ka8c4JUSTbuPCUtX8gE:-Ka9SChaZ8Vb9enabpg5:b-eowr3y) ([raw file](https://github.com/toktok/c-toxcore/blob/1cfcda98f620623706d4228f2768946f2d4f6947/toxencryptsave/toxencryptsave.api.h#L204)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Removing `allocation` from the sentence also removes the thought "are there any other failure modes I have to care for?" from the API users mind, which is IMO a good thing. But if you don't see this as a problem leave it.
</blockquote></details>

Clarified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/409)*

**Comment by robinlinden** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/409)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/409#-:-Ka9kR83Agtb-GiuqQoR:b-jbsf8z)*

**Comment by sudden6** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/409)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/409#-:-KaF98wLEiG0rs8J5i6l:b-jbsf8z)*

**Comment by nurupo** [comment]
:lgtm_strong:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/409#-:-KaK8lxh9JvwLH3o6b5s:b-jbsf8z)*

**Comment by nurupo** [comment]
@iphydf you forgot to reword the commit message, it still says

>Also clarify that passwords can be empty or NULL.

**Pull request merged**
