### PR TITLE
Improve conference test stability.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/742)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[auto_tests/conference_test.c, line 98 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/742#-L4GhWBSZXJtq6BDO-au:-L4GhWBSZXJtq6BDO-av:b8mzw8i) ([raw file](https://github.com/toktok/c-toxcore/blob/c687b666b7a01f566cd414ddfc0de26983c82a75/auto_tests/conference_test.c#L98)):*
> ```C
>     for (unsigned i = 0; i < NUM_GROUP_TOX; ++i) {
>         TOX_ERR_NEW err;
>         tox_index[i] = i + 1;
> ```

This seems pretty useless, why not just use `i` and let indices start at zero?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/742)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[auto_tests/conference_test.c, line 98 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/742#-L4GhWBSZXJtq6BDO-au:-L4GltSgTQNLf3OJxaZn:b-sm9e38) ([raw file](https://github.com/toktok/c-toxcore/blob/c687b666b7a01f566cd414ddfc0de26983c82a75/auto_tests/conference_test.c#L98)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

This seems pretty useless, why not just use `i` and let indices start at zero?
</blockquote></details>

People tend to think better in terms of 1-based indices, but ok. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/742)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[auto_tests/conference_test.c, line 98 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/742#-L4GhWBSZXJtq6BDO-au:-L4Gs1V1WiWjtp7YE5UC:b54pk97) ([raw file](https://github.com/toktok/c-toxcore/blob/d9413d557696e3aecde9d019e1738e99882d4579/auto_tests/conference_test.c#L98)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

People tend to think better in terms of 1-based indices, but ok. Done.
</blockquote></details>

Yeah, I'm actually against this. I've reverted it. All the other tests call their toxes "tox1, tox2, etc.", so I'm keeping the 1-based index here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/742)*

**Comment by sudden6** [comment]
*[auto_tests/conference_test.c, line 98 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/742#-L4GhWBSZXJtq6BDO-au:-L4HHch1bOEqIN6Sd9Kf:b-ermwjd) ([raw file](https://github.com/toktok/c-toxcore/blob/d9413d557696e3aecde9d019e1738e99882d4579/auto_tests/conference_test.c#L98)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Yeah, I'm actually against this. I've reverted it. All the other tests call their toxes "tox1, tox2, etc.", so I'm keeping the 1-based index here.
</blockquote></details>

Ok, just struck me as odd, since programmers usually use zero-based indexing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/742)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/742#-:-L4HHn3f7sbMpNVqxFUs:b-jbsf8z)*

**Pull request merged**
