### PR TITLE
Beginnings of a TCP_test.c overhaul

### PR DESCRIPTION
**Pull request by hugbubby**
This will be one of many modifications to the autotests to make their unit tests easier to read and more comprehensive. Obviously this pull request does not conclude the work on this unit test but I like to get a pull request in early to see if my style works for you.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/921)

### CODE REVIEW

**Comment by hugbubby** [comment]
Damnit, what's up I thought I already checked that this built correctly

**Comment by hugbubby** [comment]
Ah, forgive me, I was unfamiliar witht he testing framework you guys used. Probably something I should've checked out before submitting this PR.

**Comment by iphydf** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[auto_tests/TCP_test.c, line 64 at r2](https://reviewable.io/reviews/toktok/c-toxcore/921#-LFS8BXIDT-rXyLInCxi:-LFS8BXIDT-rXyLInCxj:b-xkhbqo) ([raw file](https://github.com/toktok/c-toxcore/blob/264feaa38430380f63db66123d8b3b61e7fa95af/auto_tests/TCP_test.c#L64)):*
> ```C
>     IP_Port ip_port_loopback;
>     ip_port_loopback.ip = get_loopback();
>     int ret;
> ```

Remove this "int ret", instead put it into the loop. Then add "int ret" below, at encrypt_data.

---

*[auto_tests/TCP_test.c, line 65 at r2](https://reviewable.io/reviews/toktok/c-toxcore/921#-LFS80IEDRxJ_GBzM1J0:-LFS80IEDRxJ_GBzM1J1:b-kniumi) ([raw file](https://github.com/toktok/c-toxcore/blob/264feaa38430380f63db66123d8b3b61e7fa95af/auto_tests/TCP_test.c#L65)):*
> ```C
>     ip_port_loopback.ip = get_loopback();
>     int ret;
>     for(uint8_t i = 0; i < NUM_PORTS; i++)
> ```

Space after "for".

---

*[auto_tests/TCP_test.c, line 66 at r2](https://reviewable.io/reviews/toktok/c-toxcore/921#-LFS7tumAW1WvluXotzR:-LFS7tun7qV_Mvba6B23:b-9iqu1c) ([raw file](https://github.com/toktok/c-toxcore/blob/264feaa38430380f63db66123d8b3b61e7fa95af/auto_tests/TCP_test.c#L66)):*
> ```C
>     int ret;
>     for(uint8_t i = 0; i < NUM_PORTS; i++)
>     {
> ```

Put the brace on the same line as the closing parenthesis.

---

*[auto_tests/TCP_test.c, line 68 at r2](https://reviewable.io/reviews/toktok/c-toxcore/921#-LFS7yNY-I3FzF5LfliP:-LFS7yNZ6U6mHIlLk-Mh:bvc7j8k) ([raw file](https://github.com/toktok/c-toxcore/blob/264feaa38430380f63db66123d8b3b61e7fa95af/auto_tests/TCP_test.c#L68)):*
> ```C
>     {
>         ip_port_loopback.port = net_htons(ports[i]);
>         ret = net_connect(sock, ip_port_loopback);	
> ```

Remove trailing whitespace.

---


*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/921)*

**Comment by hugbubby** [comment]
thank you iphydf senpai, changes made

**Comment by iphydf** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[auto_tests/TCP_test.c, line 52 at r4](https://reviewable.io/reviews/toktok/c-toxcore/921#-LFTjHVGAqS8-w0Xj-xJ:-LFTjHVGAqS8-w0Xj-xK:b-dhtyad) ([raw file](https://github.com/toktok/c-toxcore/blob/78f86a3519ec03e1d967fe68fd5d897167880b45/auto_tests/TCP_test.c#L52)):*
> ```C
> START_TEST(test_basic)
> {
>     //Attempt to create a new TCP_Server instance.
> ```

Space after `//`.

---

*[auto_tests/TCP_test.c, line 73 at r4](https://reviewable.io/reviews/toktok/c-toxcore/921#-LFTjKKR6zX--jTu9Ug3:-LFTjKKR6zX--jTu9Ug4:b-4le7pn) ([raw file](https://github.com/toktok/c-toxcore/blob/78f86a3519ec03e1d967fe68fd5d897167880b45/auto_tests/TCP_test.c#L73)):*
> ```C
> 
>         //Leave open one connection for the next test.
>         if (i + 1 < NUM_PORTS) {
> ```

`if (i != 0)` has the same effect but is simpler.

---


*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/921)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r5.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/921#-:-LFU9sLK7kbzV72K_Tmr:b-jbsf8z)*

**Comment by iphydf** [comment]
Thanks! Please squash all your commits into a single commit.

**Pull request merged**
