### PR TITLE
refactor: extract each case in handle packet in messenger

### PR DESCRIPTION
**Pull request by Green-Sky**
alternative / continuation of #2328 using `case:  return` to satisfy cimple

- - -
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2329)

### CODE REVIEW

**Review by Tha14 — APPROVED** [review]
Functioning

**Review by JFreegman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2329)* status: 0 of 1 approvals obtained (waiting on @Green-Sky)

___
*[`toxcore/Messenger.c` line 1942 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2329#-NCLiubb4XSsgJzlApsD:-NCLiubb4XSsgJzlApsE:b-nokny8) ([raw file](https://github.com/toktok/c-toxcore/blob/58e250a87f6507d1a1052175c4307b9f41a40226/toxcore/Messenger.c#L1942)):*
> ```C
> 
> non_null(1, 3) nullable(5)
> static int m_handle_packet_offline(Messenger *m, const int i, const uint8_t *data, const uint16_t data_length, void *userdata)
> ```

This function can be simplified:



_Code snippet:_
```C
if (clause) { 
  do_thing();  
} 

return 0;
```
___
*[`toxcore/Messenger.c` line 2271 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2329#-NCLf10Y9AboHHMshbDL:-NCLf10Y9AboHHMshbDM:bfjotxg) ([raw file](https://github.com/toktok/c-toxcore/blob/58e250a87f6507d1a1052175c4307b9f41a40226/toxcore/Messenger.c#L2271)):*
> ```C
> 
>     switch (packet_id) {
>         // TODO(Green-Sky): now all return 0 on error AND success, make errors errors?
> ```

This was the case to begin with, best to leave it as-is for now.
___
*[`toxcore/Messenger.c` line 2298 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2329#-NCLeJmg3_tBAJFTCZsw:-NCLeJmhAUAxASy7DEOg:b49ysl5) ([raw file](https://github.com/toktok/c-toxcore/blob/58e250a87f6507d1a1052175c4307b9f41a40226/toxcore/Messenger.c#L2298)):*
> ```C
>     }
> 
>     return m_handle_custom_lossless_packet(object, i, temp, len, userdata);
> ```

Should this go under a default case? Logically makes no difference but I think it might be cleaner.

**Review by Green-Sky — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2329)* status: 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[`toxcore/Messenger.c` line 1942 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2329#-NCLiubb4XSsgJzlApsD:-NCLqPQ2CiDk6wLtpRFu:b-3lon2o) ([raw file](https://github.com/toktok/c-toxcore/blob/58e250a87f6507d1a1052175c4307b9f41a40226/toxcore/Messenger.c#L1942)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

This function can be simplified:
</blockquote></details>

what is this packet for anyway?
___
*[`toxcore/Messenger.c` line 2271 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2329#-NCLf10Y9AboHHMshbDL:-NCLqdbh4sz_a_3fdMag:bg1xhg1) ([raw file](https://github.com/toktok/c-toxcore/blob/58e250a87f6507d1a1052175c4307b9f41a40226/toxcore/Messenger.c#L2271)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

This was the case to begin with, best to leave it as-is for now.
</blockquote></details>

yes, that's why i put this TODO
___
*[`toxcore/Messenger.c` line 2298 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2329#-NCLeJmg3_tBAJFTCZsw:-NCLqj18Ami4ziXSJAc-:b-hy0j1e) ([raw file](https://github.com/toktok/c-toxcore/blob/58e250a87f6507d1a1052175c4307b9f41a40226/toxcore/Messenger.c#L2298)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Should this go under a default case? Logically makes no difference but I think it might be cleaner.
</blockquote></details>

but then we cant have a final `return 0;` at the end of the function. imo it looks better like this, but that's personal preference.

**Review by JFreegman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2329)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Green-Sky)

___
*[`toxcore/Messenger.c` line 1942 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2329#-NCLiubb4XSsgJzlApsD:-NCLt6piA2GZVJ6Aq_NI:b7r0t1y) ([raw file](https://github.com/toktok/c-toxcore/blob/58e250a87f6507d1a1052175c4307b9f41a40226/toxcore/Messenger.c#L1942)):*
<details><summary><i>Previously, Green-Sky (Erik Scholz) wrote…</i></summary><blockquote>

what is this packet for anyway?
</blockquote></details>

It's self-explanatory if you follow the call stack
___
*[`toxcore/Messenger.c` line 2298 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2329#-NCLeJmg3_tBAJFTCZsw:-NCLtCYhArUdbLlzFaMo:bbj9bw3) ([raw file](https://github.com/toktok/c-toxcore/blob/58e250a87f6507d1a1052175c4307b9f41a40226/toxcore/Messenger.c#L2298)):*
<details><summary><i>Previously, Green-Sky (Erik Scholz) wrote…</i></summary><blockquote>

but then we cant have a final `return 0;` at the end of the function. imo it looks better like this, but that's personal preference.
</blockquote></details>

Yeah I suppose that's true.

**Review by Green-Sky — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2329)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Green-Sky and @JFreegman)

___
*[`toxcore/Messenger.c` line 2298 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2329#-NCLeJmg3_tBAJFTCZsw:-NCLzcV49nOaKTQmGOtf:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/58e250a87f6507d1a1052175c4307b9f41a40226/toxcore/Messenger.c#L2298)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Yeah I suppose that's true.
</blockquote></details>

Done.

**Pull request merged**
