### PR TITLE
feat: add ngc Events

### PR DESCRIPTION
**Pull request by Green-Sky**
most lines where autogenerated

- - -
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2378)

### CODE REVIEW

**Comment by Tha14** [comment]
Fuzzers seem to work good to me when I run the locally.

**Comment by Green-Sky** [comment]
had the event_fuzzer running for a while
```
#766218921	REDUCE cov: 1218 ft: 3344 corp: 1236/129Kb lim: 4096 exec/s: 83776 rss: 633Mb L: 332/3848 MS: 2 InsertByte-EraseBytes-
#766645022	REDUCE cov: 1218 ft: 3344 corp: 1236/129Kb lim: 4096 exec/s: 83777 rss: 633Mb L: 435/3848 MS: 1 EraseBytes-
#767340340	REDUCE cov: 1218 ft: 3344 corp: 1236/129Kb lim: 4096 exec/s: 83770 rss: 633Mb L: 255/3848 MS: 1 EraseBytes-
#768279758	REDUCE cov: 1218 ft: 3344 corp: 1236/129Kb lim: 4096 exec/s: 83754 rss: 633Mb L: 77/3848 MS: 2 ChangeASCIIInt-EraseBytes-
#768588187	REDUCE cov: 1218 ft: 3344 corp: 1236/129Kb lim: 4096 exec/s: 83751 rss: 633Mb L: 328/3848 MS: 1 EraseBytes-
#768703483	REDUCE cov: 1218 ft: 3344 corp: 1236/129Kb lim: 4096 exec/s: 83745 rss: 633Mb L: 410/3848 MS: 1 EraseBytes-
#768810329	REDUCE cov: 1218 ft: 3344 corp: 1236/129Kb lim: 4096 exec/s: 83748 rss: 633Mb L: 176/3848 MS: 3 EraseBytes-ChangeByte-PersAutoDict- DE: "\x00%"-
#768845221	REDUCE cov: 1218 ft: 3344 corp: 1236/129Kb lim: 4096 exec/s: 83743 rss: 633Mb L: 163/3848 MS: 2 ShuffleBytes-EraseBytes-
==2693886== libFuzzer: run interrupted; exiting
```

**Review by JFreegman — COMMENTED** [review]
This PR is too massive to review line by line. We need some autotests for it.

> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2378#-:-NRsS1QfEg7qO7fdRdjh:bo7wrpp)* status: 0 of 1 approvals obtained

**Comment by Green-Sky** [comment]
note to self: need to adopt to changes made in https://github.com/TokTok/c-toxcore/pull/2415

**Comment by Green-Sky** [comment]
updated version merged into #2392

**Pull request closed without merging**
