### PR TITLE
Add DHT_create_packet, an abstraction for DHT RPC packets

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/224)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[toxcore/DHT.c, line 1227 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVMQlMg6AHquIRozHm9:-KVMQlMg6AHquIRozHmA:b-y843di) ([raw file](https://github.com/toktok/c-toxcore/blob/7ddf542fe7eb858c1adfc000e7520ec677f6fef4/toxcore/DHT.c#L1227)):*
> ```C
> 
>     size_t len = DHT_create_packet(dht->self_public_key, shared_key, NET_PACKET_GET_NODES, plain, sizeof(plain), data);
>     if (len == -1) {
> ```

`size_t` can not be negative.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[toxcore/DHT.c, line 292 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVQVdu_fCEthid3pqCj:-KVQVdu_fCEthid3pqCk:bhm8wsj) ([raw file](https://github.com/toktok/c-toxcore/blob/23c241ed328060bddf975d27969cf47c0676b195/toxcore/DHT.c#L292)):*
> ```C
> 
> static int DHT_create_packet(const uint8_t public_key[crypto_box_PUBLICKEYBYTES],
>                              const uint8_t *shared_key, const uint8_t type, uint8_t *plain, size_t length, uint8_t *packet){
> ```

Run other/astyle/format-source.

---

*[toxcore/DHT.c, line 1226 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVQVTPFj2NMCwsfObEh:-KVQVTPFj2NMCwsfObEi:b-r2hg6r) ([raw file](https://github.com/toktok/c-toxcore/blob/23c241ed328060bddf975d27969cf47c0676b195/toxcore/DHT.c#L1226)):*
> ```C
>     DHT_get_shared_key_sent(dht, shared_key, public_key);
> 
>     ssize_t len = DHT_create_packet(dht->self_public_key, shared_key, NET_PACKET_GET_NODES, plain, sizeof(plain), data);
> ```

`DHT_create_packet` returns `int`. Unless you have a very good reason for an implicit conversion here, please use consistent types.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224)*

**Comment by GrayHatter** [comment]
will re-review once @iphydf's comments are resolved

**Comment by GrayHatter** [comment]
@tux3 welcome back mate

**Comment by tux3** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[toxcore/DHT.c, line 311 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVUnVhrMW9pOC5rXUaN:-KVUnVhtfF6MbGcoQ7GY:bz4ecwu) ([raw file](https://github.com/toktok/c-toxcore/blob/23c241ed328060bddf975d27969cf47c0676b195/toxcore/DHT.c#L311)):*
> ```C
>     memcpy(packet + 1, public_key, crypto_box_PUBLICKEYBYTES);
>     memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES, nonce, crypto_box_NONCEBYTES);
>     memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES, encrypt, length);
> ```

Is the MAC being discarded intentionally here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224)*

**Comment by endoffile78** [comment]
*[toxcore/DHT.c, line 311 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVUnVhrMW9pOC5rXUaN:-KVWvACauS2HvVFucxiY:b-vsxx5g) ([raw file](https://github.com/toktok/c-toxcore/blob/23c241ed328060bddf975d27969cf47c0676b195/toxcore/DHT.c#L311)):*
<details><summary><i>Previously, tux3 (Tux3) wrote…</i></summary>
> Is the MAC being discarded intentionally here?
</details>
That is how it was done originally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224)*

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[toxcore/DHT.c, line 311 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVUnVhrMW9pOC5rXUaN:-KVYliERHYXQjxTYfN1h:b-53l59w) ([raw file](https://github.com/toktok/c-toxcore/blob/23c241ed328060bddf975d27969cf47c0676b195/toxcore/DHT.c#L311)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary>
> That is how it was done originally.
</details>
No, @endoffile78 you're returning the wrong `length` var.

the original uses `len`,  ( the result of encrypt_data_symmetric() ) , you're using length, which is the clear text length.

---

*[toxcore/DHT.c, line 298 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVYi7X-TsijvOiGk1gk:-KVYi7X-TsijvOiGk1gl:bpmr8kv) ([raw file](https://github.com/toktok/c-toxcore/blob/bb4a4d58743371e552a64ebe6cd6c1538edf9448/toxcore/DHT.c#L298)):*
> ```C
>     new_nonce(nonce);
> 
>     int len = encrypt_data_symmetric(shared_key,
> ```

this can all be one line.

---

*[toxcore/DHT.c, line 313 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVYm0em7bmU9aEuFTM9:-KVYm0ennH9a-5WrX-M8:bp1bcy6) ([raw file](https://github.com/toktok/c-toxcore/blob/bb4a4d58743371e552a64ebe6cd6c1538edf9448/toxcore/DHT.c#L313)):*
> ```C
>     memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES, encrypt, length);
> 
>     return 1 + crypto_box_MACBYTES + crypto_box_NONCEBYTES + length;
> ```

This needs to be `len`, not `length`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[toxcore/DHT.c, line 292 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVQVdu_fCEthid3pqCj:-KVamL76kD9O7gbcKjVF:bm4tbl6) ([raw file](https://github.com/toktok/c-toxcore/blob/23c241ed328060bddf975d27969cf47c0676b195/toxcore/DHT.c#L292)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Run other/astyle/format-source.
</details>
If that didn't do anything, please add a space between `)` and `{` manually.

---

*[toxcore/DHT.c, line 298 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVYi7X-TsijvOiGk1gk:-KVamPrmvqtCj3BC69A6:batbu0b) ([raw file](https://github.com/toktok/c-toxcore/blob/bb4a4d58743371e552a64ebe6cd6c1538edf9448/toxcore/DHT.c#L298)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> this can all be one line.
</details>
Yes, but it doesn't have to be. It can be on two lines. It's mildly annoying to have >80 characters, because of line breaks in both github side by side diff views and reviewable.

---

*[toxcore/DHT.c, line 313 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVYm0em7bmU9aEuFTM9:-KVamltihaGVmbk2ZKsv:bjm7nv) ([raw file](https://github.com/toktok/c-toxcore/blob/bb4a4d58743371e552a64ebe6cd6c1538edf9448/toxcore/DHT.c#L313)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> This needs to be `len`, not `length`
</details>
@endoffile78 can you write a unit test for this function that fails if you do this wrong?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224)*

**Comment by GrayHatter** [comment]
*[toxcore/DHT.c, line 313 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVYm0em7bmU9aEuFTM9:-KVaozv6DL5HRaw0rdNQ:b-f8r3bk) ([raw file](https://github.com/toktok/c-toxcore/blob/bb4a4d58743371e552a64ebe6cd6c1538edf9448/toxcore/DHT.c#L313)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> @endoffile78 can you write a unit test for this function that fails if you do this wrong?
</details>
the last test in my tox-named pull can serve as an example for what the test could look like

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224)*

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[toxcore/DHT.c, line 298 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVYi7X-TsijvOiGk1gk:-KVcxvZlx9B2DsMA0JNz:bazi772) ([raw file](https://github.com/toktok/c-toxcore/blob/bb4a4d58743371e552a64ebe6cd6c1538edf9448/toxcore/DHT.c#L298)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Yes, but it doesn't have to be. It can be on two lines. It's mildly annoying to have >80 characters, because of line breaks in both github side by side diff views and reviewable.
</details>
1 or 2 I'm okay with. 6 I'm not. 

Your call @endoffile78 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224)*

**Comment by iphydf** [comment]
@endoffile78: I'd like to release 0.0.3 this Sunday. Will this change be ready by then?

**Comment by endoffile78** [comment]
@iphydf Yes. Sorry I've been kind of busy I just need to finish the test.

**Comment by GrayHatter** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[auto_tests/dht_test.c, line 662 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVlmDt_y0EdB6pkX3oB:-KVlmDtaiqRHInc5Fl9U:bi9imgp) ([raw file](https://github.com/toktok/c-toxcore/blob/579e13a7550c97444a575580e56a8cca1b5946e6/auto_tests/dht_test.c#L662)):*
> ```C
>     ck_assert_msg(pkt[0] == NET_PACKET_GET_NODES, "Malformed packet.");
>     ck_assert_msg(length != sizeof(pkt), "Invalid size. Should be %d got %d", sizeof(pkt), length);
>     ck_assert_msg(memcmp(pkt + 1, key, crypto_box_KEYBYTES) == 0, "Malformed packet.");
> ```

You're comparing the key to the nonce, this should fail. Don't fix it until Travis finished please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224)*

**Comment by endoffile78** [comment]
@GrayHatter the key is added before the nonce.

```c
packet[0] = type;
memcpy(packet + 1, public_key, crypto_box_PUBLICKEYBYTES);
memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES, nonce, crypto_box_NONCEBYTES);
memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES, encrypt, len);
```

**Comment by GrayHatter** [comment]
I've unassigned myself, as I've contributed code I can't review this. 

@tux3 has signed off on this via IRC, with any luck I can pester him to confirm in reviewable as well. (If not I'll signoff for him.

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[toxcore/DHT.c, line 379 at r7](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVtvizQ2ThOgdb3ffjD:-KVtvizRC2F7kfHAOZF1:b-lqas0c) ([raw file](https://github.com/toktok/c-toxcore/blob/9f5ec36233661b5c658e2ed4475d0743e166cfe0/toxcore/DHT.c#L379)):*
> ```C
>     new_nonce(nonce);
> 
>     int len = encrypt_data_symmetric(shared_key, nonce,
> ```

Can you rename this? Now we have a `len` and a `length`, so it's easy to mix them up. What is this the length of? Name it according to that. Perhaps `encrypted_length`, and rename `encrypt` to `encrypted`, since `encrypt` is a verb, which makes it look like a function when it's not. You could also rename `length` to `plain_length` for consistency and clarity.

---

*[toxcore/DHT.c, line 1309 at r7](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVtwXOtOX2gFnqkrzD_:-KVtwXOtOX2gFnqkrzDa:b-9zs8sg) ([raw file](https://github.com/toktok/c-toxcore/blob/9f5ec36233661b5c658e2ed4475d0743e166cfe0/toxcore/DHT.c#L1309)):*
> ```C
>         return -1;
>     }
>     return sendpacket(dht->net, ip_port, data, len);
> ```

Is `len` not equal to `sizeof data` here? Please add an `assert` above this line expressing the relationship between the two.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224)*

**Comment by tux3** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r6, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-:-KVv0S0e_XOPWe0fxRoO:b-jbsf8z)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r6, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-:-KVv6kGwuBzrNEmIX23i:b-jbsf8z)*

**Comment by endoffile78** [comment]
Review status: 0 of 18 files reviewed at latest revision, 8 unresolved discussions.

---

*[toxcore/DHT.c, line 1227 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVMQlMg6AHquIRozHm9:-KVv_154jdp94tqrC8xF:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7ddf542fe7eb858c1adfc000e7520ec677f6fef4/toxcore/DHT.c#L1227)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> `size_t` can not be negative.
</details>
Done.

---

*[toxcore/DHT.c, line 292 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVQVdu_fCEthid3pqCj:-KVv_AvtLTgGhdieIdBM:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/23c241ed328060bddf975d27969cf47c0676b195/toxcore/DHT.c#L292)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> If that didn't do anything, please add a space between `)` and `{` manually.
</details>
Done.

---

*[toxcore/DHT.c, line 311 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVUnVhrMW9pOC5rXUaN:-KVvZx9xVhatEzBIYBbQ:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/23c241ed328060bddf975d27969cf47c0676b195/toxcore/DHT.c#L311)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> No, @endoffile78 you're returning the wrong `length` var.
> 
> the original uses `len`,  ( the result of encrypt_data_symmetric() ) , you're using length, which is the clear text length.
</details>
Done.

---

*[toxcore/DHT.c, line 1226 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVQVTPFj2NMCwsfObEh:-KVv_0GL_uFoDZXKSggx:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/23c241ed328060bddf975d27969cf47c0676b195/toxcore/DHT.c#L1226)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> `DHT_create_packet` returns `int`. Unless you have a very good reason for an implicit conversion here, please use consistent types.
</details>
Done.

---

*[toxcore/DHT.c, line 298 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVYi7X-TsijvOiGk1gk:-KVvZuNatGNVe27mdr35:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/bb4a4d58743371e552a64ebe6cd6c1538edf9448/toxcore/DHT.c#L298)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> 1 or 2 I'm okay with. 6 I'm not. 
> 
> Your call @endoffile78 
</details>
Done.

---

*[toxcore/DHT.c, line 313 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVYm0em7bmU9aEuFTM9:-KVv_Cq4amLwy9lLnUcE:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/bb4a4d58743371e552a64ebe6cd6c1538edf9448/toxcore/DHT.c#L313)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> the last test in my tox-named pull can serve as an example for what the test could look like
</details>
Done.

---

*[toxcore/DHT.c, line 379 at r7](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVtvizQ2ThOgdb3ffjD:-KVvZymA_regxUwuXCfZ:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/31e8d240809c437b055b28933ac00fe851b7291c/toxcore/DHT.c#L379)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Can you rename this? Now we have a `len` and a `length`, so it's easy to mix them up. What is this the length of? Name it according to that. Perhaps `encrypted_length`, and rename `encrypt` to `encrypted`, since `encrypt` is a verb, which makes it look like a function when it's not. You could also rename `length` to `plain_length` for consistency and clarity.
</details>
Done.

---

*[toxcore/DHT.c, line 1309 at r7](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVtwXOtOX2gFnqkrzD_:-KVvZzPB9w5EsYWZJUMy:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/31e8d240809c437b055b28933ac00fe851b7291c/toxcore/DHT.c#L1309)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Is `len` not equal to `sizeof data` here? Please add an `assert` above this line expressing the relationship between the two.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224)*

**Comment by nurupo** [comment]
Reviewed 16 of 18 files at r10.
Review status: 16 of 18 files reviewed at latest revision, 9 unresolved discussions.

---

*[toxcore/DHT.c, line 1211 at r10](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVve1XFrcrLFJUvALDR:-KVve1XFrcrLFJUvALDS:b2n1lh2) ([raw file](https://github.com/toktok/c-toxcore/blob/5019a5aaf9b6e927e7b56b0f808efc01ba62d66a/toxcore/DHT.c#L1211)):*
> ```C
>                                      encrypt);
> 
>     if (len != sizeof(encrypt)) {
> ```

Why was this check replaced with an assert?

---

*[toxcore/DHT.c, line 1266 at r10](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVve8qX5YMYqN8xPUQG:-KVve8qX5YMYqN8xPUQH:b2n1lh2) ([raw file](https://github.com/toktok/c-toxcore/blob/5019a5aaf9b6e927e7b56b0f808efc01ba62d66a/toxcore/DHT.c#L1266)):*
> ```C
>                                      encrypt);
> 
>     if (len != 1 + nodes_length + length + crypto_box_MACBYTES) {
> ```

Why was this check replaced with an assert?

---

*[toxcore/DHT.c, line 1269 at r10](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVvdbYGHRIIJSf9PNtT:-KVvdbYHmog114ixCqdu:b-tzjz0i) ([raw file](https://github.com/toktok/c-toxcore/blob/59e09abe28fe3f5eb9305c30ea0867692df8c15f/toxcore/DHT.c#L1269)):*
> ```C
>     memcpy(plain + 1 + nodes_length, sendback_data, length);
> 
>     uint8_t data[2 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES
> ```

That shouldn't be `2 +` but `1 +` and `1 + ` later. The order of sizes should match the order of things being written into the array. Also, why not just use `sizeof(plain)` for `1 + nodes_length + length`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224)*

**Comment by endoffile78** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[toxcore/DHT.c, line 1211 at r10](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVve1XFrcrLFJUvALDR:-KVwtEALKdRaVfl8p2Po:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/5019a5aaf9b6e927e7b56b0f808efc01ba62d66a/toxcore/DHT.c#L1211)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Why was this check replaced with an assert?
</details>
Done.

---

*[toxcore/DHT.c, line 1266 at r10](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVve8qX5YMYqN8xPUQG:-KVwtlQgqj9h2mcn9MgL:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/5019a5aaf9b6e927e7b56b0f808efc01ba62d66a/toxcore/DHT.c#L1266)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Why was this check replaced with an assert?
</details>
Done.

---

*[toxcore/DHT.c, line 1269 at r10](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-KVvdbYGHRIIJSf9PNtT:-KVwtFkcCtAStU0uYaJX:b-kbwgqw) ([raw file](https://github.com/toktok/c-toxcore/blob/59e09abe28fe3f5eb9305c30ea0867692df8c15f/toxcore/DHT.c#L1269)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> That shouldn't be `2 +` but `1 +` and `1 + ` later. The order of sizes should match the order of things being written into the array. Also, why not just use `sizeof(plain)` for `1 + nodes_length + length`?
</details>
I reorder the length, but we can't use sizeof(plain) it could potentially be bigger than we need. We only need  `1 + node_length + length` but plain is`1 + Node_format_size * MAX_SENT_NODES + length`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224)*

**Comment by GrayHatter** [comment]
replaced nurupo with @robinlinden because nurupo is away, hopefully doing something fun

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 18 files at r10, 1 of 3 files at r11.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-:-KWKWgp-CmDJKZwpHZfg:b-jbsf8z)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 2 of 18 files at r10.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-:-KWK_vsLQaNXClY6DCl1:b-jbsf8z)*

**Comment by GrayHatter** [comment]
:shipit:

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 1 of 18 files at r10, 1 of 3 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/224#-:-KWMkWtsfi8UpSp_BtNH:b-jbsf8z)*

**Pull request merged**
