### PR TITLE
Use more ubuntu packages; remove hstox for now.

### PR DESCRIPTION
**Pull request by iphydf**
Since trusty has more up-to-date packages, we can remove some of the
custom install code. Also, we're not using hstox at the moment, so there
is no need to slow down the builds for now.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/759)

### CODE REVIEW

**Comment by iphydf** [comment]
The build is currently broken without this PR.

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/759#-:-L4VjJ3iMQP51xCn4NWJ:b-jbsf8z)*

**Comment by nurupo** [comment]
:lgtm_strong:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/759#-:-L4_Qelk0iuhG33EmQ5a:b-jbsf8z)*

**Comment by nurupo** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/759)*

**Comment by sudden6** [comment]
*[other/travis/toxcore-linux-install, line 24 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/759#-L4a6YL4nyJb--ev7usX:-L4a6YL5pBEkL997T8P1:bqsg4zf) ([raw file](https://github.com/toktok/c-toxcore/blob/f41c11c34e04e6d7a04cb20f79bc2643c0e33dd1/other/travis/toxcore-linux-install#L24)):*
> ```
> # Install astyle (version in ubuntu-precise too old).
> [ -f $ASTYLE ] || {
>   wget -O ../astyle.tar.gz http://http.debian.net/debian/pool/main/a/astyle/astyle_2.06.orig.tar.gz
> ```

we should use the official load balancer `https://deb.debian.org/`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/759)*

**Pull request merged**
