### PR TITLE
Build tests on appveyor, the MSVC build, but don't run them yet.

### PR DESCRIPTION
**Pull request by iphydf**
---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/556)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[.travis.yml, line 3 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/556#-Klp0J-DNEyIvUdNY4AS:-Klp0J-EzvZgM1qvYbE_:b-2pdx85) ([raw file](https://github.com/toktok/c-toxcore/blob/488b6f6e308c01cced719e3ecef7d283fe74f114/.travis.yml#L3)):*
> ```YAML
> language: c
> 
> # TODO(iphydf): Uncomment this before submitting.
> ```

It seems you forgot this ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/556)*

**Comment by iphydf** [comment]
@Diadlo I'm still working on it.

**Comment by iphydf** [comment]
This is now ready for review.

**Comment by iphydf** [comment]
Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 3 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/556#-Klp0J-DNEyIvUdNY4AS:-Klp_JFOFdjsY0HJvJdv:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/488b6f6e308c01cced719e3ecef7d283fe74f114/.travis.yml#L3)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

It seems you forgot this ;)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/556)*

**Comment by Diadlo** [comment]
Reviewed 28 of 28 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[appveyor.yml, line 11 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/556#-KlqygXebGpqT_8UByE4:-KlqygXfiOd1vujQl_PN:b-d469ap) ([raw file](https://github.com/toktok/c-toxcore/blob/f7af299ea601587b70d00a353cb67366536f51cc/appveyor.yml#L11)):*
> ```YAML
> - if not exist %APPDATA%\downloads mkdir %APPDATA%\downloads
> # libcheck
> - if not exist %APPDATA%\downloads\check.tar.gz curl -L https://github.com/libcheck/check/archive/0.11.0.zip -o %APPDATA%\downloads\check.zip
> ```

You checke the existence of `check.tar.gz` but download `check.zip`

---

*[cmake/Dependencies.cmake, line 69 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/556#-KlqwC3gapmpHeRm6Wu2:-KlqwC3hKk-tss8QBgT7:bcwojdo) ([raw file](https://github.com/toktok/c-toxcore/blob/f7af299ea601587b70d00a353cb67366536f51cc/cmake/Dependencies.cmake#L69)):*
> ```CMake
>   find_library(LIBCHECK_LIBRARIES
>     NAMES check libcheck
>     PATHS "C:/Program Files (x86)/check/lib"
> ```

I think `%ProgramFilesDir%/check/lib` will be better. Same for other "Prgram Files (x86)"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/556)*

**Comment by iphydf** [comment]
Review status: 25 of 27 files reviewed at latest revision, 2 unresolved discussions.

---

*[appveyor.yml, line 11 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/556#-KlqygXebGpqT_8UByE4:-KlsCGyrMajOuRCK3rzx:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/f7af299ea601587b70d00a353cb67366536f51cc/appveyor.yml#L11)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

You checke the existence of `check.tar.gz` but download `check.zip`
</blockquote></details>

Done.

---

*[cmake/Dependencies.cmake, line 69 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/556#-KlqwC3gapmpHeRm6Wu2:-KlsCcLExAO5N7AJzodq:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/f7af299ea601587b70d00a353cb67366536f51cc/cmake/Dependencies.cmake#L69)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I think `%ProgramFilesDir%/check/lib` will be better. Same for other "Prgram Files (x86)"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/556)*

**Comment by nurupo** [comment]
*[CMakeLists.txt, line 397 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/556#-KlsBTTuemjjlEl1l1jY:-KlsBTTvXRHA_M8pa2B2:b-pa08nc) ([raw file](https://github.com/toktok/c-toxcore/blob/f7af299ea601587b70d00a353cb67366536f51cc/CMakeLists.txt#L397)):*
> ```CMake
>       set_tests_properties(${target} PROPERTIES TIMEOUT "${TEST_TIMEOUT_SECONDS}")
>     endif()
>   endif()
> ```

Kind of weird how `DISABLED` test means "build=true, run=false", while `MSVC_DISABLED` means "build=false, run=false". One could think that `MSVC_DISABLED` does exactly what `DISABLED` does but only for MSVC and they would be wrong.

Perhaps changing `DISABLED` to `DONT_RUN` and `MSVC_DISABLED` to `MSVC_DONT_BUILD`, or to something along these lines, would be better? Alternatively, keeping `DISABLED` as it is but removing `MSVC_DISABLED` by pulling the `if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")` out of `auto_test()` would be fine too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/556)*

**Comment by nurupo** [comment]
*[cmake/Dependencies.cmake, line 69 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/556#-KlqwC3gapmpHeRm6Wu2:-KlsENf4ACKUCX0-Zz-2:b-5uzj44) ([raw file](https://github.com/toktok/c-toxcore/blob/f7af299ea601587b70d00a353cb67366536f51cc/cmake/Dependencies.cmake#L69)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't understand what was wrong with using the working directory for everything and doing things relative to its path. You don't install libraries in `Program Files` on Windows. When you develop on Windows, all libraries your program depends on are usually in some directory called "deps" or "3rd-party" next to your source tree. You also ship the libraries together with your software product, so that when you install, say, qTox, all the libraries qTox depends on are in `C:/Program Files (x86)/qTox`, next to `qTox.exe`, not in `C:/Program Files (x86)/tocore`, `C:/Program Files (x86)/opus`, `C:/Program Files (x86)/sodium`, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/556)*

**Comment by nurupo** [comment]
Reviewed 28 of 28 files at r2.
Review status: 25 of 27 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/556)*

**Comment by iphydf** [comment]
Review status: 24 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[CMakeLists.txt, line 397 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/556#-KlsBTTuemjjlEl1l1jY:-KlsH4b_JFWII22vG-La:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/f7af299ea601587b70d00a353cb67366536f51cc/CMakeLists.txt#L397)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Kind of weird how `DISABLED` test means "build=true, run=false", while `MSVC_DISABLED` means "build=false, run=false". One could think that `MSVC_DISABLED` does exactly what `DISABLED` does but only for MSVC and they would be wrong.

Perhaps changing `DISABLED` to `DONT_RUN` and `MSVC_DISABLED` to `MSVC_DONT_BUILD`, or to something along these lines, would be better? Alternatively, keeping `DISABLED` as it is but removing `MSVC_DISABLED` by pulling the `if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")` out of `auto_test()` would be fine too.
</blockquote></details>

Done.

---

*[cmake/Dependencies.cmake, line 69 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/556#-KlqwC3gapmpHeRm6Wu2:-KlsH5VTvwRfqGgIDeyp:b-4pcn7j) ([raw file](https://github.com/toktok/c-toxcore/blob/f7af299ea601587b70d00a353cb67366536f51cc/cmake/Dependencies.cmake#L69)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

I don't understand what was wrong with using the working directory for everything and doing things relative to its path. You don't install libraries in `Program Files` on Windows. When you develop on Windows, all libraries your program depends on are usually in some directory called "deps" or "3rd-party" next to your source tree. You also ship the libraries together with your software product, so that when you install, say, qTox, all the libraries qTox depends on are in `C:/Program Files (x86)/qTox`, next to `qTox.exe`, not in `C:/Program Files (x86)/tocore`, `C:/Program Files (x86)/opus`, `C:/Program Files (x86)/sodium`, etc.
</blockquote></details>

Added an explanation for it. I like to override defaults as little as possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/556)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 22 of 28 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/556#-:-Klti-ebMP-9YOwS06Gy:b-jbsf8z)*

**Pull request merged**
