### PR TITLE
Reverting tox_loop PR changes

### PR DESCRIPTION
**Pull request by nurupo**
Want to see if reverting the tox loop PR would fix OS X tests, before actually looking into the code to see what could have broken them.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/538)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/538#-:-KhqxX24u0izsQ-7_Qty:b-jbsf8z)*

**Comment by nurupo** [comment]
Why lgtm? This isn't meant to be merged.

**Comment by optimumtact** [comment]
lgtm

**Comment by nurupo** [comment]
@robinlinden @iphydf So, do we want to merge this?

**Comment by robinlinden** [comment]
I think we should merge this and ask @Ansa89 to open a new PR with the tox_loop code. I don't want to make a release while OS X is broken.

**Comment by nurupo** [comment]
@vassad It breaks toxcore tests for OSX.

**Comment by vassad** [comment]
@nurupo thx, didn't see this PR ...

**Comment by iphydf** [comment]
I guess this never got its new PR.

**Pull request merged**
