### PR TITLE
add back legacy bitrate change functions

### PR DESCRIPTION
**Pull request by zoff99**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/732)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxav/toxav.c, line 544 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/732#-L3tZI1s5jl83ktYg5Fy:-L3tWuFIDkQufde0DBoT:b-nqxr58) ([raw file](https://github.com/toktok/c-toxcore/blob/f62f641f6c75bfb0cce73f9aea8e7d74fb2f383a/toxav/toxav.c#L544)):*
> ```C
>     if (audio_bit_rate >= 0) {
>         res_audio = toxav_bit_rate_set_audio(av, friend_number,
>                                              audio_bit_rate, &error_audio);
> ```

Personally I would use an early return construct here:
```
if(!res_audio) {
// map error return value
return false
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/732)*

**Comment by xhebox** [comment]
@zoff99 Sorry, for not to request three pull requests, i think better merge my pr first to completely remove namespace bit_rate, and rebase your work. Or we have to open another pull request to add legacy event callback...

Hope you dont mind! Therefore, this pr should add bit_rate event as well as bit_rate_set() at the same time.

**Comment by iphydf** [comment]
@xhebox's change was merged. This now needs a merge and then adding back the old callback.

**Comment by iphydf** [comment]
Closing in favour of the discussed new PR today.

**Comment by zoff99** [comment]
let's leave only the new ones.

**Pull request closed without merging**
