### PR TITLE
Make crypto_memcmp timing test more reliable.

### PR DESCRIPTION
**Pull request by iphydf**
---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/740)

### CODE REVIEW

**Comment by nurupo** [comment]
5% time difference for something that should always take constant time?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/740#-:-L428L9mAfYRBSSArd89:b-rwkepi)*

**Comment by iphydf** [comment]
5% because this is running on a VM which can be more or less busy depending on what other things run there.

**Comment by iphydf** [comment]
In reality it's closer to 0.5% most of the time, sometimes up to 2%, but today I observed 4.5%.

**Comment by iphydf** [comment]
@nurupo done.

**Pull request closed without merging**
