### PR TITLE
Fix LAN discovery on FreeBSD.

### PR DESCRIPTION
**Pull request by iphydf**
Bootstrap is never tested otherwise, and LAN discovery is a prerequisite
for everything else. Having these two tests lets us rule out or identify
LAN discovery as a possible cause for test failures.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/764)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 7 of 13 files at r1.
Review status: 7 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[auto_tests/bootstrap_test.c, line 18 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/764#-L4pPEJsMP8rnfCVPTMD:-L4pPEJsMP8rnfCVPTME:b-vgo920) ([raw file](https://github.com/toktok/c-toxcore/blob/84a5f354cd4e1789919615c8d862ec3f53e1cb2c/auto_tests/bootstrap_test.c#L18)):*
> ```C
>     Tox *tox = tox_new_log(nullptr, nullptr, nullptr);
> 
>     tox_bootstrap(tox, "biribiri.org", 33445, key, nullptr);
> ```

Didn't this change to node.tox.biribiri.org?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/764#-:-L4pQBTOAA01LyXz6a2h:b-jbsf8z)*

**Comment by robinlinden** [comment]
Reviewed 6 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/764)*

**Comment by nurupo** [comment]
Reviewed 2 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[auto_tests/bootstrap_test.c, line 18 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/764#-L4pPEJsMP8rnfCVPTMD:-L4pQstU9VKBc7GWNHZl:bnuagyh) ([raw file](https://github.com/toktok/c-toxcore/blob/84a5f354cd4e1789919615c8d862ec3f53e1cb2c/auto_tests/bootstrap_test.c#L18)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Didn't this change to node.tox.biribiri.org?
</blockquote></details>

Please use node.tox.biribiri.org even if the node is still reachable on biribiri.org.

Also, why not create a local bootstrap node in the test itself and bootstrap off that? I think you can get the DHT key and the UDP port from tox.h, which is all you need for bootstrapping.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/764)*

**Comment by nurupo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[toxcore/LAN_discovery.c, line 355 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/764#-L4pS0uTuAjq6TEtBq1c:-L4pS0uTuAjq6TEtBq1d:b-y34m1b) ([raw file](https://github.com/toktok/c-toxcore/blob/84a5f354cd4e1789919615c8d862ec3f53e1cb2c/toxcore/LAN_discovery.c#L355)):*
>Why should we reject discovery packets from outside the LAN?

Because this feature is called "LAN discovery", so it doesn't make sense to discover outside LAN.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/764)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toxcore/LAN_discovery.c, line 355 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/764#-L4pS0uTuAjq6TEtBq1c:-L4ptreAfZYz1Fpthuhm:blow35) ([raw file](https://github.com/toktok/c-toxcore/blob/84a5f354cd4e1789919615c8d862ec3f53e1cb2c/toxcore/LAN_discovery.c#L355)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

>Why should we reject discovery packets from outside the LAN?

Because this feature is called "LAN discovery", so it doesn't make sense to discover outside LAN.
</blockquote></details>

We're not discovering, but if someone advertises themselves as a bootstrap node via the LAN discovery packet, why not accept it?

Concretely, this condition breaks LAN discovery on systems that aren't in a LAN (so it's just discovery).

Again: why should we reject it? "Because of the name" seems like a weak reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/764)*

**Comment by Diadlo** [comment]
I'm not sure but without rejecting packages outside the LAN intruder can create fake nodes and send a lot of fake "LAN discovery" requests to increase probability of using fake node to work with DHT.
If I'm wrong, still agree with @nurupo

**Comment by iphydf** [comment]
If you have a public IP and someone sends you a LAN discovery packet on that IP, then you will send a "getnodes" packet to them. If you have a public IP and someone sends you a DHT ping packet, then you will send them a DHT pong packet. Either of those exchanges can lead to a DHT ping-pong connection (with occasional getnodes) being established. This is working as intended. There is no functional difference between the LAN discovery and the ping packet, so whatever you can do without this check, you can do with it.

**Pull request merged**
