### PR TITLE
feat: Add unpacker functions for events structures.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1996)

### CODE REVIEW

**Review by JFreegman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1996)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[toxcore/tox_events.c, line 158 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1996#-MvKjaId5ClSUw_-whLI:-MvKjaId5ClSUw_-whLJ:b-9cg0rk) ([raw file](https://github.com/toktok/c-toxcore/blob/17c691743eb43ec75ad44b293c15e89d1bd55ce4/toxcore/tox_events.c#L158)):*
> ```C
> 
>     Tox_Events *events = (Tox_Events *)calloc(1, sizeof(Tox_Events));
>     *events = (Tox_Events) {
> ```

Null dereference if calloc fails
___
*[toxcore/events/conference_invite.c, line 120 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1996#-MvKl0wq5Mk-xgmKcSDg:-MvKl0wq5Mk-xgmKcSDh:ba806bm) ([raw file](https://github.com/toktok/c-toxcore/blob/17c691743eb43ec75ad44b293c15e89d1bd55ce4/toxcore/events/conference_invite.c#L120)):*
> ```C
>     return tox_unpack_u32(&event->friend_number, &obj->via.array.ptr[0])
>            && tox_unpack_u32(&event->type, &obj->via.array.ptr[1])
>            && tox_unpack_bin(&event->cookie, &event->cookie_length, &obj->via.array.ptr[1]);
> ```

Should this index be 2?

**Review by JFreegman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1996)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[toxcore/tox_events.c, line 155 at r2](https://reviewable.io/reviews/toktok/c-toxcore/1996#-MvKtfV0DaGSZh2bURkm:-MvKtfV0DaGSZh2bURkn:bqva8v3) ([raw file](https://github.com/toktok/c-toxcore/blob/30f307de615390bc4335d8fb7c6a5ee33de0893a/toxcore/tox_events.c#L155)):*
> ```C
> 
>     msgpack_object obj;
>     msgpack_unpack((const char *)bytes, bytes_size, nullptr, &mempool, &obj);
> ```

Their docs say that this function is obsolete, not sure if we care.
https://github.com/msgpack/msgpack-c/wiki/v2_0_c_overview

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1996)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[toxcore/tox_events.c, line 158 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1996#-MvKjaId5ClSUw_-whLI:-MvL4fDYA5X1mVn3ine_:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/17c691743eb43ec75ad44b293c15e89d1bd55ce4/toxcore/tox_events.c#L158)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Null dereference if calloc fails
</blockquote></details>

Done.
___
*[toxcore/tox_events.c, line 155 at r2](https://reviewable.io/reviews/toktok/c-toxcore/1996#-MvKtfV0DaGSZh2bURkm:-MvL4fUd5lpExnln9BL3:biibgz4) ([raw file](https://github.com/toktok/c-toxcore/blob/30f307de615390bc4335d8fb7c6a5ee33de0893a/toxcore/tox_events.c#L155)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Their docs say that this function is obsolete, not sure if we care.
https://github.com/msgpack/msgpack-c/wiki/v2_0_c_overview
</blockquote></details>

I guess we care. It also simplified the code a bit.
___
*[toxcore/events/conference_invite.c, line 120 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1996#-MvKl0wq5Mk-xgmKcSDg:-MvL4ij_B2e27s1TjLf2:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/17c691743eb43ec75ad44b293c15e89d1bd55ce4/toxcore/events/conference_invite.c#L120)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Should this index be 2?
</blockquote></details>

Done.

**Review by JFreegman — COMMENTED** [review]
> Reviewed 20 of 28 files at r1, 3 of 3 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1996)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @JFreegman)

**Review by JFreegman — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1996)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @JFreegman)

**Pull request merged**
