### PR TITLE
Move c_sleep to helpers.h and misc_tools.h

### PR DESCRIPTION
**Pull request by Diadlo**
Also fix a mistake with forgotten braces around parameter

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/490)

### CODE REVIEW

**Comment by Zer0-One** [comment]
:lgtm_strong:

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/490#-:-KeM5cxKrb-97ksCN8g7:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 17 of 17 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/490#-:-KeTdu67M0ptXwqP_860:b-jbsf8z)*

**Comment by iphydf** [comment]
Looks good - rebase or check the checkbox that lets me rebase.

**Comment by Diadlo** [comment]
Done

**Comment by iphydf** [comment]
Unfortunately, github is buggy, and only collaborators on irungentoo/toxcore can rebase this. @Diadlo can you rebase again?

**Comment by Diadlo** [comment]
@iphydf No problems. Done.

**Comment by iphydf** [comment]
Can you rebase again? Sorry.

**Comment by Diadlo** [comment]
@iphydf Done

**Pull request merged**
