### PR TITLE
cleanup: Add comment after every `#endif`.

### PR DESCRIPTION
**Pull request by iphydf**
This makes far-away endifs clearer, so we're applying the rule to all endifs to be consistent.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2587)

### CODE REVIEW

**Review by JFreegman — APPROVED** [review]
> Reviewed 73 of 73 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2587)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Review by nurupo — APPROVED** [review]
> Reviewed 73 of 73 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2587)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Review by nurupo — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2587)* status: <span>:shipit:</span> complete! 1 change requests, 1 of 1 approvals obtained (waiting on @iphydf)

___
*[`toxcore/network.c` line 44 at r3](https://reviewable.io/reviews/TokTok/c-toxcore/2587#-NorWKDK2sRpZHfxfhNz:-NorWKDK2sRpZHfxfhO-:bbxg8jr) ([raw file](https://github.com/TokTok/c-toxcore/blob/ba99d4dc4b8c64a64da5036ce49dc91cea5dc51a/toxcore/network.c#L44)):*
> ```C
> // Comment line here to avoid reordering by source code formatters.
> #include <libc.h>
> #endif
> ```

What happened here?

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2587)* status: <span>:shipit:</span> complete! 1 change requests, 1 of 1 approvals obtained (waiting on @nurupo)

___
*[`toxcore/network.c` line 44 at r3](https://reviewable.io/reviews/TokTok/c-toxcore/2587#-NorWKDK2sRpZHfxfhNz:-NorqWp12FwG9Lm9dPsZ:b61u20p) ([raw file](https://github.com/TokTok/c-toxcore/blob/ba99d4dc4b8c64a64da5036ce49dc91cea5dc51a/toxcore/network.c#L44)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

What happened here?
</blockquote></details>

Deleted. But, since you asked, I've made a separate PR for it: https://github.com/TokTok/c-toxcore/pull/2588.

**Review by nurupo — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2587)* status: <span>:shipit:</span> complete! 2 of 1 approvals obtained

**Pull request merged**
