### PR TITLE
Replace make_quick_sort with qsort

### LINKED ISSUE #378: Replace all uses of `make_quick_sort` with `qsort`
It's only used in tests. There isn't really a good reason to have our own implementation of sort.

### PR DESCRIPTION
**Pull request by endoffile78**
closes #378

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/397)

### CODE REVIEW

**Comment by iphydf** [comment]
Also, rebase.

**Comment by endoffile78** [comment]
@iphydf Done.

**Comment by Diadlo** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxcore/Makefile.inc, line 51 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/397#-K_mrHu9-nSdMI2-dxr9:-K_mrHu9-nSdMI2-dxrA:beksd2f) ([raw file](https://github.com/toktok/c-toxcore/blob/069f6b94f14de4dc5006ba85869144486ee2046f/toxcore/Makefile.inc#L51)):*
> ```Makefile
>                         ../toxcore/TCP_connection.c \
>                         ../toxcore/list.c \
>                         ../toxcore/list.h \
> ```

Remove `\` in the last line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/397)*

**Comment by endoffile78** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxcore/Makefile.inc, line 51 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/397#-K_mrHu9-nSdMI2-dxr9:-K_q7k-Kpd19U6f0Hjxt:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/069f6b94f14de4dc5006ba85869144486ee2046f/toxcore/Makefile.inc#L51)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Remove `\` in the last line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/397)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/397#-:-K_qH99901jLjATldTqs:b-jbsf8z)*

**Comment by iphydf** [comment]
Am I confused about how qsort works? Why doesn't this code fail?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[auto_tests/crypto_test.c, line 347 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/397#-K_qSIYRD5hXfitHvFKq:-K_qSIYRD5hXfitHvFKr:b-e1eqlg) ([raw file](https://github.com/toktok/c-toxcore/blob/0c537b4e801d73c5431a8356bd39c675735462ae/auto_tests/crypto_test.c#L347)):*
> ```C
> static int cmp(const void *a, const void *b)
> {
>     if (a < b) {
> ```

This doesn't work. You're comparing the pointers, but should be comparing the values pointed at by a and b, which are `clock_t`s. It's surprising that it passes the tests.

---

*[auto_tests/crypto_test.c, line 374 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/397#-K_qS-Z7xrC5T56XO1Pz:-K_qS-Z7xrC5T56XO1Q-:bgk6t8s) ([raw file](https://github.com/toktok/c-toxcore/blob/0c537b4e801d73c5431a8356bd39c675735462ae/auto_tests/crypto_test.c#L374)):*
> ```C
>     }
> 
>     qsort(results, CRYPTO_TEST_MEMCMP_COUNT, sizeof(results), cmp);
> ```

It's coincidence that this works. The third argument is the element size. `sizeof(results)` happens to be 8 because it's a pointer. What it should really be is `sizeof(*results)`, because that's the size of a single array element, which happens to be 8 as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/397#-:-K_qSZGMYfxBIcdhWzz_:b3xgq78)*

**Comment by endoffile78** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[auto_tests/crypto_test.c, line 347 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/397#-K_qSIYRD5hXfitHvFKq:-K_u0snx8IRSZ8ryakjC:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/0c537b4e801d73c5431a8356bd39c675735462ae/auto_tests/crypto_test.c#L347)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

This doesn't work. You're comparing the pointers, but should be comparing the values pointed at by a and b, which are `clock_t`s. It's surprising that it passes the tests.
</blockquote></details>

Done.

---

*[auto_tests/crypto_test.c, line 374 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/397#-K_qS-Z7xrC5T56XO1Pz:-K_u0tdR-qg7-dgLjBGn:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/0c537b4e801d73c5431a8356bd39c675735462ae/auto_tests/crypto_test.c#L374)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

It's coincidence that this works. The third argument is the element size. `sizeof(results)` happens to be 8 because it's a pointer. What it should really be is `sizeof(*results)`, because that's the size of a single array element, which happens to be 8 as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/397)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 1 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/397#-:-K_u9YsoDhhPwQm5l7Z8:b-jbsf8z)*

**Comment by nurupo** [comment]
No squashing, huh.

That first commit really threw me off when I saw the mistakes in the commits in master branch, just to see it getting fixed in the following commit.

**Comment by nurupo** [comment]
:lgtm_strong:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/397#-:-KaK3v3v1CR3St_mOowm:b-jbsf8z)*

**Pull request merged**
