### PR TITLE
Adjust docs of few toxencrypt function to the code

### LINKED ISSUE #590: toxencryptsave api info typo?
https://github.com/TokTok/c-toxcore/blob/master/toxencryptsave/toxencryptsave.h#L375

is this line correct? or should it say *"If data is NULL, this function returns false."*

### PR DESCRIPTION
**Pull request by Diadlo**
Add correct information about behaviour if input pointer is NULL

Fix #590

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/592)

### CODE REVIEW

**Comment by zoff99** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/592#-:-Kt0xxGEXTeVgAec2BMT:b-jbsf8z)*

**Comment by nurupo** [comment]
You shouldn't edit `toxencryptsave.h` directly, you should edit `toxencryptsave.api.h` and run APIDSL on it and then run astyle on the resulting `toxencryptsave.h` using toxcore's astyle rules.

**Comment by Diadlo** [comment]
@nurupo IDK what APIDSL is and how does it works. But I hope, that now it's made correct

**Comment by nurupo** [comment]
[APIDSL](https://github.com/TokTok/apidsl) converts files written in a special c-like language that @iphydf came up with, the goal of the language being improving API consistency, to the C language. E.g. (`tox.api.h`)[https://github.com/TokTok/c-toxcore/blob/master/toxcore/tox.api.h] gets converted into (`tox.h`)[https://github.com/TokTok/c-toxcore/blob/master/toxcore/tox.h]. I think the plan is to eventually port all public APIs and also toxcore layers to it. There is also [this doc](https://github.com/TokTok/c-toxcore/blob/master/docs/apidsl.md) on it, though I remember APIDSL on Heroku being outdated, so it might be better to build the latest version of it locally.

[Here are the astyle rules](https://github.com/TokTok/c-toxcore/tree/master/other/astyle).

There is a tests Travis runs that checks if someone forgot to run astyle or edited a header file without editing the corresponding APIDSL file accordingly, which is why [your previous change was failing on Travis](https://travis-ci.org/TokTok/c-toxcore/jobs/271113957#L4107).

**Comment by nurupo** [comment]
Hm, actually, [the tests still fails](https://travis-ci.org/TokTok/c-toxcore/jobs/271273503#L2623),  `toxencryptsave.h` and `toxencryptsave.api.h` are still out of sync in this PR.

**Comment by Diadlo** [comment]
Thanks for the links. Fixed

**Comment by zoff99** [comment]
@nurupo maybe you can add somewhere in the docs that if you compile libsodium with
*"--enable-minimal"*
then 99,9% of tox works (including all A/V stuff) but only 1 function is missing for toxencryptsave
that one will only be built with the full version of libsodium

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/592#-:-Kvqfv19uGWH7uGNUV8K:b-jbsf8z)*

**Comment by robinlinden** [comment]
Please enable the checkbox "Allow edits from maintainers." on the bottom right.

**Comment by Diadlo** [comment]
@robinlinden Done

**Pull request merged**
