### PR TITLE
Make Ping_Array a module-private type.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/668)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 7 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[toxcore/ping_array.c, line 70 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/668#-L2kvSyj-SqqUX5xXv2N:-L2kvSyj-SqqUX5xXv2O:b-p8921k) ([raw file](https://github.com/toktok/c-toxcore/blob/6b237f44dc74ecc81b08af8479ef74c13af6617a/toxcore/ping_array.c#L70)):*
> ```C
>     empty_array->entries = (Ping_Array_Entry *)calloc(size, sizeof(Ping_Array_Entry));
>     if (empty_array->entries == NULL) {
>         return NULL;
> ```

leak of `empty_array`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/668)*

**Comment by iphydf** [comment]
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[toxcore/ping_array.c, line 70 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/668#-L2kvSyj-SqqUX5xXv2N:-L2l-hkqWxMSRRXLOaxq:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/6b237f44dc74ecc81b08af8479ef74c13af6617a/toxcore/ping_array.c#L70)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

leak of `empty_array`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/668)*

**Comment by endoffile78** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[toxcore/ping_array.h, line 47 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/668#-L2l1UZ44RPIux-2LNrn:-L2l1UZ44RPIux-2LNro:b5ag68c) ([raw file](https://github.com/toktok/c-toxcore/blob/2da144fe3243ee9f2a36e6c2adf06728a0954f54/toxcore/ping_array.h#L47)):*
> ```objc
>  * Free all the allocated memory in a Ping_Array.
>  */
> void ping_array_kill(struct Ping_Array *_array);
> ```

The first argument here is listed as `_array` but in the function declaration its `array`.

---

*[toxcore/ping_array.h, line 55 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/668#-L2l1_3Ypi0FrYpba93f:-L2l1_3Ypi0FrYpba93g:b5ag68c) ([raw file](https://github.com/toktok/c-toxcore/blob/2da144fe3243ee9f2a36e6c2adf06728a0954f54/toxcore/ping_array.h#L55)):*
> ```objc
>  * return 0 on failure.
>  */
> uint64_t ping_array_add(struct Ping_Array *_array, const uint8_t *data, uint32_t length);
> ```

The first argument here is listed as `_array` but in the function declaration its `array`.

---

*[toxcore/ping_array.h, line 65 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/668#-L2l1GfPPxhIC3FKeQJ5:-L2l1GfQ63qjkIm_tC2C:b5ag68c) ([raw file](https://github.com/toktok/c-toxcore/blob/2da144fe3243ee9f2a36e6c2adf06728a0954f54/toxcore/ping_array.h#L65)):*
> ```objc
>  * return -1 on failure.
>  */
> int32_t ping_array_check(struct Ping_Array *_array, uint8_t *data, size_t length, uint64_t ping_id);
> ```

The first argument here is listed as `_array` but in the function declaration its `array`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/668)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/668#-:-L2l2N5sOZePNu6A788z:b-jbsf8z)*

**Comment by iphydf** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[toxcore/ping_array.h, line 47 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/668#-L2l1UZ44RPIux-2LNrn:-L2lmBDlQYMM0kfJpEL-:br50d7j) ([raw file](https://github.com/toktok/c-toxcore/blob/2da144fe3243ee9f2a36e6c2adf06728a0954f54/toxcore/ping_array.h#L47)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

The first argument here is listed as `_array` but in the function declaration its `array`.
</blockquote></details>

Can't be fixed right now. I need to fix apidsl. I will, but not for this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/668)*

**Pull request merged**
