### PR TITLE
refactor: Remove VLAs from Messenger.c

### PR DESCRIPTION
**Pull request by crypto-universe**
Prefer static arrays to VLAs because:
1) static arrays are initialized once, no runtime overhead;
2) they consume data segment, stack is protected from attacks;
3) in contrast to `malloc` memory leaks are impossible.

Caution! Static arrays are not suitable for sensitive data!
Don't forget to invalidate sensitive data after usage!
Keep in mind, static arrays are not thread safe!

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1300)

### CODE REVIEW

**Comment by crypto-universe** [comment]
Does it mean that `static` keyword is restricted somehow? Message from travis-ci:

`check-cimple: L (AlexPn 15122 518 5) KwStatic "static"`

**Comment by zoff99** [comment]
`Keep in mind, static arrays are not thread safe!`
@crypto-universe please don't add any more non-thread safe stuff. we have enough problems already with that
@iphydf can we at least try to make anything we change or add thread safe if reasonably possible?

**Comment by crypto-universe** [comment]
@zoff99 OK, got it. Thread safety is important here.

**Comment by zoff99** [comment]
i would use calloc() for those

**Comment by iphydf** [comment]
@zoff99 this code doesn't pass tokstyle: https://travis-ci.org/TokTok/c-toxcore/jobs/480139391#L1350 because it's using global variables, which are either obviously not thread-safe, or non-obviously thread-safe, neither of which we allow.

**Comment by zoff99** [comment]
why are you using ```malloc()``` and not ```calloc()``` , is there a special reason?

**Comment by iphydf** [comment]
This PR can't be merged as is. If you change it to fixed length local arrays or variable length malloc'd arrays, you can reopen the PR.

**Pull request closed without merging**
