### PR TITLE
cleanup: Move all vptr-to-ptr casts to the beginning of a function.

### PR DESCRIPTION
**Pull request by iphydf**
These casts are effectively part of the function type, so it makes sense to have them at the beginning.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2512)

### CODE REVIEW

**Review by nurupo — COMMENTED** [review]
A bit conflicted about this change as I'm more of "declare it right before you use it" mindset. Most of these functions start with some sort of argument check, and it feels weird to declare the type cast before the check and then not use it in the check at all. In a rare case when the check actually needs to know the type of the `void *` argument, then sure, in this case it's fine to declare beforehand.

Your "it's part of the function type" reasoning makes sense, but it's a bit jarring to read a declaration and then proceed reading the check and not see the declared thing being used in it, it kind of annoys me, like what was the point of me even reading it and keeping it in mind?

> Reviewed 10 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2512#-:-Nms_yxs6IIljchx4Lj1:b-m196gt)* status: 0 of 1 approvals obtained

**Review by JFreegman — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2512)* status: 0 of 1 approvals obtained (waiting on @iphydf)

___
*[`toxav/bwcontroller.c` line 211 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2512#-Nmsaq-3AKQ1zpgaJAhN:-Nmsaq-3AKQ1zpgaJAhO:b-efqd4d) ([raw file](https://github.com/TokTok/c-toxcore/blob/0e42752f0fc2a460b08ac4d275ae5b5f18c8d3ea/toxav/bwcontroller.c#L211)):*
> ```C
> static int bwc_handle_data(Messenger *m, uint32_t friendnumber, const uint8_t *data, uint16_t length, void *object)
> {
>     BWController *bwc = (BWController *)object;
> ```

Should we check if it's null like we do with the others? `on_update()` uses it without a null check. There are a few other missing null checks, you can decide if they're necessary or not.

**Review by nurupo — COMMENTED** [review]
Anyway, LGTM.

(Not directly approving to avoid the auto-merge as JFreegman wants you to see his message).

> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2512#-:-Nmsf54O22U-3Wj5TDJo:b-sgxv4x)* status: 0 of 1 approvals obtained (waiting on @iphydf)

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2512)* status: 0 of 1 approvals obtained (waiting on @zoff99)

___
*[`toxav/bwcontroller.c` line 211 at r2](https://reviewable.io/reviews/TokTok/c-toxcore/2512#-Nmsaq-3AKQ1zpgaJAhN:-Nmvg3FC-5pRgMq7hdIh:bus1x31) ([raw file](https://github.com/TokTok/c-toxcore/blob/0e42752f0fc2a460b08ac4d275ae5b5f18c8d3ea/toxav/bwcontroller.c#L211)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Should we check if it's null like we do with the others? `on_update()` uses it without a null check. There are a few other missing null checks, you can decide if they're necessary or not.
</blockquote></details>

I'm hesitant to touch toxav more than necessary to pass tokstyle. If I touch it too much, @zoff99's toxav PR will be harder and harder to merge.

**Review by JFreegman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2512)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Pull request merged**
