### PR TITLE
Remove deprecated ToxDNS

### PR DESCRIPTION
**Pull request by zetok**
Services & clients have moved to ToxMe.

Removal of ToxDNS from codebase is a clear sign that it is to not be
treated as standard and that no one should be using this.

No client and no service aside from those ran by µTox are using this.

This should help move µTox to the ToxMe.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/331)

### CODE REVIEW

**Comment by GrayHatter** [comment]
> This should help move µTox to the ToxMe.

uTox will NEVER support HTTP* lookups while I'm the lead developer.

**Comment by zetok** [comment]
@GrayHatter that's an internal µTox problem, not related to toxcore.

**Comment by iphydf** [comment]
Can you remove the "fix: " from the commit message? This is not fixing anything.

**Comment by zetok** [comment]
@iphydf done.

**Comment by iphydf** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/331)*

**Comment by iphydf** [comment]
Done in #650.

**Pull request closed without merging**
