### PR TITLE
Release v0.2.2

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/862)

### CODE REVIEW

**Comment by SkyzohKey** [comment]
What about the persistent groupchats PR?

**Comment by tox-user** [comment]
Can we switch groupbot to use persistent groups? That way more people will be able to test it easier. Tens of people use groupbot every day, so we could ask some of them to help us test persistent group chats.

**Comment by sudden6** [comment]
blocked by #872

**Comment by nurupo** [comment]
Also blocked by the autotools build being broken in master. You will want to cherry-pick this commit that fixes it before making a release https://github.com/TokTok/c-toxcore/pull/867/commits/90202a1c4793c359ce557be32286c7bc0d9fef2a. It's part of https://github.com/TokTok/c-toxcore/pull/867 but I see that that PR might not make it in 0.2.2, so just cherry-pick.

**Comment by nurupo** [comment]
It would also be nice to get https://github.com/TokTok/c-toxcore/pull/875 in before the release, so that we could see if bootstrap node maintainers update the nodes after we ask them over the mailing list to update. It's not a required PR though, feel free to skip it.

**Comment by robinlinden** [comment]
The release will be without #867 as I can't merge unsigned commits and I can't push to forks based on irungentoo's Toxcore repository. I've cherry-picked the commit fixing the autotools build. There's still lots of discussion going on in #875 and it shouldn't block the release, so that PR will have to wait too.

**Pull request merged**
