### PR TITLE
Set up autotools build to build against vanilla NaCl.

### LINKED ISSUE #363: Test against NaCl in addition to libsodium on Travis.
I suggest making one of the builds (the autotools one) use nacl instead of libsodium. The other one (cmake) can still use libsodium. This way, we'll know toxcore is compatible with both.

### PR DESCRIPTION
**Pull request by iphydf**
Fixes #363.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/393)

### CODE REVIEW

**Comment by Diadlo** [comment]
Seems `auto_tests/crypto_test.c` changes out of the scope of PR. But if you want to leave it, `printf` calls seems reduant

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[other/travis/autotools-linux-install, line 7 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/393#-K_kUR1-DIFTAQXHL9qP:-K_kUR1-DIFTAQXHL9qQ:b-n3rn8v) ([raw file](https://github.com/toktok/c-toxcore/blob/aa01db6c084530eff1241adcfa6994b8729d8dc7/other/travis/autotools-linux-install#L7)):*
> ```
> # Also install vanilla NaCl
> [ -f $CACHE_DIR/lib/amd64/libnacl.a ] || {
>   wget https://hyperelliptic.org/nacl/nacl-20110221.tar.bz2
> ```

To avoid of file save we can use 
```
wget https://hyperelliptic.org/nacl/nacl-20110221.tar.bz2 -O - | bunzip2 | tar -xf -
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/393#-:-K_kSXeVAszWGPQIvGMk:b-qf51e1)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[other/travis/autotools-linux-install, line 7 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/393#-K_kUR1-DIFTAQXHL9qP:-K_yfk-KiAgrQeAP9gkb:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/aa01db6c084530eff1241adcfa6994b8729d8dc7/other/travis/autotools-linux-install#L7)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

To avoid of file save we can use 
```
wget https://hyperelliptic.org/nacl/nacl-20110221.tar.bz2 -O - | bunzip2 | tar -xf -
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/393)*

**Comment by iphydf** [comment]
Not really redundant. Those things take a considerable amount of time, and for a user running the test manually, it's useful to see what's happening.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/393#-:-K_yfrMAw0YajjjYHwMu:b-xovaqp)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/393#-:-K_yolt1_Nqvf_WChWCB:b-jbsf8z)*

**Comment by nurupo** [comment]
:lgtm_strong:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/393#-:-KaK0zoOndXcuAUMcdkT:b-jbsf8z)*

**Pull request merged**
