### PR TITLE
Configure needs to find libsodium headers.

### PR DESCRIPTION
**Pull request by JamesC1**
Add soft-links for them, in the places that it expects.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/571)

### CODE REVIEW

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/571#-:-Kq9My3541T42O5i6wAk:b-jbsf8z)*

**Comment by robinlinden** [comment]
:lgtm_strong: Can you check the box that allows me to rebase this or rebase on master yourself?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/571#-:-Kqmqa3JF35mhC16GRvX:b-nb1yn0)*

**Comment by JamesC1** [comment]
I think that the relevant tick box is "Allow edits from maintainers" on the right.  I have ticked it.

I have had a go at rebasing.  It ended up requiring a 'git push -f', to get github to accept the rewritten history.  Is that normal?

**Comment by robinlinden** [comment]
Yeah, that's normal. GitHub requires you to confirm you know what you're doing when you rewrite history. 
Thanks for rebasing!

**Comment by robinlinden** [comment]
Please enable the checkbox "Allow edits from maintainers." on the bottom right, or rebase again. This repo only does fast-forward merges, so this has to be ahead of `master` when I go ahead and merge it.

**Comment by JamesC1** [comment]
Hi Robin,

I think that's the tick box on the right side of this page: https://github.com/TokTok/c-toxcore/pull/571
which might be visible only to me.  It's currently ticked.  I think that it has unticked itself at least once.

I'm on a strange machine, so I've had a hairy go at rebasing.  It didn't satisfy the box of checks, so I clicked the "Update branch" button, but I don't know what it did :-)

Regards,
James.

**Pull request merged**
