### PR TITLE
Make ToxAV stateless

### PR DESCRIPTION
**Pull request by GrayHatter**
This is the second attempt at making toxav stateless.
Pretty much just a cherry-pick of the last attempt with a few addition lines.

I need someone to tell me how I can duplicate the errors of yesteryear, otherwise I've re-read the whole section of code. Looked at all (or nearly all callbacks) and... well, I works for me!

I didn't assign a mile stone yet, as this will replace v..* with v0.1

@iphydf make bug how?

@mannol you're awesome, thanks' for toxAV and you keep being you!

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/282)

### CODE REVIEW

**Comment by mannol** [comment]
<3

**Comment by sudden6** [comment]
Review status: 0 of 21 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[other/toktok-rebase, line 1 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KWz1N9XMDy-TXJdFnBf:-KWz1N9Yl5nu3qaqFByS:b8lu493) ([raw file](https://github.com/toktok/c-toxcore/blob/90b7f9b84f41ab63fe47f192cebce5fc8c7198ab/other/toktok-rebase#L1)):*
> ```
> #!/usr/bin/zsh
> ```

are you sure this should go into this PR?

---

*[toxav/audio.h, line 30 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KWz1W1M7xen3TMAxKhe:-KWz1W1Nxs9md6bbLARb:bfwruez) ([raw file](https://github.com/toktok/c-toxcore/blob/90b7f9b84f41ab63fe47f192cebce5fc8c7198ab/toxav/audio.h#L30)):*
> ```objc
> #include "../toxcore/util.h"
> 
> #include <opus/opus.h> // local change, do not commit
> ```

well, the comment says not to commit, why did you?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by sudden6** [comment]
Review status: 0 of 24 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[toxav/audio.c, line 208 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc3-w4E590Yl7nKspV:-KYc3-w4E590Yl7nKspW:b-frc651) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/audio.c#L208)):*
> ```C
>     ACSession *ac = (ACSession *)acp;
> 
>     if (msg->header.pt != rtp_TypeAudio && msg->header.pt != 64) {
> ```

64 is a magic number?

---

*[toxav/msi.c, line 494 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc5iuwKAbHKhzex9hA:-KYc5iuxZwPkS5MGuc__:bxjqr8o) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/msi.c#L494)):*
> ```C
>                            "Callback state handling failed, sending error");
> 
>             /* If no callback present or error happened while handling,
> ```

The comment doesn't match the logic anymore, if no callback is present, nothing will be done.

---

*[toxav/rtp.c, line 365 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc6pEg8iYRAXLtRFWJ:-KYc6pEhAQfgq9syc0K0:b-jmasbz) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/rtp.c#L365)):*
> ```C
> 
>         /**
>          * The lenght is lesser than the maximum allowed lenght (including header)
> ```

typo "length"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by robinlinden** [comment]
Reviewed 2 of 21 files at r1, 5 of 17 files at r2.
Review status: 7 of 24 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[toxav/rtp.c, line 83 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc5UJmMJeG3xtJyQvs:-KYc5UJrx1ulbE46znn-:bgawlkt) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/rtp.c#L83)):*
> ```C
>                       void *userdata)
> {
>     (void) friendnumber;
> ```

Why did you remove one of the unused warning suppressions? Remove both or add (void) userdata too.

---

*[toxav/rtp.c, line 98 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc6WhvBIibJpR49oSZ:-KYc6WhwBiEaMIw7IZow:b-cjs123) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/rtp.c#L98)):*
> ```C
>     const struct RTPHeader *header = (const struct RTPHeader *) data;
> 
>     if (header->pt != session->payload_type && header->pt != 64) {
> ```

Why are you letting payload type 64 past? What payload type is 64?

---

*[toxav/video.c, line 198 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYcG4eyLvjJaBR7w0RO:-KYcG4eyLvjJaBR7w0RP:b8oxlko) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/video.c#L198)):*
> ```C
>     VCSession *vc = (VCSession *)vcp;
> 
>     if (msg->header.pt != rtp_TypeVideo && msg->header.pt != 65) {
> ```

If 65 the only payload type you're letting through here? What payload type is 65?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by robinlinden** [comment]
Reviewed 3 of 17 files at r2.
Review status: 10 of 24 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by robinlinden** [comment]
Reviewed 1 of 21 files at r1, 5 of 17 files at r2.
Review status: 15 of 24 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by robinlinden** [comment]
Reviewed 5 of 21 files at r1, 4 of 17 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[toxav/msi.c, line 494 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc5iuwKAbHKhzex9hA:-KYcKpNUo1NnKdZld38R:b-5yowp5) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/msi.c#L494)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

The comment doesn't match the logic anymore, if no callback is present, nothing will be done.
</blockquote></details>

The logic of the function hasn't changed. The only thing different is the removed goto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by sudden6** [comment]
*[toxav/msi.c, line 494 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc5iuwKAbHKhzex9hA:-KYcLqg039tavtbY0kEF:b8aad3g) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/msi.c#L494)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

The logic of the function hasn't changed. The only thing different is the removed goto.
</blockquote></details>

it has, previously `if (call->session->callbacks[cb]) ` being `false would return `-1` now it returns `0`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[toxav/msi.c, line 494 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc5iuwKAbHKhzex9hA:-KYcOjeR-W2KpkT2c3y1:bsrzhq) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/msi.c#L494)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

it has, previously `if (call->session->callbacks[cb]) ` being `false would return `-1` now it returns `0`
</blockquote></details>

Yeah, you're right. Good catch. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[toxav/msi.c, line 494 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc5iuwKAbHKhzex9hA:-KYcPj2dXyyYPhtODzUm:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/msi.c#L494)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Yeah, you're right. Good catch. :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by sudden6** [comment]
*[toxav/msi.c, line 494 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc5iuwKAbHKhzex9hA:-KYcQFtp1VtOKz2_l7gR:b-cg93rd) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/msi.c#L494)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's still missing the
```             if (call->error == msi_ENone) {
                 call->error = msi_EHandle;```
block to be the same as before. I don't know if this matters though.
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by GrayHatter** [comment]
Review status: 22 of 24 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[toxav/rtp.c, line 83 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc5UJmMJeG3xtJyQvs:-KYcQo--yQECakUXm6WB:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/rtp.c#L83)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Why did you remove one of the unused warning suppressions? Remove both or add (void) userdata too.
</blockquote></details>

Done.

---

*[toxav/rtp.c, line 98 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc6WhvBIibJpR49oSZ:-KYcPz09nKeX8JAvvJBo:bl83we5) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/rtp.c#L98)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Why are you letting payload type 64 past? What payload type is 64?
</blockquote></details>

https://i.imgur.com/iZcUNxH.gif

It's the old packet number type from how toxav used to count packets. This way it'll work to and from old toxav.

---

*[toxav/rtp.c, line 365 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc6pEg8iYRAXLtRFWJ:-KYcQLAvO34xdPdaerWc:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/rtp.c#L365)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo "length"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by GrayHatter** [comment]
Review status: 22 of 24 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[other/toktok-rebase, line 1 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KWz1N9XMDy-TXJdFnBf:-KYcQtj-woOK1Lh6nlzM:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/90b7f9b84f41ab63fe47f192cebce5fc8c7198ab/other/toktok-rebase#L1)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

are you sure this should go into this PR?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by GrayHatter** [comment]
Review status: 22 of 24 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[toxav/audio.c, line 208 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc3-w4E590Yl7nKspV:-KYcRWS5u87wmdreiJw_:b-q8d603) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/audio.c#L208)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

64 is a magic number?
</blockquote></details>

magic number from old toxav video

---

*[toxav/audio.h, line 30 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KWz1W1M7xen3TMAxKhe:-KYcQxDglmQC_lOuUB0O:b-y5s53p) ([raw file](https://github.com/toktok/c-toxcore/blob/90b7f9b84f41ab63fe47f192cebce5fc8c7198ab/toxav/audio.h#L30)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

well, the comment says not to commit, why did you?
</blockquote></details>

Will rebase and remove once I don't need to compile every 5m

---

*[toxav/msi.c, line 494 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc5iuwKAbHKhzex9hA:-KYcRGZapkoLmD0IVY8I:bu6pd2b) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/msi.c#L494)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

It's still missing the
```             if (call->error == msi_ENone) {
                 call->error = msi_EHandle;```
block to be the same as before. I don't know if this matters though.

</blockquote></details>

I just triple checked, the flow is the same as before. Someone else please confirm.

---

*[toxav/video.c, line 198 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYcG4eyLvjJaBR7w0RO:-KYcRSXWqr8padxt5EC8:bxz0t2x) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/video.c#L198)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

If 65 the only payload type you're letting through here? What payload type is 65?
</blockquote></details>

https://i.imgur.com/iZcUNxH.gif

65 is the magic number for old toxav video

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*
<!-- Sent from Reviewable.io -->

**Comment by robinlinden** [comment]
Review status: 22 of 24 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[toxav/msi.c, line 494 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc5iuwKAbHKhzex9hA:-KYcSxcgMQwsDIivcnPc:b-l4iw6p) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/msi.c#L494)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

I just triple checked, the flow is the same as before. Someone else please confirm.
</blockquote></details>

@sudden6 is right. Still missing `call->error = msi_EHandle`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by sudden6** [comment]
Review status: 22 of 24 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[toxav/audio.c, line 208 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc3-w4E590Yl7nKspV:-KYcTRI7_ogXr9KnJqNt:by54eqb) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/audio.c#L208)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

magic number from old toxav video
</blockquote></details>

can you make it not magic and introduce a define? or at least make a comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by robinlinden** [comment]
Reviewed 1 of 2 files at r3.
Review status: 23 of 24 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[toxav/msi.c, line 494 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc5iuwKAbHKhzex9hA:-KYcVi01nM_lcn2RkH64:b-5f6lnq) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/msi.c#L494)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

@sudden6 is right. Still missing `call->error = msi_EHandle`.
</blockquote></details>

It's fine now.

---

*[toxav/rtp.c, line 98 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc6WhvBIibJpR49oSZ:-KYcUFAb0a1BcFRQ-H4J:b-ihjzf2) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/rtp.c#L98)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

https://i.imgur.com/iZcUNxH.gif

It's the old packet number type from how toxav used to count packets. This way it'll work to and from old toxav.
</blockquote></details>

Maybe add `const uint8_t old_toxav_packetid = 64` to the line above and use the variable in place of the magic number?

---

*[toxav/video.c, line 198 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYcG4eyLvjJaBR7w0RO:-KYcUr4-5IJshToB6ASQ:b-ut28f8) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/video.c#L198)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

https://i.imgur.com/iZcUNxH.gif

65 is the magic number for old toxav video
</blockquote></details>

Maybe add `const uint8_t old_video_packetid = 65` to the line above and use the variable in place of the magic number?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by sudden6** [comment]
*[toxav/msi.c, line 494 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYc5iuwKAbHKhzex9hA:-KYccQbgvkHNTrQRk8hV:b-m1p1yy) ([raw file](https://github.com/toktok/c-toxcore/blob/b9feff2eab0b1412208c7075417c1dc9e5a26dbd/toxav/msi.c#L494)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

It's fine now.
</blockquote></details>

yep, now it's ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by nurupo** [comment]
Reviewed 3 of 17 files at r2.
Review status: 23 of 24 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[toxcore/net_crypto.c, line 1442 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYvhNKjKGNwU4jIiqAg:-KYvhNKjKGNwU4jIiqAh:bvxigf1) ([raw file](https://github.com/toktok/c-toxcore/blob/f517fae4ac61ab0a52709c751dfc6d1316b9988d/toxcore/net_crypto.c#L1442)):*
> ```C
>         /* Packet counter. */
>         ++conn->packet_counter;
>     } else if (real_data[0] >= PACKET_ID_LOSSY_RANGE_START && real_data[0] <= PACKET_ID_LOSSY_RANGE_LAST) {
> ```

Again, this should be `real_data[0] >= PACKET_ID_LOSSY_RANGE_START && real_data[0] < PACKET_ID_LOSSY_RANGE_LAST` instead, `<` vs `<=`. `PACKET_ID_LOSSY_RANGE_LAST` equals to `(PACKET_ID_LOSSY_RANGE_START + PACKET_ID_LOSSY_RANGE_SIZE)`, they are both 255, so the comparison should be kept as in the original.

---

*[toxcore/net_crypto.c, line 2639 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYvfPSxVEjlh_b6ftcw:-KYvfPSxVEjlh_b6ftcx:bpnidjo) ([raw file](https://github.com/toktok/c-toxcore/blob/f517fae4ac61ab0a52709c751dfc6d1316b9988d/toxcore/net_crypto.c#L2639)):*
> ```C
>     }
> 
>     if (data[0] < PACKET_ID_LOSSY_RANGE_START || data[0] > PACKET_ID_LOSSY_RANGE_LAST) {
> ```

This should be `data[0] < PACKET_ID_LOSSY_RANGE_START || data[0] >= PACKET_ID_LOSSY_RANGE_LAST` instead, `>=` vs `>`. The original code had `>= PACKET_ID_LOSSY_RANGE_START + PACKET_ID_LOSSY_RANGE_SIZE`, which is `>= 255`.`PACKET_ID_LOSSY_RANGE_LAST` is 255 too, it's the first invalid id after the lossy id block (the last valid lossy id is 254, which would be `PACKET_ID_LOSSY_RANGE_LAST -1`), so since they are the same value, you need to keep the same comparison operator as in the original code.

---

*[toxcore/net_crypto.c, line 2648 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYvfEao-JZYsfY4Oz_d:-KYvfEao-JZYsfY4Oz_e:bcdia9q) ([raw file](https://github.com/toktok/c-toxcore/blob/d8ae726d0a332c74da7bbed70982367dd01899e1/toxcore/net_crypto.c#L2648)):*
> ```C
>     }
> 
>     if (data[0] >= (PACKET_ID_LOSSY_RANGE_START + PACKET_ID_LOSSY_RANGE_SIZE)) {
> ```

See, the does the original code returns `-1` on `data[0] => PACKET_ID_LOSSY_RANGE_LAST` (what was `data[0] >= (PACKET_ID_LOSSY_RANGE_START + PACKET_ID_LOSSY_RANGE_SIZE)`)? Is the last id not inclusive, i.e. `PACKET_ID_LOSSY_RANGE_LAST` should really be 254 instead if we assume the START and LAST as inclusive?

---

*[toxcore/net_crypto.h, line 79 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYvefongA5-znuTPBTu:-KYvefongA5-znuTPBTv:b-kvu257) ([raw file](https://github.com/toktok/c-toxcore/blob/f517fae4ac61ab0a52709c751dfc6d1316b9988d/toxcore/net_crypto.h#L79)):*
> ```objc
> /* All packets starting with a byte in this range are considered lossless packets. */
> #define PACKET_ID_LOSSLESS_RANGE_START  160
> #define PACKET_ID_LOSSLESS_RANGE_LAST   191
> ```

`START` and `LAST`? Why not `START` and `END` or `FIRST` and `LAST`?

---

*[toxcore/net_crypto.h, line 82 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYvejICq3jVhqO7zfOU:-KYvejICq3jVhqO7zfOV:b11ir3j) ([raw file](https://github.com/toktok/c-toxcore/blob/f517fae4ac61ab0a52709c751dfc6d1316b9988d/toxcore/net_crypto.h#L82)):*
> ```objc
> /* All packets starting with a byte in this range are considered lossy packets. */
> #define PACKET_ID_LOSSY_RANGE_START     192
> #define PACKET_ID_LOSSY_RANGE_LAST      255
> ```

Last valid lossy packet is actually 254. `PACKET_ID_LOSSY_RANGE_START` is the inclusive start of the range and `PACKET_ID_LOSSY_RANGE_SIZE` is the total number of lossy ids, including the starting one.

This should be changed to 254 and all the comparisons in `if`-statements need to be corrected, because it's not equivalent to `PACKET_ID_LOSSY_RANGE_START+PACKET_ID_LOSSY_RANGE_SIZE` which is the first invalid id after the lossy id block range, it's 1 less than that.

---

*[toxcore/net_crypto.h, line 326 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYvenojpL1Qn2HV8eXW:-KYvenojpL1Qn2HV8eXX:b-74y24f) ([raw file](https://github.com/toktok/c-toxcore/blob/f517fae4ac61ab0a52709c751dfc6d1316b9988d/toxcore/net_crypto.h#L326)):*
>CRYPTO_RESERVED_PACKETS to PACKET_ID_LOSSY_RANGE_START range

was 16 to 192 range and you changed it to

>PACKET_ID_LOSSLESS_RANGE_START to PACKET_ID_LOSSLESS_RANGE_LAST range

which is 160 to 191 range.

Why the difference?

---

*[toxcore/tox.c, line 1591 at r3](https://reviewable.io:443/reviews/toktok/c-toxcore/282#-KYvdUcWmJDcphXL50jG:-KYvdUcWmJDcphXL50jH:b-rrrg19) ([raw file](https://github.com/toktok/c-toxcore/blob/f517fae4ac61ab0a52709c751dfc6d1316b9988d/toxcore/tox.c#L1591)):*
> ```C
>     }
> 
>     if (data[0] < (PACKET_ID_LOSSY_RANGE_START)) {
> ```

This change doesn't look correct. It was `< PACKET_ID_LOSSY_RANGE_START + more` before and now it's just `PACKET_ID_LOSSY_RANGE_START`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/282)*

**Comment by nurupo** [comment]
Too many files to review, will continue reviewing sometime later.

**Pull request closed without merging**
