### PR TITLE
Update install instructions to use CMake

### LINKED ISSUE #383: TODO: add cmake instructions in README.md
Aside from the default autotools instructions there should be docs on building toxcore with cmake.

Given that currently cmake build isn't as easy to use as autotools one, cmake instructions should be added without removal of autotools instructions and mention that cmake might not yet provide same level of functionality as autotools.

### PR DESCRIPTION
**Pull request by nurupo**
- Updated INSTALL.md to use CMake
  - Fixed CMakeLists.txt a bit, mainly regarding cross-compiling to Windows
  - Added Dockerfile for cross-compiling to Windows which is used in the INSTALL.md instructions

When cross-compiling toxcore to Windows and running the test suit, on i686 I get `messenger` test crashing and `tox_many_tcp` test never finishing, but on x86_64 it's just `tox_many_tcp test` never finishing.

TODO(@iphydf ?): make Travis cross-compile toxcore to Windows using the provided in this PR Dockerfile, so that we know the Windows cross-compilation section from INSTALL.md is still valid and also that toxcore cross-compiles for Windows successfully.

Fixes #383.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/477)

### CODE REVIEW

**Comment by iphydf** [comment]
Neat! @nurupo would you mind adding a travis build using docker that builds the image? (It's ok to say no, I'm still happy with this change).

**Comment by nurupo** [comment]
The `INSTALL.md` in this PR needs to be updated, since we now support MSVC and it claims otherwise. The instructions for MSVC would also be good to have, but there is an issue that one can't currently build toxav with MSVC as cmake doesn't know where to look for opus and vpx without pkg-config. It might make sense to move away from using pkg-config in cmake to using the cmake's `find_package()` (though we could just have both). I started working on writing `FindX.cmake` for every Tox dependency so that `find_package()` could find it, but I haven't finished and probably won't come back to it in a while. I can push my progress to a branch on my fork if someone wants to take it over.

I think there also were some new cmake options added recently, which `INSTALL.md` misses.

>Neat! @nurupo would you mind adding a travis build using docker that builds the image? (It's ok to say no, I'm still happy with this change).

I wouldn't really call it neat, I'm not very happy with the shell scripts, you have to read the entire thing (all the scripts) to understand what the variables are used for and where the things are done in fs.

As far as the Travis build goes, I will try adding a Travis build for it later this week if I will have time.

**Comment by zoff99** [comment]
Reviewed 2 of 7 files at r1.
Review status: 2 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/477)*

**Comment by nurupo** [comment]
@iphydf added Travis build jobs.

As mentioned earlier, `INSTALL.md` needs to be updated before this PR is merged.

**Comment by iphydf** [comment]
Ok, let me know when it's ready.

**Comment by robinlinden** [comment]
I think everything looks good with the exception of some minor typos.

---

Reviewed 5 of 7 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[INSTALL.md, line 24 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-Kw1ejjVxtsYT6eMlCTH:-Kw1ejjVxtsYT6eMlCTI:b-7skvaf) ([raw file](https://github.com/toktok/c-toxcore/blob/a5fb3e6b7cf4c4c44aded6d22c0d18f14edf5988/INSTALL.md#L24)):*
> ```Markdown
>         - [msys/cygwin](#msyscygwin)
>       - [Cross-compiling from Linux](#cross-compiling-from-linux)
> - [Pre-build binaries](#pre-build-binaries)
> ```

built

---

*[INSTALL.md, line 74 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-Kw1cdo_PQ3LtVbBjZLB:-Kw1cdo_PQ3LtVbBjZLC:b-57pyx6) ([raw file](https://github.com/toktok/c-toxcore/blob/a5fb3e6b7cf4c4c44aded6d22c0d18f14edf5988/INSTALL.md#L74)):*
> ```Markdown
> #### Library dependencies
> 
> Librariy dependencies are listed in the [components](#components) table. The dependencies need to be satisfied for the components to be built. Note that if you don't have a dependency for some component, e.g. you don't have `libopus` installed required for building `toxav` component, building of that component is silently disabled.
> ```

Library

---

*[INSTALL.md, line 84 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-Kw1cpcLkQcG3ocFX_uJ:-Kw1cpcLkQcG3ocFX_uK:b-uy506d) ([raw file](https://github.com/toktok/c-toxcore/blob/a5fb3e6b7cf4c4c44aded6d22c0d18f14edf5988/INSTALL.md#L84)):*
> ```Markdown
> Microsoft Visual C++ compiler is not supported, as it doesn't fully support C99 and it doesn't support GCC compiler flags. However, it's possible to cross-compile Tox libraries to Windows using GCC or Clang and use them in a MSVC project.
> 
> You should have a C99 compatible compiler in order to build the main components. The secondary componets might require the compiler to support GNU extensions.
> ```

components

---

*[INSTALL.md, line 199 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-Kw1eB0nnkjUZe21T3x_:-Kw1eB0nnkjUZe21T3xa:b-7j8d0t) ([raw file](https://github.com/toktok/c-toxcore/blob/a5fb3e6b7cf4c4c44aded6d22c0d18f14edf5988/INSTALL.md#L199)):*
> ```Markdown
> | Name               | Description                                                                              | Expected Value                      | Default Value                                                      |
> |--------------------|------------------------------------------------------------------------------------------|-------------------------------------|--------------------------------------------------------------------|
> | ALLOW_TEST_FAILURE | Don't stop if a test suit fails.                                                         | "true" or "false" (case sensitive). | false                                                              |
> ```

suite

---

*[INSTALL.md, line 219 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-Kw1eLDI4C_iVBr_tGgh:-Kw1eLDI4C_iVBr_tGgi:b-7skvaf) ([raw file](https://github.com/toktok/c-toxcore/blob/a5fb3e6b7cf4c4c44aded6d22c0d18f14edf5988/INSTALL.md#L219)):*
> ```Markdown
> After the build succeeds, you should see the built toxcore libraries in `/path/to/where/output/build/result`.
> 
> ## Pre-build binaries
> ```

built

---

*[other/docker/build_dependencies.sh, line 11 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-Kw1awbWRW5gW6per5id:-Kw1awbWRW5gW6per5ie:b-s9fui0) ([raw file](https://github.com/toktok/c-toxcore/blob/a5fb3e6b7cf4c4c44aded6d22c0d18f14edf5988/other/docker/build_dependencies.sh#L11)):*
> ```Shell
>     ARCH=${1}
> 
>     echo "Building for ${ARCH} architecrute"
> ```

architecture

---

*[other/docker/build_toxcore.sh, line 11 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-Kw1b5cQ2D9H8JtOoy4Z:-Kw1b5cQ2D9H8JtOoy4_:b-s9fui0) ([raw file](https://github.com/toktok/c-toxcore/blob/a5fb3e6b7cf4c4c44aded6d22c0d18f14edf5988/other/docker/build_toxcore.sh#L11)):*
> ```Shell
>     ARCH=${1}
> 
>     echo "Building for ${ARCH} architecrute"
> ```

architecture

---

*[other/docker/get_packages.sh, line 9 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-Kw1bjZ6MDH20Zjw3APH:-Kw1bjZ6MDH20Zjw3API:b-mf426m) ([raw file](https://github.com/toktok/c-toxcore/blob/a5fb3e6b7cf4c4c44aded6d22c0d18f14edf5988/other/docker/get_packages.sh#L9)):*
> ```Shell
> apt-get update
> 
> # Arch-independent pacakges required for building toxcore's dependencies and toxcore itself
> ```

packages

---

*[other/docker/get_packages.sh, line 23 at r2](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-Kw1bmZBaFK-UCvvEmOe:-Kw1bmZBaFK-UCvvEmOf:b-mf426m) ([raw file](https://github.com/toktok/c-toxcore/blob/a5fb3e6b7cf4c4c44aded6d22c0d18f14edf5988/other/docker/get_packages.sh#L23)):*
> ```Shell
>     yasm
> 
> # Arch-dependent pacakges required for building toxcore's dependencies and toxcore itself
> ```

packages

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-:-Kw1enGjC-8HFMIrsZqF:b-wcyyst)*

**Comment by nurupo** [comment]
I will look into it. I might change how the Docker Windows cross-compilation is done. I have contributed cross-compilation Docker to qTox not so long ago and it made me rethink the Docker madness I have written in this PR.

**Comment by nurupo** [comment]
On the second thought, this looks kind of reasonable.

**Comment by nurupo** [comment]
Fixed typos for now. Later will take a deeper look and check if INSTALL.md requires any updating since the last time I wrote it and see what I want to change with the cross-compilation, if anything.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-:-KwEraG27vKtNKgrS6sY:bcotl8e)*

**Comment by iphydf** [comment]
This needs rebasing.

**Comment by nurupo** [comment]
@iphydf this should be ready for a final review.

Check the INSTALL instructions. Previously it said that toxcore doesn't support building with MSVC under cmake, but now it kind of does support it in a limited no-toxav sense and if you put the libraries in [the exact paths cmake expects to find them at](https://github.com/TokTok/c-toxcore/blob/master/cmake/Dependencies.cmake#L36-L103). Should I document the library paths? They are a bit of a mess, most library paths are in the current directory (can be re-rotted to any directory with `CMAKE_FIND_ROOT_PATH` option provided by the user), yet other are in the Program Files. It's also a bit of a mess that cmake doesn't look for toxav dependencies and thus is unable to build toxav with MSVC.

Also, is it really a good idea to have the pre-built section mentioning which distributions have toxcore in their package repository and also linking to windows nightly builds of toxcore? I don't feel especially strongly about it.

What do I do with the Travis builds? I left them unconditioned to let you see that they work. I assume you will ask me to put them under the cron condition after you are happy with the PR.

**Comment by iphydf** [comment]
Reviewed 1 of 8 files at r2, 13 of 14 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 24 unresolved discussions, some commit checks failed.

---

*[INSTALL.md, line 3 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L6maniAioi7qRHwfm:-L3L6maoTrsB2Mi13blE:b-gv5uyr) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L3)):*
> ```Markdown
> # Installation instructions
> 
> These instructions will guide you through the process of building and installing toxcore library and its components, as well as getting already pre-built binaries.
> ```

"installing *the* toxcore library"

Also, maybe mdformat or something, make the line length not super long.

---

*[INSTALL.md, line 34 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L7NEJ5bctCQYAt3Cd:-L3L7NEJ5bctCQYAt3Ce:be0l2du) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L34)):*
> ```Markdown
> #### Main
> 
> This repository, although called `toxcore`, in fact contains several libraries besides `toxcore` which complement it, as well as several executables. However, note that although these are separate libraries, at the moment, when building the libraries, they are all merged into a single `toxcore` library. Here is the full list of the main components that can be built using the CMake, their dependencies and descriptions.
> ```

1. "using the CMake" <- why *the* CMake?
2. There are a lot of commas in this sentence. I don't think there should be. Let's have some native speaker look over it.
3. One line per paragraph makes adding review comments hard.

---

*[INSTALL.md, line 50 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L7s9hKG9nuqT00kWa:-L3L7s9hKG9nuqT00kWb:b-gwv47t) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L50)):*
> ```Markdown
> | Name        | Type       | Dependencies           | Platform  | Description                                                                                                                             |
> |-------------|------------|------------------------|-----------|-----------------------------------------------------------------------------------------------------------------------------------------|
> | irc_syncbot | Executable | libtoxcore             | Unix-like | Bot that synchronizes IRC channel and Tox group chat (conference).                                                                      |
> ```

"synchronises *an* IRC channel and *a* Tox group chat"

---

*[INSTALL.md, line 51 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L7oZCjpUR3nPrXANN:-L3L7oZCjpUR3nPrXANO:b-87j1qu) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L51)):*
> ```Markdown
> |-------------|------------|------------------------|-----------|-----------------------------------------------------------------------------------------------------------------------------------------|
> | irc_syncbot | Executable | libtoxcore             | Unix-like | Bot that synchronizes IRC channel and Tox group chat (conference).                                                                      |
> | nTox        | Executable | libtoxcore, libncurses | Unix-like | Simple text-based Tox client with support of file transfers and group chat (conference). Testing program, not intended for actual use.  |
> ```

Gone.

---

*[INSTALL.md, line 55 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L81f-7i1FEbXnS0HQ:-L3L81f-7i1FEbXnS0HR:b-8dv05g) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L55)):*
> ```Markdown
> | tox_sync    | Executable | libtoxcore             | Unix-like | Bittorrent-sync-like software using Tox. Syncs two directories together.                                                                |
> 
> There are also some programs that are not plugged into the CMake build system which you might want to find interesting. You would need to build those programs yourself. These programs reside in [`other/fun`](other/fun) directory.
> ```

"might want to find interesting" sounds odd. Do I want to find it interesting? Maybe just "find interesting".

---

*[INSTALL.md, line 87 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L8Yp-X6I9eLRHgfLh:-L3L8Yp-X6I9eLRHgfLi:b4gvz88) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L87)):*
> ```Markdown
> To build the main components you need to have CMake of at least 2.8.6 version installed. You also need to have pkg-config installed, the build system uses it to find dependency libraries.
> 
> There is some experimental accommodation for building natively on Windows, i.e. without having to use MSYS/Cygwin and pkg-config, but it uses exact hardcoded paths for finding libraries and supports building only of some of txocore components, so your mileage might vary.
> ```

txocore => toxcore

---

*[INSTALL.md, line 98 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L8gU1Y8a-SkOZzZ4y:-L3L8gU1Y8a-SkOZzZ4z:b-87j1qu) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L98)):*
> ```Markdown
> | BOOTSTRAP_DAEMON     | Enable building of tox-bootstrapd, the DHT bootstrap node daemon. For Unix-like systems only. | ON or OFF                                  | ON                                                |
> | BUILD_AV_TEST        | Build toxav test.                                                                             | ON or OFF                                  | ON                                                |
> | BUILD_NTOX           | Build nTox client.                                                                            | ON or OFF                                  | OFF                                               |
> ```

Gone.

---

*[INSTALL.md, line 127 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L8x5ZyiYfHUjeqPNV:-L3L8x5ZyiYfHUjeqPNW:blqd9fm) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L127)):*
> ```Markdown
> ```sh
> cmake \
>   -D ENABLE_STATIC=OFF \
> ```

Prefer `-DENABLE_...`, without space, as we have that everywhere in the travis scripts.

---

*[INSTALL.md, line 140 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L9AnzVWOl3jwUUXpA:-L3L9Ao-NMai44FPWSMD:b-88rd64) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L140)):*
> ```Markdown
> 
> ```sh
> cd build
> ```

This directory contains Makefile.am. I'm not sure we want to build from that. I usually build from `_build`, because that's what "make distcheck" does when using autotools, so for all projects using autotools, that is guaranteed to work.

---

*[INSTALL.md, line 168 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L9cO2mTlT-u_dnUUI:-L3L9cO2mTlT-u_dnUUJ:b-4fbbyo) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L168)):*
> ```Markdown
> ```sh
> apt-get update
> apt-get install docker.io
> ```

Does this work? I think I need to do "apt-get install docker", not docker.io.

---

*[cmake/ModulePackage.cmake, line 99 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3LADjCJxZfuGbJVm3f:-L3LADjCJxZfuGbJVm3g:b-xzw7y2) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/cmake/ModulePackage.cmake#L99)):*
> ```CMake
>   if(ENABLE_STATIC)
>     install(TARGETS ${lib}_static
>       RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
> ```

No idea what this does, or what parts of the library would end up in bindir.

---

*[other/docker/windows/build_dependencies.sh, line 9 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3LAQ9KAHJco5u-L1x0:-L3LAQ9KAHJco5u-L1x1:bunqvmm) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/other/docker/windows/build_dependencies.sh#L9)):*
> ```Shell
> build()
> {
>     ARCH=${1}
> ```

Other scripts have 2-space indent. Should we change those or this one?

---

*[other/docker/windows/build_toxcore.sh, line 42 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3LAmWyAYUISlrCGkFa:-L3LAmWyAYUISlrCGkFb:b-oc8rc7) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/other/docker/windows/build_toxcore.sh#L42)):*
> ```Shell
>     cp /toxcore /tmp/toxcore -R
>     cd /tmp/toxcore/build
>     echo "
> ```

Maybe a heredoc is nicer. Your call though.

---

*[other/docker/windows/build_toxcore.sh, line 99 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3LAuPh0ypLNsgDMEgK:-L3LAuPh0ypLNsgDMEgL:b-v7qf5n) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/other/docker/windows/build_toxcore.sh#L99)):*
> ```Shell
>     done
>     ${WINDOWS_TOOLCHAIN}-gcc -Wl,--export-all-symbols \
>                                  -Wl,--out-implib=libtox.dll.a \
> ```

Less indentation here.

---

*[other/docker/windows/get_packages.sh, line 25 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3LB8Q8ff4xmOhV2Gor:-L3LB8Q8ff4xmOhV2Gos:b-as7kn1) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/other/docker/windows/get_packages.sh#L25)):*
> ```Shell
> # Arch-dependent packages required for building toxcore's dependencies and toxcore itself
> if [ "${SUPPORT_ARCH_i686}" = "true" ]; then
>     # g++ is unnecessary, but CMake requires it when doing its check
> ```

Just fyi: g++ may become necessary soon (for tests).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/477)*

**Comment by nurupo** [comment]
Review status: 8 of 11 files reviewed at latest revision, 25 unresolved discussions, some commit checks failed.

---

*[INSTALL.md, line 3 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L6maniAioi7qRHwfm:-L3L_ZeuiAd2ZtoMWyPn:bvul3se) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L3)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

"installing *the* toxcore library"

Also, maybe mdformat or something, make the line length not super long.
</blockquote></details>

What is mdformat? Can't find it in Google or Debian packages (both as package name or a file name that is contained by any package). I can put each sentence on its own line. Splitting the text to fit into 80 characters might be doable too, markdown formatting might get in the way of doing that though, since you can't split it on new line (or can you? don't think i ever tried).

---

*[INSTALL.md, line 34 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L7NEJ5bctCQYAt3Cd:-L3LaraIML_eQ2yDrrcL:b-htwepd) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L34)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

1. "using the CMake" <- why *the* CMake?
2. There are a lot of commas in this sentence. I don't think there should be. Let's have some native speaker look over it.
3. One line per paragraph makes adding review comments hard.
</blockquote></details>

1. Is that incorrect? I will remove this instance of "the CMake" then. There are a few more instances of "the CMake" in the INSTALL.md that you didn't comment on which I assume are fine so I will keep those. Noun articles are hard, my language doesn't have them at all.
2. Sure. Who is a native speaker here?
3. Replied in the reply to your "mdformat" comment.

---

*[INSTALL.md, line 55 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L81f-7i1FEbXnS0HQ:-L3QaS8lGM8oPiwcAYRh:b68ways) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L55)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

"might want to find interesting" sounds odd. Do I want to find it interesting? Maybe just "find interesting".
</blockquote></details>

Right, this doesn't sound right at all. Should be fixed now.

---

*[INSTALL.md, line 127 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L8x5ZyiYfHUjeqPNV:-L3Qas-MwzLGiSIvb3uf:b-sd4ftn) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L127)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Prefer `-DENABLE_...`, without space, as we have that everywhere in the travis scripts.
</blockquote></details>

[According to the documentation](https://cmake.org/cmake/help/v3.10/manual/cmake.1.html) you can use both `-D <var>:<type>=<value>` or `-D<var>:<type>=<value>`. I'm preferring to use the space-separated version in the install guide purely for clarity reasons, it's easier to spot where `ENABLE_STATIC` comes from than `-DENABLE_STATIC`.

---

*[INSTALL.md, line 128 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3Qcym9JuDQdkvtWHwS:-L3QcymAtGTaWh7hev69:b-19gjj) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L128)):*
> ```Markdown
> cmake \
>   -D ENABLE_STATIC=OFF \
>   -D DEBUG=ON -DCMAKE_INSTALL_PREFIX=/opt \
> ```

This line is inconsistent with the rest. Should be fixed now.

---

*[INSTALL.md, line 140 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L9AnzVWOl3jwUUXpA:-L3QhctfHu4rRdPG7Pw0:b-m5ipiq) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L140)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

This directory contains Makefile.am. I'm not sure we want to build from that. I usually build from `_build`, because that's what "make distcheck" does when using autotools, so for all projects using autotools, that is guaranteed to work.
</blockquote></details>

I always use "build" for this, but it's a bit annoying that I can't easily `rm -rf build` without git getting upset about this. I will `_build` for the installation guide.

---

*[INSTALL.md, line 168 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L9cO2mTlT-u_dnUUI:-L3QdM16ZlstXS7aQr0i:b-ciulxn) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L168)):*
Yes, I did check it in a Ubuntu 16.04 VM in Virtual Box back when I was writing these instructions a year ago.

The `docker` package in Ubuntu is

>[System tray for KDE3/GNOME2 docklet applications](https://packages.ubuntu.com/xenial/docker)

The `docker.io` is

>[Linux container runtime](https://packages.ubuntu.com/xenial/docker.io)

---

*[cmake/ModulePackage.cmake, line 99 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3LADjCJxZfuGbJVm3f:-L3QeN1Fr2TVCSEo0T46:b1v9ibj) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/cmake/ModulePackage.cmake#L99)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

No idea what this does, or what parts of the library would end up in bindir.
</blockquote></details>

This puts runtime things into `/bin`. Those are executables, and in case of Windows also `.dll` files. We want `.dll` be in `/bin` because that's how everyone does it and because the `.exe` files from `/bin` will need those `.dll` in order to run. Linux and macOS, the "non-DLL platforms" as cmake documentation calls them, are not affected by this change, `.so` files and `.dynlib` files will keep going into `/lib` like they always did. You can read more on what `RUNTIME`, `LIBRARY` and `ARCHIVE` on each platform are at https://cmake.org/cmake/help/v3.10/command/install.html#installing-targets

---

*[other/docker/windows/build_dependencies.sh, line 9 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3LAQ9KAHJco5u-L1x0:-L3QlolIpRF_u_mJPTcs:b-l74lvy) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/other/docker/windows/build_dependencies.sh#L9)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Other scripts have 2-space indent. Should we change those or this one?
</blockquote></details>

What are you talking about? All of the 3 scripts have 4-space indentation.

---

*[other/docker/windows/get_packages.sh, line 25 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3LB8Q8ff4xmOhV2Gor:-L3QgtkuJedMHFktqXgL:bap9gf5) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/other/docker/windows/get_packages.sh#L25)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Just fyi: g++ may become necessary soon (for tests).
</blockquote></details>

Well, based on our discussion in other PR, the C++ compiler requirement is rather artificial and can be made optional, which I think it should be. I will remove this comment to spare any confusion though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/477)*

**Comment by iphydf** [comment]
Review status: 6 of 11 files reviewed at latest revision, 18 unresolved discussions.

---

*[INSTALL.md, line 3 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L6maniAioi7qRHwfm:-L3UajBmGJdTvMKa_Xdg:b-co7r21) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L3)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

What is mdformat? Can't find it in Google or Debian packages (both as package name or a file name that is contained by any package). I can put each sentence on its own line. Splitting the text to fit into 80 characters might be doable too, markdown formatting might get in the way of doing that though, since you can't split it on new line (or can you? don't think i ever tried).
</blockquote></details>

It's ok, we can run a markdown formatter later.

---

*[INSTALL.md, line 34 at r4](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-L3L7NEJ5bctCQYAt3Cd:-L3UeO0ZbHP703UMB1Sj:bnqjk8f) ([raw file](https://github.com/toktok/c-toxcore/blob/7dc8b87f2b6be2c34b1324dc76db725d094cd920/INSTALL.md#L34)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

1. Is that incorrect? I will remove this instance of "the CMake" then. There are a few more instances of "the CMake" in the INSTALL.md that you didn't comment on which I assume are fine so I will keep those. Noun articles are hard, my language doesn't have them at all.
2. Sure. Who is a native speaker here?
3. Replied in the reply to your "mdformat" comment.
</blockquote></details>

1. I think so. I didn't check very carefully, but this one stood out to me.
2. I don't know. I think it's ok though, it's not too important. I'd rather get this submitted sooner.
3. Another time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/477)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 2 of 14 files at r3, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/477#-:-L3UeeNXc_aW5qf-JLNG:b-jbsf8z)*

**Comment by iphydf** [comment]
@nurupo can you rebase and squash commits as appropriate? If you deem each commit to be a separate thing, then no need to squash anything.

**Comment by nurupo** [comment]
I guess I should remove the option to compile as CXX too from the INSTALL.md.

**Comment by nurupo** [comment]
I will let Travis run this first and after it passes I will change the commit to disable Windows builds on Travis.

**Comment by nurupo** [comment]
Alright, it passed.

**Comment by nurupo** [comment]
Moved Travis Windows builds to cron.

**Pull request merged**
