### PR TITLE
Remove minitox from the README.

### PR DESCRIPTION
**Pull request by iphydf**
This program is very broken. It needs to be reviewed and fixed before we
can link to it.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/934)

### CODE REVIEW

**Comment by iphydf** [comment]
@hqwrong: please come talk on IRC so we can fix minitox.

**Comment by tox-user** [comment]
Is it a problem with minitox or with persistent groups?

**Comment by iphydf** [comment]
Both, or minitox. Minitox definitely has bugs that need fixing.

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/934#-:-LFnRqy9EHqOdVMzNVkO:b-jbsf8z)*

**Pull request closed without merging**
