### PR TITLE
Issue 404: semicolon not found

### PR DESCRIPTION
**Pull request by nurupo**
Found through [cppcheck](https://build.tox.chat/job/libtoxcore-toktok_analyze_cppcheck/55/cppcheckResult/source.17/#35).

---

This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/404)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/crypto_core_mem.c, line 40 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/404#-K_pfnYo1zOHS6egODNz:-K_pfnYo1zOHS6egODO-:b-2w31n5) ([raw file](https://github.com/toktok/c-toxcore/blob/f7cefe42d82a7d3dff9c1766e699efff438a4890/toxcore/crypto_core_mem.c#L40)):*
> ```C
> #else
> #ifdef _WIN32
>     SecureZeroMemory(pnt, len);
> ```

`len` doesn't exist.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/404)*

**Comment by nurupo** [comment]
*[toxcore/crypto_core_mem.c, line 40 at r1](https://reviewable.io:443/reviews/toktok/c-toxcore/404#-K_pfnYo1zOHS6egODNz:-K_phXmUXIYIj4pCc-X6:bt2vr1b) ([raw file](https://github.com/toktok/c-toxcore/blob/f7cefe42d82a7d3dff9c1766e699efff438a4890/toxcore/crypto_core_mem.c#L40)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

`len` doesn't exist.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/404)*

**Comment by nurupo** [comment]
Also fixed the if condition. In [libsodium's original code](https://github.com/jedisct1/libsodium/blob/9cae7b6b7c6f527df807157602ba48821281048b/src/libsodium/sodium/utils.c#L80) `memset_s()` is called iff `len > 0U`, but in ours it was called always.

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/404#-:-K_piLgfONkBAdIld8CN:bg7igkv)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/404#-:-K_pjaXoEMkQORyetnA3:b-jbsf8z)*

**Pull request merged**
