### PR TITLE
fix DHT_bootstrap key loading

### PR DESCRIPTION
**Pull request by anthonybilinski**
Introduced by 643eea60bb9dcf4ecb33d64666b1bc77cbfd7438

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/878)

### CODE REVIEW

**Comment by nurupo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/c-toxcore/878)*

**Comment by crypto-universe** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/878)*

**Comment by crypto-universe** [comment]
:lgtm_strong: looks like a fix for a copy-paste error.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/878#-:-LBbke-g2tKKAfqnQDct:b-7n4y1r)*

**Comment by crypto-universe** [comment]
@anthonybilinski , are you going to accept contributor license agreement?

**Comment by nurupo** [comment]
Forgot to put LTMG :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/878#-:-LBeWORD5lF7CUAIcpi6:b-xpnsb0)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/878#-:-LC9jOC5EUt97-3hepG2:b-jbsf8z)*

**Pull request merged**
