### PR TITLE
Add VScode folder to .gitignore

### PR DESCRIPTION
**Pull request by crypto-universe**
Add one more IDE to the list of ignored folders.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1299)

### CODE REVIEW

**Comment by crypto-universe** [comment]
@iphydf I'd mark this tsan test as non-reliable.

**Comment by Diadlo** [comment]
Please, don't add your IDEs in the project gitignore. Project gitignore should contain only project/language-specific ignores. If everybody starts adding he's own IDE, OS-specific files (`.DS_store/`, `Thumbs.db`, etc.) file will grow a lot. Please, use [global gitignore](https://stackoverflow.com/questions/7335420/global-git-ignore). Thanks

**Comment by Diadlo** [comment]
@robinlinden It was said that you would destroy the Sith, not join them!

**Comment by robinlinden** [comment]
@Diadlo We already had lots of different IDEs stuffed in there and no one commented on this PR. I'm fine with a PR removing all of them if we'd like to keep it cleaner. 😁

**Pull request merged**
