### PR TITLE
cleanup: Make all .c files include the headers they need.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2505)

### CODE REVIEW

**Comment by nurupo** [comment]
Wow, this is great. Is there a tool for this?

We also need a commit/PR removing unnecessary includes, as this PR has added some. For example, before this PR, `bootstrap_daemon/src/command_line_arguments.c` replied on getting `#include "log.h"` from `bootstrap_daemon/src/command_line_arguments.h`. But now that you have added `#include "log.h"` directly to `bootstrap_daemon/src/command_line_arguments.c` in this PR, the `#include "log.h"` in `bootstrap_daemon/src/command_line_arguments.h` is no longer needed.

**Comment by nurupo** [comment]
My bad, `bootstrap_daemon/src/command_line_arguments.h` actually needs `#include "log.h"`. Edited my earlier comment.

**Comment by iphydf** [comment]
It was completely manually, because `clang-tidy --fix` makes a huge mess. I took the error messages and manually added all the includes.

**Comment by nurupo** [comment]
How can I get these error messages from clang-tidy? Is there a specific check name I need to enable?

**Comment by nurupo** [comment]
Looks like this might be it https://clang.llvm.org/extra/clang-include-fixer.html

**Comment by iphydf** [comment]
It's `--checks=-*,misc-include-cleaner`.

**Review by nurupo — APPROVED** [review]
> Reviewed 65 of 65 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2505)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Review by JFreegman — COMMENTED** [review]
> Reviewed 4 of 65 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TokTok/c-toxcore/2505)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @iphydf)

___
*[`toxcore/ccompat.c` line 6 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2505#-NmcxkE6C5N-riVVP9oH:-NmcxkE6C5N-riVVP9oI:b73o3ie) ([raw file](https://github.com/TokTok/c-toxcore/blob/fad6e4e1734e8f241c7f71ed8c06f69d77a05179/toxcore/ccompat.c#L6)):*
> ```C
> #include "ccompat.h"
> 
> static_assert(sizeof(int) >= 4, "toxcore does not support 16-bit platform");
> ```

Missing an `s`?
___
*[`toxcore/group_moderation.c` line 461 at r1](https://reviewable.io/reviews/TokTok/c-toxcore/2505#-NmcwYlP0YnoJMLuh7y9:-NmcwYlP0YnoJMLuh7yA:bv6u5kz) ([raw file](https://github.com/TokTok/c-toxcore/blob/fad6e4e1734e8f241c7f71ed8c06f69d77a05179/toxcore/group_moderation.c#L461)):*
> ```C
>     const int packed_len = sanctions_list_pack(packed_data, sizeof(packed_data), sanction, 1, nullptr);
> 
>     if (packed_len <= SIGNATURE_SIZE) {
> ```

https://github.com/JFreegman/toxcore/commit/1732318e05c8e3ddad67411eb59de999ee62db0d

For clarity sake, `SIGNATURE_SIZE` used to be a `size_t`, making the cast necessary. Now it's an int so this change is okay.

**Pull request merged**
