### PR TITLE
Remove leftover symmetric key from DHT struct.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/779)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/779#-:-L5KT6eyWsf0s-RLM0pu:b-jbsf8z)*

**Comment by SkyzohKey** [comment]
Why?

**Comment by iphydf** [comment]
@SkyzohKey because it wasn't used anywhere.

**Comment by SkyzohKey** [comment]
@iphydf Ok seems logic, c:

**Pull request merged**
